package com.saprigrat.ui.forms.personas;

import java.sql.Date;
import java.util.LinkedList;

import org.joda.time.LocalDate;
import org.joda.time.format.DateTimeFormat;
import org.vaadin.addons.tuningdatefield.TuningDateField;

import com.saprigrat.data.Datos;
import com.saprigrat.data.Usuario;
import com.saprigrat.ui.interfaces.Formulario;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class Regador extends CustomComponent implements Formulario
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horLDetallesBtn;
	@AutoGenerated
	private Button btnAccion;
	@AutoGenerated
	private Panel panDetalles;
	@AutoGenerated
	private AbsoluteLayout absLDetalles;
	@AutoGenerated
	private CheckBox chkCapacitacion;
	@AutoGenerated
	private TuningDateField datIngreso;
	@AutoGenerated
	private Panel panGenerales;
	@AutoGenerated
	private AbsoluteLayout absLGenerales;
	@AutoGenerated
	private TextField txtApM;
	@AutoGenerated
	private TextField txtApP;
	@AutoGenerated
	private TextField txtNombre;
	@AutoGenerated
	private Panel panProductor;
	@AutoGenerated
	private AbsoluteLayout absLProductor;
	@AutoGenerated
	private ComboBox txtProductor;
	private int tipoPersona;
	private Usuario usuario;
	private Datos datos;
	
	public Regador(int tipo, Usuario user)
	{
		tipoPersona = tipo;
		usuario = user;
		inicializar();
	}

	@Override
	public void inicializar()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		datos = new Datos();
		
		//Configurar el formato de fecha mostrado
		datIngreso.setWeekendDisabled(false);
		datIngreso.setDateTimeFormatter(DateTimeFormat.longDate());
		datIngreso.setDateTextReadOnly(true);
		//Agregar las validaciones necesarias
		setValidaciones();
	}

	@Override
	public void setTipo(int tipoOperacion)
	{
		if(tipoOperacion == 1)
			btnAccion.addClickListener(agregarListener());
		else
		{
			btnAccion.setCaption("Modificar");
			btnAccion.addClickListener(modificarListener());
		}
	}

	@Override
	public int getEntidad()
	{
		return 0;
	}

	@Override
	public Object[] getRestricciones()
	{
		return new Object[]{usuario.getCURR(),
							tipoPersona};
	}
	
	private void setValidaciones()
	{
		txtNombre.setMaxLength(40);
		txtApP.setMaxLength(20);
		txtApM.setMaxLength(20);
	}
	
	private Date getFecha(TuningDateField calendario)
	{
		if(calendario.getValue() == null)
			return null;
		else
			return new Date(calendario.getLocalDate().toDate().getTime());
	}
	
	private LocalDate setFecha(Date fecha)
	{
		if(fecha == null)
			return null;
		else
			return new LocalDate(fecha.getTime());
	}
	
	private ClickListener agregarListener()
	{
		return  new ClickListener()
				{
					@Override
					public void buttonClick(ClickEvent event)
					{
						LinkedList<Object> valores = new LinkedList<Object>();
						valores.add(usuario.getCURR());
						valores.add(txtNombre.getValue());
						valores.add(txtApP.getValue());
						valores.add(txtApM.getValue());
						valores.add(usuario.getEstado());
						valores.add(getFecha(datIngreso));
						
						if(datos.registrarPersona(valores) != null)
						{
							Notification.show("Registro añadido correctamente.", Notification.Type.TRAY_NOTIFICATION);
						}
						else
							Notification.show("Error al añadir registro, comuníquese con el administrador.", Notification.Type.ERROR_MESSAGE);
					}
				};
	}
	
	private ClickListener modificarListener()
	{
		return  new ClickListener()
				{
					@Override
					public void buttonClick(ClickEvent event)
					{
						LinkedList<Object> valores = new LinkedList<Object>();
						valores.add(txtNombre.getValue());
						valores.add(txtApP.getValue());
						valores.add(txtApM.getValue());
						
						if(datos.modificar("regadores", valores))
							Notification.show("Registro modificado correctamente.", Notification.Type.TRAY_NOTIFICATION);
					}
				};
	}
	
	private ValueChangeListener llenarDatosListener()
	{
		return  new ValueChangeListener()
				{
					@Override
					public void valueChange(ValueChangeEvent event)
					{
						LinkedList<Object> valores = datos.getRegistro("");
						txtProductor.setValue((String)valores.remove());
						txtNombre.setValue((String)valores.remove());
						txtApP.setValue((String)valores.remove());
						txtApM.setValue((String)valores.remove());
						datIngreso.setLocalDate(setFecha((Date)valores.remove()));
					}
				};
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// panProductor
		panProductor = buildPanProductor();
		mainLayout.addComponent(panProductor);
		
		// panGenerales
		panGenerales = buildPanGenerales();
		mainLayout.addComponent(panGenerales);
		
		// horLDetallesBtn
		horLDetallesBtn = buildHorLDetallesBtn();
		mainLayout.addComponent(horLDetallesBtn);
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanProductor() {
		// common part: create layout
		panProductor = new Panel();
		panProductor.setCaption("Usuario/Productor");
		panProductor.setImmediate(false);
		panProductor.setWidth("331px");
		panProductor.setHeight("-1px");
		
		// absLProductor
		absLProductor = buildAbsLProductor();
		panProductor.setContent(absLProductor);
		
		return panProductor;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLProductor() {
		// common part: create layout
		absLProductor = new AbsoluteLayout();
		absLProductor.setImmediate(false);
		absLProductor.setWidth("100.0%");
		absLProductor.setHeight("45px");
		
		// txtProductor
		txtProductor = new ComboBox();
		txtProductor.setImmediate(false);
		txtProductor.setWidth("310px");
		txtProductor.setHeight("25px");
		absLProductor.addComponent(txtProductor, "top:10.0px;left:10.0px;");
		
		return absLProductor;
	}

	@AutoGenerated
	private Panel buildPanGenerales() {
		// common part: create layout
		panGenerales = new Panel();
		panGenerales.setCaption("Datos Generales");
		panGenerales.setImmediate(false);
		panGenerales.setWidth("601px");
		panGenerales.setHeight("-1px");
		
		// absLGenerales
		absLGenerales = buildAbsLGenerales();
		panGenerales.setContent(absLGenerales);
		
		return panGenerales;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLGenerales() {
		// common part: create layout
		absLGenerales = new AbsoluteLayout();
		absLGenerales.setImmediate(false);
		absLGenerales.setWidth("100.0%");
		absLGenerales.setHeight("65px");
		
		// txtNombre
		txtNombre = new TextField();
		txtNombre.setCaption("Nombre");
		txtNombre.setImmediate(false);
		txtNombre.setWidth("260px");
		txtNombre.setHeight("25px");
		txtNombre.setInvalidAllowed(false);
		absLGenerales.addComponent(txtNombre, "top:28.0px;left:10.0px;");
		
		// txtApP
		txtApP = new TextField();
		txtApP.setCaption("Apellido Paterno");
		txtApP.setImmediate(false);
		txtApP.setWidth("140px");
		txtApP.setHeight("25px");
		absLGenerales.addComponent(txtApP, "top:28.0px;left:290.0px;");
		
		// txtApM
		txtApM = new TextField();
		txtApM.setCaption("Apellido Materno");
		txtApM.setImmediate(false);
		txtApM.setWidth("140px");
		txtApM.setHeight("25px");
		absLGenerales.addComponent(txtApM, "top:28.0px;left:450.0px;");
		
		return absLGenerales;
	}

	@AutoGenerated
	private HorizontalLayout buildHorLDetallesBtn() {
		// common part: create layout
		horLDetallesBtn = new HorizontalLayout();
		horLDetallesBtn.setImmediate(false);
		horLDetallesBtn.setWidth("601px");
		horLDetallesBtn.setHeight("-1px");
		horLDetallesBtn.setMargin(false);
		
		// panDetalles
		panDetalles = buildPanDetalles();
		horLDetallesBtn.addComponent(panDetalles);
		
		// btnAccion
		btnAccion = new Button();
		btnAccion.setCaption("Agregar");
		btnAccion.setImmediate(true);
		btnAccion.setWidth("120px");
		btnAccion.setHeight("-1px");
		horLDetallesBtn.addComponent(btnAccion);
		horLDetallesBtn.setComponentAlignment(btnAccion, new Alignment(10));
		
		return horLDetallesBtn;
	}

	@AutoGenerated
	private Panel buildPanDetalles() {
		// common part: create layout
		panDetalles = new Panel();
		panDetalles.setCaption("Detalles del Programa");
		panDetalles.setImmediate(false);
		panDetalles.setWidth("381px");
		panDetalles.setHeight("-1px");
		
		// absLDetalles
		absLDetalles = buildAbsLDetalles();
		panDetalles.setContent(absLDetalles);
		
		return panDetalles;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDetalles() {
		// common part: create layout
		absLDetalles = new AbsoluteLayout();
		absLDetalles.setImmediate(false);
		absLDetalles.setWidth("100.0%");
		absLDetalles.setHeight("65px");
		
		// datIngreso
		datIngreso = new TuningDateField();
		datIngreso.setCaption("Fecha de Ingreso al Programa");
		datIngreso.setImmediate(false);
		datIngreso.setWidth("200px");
		datIngreso.setHeight("25px");
		absLDetalles.addComponent(datIngreso, "top:28.0px;left:10.0px;");
		
		// chkCapacitacion
		chkCapacitacion = new CheckBox();
		chkCapacitacion.setCaption("Capacitación Recibida");
		chkCapacitacion.setImmediate(false);
		chkCapacitacion.setWidth("-1px");
		chkCapacitacion.setHeight("-1px");
		absLDetalles.addComponent(chkCapacitacion, "top:28.0px;left:230.0px;");
		
		return absLDetalles;
	}
}