package com.saprigrat.ui.forms.nivelesDeAdministracion;

import java.sql.Date;
import java.util.LinkedList;

import org.joda.time.LocalDate;
import org.vaadin.addons.tuningdatefield.TuningDateField;
import org.vaadin.dialogs.ConfirmDialog;

import com.saprigrat.data.Datos;
import com.saprigrat.data.Usuario;
import com.saprigrat.data.Utilerias;
import com.saprigrat.ui.interfaces.Formulario;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.event.ItemClickEvent.ItemClickListener;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.event.ShortcutAction.ModifierKey;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class Administrador extends CustomComponent implements Formulario
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout absLBotones;
	@AutoGenerated
	private HorizontalLayout horLBotones;
	@AutoGenerated
	private Button btnVolver;
	@AutoGenerated
	private Button btnNuevo;
	@AutoGenerated
	private Button btnGuardar;
	@AutoGenerated
	private VerticalLayout verLDatos;
	@AutoGenerated
	private Panel panUser;
	@AutoGenerated
	private AbsoluteLayout absLUser;
	@AutoGenerated
	private PasswordField txtPass2;
	@AutoGenerated
	private PasswordField txtPass;
	@AutoGenerated
	private TextField txtUser;
	@AutoGenerated
	private Panel panEntidad;
	@AutoGenerated
	private VerticalLayout verLEntidad;
	@AutoGenerated
	private AbsoluteLayout absLEntidad3;
	@AutoGenerated
	private TextField txtCargo;
	@AutoGenerated
	private AbsoluteLayout absLEntidad2;
	@AutoGenerated
	private TextField txtNombreEnt;
	@AutoGenerated
	private ComboBox cmbNombreEnt;
	@AutoGenerated
	private ComboBox cmbEntidad;
	@AutoGenerated
	private AbsoluteLayout absLEntidad1;
	@AutoGenerated
	private ComboBox cmbEdo;
	@AutoGenerated
	private TuningDateField datIngreso;
	@AutoGenerated
	private TextField txtCURR;
	@AutoGenerated
	private Panel panContacto;
	@AutoGenerated
	private AbsoluteLayout absLContacto;
	@AutoGenerated
	private TextField txtEmail;
	@AutoGenerated
	private TextField txtCel;
	@AutoGenerated
	private TextField txtTel;
	@AutoGenerated
	private Panel panGenerales;
	@AutoGenerated
	private VerticalLayout verLGenerales;
	@AutoGenerated
	private AbsoluteLayout absLGenerales;
	@AutoGenerated
	private TextField txtApM;
	@AutoGenerated
	private TextField txtApP;
	@AutoGenerated
	private TextField txtNombre;
	@AutoGenerated
	private Table tblListado;
	private int tipoPersona;
	private Utilerias u;
	private Usuario usuario;
	private Datos datos;
	private LinkedList<String> entidades, estados;
	private int idAdministrador;

	//region eventos
	private ClickListener agregarListener = new ClickListener()
			{
				@Override
				public void buttonClick(ClickEvent event)
				{
					if(validar())
					{
						LocalDate fecha = datIngreso.getLocalDate();
						String curr =   u.setDecimalFormat("00", tipoPersona) +
										u.setDecimalFormat("00", fecha.getYearOfCentury()) +
										u.setDecimalFormat("00", fecha.getMonthOfYear()) +
										u.setDecimalFormat("00", fecha.getDayOfMonth()) +
										u.setDecimalFormat("00", estados.indexOf(cmbEdo.getValue()) + 1);
						LinkedList<Object> valores = llenarListaDeParametros();
						valores.addFirst(cmbEdo.getValue());
						valores.addFirst(u.fechaUtilToSQL(datIngreso.getLocalDate().toDate()));
						valores.addFirst(tipoPersona);
						valores.addFirst(curr);
						
						curr = datos.registrarAdministrador(valores);
						if(!curr.isEmpty() && curr.indexOf("err") == -1)
						{
							String[]currArr = curr.split(" ");
							Notification.show("Registro añadido correctamente.\nCURR asignado: " + currArr[0], Notification.Type.TRAY_NOTIFICATION);
							txtCURR.setValue(currArr[0]);
							//Se cambia a modo de modificación
							setTipo(MODO_MODIFICAR);
							idAdministrador = Integer.parseInt(currArr[1]);
						}
						else
							if(curr.indexOf("Log") == -1)
								Notification.show("Error al añadir registro, comuníquese con el administrador.", Notification.Type.ERROR_MESSAGE);
							else
								if(curr.indexOf("LogRep") != -1)
									Notification.show("Ese nombre de usuario no se encuentra disponible, intente con uno diferente.", Notification.Type.ERROR_MESSAGE);
								else
									Notification.show("Se guardó la información del administrador, pero sus credenciales para ingresar al sistema no. Comuníquese con el administrador.", Notification.Type.WARNING_MESSAGE);
					}
				}
			};
	private ClickListener modificarListener = new ClickListener()
			{
				@Override
				public void buttonClick(ClickEvent event)
				{
					if(validar())
					{
						LinkedList<Object> valores = llenarListaDeParametros();
						valores.addFirst(txtCURR.getValue());
						valores.addFirst(idAdministrador);
						
						String status = datos.modificarAdministrador(valores);
						if(!status.isEmpty() && status.indexOf("err") == -1)
							Notification.show("Registro modificado correctamente.", Notification.Type.TRAY_NOTIFICATION);
						else
							if(status.indexOf("Log") != -1)
								Notification.show("Ese nombre de usuario no se encuentra disponible, intente con uno diferente.", Notification.Type.ERROR_MESSAGE);
							else
								Notification.show("Error al modificar registro, comuníquese con el administrador.", Notification.Type.ERROR_MESSAGE);
					}
				}
			};
	private ItemClickListener llenarFormListener = new ItemClickListener()
			{
				@Override
				public void itemClick(ItemClickEvent event)
				{
					if(event.isDoubleClick())
					{
						idAdministrador = Integer.parseInt(tblListado.getItemCaption(event.getItem()).split(" ")[0]);
						llenarForm();
					}
				}
			};
	private ValueChangeListener nombreEntidadListener = new ValueChangeListener()
			{
				@Override
				public void valueChange(ValueChangeEvent event)
				{
					int entidadIndex = entidades.indexOf(cmbEntidad.getValue());
					if (entidadIndex == 0 || entidadIndex == 2)
					{
						isListado(true);
						if(entidadIndex != 0)
						{
							cmbNombreEnt.setCaption("Nombre");
							u.llenarCombo(cmbNombreEnt, datos.getAllSRL());
						}
						else
						{
							cmbNombreEnt.setCaption("Número");
							u.llenarCombo(cmbNombreEnt, datos.getDtoRiego());
						}
					}
					else
						isListado(false);
				}
				
				private void isListado(boolean estado)
				{
					cmbNombreEnt.setVisible(estado);
					txtNombreEnt.setVisible(!estado);
					cmbNombreEnt.setValue("");
					txtNombreEnt.setValue("");
				}
			};
	private ClickListener nuevoListener = new ClickListener()
			{
				@Override
				public void buttonClick(ClickEvent event)
				{
					if(!tblListado.isVisible())
						showDialog(MODO_AGREGAR);
					else
						resetForm(MODO_AGREGAR);
				}
			};
	private ClickListener listadoListener = new ClickListener()
			{
				@Override
				public void buttonClick(ClickEvent event)
				{
					showDialog(MODO_LISTA);
				}
			};
	//endregion
	
	public Administrador(int tipo, Usuario user)
	{
		tipoPersona = tipo;
		usuario = user;
		u = new Utilerias();
		datos = new Datos();
		entidades = new LinkedList<String>();
		entidades.add("Distrito de Riego CONAGUA");
		entidades.add("Unidad de Riego CONAGUA");
		entidades.add("SRL");
		entidades.add("Institución Educativa");
		entidades.add("Empresa");
		entidades.add("Persona Física");
		entidades.add("Otra");
	}
	
	@Override
	public void inicializar()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		//Variables
		estados = datos.getEstados();
		//Textfields
		txtCURR.setEnabled(false);
		txtNombreEnt.setVisible(false);
		//Comboboxes
		u.setupCombo(cmbEdo, estados, null, null, false);
		u.setupCombo(cmbEntidad, entidades, null, null, false);
		u.setupCombo(cmbNombreEnt, null, null, null, true);
		cmbNombreEnt.setVisible(false);
		cmbEntidad.addValueChangeListener(nombreEntidadListener);
		//Datefields
		datIngreso.setWeekendDisabled(false);
		datIngreso.setDateTextReadOnly(true);
		//Buttons
		btnNuevo.addClickListener(nuevoListener);
		btnVolver.addClickListener(listadoListener);
		//Tables
		tblListado.setSelectable(true);
		tblListado.setSortEnabled(true);
		tblListado.setColumnCollapsingAllowed(true);
		tblListado.addItemClickListener(llenarFormListener);

		//Inicializar dependiendo del tipo de administrador que se quiera agregar/editar
		setupTipoAdmin();
		//Agregar las validaciones necesarias
		setValidaciones();
	}
	
	private void setupTipoAdmin()
	{
		if(tipoPersona == usuario.ADMINISTRADOR_GENERAL)
		{
			horLBotones.setVisible(false);
			idAdministrador = datos.getIdAdministradorGeneral(tipoPersona);
			llenarForm();
			setTipo(MODO_MODIFICAR);
		}
		else
			setTipo(MODO_LISTA);
	}
	
	@Override
	public void setTipo(int modoOperacion)
	{
		btnNuevo.setClickShortcut(KeyCode.N, ModifierKey.ALT);
		if(modoOperacion == MODO_LISTA)
		{
			mostrarTabla(true);
			u.llenarTabla(tblListado, datos.getAdministradores(tipoPersona));
			btnGuardar.removeClickShortcut();
			btnGuardar.setVisible(false);
			btnVolver.removeClickShortcut();
			btnVolver.setVisible(false);
			btnNuevo.setCaption("Agregar Nuevo");
		}
		else
		{
			mostrarTabla(false);
			btnGuardar.setClickShortcut(KeyCode.G, ModifierKey.ALT);
			btnGuardar.setVisible(true);
			if(tipoPersona == usuario.ADMINISTRADOR)
			{
				btnVolver.setClickShortcut(KeyCode.V, ModifierKey.ALT);
				btnVolver.setVisible(true);
			}
			
			if(modoOperacion == MODO_AGREGAR)
			{
				elementosCurrHabilitados(true);
				btnGuardar.removeClickListener(modificarListener);
				btnGuardar.addClickListener(agregarListener);
				btnGuardar.setCaption("Guardar");
				btnNuevo.setClickShortcut(KeyCode.L, ModifierKey.ALT);
				btnNuevo.setCaption("Limpiar");
			}
			else
			{
				elementosCurrHabilitados(false);
				btnGuardar.removeClickListener(agregarListener);
				btnGuardar.addClickListener(modificarListener);
				btnGuardar.setCaption("Guardar cambios");
				btnNuevo.setCaption("Agregar Nuevo");
			}
		}
	}
	
	private void mostrarTabla(boolean visible)
	{
		tblListado.setVisible(visible);
		verLDatos.setVisible(!visible);
	}
	
	private void elementosCurrHabilitados(boolean habilitado)
	{
		datIngreso.setEnabled(habilitado);
		cmbEdo.setEnabled(habilitado);
	}

	private void setValidaciones()
	{
		txtNombre.setMaxLength(40);
		txtApP.setMaxLength(20);
		txtApM.setMaxLength(20);
		
		txtTel.setMaxLength(10);
		txtCel.setMaxLength(10);
		txtEmail.setMaxLength(254);
		txtEmail.addValidator(u.getRegExEmail());
		
		txtPass.addValidator(u.getRegExPass());
	}

	private boolean validar()
	{
		if(txtNombre.getValue().isEmpty())
			return notificar("Se requiere especificar el nombre", txtNombre);
		if(txtApP.getValue().isEmpty() || txtApM.getValue().isEmpty())
			return notificar("Se requiere especificar ambos apellidos", txtApP);
		if(txtTel.getValue().isEmpty() && txtCel.getValue().isEmpty())
			return notificar("Se requiere especificar al menos un número de teléfono", txtTel);
		
		if(datIngreso.getValue() == null)
			return notificar("Se requiere especificar la fecha de ingreso", datIngreso);
		if(cmbEdo.getValue() == null)
			return notificar("Se requiere especificar el estado", cmbEdo);
		if(cmbEntidad.getValue() == null)
			return notificar("Se requiere especificar la entidad a la cual pertenece el administrador", cmbEntidad);
		if(cmbNombreEnt.isVisible() && cmbNombreEnt.getValue() == null)
			return notificar("Se requiere especificar el nombre de la entidad", cmbNombreEnt);
		if(txtNombreEnt.isVisible() && txtNombreEnt.getValue().isEmpty())
			return notificar("Se requiere especificar el nombre de la entidad", txtNombreEnt);
		if(txtCargo.getValue().isEmpty())
			return notificar("Se requiere especificar el cargo", txtCargo);
		
		if(txtUser.getValue().isEmpty())
			return notificar("Se requiere especificar el nombre de usuario", txtUser);
		if(txtPass.getValue().isEmpty())
			return notificar("Se requiere especificar la contraseña", txtPass);
		
		if(!txtPass.getValue().equals(txtPass2.getValue()))
			return notificar("Los valores de contraseña no coinciden", txtPass);
		
		return true;
	}
	
	@SuppressWarnings("rawtypes")
	private boolean notificar(String notificacion, AbstractField field)
	{
		Notification.show(notificacion, Notification.Type.ERROR_MESSAGE);
		field.focus();
		return false;
	}
	
	private LinkedList<Object> llenarListaDeParametros()
	{
		LinkedList<Object>valores = new LinkedList<Object>();
		valores.add(txtNombre.getValue());
		valores.add(txtApP.getValue());
		valores.add(txtApM.getValue());
		valores.add(txtTel.getValue());
		valores.add(txtCel.getValue());
		valores.add(txtEmail.getValue());
		valores.add(entidades.indexOf(cmbEntidad.getValue()));
		valores.add(((String)cmbEntidad.getValue()).equals("Distrito de Riego CONAGUA"));
		valores.add(((String)cmbEntidad.getValue()).equals("SRL"));
		valores.add(cmbNombreEnt.isVisible() ? cmbNombreEnt.getValue() : txtNombreEnt.getValue());
		valores.add(txtCargo.getValue());
		valores.add(txtUser.getValue());
		valores.add(txtPass.getValue());
		return valores;
	}

	private void showDialog(final int modo)
	{
		ConfirmDialog.show( this.getUI(),
							"Advertencia:",
							"Perderá todos los cambios realizados hasta el momento.\n¿Desea continuar?",
							"Si", "No",
							new ConfirmDialog.Listener()
							{
								public void onClose(ConfirmDialog dialog)
								{
									if (dialog.isConfirmed())
										resetForm(modo);
								}
							});
	}
	
	private void resetForm(int modo)
	{
		inicializar();
		setTipo(modo);
	}
	
	private void llenarForm()
	{
		LinkedList<Object> valores = datos.getAdministrador(idAdministrador);
		if(!valores.isEmpty())
		{
			setTipo(MODO_MODIFICAR);
			
			txtNombre.setValue((String)valores.remove());
			txtApP.setValue((String)valores.remove());
			txtApM.setValue((String)valores.remove());
			txtTel.setValue((String)valores.remove());
			txtCel.setValue((String)valores.remove());
			txtEmail.setValue((String)valores.remove());
			txtCURR.setValue((String)valores.remove());
			datIngreso.setLocalDate(u.fechaSQLToLocalDate((Date)valores.remove()));
			cmbEdo.select(valores.remove());
			cmbEntidad.setValue(entidades.get((Integer)valores.remove()));
			boolean isDR = (Boolean)valores.remove(), isSRL = (Boolean)valores.remove();
			if(isDR || isSRL)
				cmbNombreEnt.setValue(valores.remove());
			else
				txtNombreEnt.setValue((String)valores.remove());
			txtCargo.setValue((String)valores.remove());
			txtUser.setValue((String)valores.remove());
			txtPass.setValue((String)valores.remove());
			txtPass2.setValue(txtPass.getValue());
		}
		else
			Notification.show("Error al obtener el registro, comuníquese con el administrador.", Notification.Type.ERROR_MESSAGE);
	}
	//region UI
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// tblListado
		tblListado = new Table();
		tblListado
				.setCaption("* Dar doble click sobre un elemento para modificarlo");
		tblListado.setImmediate(false);
		tblListado.setWidth("801px");
		tblListado.setHeight("300px");
		mainLayout.addComponent(tblListado);
		
		// verLDatos
		verLDatos = buildVerLDatos();
		mainLayout.addComponent(verLDatos);
		
		// absLBotones
		absLBotones = buildAbsLBotones();
		mainLayout.addComponent(absLBotones);
		mainLayout.setComponentAlignment(absLBotones, new Alignment(24));
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerLDatos() {
		// common part: create layout
		verLDatos = new VerticalLayout();
		verLDatos.setImmediate(false);
		verLDatos.setWidth("-1px");
		verLDatos.setHeight("-1px");
		verLDatos.setMargin(false);
		verLDatos.setSpacing(true);
		
		// panGenerales
		panGenerales = buildPanGenerales();
		verLDatos.addComponent(panGenerales);
		
		// panContacto
		panContacto = buildPanContacto();
		verLDatos.addComponent(panContacto);
		
		// panEntidad
		panEntidad = buildPanEntidad();
		verLDatos.addComponent(panEntidad);
		
		// panUser
		panUser = buildPanUser();
		verLDatos.addComponent(panUser);
		
		return verLDatos;
	}

	@AutoGenerated
	private Panel buildPanGenerales() {
		// common part: create layout
		panGenerales = new Panel();
		panGenerales.setCaption("Datos Generales");
		panGenerales.setImmediate(false);
		panGenerales.setWidth("801px");
		panGenerales.setHeight("-1px");
		
		// verLGenerales
		verLGenerales = buildVerLGenerales();
		panGenerales.setContent(verLGenerales);
		
		return panGenerales;
	}

	@AutoGenerated
	private VerticalLayout buildVerLGenerales() {
		// common part: create layout
		verLGenerales = new VerticalLayout();
		verLGenerales.setImmediate(false);
		verLGenerales.setWidth("100.0%");
		verLGenerales.setHeight("-1px");
		verLGenerales.setMargin(false);
		
		// absLGenerales
		absLGenerales = buildAbsLGenerales();
		verLGenerales.addComponent(absLGenerales);
		
		return verLGenerales;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLGenerales() {
		// common part: create layout
		absLGenerales = new AbsoluteLayout();
		absLGenerales.setImmediate(false);
		absLGenerales.setWidth("100.0%");
		absLGenerales.setHeight("65px");
		
		// txtNombre
		txtNombre = new TextField();
		txtNombre.setCaption("Nombre");
		txtNombre.setImmediate(false);
		txtNombre.setWidth("340px");
		txtNombre.setHeight("25px");
		absLGenerales.addComponent(txtNombre, "top:28.0px;left:10.0px;");
		
		// txtApP
		txtApP = new TextField();
		txtApP.setCaption("Apellido Paterno");
		txtApP.setImmediate(false);
		txtApP.setWidth("200px");
		txtApP.setHeight("25px");
		absLGenerales.addComponent(txtApP, "top:28.0px;left:370.0px;");
		
		// txtApM
		txtApM = new TextField();
		txtApM.setCaption("Apellido Materno");
		txtApM.setImmediate(false);
		txtApM.setWidth("200px");
		txtApM.setHeight("25px");
		absLGenerales.addComponent(txtApM, "top:28.0px;left:590.0px;");
		
		return absLGenerales;
	}

	@AutoGenerated
	private Panel buildPanContacto() {
		// common part: create layout
		panContacto = new Panel();
		panContacto.setCaption("Contacto");
		panContacto.setImmediate(false);
		panContacto.setWidth("801px");
		panContacto.setHeight("-1px");
		
		// absLContacto
		absLContacto = buildAbsLContacto();
		panContacto.setContent(absLContacto);
		
		return panContacto;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLContacto() {
		// common part: create layout
		absLContacto = new AbsoluteLayout();
		absLContacto.setImmediate(false);
		absLContacto.setWidth("100.0%");
		absLContacto.setHeight("65px");
		
		// txtTel
		txtTel = new TextField();
		txtTel.setCaption("Teléfono Fijo (10dig)");
		txtTel.setImmediate(false);
		txtTel.setWidth("170px");
		txtTel.setHeight("25px");
		absLContacto.addComponent(txtTel, "top:28.0px;left:10.0px;");
		
		// txtCel
		txtCel = new TextField();
		txtCel.setCaption("Celular (10dig)");
		txtCel.setImmediate(false);
		txtCel.setWidth("170px");
		txtCel.setHeight("25px");
		absLContacto.addComponent(txtCel, "top:28.0px;left:200.0px;");
		
		// txtEmail
		txtEmail = new TextField();
		txtEmail.setCaption("Correo electrónico");
		txtEmail.setImmediate(true);
		txtEmail.setWidth("400px");
		txtEmail.setHeight("25px");
		absLContacto.addComponent(txtEmail, "top:28.0px;left:390.0px;");
		
		return absLContacto;
	}

	@AutoGenerated
	private Panel buildPanEntidad() {
		// common part: create layout
		panEntidad = new Panel();
		panEntidad.setImmediate(false);
		panEntidad.setWidth("801px");
		panEntidad.setHeight("-1px");
		
		// verLEntidad
		verLEntidad = buildVerLEntidad();
		panEntidad.setContent(verLEntidad);
		
		return panEntidad;
	}

	@AutoGenerated
	private VerticalLayout buildVerLEntidad() {
		// common part: create layout
		verLEntidad = new VerticalLayout();
		verLEntidad.setImmediate(false);
		verLEntidad.setWidth("100.0%");
		verLEntidad.setHeight("100.0%");
		verLEntidad.setMargin(false);
		
		// absLEntidad1
		absLEntidad1 = buildAbsLEntidad1();
		verLEntidad.addComponent(absLEntidad1);
		
		// absLEntidad2
		absLEntidad2 = buildAbsLEntidad2();
		verLEntidad.addComponent(absLEntidad2);
		
		// absLEntidad3
		absLEntidad3 = buildAbsLEntidad3();
		verLEntidad.addComponent(absLEntidad3);
		
		return verLEntidad;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLEntidad1() {
		// common part: create layout
		absLEntidad1 = new AbsoluteLayout();
		absLEntidad1.setImmediate(false);
		absLEntidad1.setWidth("100.0%");
		absLEntidad1.setHeight("55px");
		
		// txtCURR
		txtCURR = new TextField();
		txtCURR.setCaption("CURR (Clave Unica de Registro RIGRAT)");
		txtCURR.setImmediate(false);
		txtCURR.setWidth("250px");
		txtCURR.setHeight("25px");
		absLEntidad1.addComponent(txtCURR, "top:28.0px;left:10.0px;");
		
		// datIngreso
		datIngreso = new TuningDateField();
		datIngreso.setCaption("Fecha de Ingreso al Programa");
		datIngreso.setImmediate(false);
		datIngreso.setWidth("170px");
		datIngreso.setHeight("25px");
		absLEntidad1.addComponent(datIngreso, "top:28.0px;left:280.0px;");
		
		// cmbEdo
		cmbEdo = new ComboBox();
		cmbEdo.setCaption("Estado");
		cmbEdo.setImmediate(true);
		cmbEdo.setWidth("320px");
		cmbEdo.setHeight("25px");
		absLEntidad1.addComponent(cmbEdo, "top:28.0px;left:470.0px;");
		
		return absLEntidad1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLEntidad2() {
		// common part: create layout
		absLEntidad2 = new AbsoluteLayout();
		absLEntidad2.setImmediate(false);
		absLEntidad2.setWidth("100.0%");
		absLEntidad2.setHeight("45px");
		
		// cmbEntidad
		cmbEntidad = new ComboBox();
		cmbEntidad.setCaption("Personal de:");
		cmbEntidad.setImmediate(true);
		cmbEntidad.setWidth("270px");
		cmbEntidad.setHeight("25px");
		absLEntidad2.addComponent(cmbEntidad, "top:18.0px;left:10.0px;");
		
		// cmbNombreEnt
		cmbNombreEnt = new ComboBox();
		cmbNombreEnt.setImmediate(true);
		cmbNombreEnt.setWidth("490px");
		cmbNombreEnt.setHeight("25px");
		absLEntidad2.addComponent(cmbNombreEnt, "top:18.0px;left:300.0px;");
		
		// txtNombreEnt
		txtNombreEnt = new TextField();
		txtNombreEnt.setCaption("Nombre");
		txtNombreEnt.setImmediate(false);
		txtNombreEnt.setWidth("490px");
		txtNombreEnt.setHeight("25px");
		absLEntidad2.addComponent(txtNombreEnt, "top:18.0px;left:300.0px;");
		
		return absLEntidad2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLEntidad3() {
		// common part: create layout
		absLEntidad3 = new AbsoluteLayout();
		absLEntidad3.setImmediate(false);
		absLEntidad3.setWidth("100.0%");
		absLEntidad3.setHeight("55px");
		
		// txtCargo
		txtCargo = new TextField();
		txtCargo.setCaption("Cargo");
		txtCargo.setImmediate(false);
		txtCargo.setWidth("380px");
		txtCargo.setHeight("25px");
		absLEntidad3.addComponent(txtCargo, "top:18.0px;left:10.0px;");
		
		return absLEntidad3;
	}

	@AutoGenerated
	private Panel buildPanUser() {
		// common part: create layout
		panUser = new Panel();
		panUser.setImmediate(false);
		panUser.setWidth("801px");
		panUser.setHeight("-1px");
		
		// absLUser
		absLUser = buildAbsLUser();
		panUser.setContent(absLUser);
		
		return panUser;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLUser() {
		// common part: create layout
		absLUser = new AbsoluteLayout();
		absLUser.setImmediate(false);
		absLUser.setWidth("100.0%");
		absLUser.setHeight("65px");
		
		// txtUser
		txtUser = new TextField();
		txtUser.setCaption("Nombre de Usuario");
		txtUser.setImmediate(false);
		txtUser.setWidth("260px");
		txtUser.setHeight("25px");
		absLUser.addComponent(txtUser, "top:28.0px;left:10.0px;");
		
		// txtPass
		txtPass = new PasswordField();
		txtPass.setCaption("Contraseña");
		txtPass.setImmediate(true);
		txtPass.setWidth("240px");
		txtPass.setHeight("25px");
		absLUser.addComponent(txtPass, "top:28.0px;left:290.0px;");
		
		// txtPass2
		txtPass2 = new PasswordField();
		txtPass2.setCaption("Repetir Contraseña");
		txtPass2.setImmediate(false);
		txtPass2.setWidth("240px");
		txtPass2.setHeight("25px");
		absLUser.addComponent(txtPass2, "top:28.0px;left:550.0px;");
		
		return absLUser;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLBotones() {
		// common part: create layout
		absLBotones = new AbsoluteLayout();
		absLBotones.setImmediate(false);
		absLBotones.setWidth("801px");
		absLBotones.setHeight("30px");
		
		// btnGuardar
		btnGuardar = new Button();
		btnGuardar.setCaption("Guardar");
		btnGuardar.setImmediate(true);
		btnGuardar.setWidth("-1px");
		btnGuardar.setHeight("-1px");
		absLBotones.addComponent(btnGuardar, "right:0.0px;bottom:0.0px;");
		
		// horLBotones
		horLBotones = buildHorLBotones();
		absLBotones.addComponent(horLBotones, "bottom:0.0px;left:0.0px;");
		
		return absLBotones;
	}

	@AutoGenerated
	private HorizontalLayout buildHorLBotones() {
		// common part: create layout
		horLBotones = new HorizontalLayout();
		horLBotones.setImmediate(false);
		horLBotones.setWidth("-1px");
		horLBotones.setHeight("-1px");
		horLBotones.setMargin(false);
		horLBotones.setSpacing(true);
		
		// btnNuevo
		btnNuevo = new Button();
		btnNuevo.setCaption("Agregar Nuevo");
		btnNuevo.setImmediate(true);
		btnNuevo.setWidth("-1px");
		btnNuevo.setHeight("-1px");
		horLBotones.addComponent(btnNuevo);
		
		// btnVolver
		btnVolver = new Button();
		btnVolver.setCaption("Volver");
		btnVolver.setImmediate(true);
		btnVolver.setWidth("-1px");
		btnVolver.setHeight("-1px");
		horLBotones.addComponent(btnVolver);
		
		return horLBotones;
	}
	
	//endregion
}