package com.saprigrat.ui.forms.nivelesDeAdministracion;

import java.sql.Date;
import java.util.LinkedList;

import org.joda.time.LocalDate;
import org.vaadin.addons.tuningdatefield.TuningDateField;
import org.vaadin.dialogs.ConfirmDialog;

import com.saprigrat.data.Datos;
import com.saprigrat.data.Utilerias;
import com.saprigrat.entities.Usuario;
import com.saprigrat.enums.TipoUsuario;
import com.saprigrat.ui.interfaces.Formulario;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.event.ItemClickEvent.ItemClickListener;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.event.ShortcutAction.ModifierKey;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class Productor extends CustomComponent implements Formulario
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	//region controles autogenerados
	
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout absLBotones;
	@AutoGenerated
	private HorizontalLayout horLBotones;
	@AutoGenerated
	private Button btnVolver;
	@AutoGenerated
	private Button btnNuevo;
	@AutoGenerated
	private Button btnGuardar;
	@AutoGenerated
	private VerticalLayout verLDatos;
	@AutoGenerated
	private Panel panContacto;
	@AutoGenerated
	private AbsoluteLayout absLContacto;
	@AutoGenerated
	private TextField txtEmail;
	@AutoGenerated
	private TextField txtCel;
	@AutoGenerated
	private TextField txtTel;
	@AutoGenerated
	private Panel panDireccion;
	@AutoGenerated
	private VerticalLayout verLDireccion;
	@AutoGenerated
	private AbsoluteLayout absLDireccion3;
	@AutoGenerated
	private TextField txtCP;
	@AutoGenerated
	private TextField txtNoInt;
	@AutoGenerated
	private TextField txtNoExt;
	@AutoGenerated
	private TextField txtCalle;
	@AutoGenerated
	private AbsoluteLayout absLDireccion2;
	@AutoGenerated
	private TextField txtCol;
	@AutoGenerated
	private TextField txtLoc;
	@AutoGenerated
	private AbsoluteLayout absLDireccion1;
	@AutoGenerated
	private ComboBox cmbMpio;
	@AutoGenerated
	private ComboBox cmbEdo;
	@AutoGenerated
	private Panel panGenerales;
	@AutoGenerated
	private VerticalLayout verLGenerales;
	@AutoGenerated
	private AbsoluteLayout absLGenerales1;
	@AutoGenerated
	private TuningDateField datIngreso;
	@AutoGenerated
	private TextField txtApM;
	@AutoGenerated
	private TextField txtApP;
	@AutoGenerated
	private TextField txtNombre;
	@AutoGenerated
	private VerticalLayout verLListado;
	@AutoGenerated
	private Label lblRowCount;
	@AutoGenerated
	private Table tblListado;
	@AutoGenerated
	private AbsoluteLayout absLRespCURR;
	@AutoGenerated
	private Panel panCURR;
	@AutoGenerated
	private AbsoluteLayout absLCURR;
	@AutoGenerated
	private TextField txtCURR;
	@AutoGenerated
	private Panel panResponsable;
	@AutoGenerated
	private AbsoluteLayout absLResponsable;
	@AutoGenerated
	private ComboBox cmbResponsable;
	//endregion
	private Utilerias u;
	private Usuario usuario;
	private Datos datos;
	private LinkedList<String> estados;
	private int idProductor;

	//region eventos
	private ClickListener agregarListener = new ClickListener()
			{
				@Override
				public void buttonClick(ClickEvent event)
				{
					if(validar())
					{
						LocalDate fecha = datIngreso.getLocalDate();
						String curr =   u.setDecimalFormat("00", usuario.PRODUCTOR) +
										u.setDecimalFormat("00", fecha.getYearOfCentury()) +
										u.setDecimalFormat("00", fecha.getMonthOfYear()) +
										u.setDecimalFormat("00", fecha.getDayOfMonth()) +
										u.setDecimalFormat("00", estados.indexOf(cmbEdo.getValue()) + 1);

						LinkedList<Object> valores = llenarListaDeParametros();
						valores.add(0, curr);
						valores.add(5, u.fechaUtilToSQL(datIngreso.getLocalDate().toDate()));
						
						curr = datos.registrarProductor(valores);
						if(!curr.isEmpty())
						{
							String[]currArr = curr.split(" ");
							Notification.show("Registro añadido correctamente.\nCURR asignado: " + currArr[0], Notification.Type.TRAY_NOTIFICATION);
							txtCURR.setValue(currArr[0]);
							//Se cambia a modo de modificación
							setTipo(MODO_MODIFICAR);
							idProductor = Integer.parseInt(currArr[1]);
						}
						else
							Notification.show("Error al añadir registro, comuníquese con el administrador.", Notification.Type.ERROR_MESSAGE);
					}
				}
			};
	private ClickListener modificarListener = new ClickListener()
			{
				@Override
				public void buttonClick(ClickEvent event)
				{
					if(validar())
					{
						LinkedList<Object> valores = llenarListaDeParametros();
						valores.add(0, idProductor);
						
						if(!datos.modificarProductor(valores).isEmpty())
							Notification.show("Registro modificado correctamente.", Notification.Type.TRAY_NOTIFICATION);
						else
							Notification.show("Error al modificar registro, comuníquese con el administrador.", Notification.Type.ERROR_MESSAGE);
					}
				}
			};
	private ItemClickListener llenarFormListener = new ItemClickListener()
			{
				@Override
				public void itemClick(ItemClickEvent event)
				{
					if(event.isDoubleClick())
					{
						idProductor = Integer.parseInt(tblListado.getItemCaption(event.getItem()).split(" ")[0]);
						LinkedList<Object> valores = datos.getProductor(idProductor);
						if(!valores.isEmpty())
						{
							setTipo(MODO_MODIFICAR);

							txtCURR.setValue((String)valores.remove());
							cmbResponsable.select(valores.remove());
							txtNombre.setValue((String)valores.remove());
							txtApP.setValue((String)valores.remove());
							txtApM.setValue((String)valores.remove());
							datIngreso.setLocalDate(u.fechaSQLToLocalDate((Date)valores.remove()));
							cmbEdo.select(valores.remove());
							cmbMpio.select(valores.remove());
							txtLoc.setValue((String)valores.remove());
							txtCol.setValue((String)valores.remove());
							txtCalle.setValue((String)valores.remove());
							txtNoExt.setValue((String)valores.remove());
							txtNoInt.setValue((String)valores.remove());
							txtCP.setValue((String)valores.remove());
							txtTel.setValue((String)valores.remove());
							txtCel.setValue((String)valores.remove());
							txtEmail.setValue((String)valores.remove());
						}
						else
							Notification.show("Error al obtener el registro, comuníquese con el administrador.", Notification.Type.ERROR_MESSAGE);
					}
				}
			};
	private ValueChangeListener llenarTablaListener = new ValueChangeListener()
			{
				@Override
				public void valueChange(ValueChangeEvent event)
				{
					lblRowCount.setValue(u.llenarTabla(tblListado, datos.getProductores(((String)cmbResponsable.getValue()).split(" ")[0]), TipoUsuario.PRODUCTOR.toString()));
				}
			};
	private ClickListener nuevoListener = new ClickListener()
			{
				@Override
				public void buttonClick(ClickEvent event)
				{
					if(!verLListado.isVisible())
						showDialog(MODO_AGREGAR);
					else
						resetForm(MODO_AGREGAR);
				}
			};
	private ClickListener volverEliminarListener = new ClickListener()
			{
				@Override
				public void buttonClick(ClickEvent event)
				{
					if(btnVolver.getCaption().equals("Volver"))
						showDialog(MODO_LISTA);
					else
					{
						if(tblListado.getValue() != null)
						{
							ConfirmDialog.show( event.getButton().getUI(),
												"Atención:",
												"Está a punto de eliminar un usuario y esta acción no se puede deshacer." +
												"\n¿Desea continuar?", "Si", "No",
												new ConfirmDialog.Listener()
												{
													public void onClose(ConfirmDialog dialog)
													{
														if (dialog.isConfirmed())
														{
															int rowSel = (Integer)tblListado.getValue();
															rowSel = (Integer)tblListado.getContainerProperty(rowSel, "ID").getValue();
															String status = datos.eliminarProductor(rowSel);
															if(!status.isEmpty() && status.indexOf("err") == -1)
															{
																lblRowCount.setValue(u.llenarTabla(tblListado, datos.getProductores(((String)cmbResponsable.getValue()).split(" ")[0]), TipoUsuario.PRODUCTOR.toString()));
																u.notificar("El usuario fue eliminado correctamente", null, u.MSJ_BANDEJA);
															}
															else
																if(status.indexOf("Tec") == -1)
																	u.notificar("El usuario no se pudo eliminar porque tiene parcelas asignadas, si desea continuar elimine primero las parcelas e inténtelo de nuevo", null, u.MSJ_ADVERTENCIA);
																else
																	u.notificar("Error al eliminar registro, comuníquese con el administrador", null, u.MSJ_ERROR);
														}
													}
												});
						}
						else
							u.notificar("No ha seleccionado ningún usuario a eliminar", null, u.MSJ_ADVERTENCIA);
					}
				}
			};
	private ValueChangeListener llenarMpiosListener = new ValueChangeListener()
			{
				@Override
				public void valueChange(ValueChangeEvent event)
				{
					u.llenarCombo(cmbMpio, datos.getMunicipios((String)cmbEdo.getValue()));
				}
			};
	//endregion
														
	public Productor(Usuario user)
	{
		usuario = user;
		u = new Utilerias();
		datos = new Datos();
	}

	@Override
	public void inicializar()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		//Variables
		estados = datos.getEstados();
		//Textfields
		txtCURR.setEnabled(false);
		//Comboboxes
		u.setupCombo(cmbResponsable, null, "Busque por nombre o CURR.", FilteringMode.CONTAINS, false, true);
		u.setupCombo(cmbEdo, estados, null, null, false, true);
		u.setupCombo(cmbMpio, null, null, null, false, true);
		cmbEdo.addValueChangeListener(llenarMpiosListener);
		//Datefields
		u.setupCalendario(datIngreso, true);
		//Tables
		tblListado.setSelectable(true);
		tblListado.setSortEnabled(true);
		tblListado.setColumnCollapsingAllowed(true);
		tblListado.addItemClickListener(llenarFormListener);
		//Buttons
		btnNuevo.addClickListener(nuevoListener);
		btnVolver.addClickListener(volverEliminarListener);
		
		//Inicializar en modo lista
		setTipo(MODO_LISTA);
		//Agregar las validaciones necesarias
		setValidaciones();
	}
	
	@Override
	public void setTipo(int modoOperacion)
	{
		btnNuevo.setClickShortcut(KeyCode.N, ModifierKey.ALT);
		if(modoOperacion == MODO_LISTA)
		{
			cmbResponsable.addValueChangeListener(llenarTablaListener);
			setResponsableDirecto(usuario.getTipo());
			mostrarTabla(true);
			btnGuardar.removeClickShortcut();
			btnGuardar.setVisible(false);
			btnVolver.setClickShortcut(KeyCode.E, ModifierKey.ALT);
			btnVolver.setCaption("Eliminar");
			btnNuevo.setCaption("Agregar Nuevo");
		}
		else
		{
			cmbResponsable.removeValueChangeListener(llenarTablaListener);
			mostrarTabla(false);
			btnGuardar.setClickShortcut(KeyCode.G, ModifierKey.ALT);
			btnGuardar.setVisible(true);
			btnVolver.setClickShortcut(KeyCode.V, ModifierKey.ALT);
			btnVolver.setCaption("Volver");
			
			if(modoOperacion == MODO_AGREGAR)
			{
				elementosCurrHabilitados(true);
				btnGuardar.removeClickListener(modificarListener);
				btnGuardar.addClickListener(agregarListener);
				btnGuardar.setCaption("Guardar");
				btnNuevo.setClickShortcut(KeyCode.L, ModifierKey.ALT);
				btnNuevo.setCaption("Limpiar");
			}
			else
			{
				elementosCurrHabilitados(false);
				btnGuardar.removeClickListener(agregarListener);
				btnGuardar.addClickListener(modificarListener);
				btnGuardar.setCaption("Guardar cambios");
				btnNuevo.setCaption("Agregar Nuevo");
			}
		}
	}
	
	private void setResponsableDirecto(int tipoAgregando)
	{
		if(tipoAgregando == usuario.RESPONSABLE)
		{
			String item = usuario.getCURR() + " " + usuario.getNombre() + " " +
						  usuario.getApPaterno() + " " + usuario.getApMaterno();
			cmbResponsable.addItem(item);
			cmbResponsable.select(item);
			cmbResponsable.setEnabled(false);
		}
		else
		{
			u.llenarCombo(cmbResponsable, datos.getRespTecnicos(usuario.getCURR(), tipoAgregando, usuario.RESPONSABLE));
			if(cmbResponsable.size() == 0)
			{
				mainLayout.removeAllComponents();
				Notification.show("Imposible registrar. Se requiere que exista en la base de datos al menos un responsable técnico a quien pueda ser asignada esta persona.", Notification.Type.ERROR_MESSAGE);
			}
		}
	}

	private void mostrarTabla(boolean visible)
	{
		panCURR.setVisible(!visible);
		verLListado.setVisible(visible);
		verLDatos.setVisible(!visible);
	}

	private void elementosCurrHabilitados(boolean habilitado)
	{
		if(usuario.getTipo() > usuario.ADMINISTRADOR)
			cmbResponsable.setEnabled(habilitado);
		datIngreso.setEnabled(habilitado);
		cmbEdo.setEnabled(habilitado);
	}
	
	private void setValidaciones()
	{
		txtNombre.setMaxLength(40);
		txtApP.setMaxLength(20);
		txtApM.setMaxLength(20);
		
		txtCol.setMaxLength(40);
		txtCalle.setMaxLength(40);
		txtNoExt.setMaxLength(5);
		txtNoInt.setMaxLength(5);
		txtCP.setMaxLength(5);
		txtCP.addValidator(u.getRegExCP());
		
		txtTel.setMaxLength(10);
		txtCel.setMaxLength(10);
		txtEmail.setMaxLength(254);
		txtEmail.addValidator(u.getRegExEmail());
	}
	
	private boolean validar()
	{
		if(cmbResponsable.getValue() == null)
			return notificar("Se requiere especificar el responsable técnico", cmbResponsable);
		if(txtNombre.getValue().isEmpty())
			return notificar("Se requiere especificar el nombre", txtNombre);
		if(txtApP.getValue().isEmpty() || txtApM.getValue().isEmpty())
			return notificar("Se requiere especificar ambos apellidos", txtApP);
		if(datIngreso.getValue() == null)
			return notificar("Se requiere especificar la fecha de ingreso", datIngreso);
		if(cmbEdo.getValue() == null)
			return notificar("Se requiere especificar el estado", cmbEdo);
		if(cmbMpio.getValue() == null)
			return notificar("Se requiere especificar el municipio", cmbMpio);
		if(txtLoc.getValue().isEmpty())
			return notificar("Se requiere especificar la localidad", txtLoc);
		if(txtCalle.getValue().isEmpty())
			return notificar("Se requiere especificar la calle", txtCalle);
		if(txtNoExt.getValue().isEmpty())
			return notificar("Se requiere especificar el número exterior", txtNoExt);
		if(txtTel.getValue().isEmpty() && txtCel.getValue().isEmpty())
			return notificar("Se requiere especificar al menos un número de teléfono", txtTel);
		
		return true;
	}
	
	@SuppressWarnings("rawtypes")
	private boolean notificar(String notificacion, AbstractField field)
	{
		Notification.show(notificacion, Notification.Type.ERROR_MESSAGE);
		field.focus();
		return false;
	}

	private LinkedList<Object> llenarListaDeParametros()
	{
		LinkedList<Object> valores = new LinkedList<Object>();
		valores.add(((String)cmbResponsable.getValue()).split(" ")[0]);
		valores.add(txtNombre.getValue());
		valores.add(txtApP.getValue());
		valores.add(txtApM.getValue());
		valores.add(cmbEdo.getValue());
		valores.add(cmbMpio.getValue());
		valores.add(txtLoc.getValue());
		valores.add(txtCol.getValue());
		valores.add(txtCalle.getValue());
		valores.add(txtNoExt.getValue());
		valores.add(txtNoInt.getValue());
		valores.add(txtCP.getValue());
		valores.add(txtTel.getValue());
		valores.add(txtCel.getValue());
		valores.add(txtEmail.getValue());
		return valores;
	}

	private void showDialog(final int modo)
	{
		ConfirmDialog.show( this.getUI(),
							"Advertencia:",
							"Perderá todos los cambios realizados hasta el momento.\n¿Desea continuar?",
							"Si", "No",
							new ConfirmDialog.Listener()
							{
								public void onClose(ConfirmDialog dialog)
								{
									if (dialog.isConfirmed())
										resetForm(modo);
								}
							});
	}
	
	private void resetForm(int modo)
	{
		Object respSelected = cmbResponsable.getValue();
		inicializar();
		setTipo(modo);
		cmbResponsable.setValue(respSelected);
	}
	//region UI
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// absLRespCURR
		absLRespCURR = buildAbsLRespCURR();
		mainLayout.addComponent(absLRespCURR);
		
		// verLListado
		verLListado = buildVerLListado();
		mainLayout.addComponent(verLListado);
		
		// verLDatos
		verLDatos = buildVerLDatos();
		mainLayout.addComponent(verLDatos);
		
		// absLBotones
		absLBotones = buildAbsLBotones();
		mainLayout.addComponent(absLBotones);
		mainLayout.setComponentAlignment(absLBotones, new Alignment(24));
		
		return mainLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLRespCURR() {
		// common part: create layout
		absLRespCURR = new AbsoluteLayout();
		absLRespCURR.setImmediate(false);
		absLRespCURR.setWidth("801px");
		absLRespCURR.setHeight("66px");
		
		// panResponsable
		panResponsable = buildPanResponsable();
		absLRespCURR.addComponent(panResponsable, "top:0.0px;left:0.0px;");
		
		// panCURR
		panCURR = buildPanCURR();
		absLRespCURR.addComponent(panCURR, "top:0.0px;right:0.0px;");
		
		return absLRespCURR;
	}

	@AutoGenerated
	private Panel buildPanResponsable() {
		// common part: create layout
		panResponsable = new Panel();
		panResponsable.setCaption("Responsable Técnico");
		panResponsable.setImmediate(false);
		panResponsable.setWidth("501px");
		panResponsable.setHeight("-1px");
		
		// absLResponsable
		absLResponsable = buildAbsLResponsable();
		panResponsable.setContent(absLResponsable);
		
		return panResponsable;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLResponsable() {
		// common part: create layout
		absLResponsable = new AbsoluteLayout();
		absLResponsable.setImmediate(false);
		absLResponsable.setWidth("100.0%");
		absLResponsable.setHeight("45px");
		
		// cmbResponsable
		cmbResponsable = new ComboBox();
		cmbResponsable.setImmediate(true);
		cmbResponsable.setWidth("480px");
		cmbResponsable.setHeight("25px");
		absLResponsable.addComponent(cmbResponsable, "top:10.0px;left:10.0px;");
		
		return absLResponsable;
	}

	@AutoGenerated
	private Panel buildPanCURR() {
		// common part: create layout
		panCURR = new Panel();
		panCURR.setCaption("CURR (Clave Unica de Registro RIGRAT)");
		panCURR.setImmediate(false);
		panCURR.setWidth("271px");
		panCURR.setHeight("-1px");
		
		// absLCURR
		absLCURR = buildAbsLCURR();
		panCURR.setContent(absLCURR);
		
		return panCURR;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCURR() {
		// common part: create layout
		absLCURR = new AbsoluteLayout();
		absLCURR.setImmediate(false);
		absLCURR.setWidth("100.0%");
		absLCURR.setHeight("45px");
		
		// txtCURR
		txtCURR = new TextField();
		txtCURR.setImmediate(false);
		txtCURR.setWidth("250px");
		txtCURR.setHeight("25px");
		absLCURR.addComponent(txtCURR, "top:10.0px;left:10.0px;");
		
		return absLCURR;
	}
	@AutoGenerated
	private VerticalLayout buildVerLListado() {
		// common part: create layout
		verLListado = new VerticalLayout();
		verLListado.setImmediate(false);
		verLListado.setWidth("-1px");
		verLListado.setHeight("-1px");
		verLListado.setMargin(false);
		
		// tblListado
		tblListado = new Table();
		tblListado
				.setCaption("* Dar doble click sobre un elemento para modificarlo");
		tblListado.setImmediate(false);
		tblListado.setWidth("801px");
		tblListado.setHeight("300px");
		verLListado.addComponent(tblListado);
		
		// lblRowCount
		lblRowCount = new Label();
		lblRowCount.setImmediate(false);
		lblRowCount.setWidth("-1px");
		lblRowCount.setHeight("-1px");
		lblRowCount.setValue("0 registros encontrados");
		verLListado.addComponent(lblRowCount);
		
		return verLListado;
	}

	@AutoGenerated
	private VerticalLayout buildVerLDatos() {
		// common part: create layout
		verLDatos = new VerticalLayout();
		verLDatos.setImmediate(false);
		verLDatos.setWidth("-1px");
		verLDatos.setHeight("-1px");
		verLDatos.setMargin(false);
		verLDatos.setSpacing(true);
		
		// panGenerales
		panGenerales = buildPanGenerales();
		verLDatos.addComponent(panGenerales);
		
		// panDireccion
		panDireccion = buildPanDireccion();
		verLDatos.addComponent(panDireccion);
		
		// panContacto
		panContacto = buildPanContacto();
		verLDatos.addComponent(panContacto);
		
		return verLDatos;
	}

	@AutoGenerated
	private Panel buildPanGenerales() {
		// common part: create layout
		panGenerales = new Panel();
		panGenerales.setCaption("Datos Generales");
		panGenerales.setImmediate(false);
		panGenerales.setWidth("801px");
		panGenerales.setHeight("-1px");
		
		// verLGenerales
		verLGenerales = buildVerLGenerales();
		panGenerales.setContent(verLGenerales);
		
		return panGenerales;
	}

	@AutoGenerated
	private VerticalLayout buildVerLGenerales() {
		// common part: create layout
		verLGenerales = new VerticalLayout();
		verLGenerales.setImmediate(false);
		verLGenerales.setWidth("100.0%");
		verLGenerales.setHeight("-1px");
		verLGenerales.setMargin(false);
		
		// absLGenerales1
		absLGenerales1 = buildAbsLGenerales1();
		verLGenerales.addComponent(absLGenerales1);
		
		return verLGenerales;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLGenerales1() {
		// common part: create layout
		absLGenerales1 = new AbsoluteLayout();
		absLGenerales1.setImmediate(false);
		absLGenerales1.setWidth("100.0%");
		absLGenerales1.setHeight("65px");
		
		// txtNombre
		txtNombre = new TextField();
		txtNombre.setCaption("Nombre");
		txtNombre.setImmediate(false);
		txtNombre.setWidth("250px");
		txtNombre.setHeight("25px");
		absLGenerales1.addComponent(txtNombre, "top:28.0px;left:10.0px;");
		
		// txtApP
		txtApP = new TextField();
		txtApP.setCaption("Apellido Paterno");
		txtApP.setImmediate(false);
		txtApP.setWidth("140px");
		txtApP.setHeight("25px");
		absLGenerales1.addComponent(txtApP, "top:28.0px;left:280.0px;");
		
		// txtApM
		txtApM = new TextField();
		txtApM.setCaption("Apellido Materno");
		txtApM.setImmediate(false);
		txtApM.setWidth("140px");
		txtApM.setHeight("25px");
		absLGenerales1.addComponent(txtApM, "top:28.0px;left:440.0px;");
		
		// datIngreso
		datIngreso = new TuningDateField();
		datIngreso.setCaption("Fecha de Ingreso al Programa");
		datIngreso.setImmediate(false);
		datIngreso.setWidth("190px");
		datIngreso.setHeight("25px");
		absLGenerales1.addComponent(datIngreso, "top:28.0px;left:600.0px;");
		
		return absLGenerales1;
	}

	@AutoGenerated
	private Panel buildPanDireccion() {
		// common part: create layout
		panDireccion = new Panel();
		panDireccion.setCaption("Dirección");
		panDireccion.setImmediate(false);
		panDireccion.setWidth("801px");
		panDireccion.setHeight("-1px");
		
		// verLDireccion
		verLDireccion = buildVerLDireccion();
		panDireccion.setContent(verLDireccion);
		
		return panDireccion;
	}

	@AutoGenerated
	private VerticalLayout buildVerLDireccion() {
		// common part: create layout
		verLDireccion = new VerticalLayout();
		verLDireccion.setImmediate(false);
		verLDireccion.setWidth("100.0%");
		verLDireccion.setHeight("100.0%");
		verLDireccion.setMargin(false);
		
		// absLDireccion1
		absLDireccion1 = buildAbsLDireccion1();
		verLDireccion.addComponent(absLDireccion1);
		
		// absLDireccion2
		absLDireccion2 = buildAbsLDireccion2();
		verLDireccion.addComponent(absLDireccion2);
		
		// absLDireccion3
		absLDireccion3 = buildAbsLDireccion3();
		verLDireccion.addComponent(absLDireccion3);
		
		return verLDireccion;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDireccion1() {
		// common part: create layout
		absLDireccion1 = new AbsoluteLayout();
		absLDireccion1.setImmediate(false);
		absLDireccion1.setWidth("100.0%");
		absLDireccion1.setHeight("55px");
		
		// cmbEdo
		cmbEdo = new ComboBox();
		cmbEdo.setCaption("Estado");
		cmbEdo.setImmediate(true);
		cmbEdo.setWidth("260px");
		cmbEdo.setHeight("25px");
		absLDireccion1.addComponent(cmbEdo, "top:28.0px;left:10.0px;");
		
		// cmbMpio
		cmbMpio = new ComboBox();
		cmbMpio.setCaption("Municipio");
		cmbMpio.setImmediate(true);
		cmbMpio.setWidth("500px");
		cmbMpio.setHeight("25px");
		absLDireccion1.addComponent(cmbMpio, "top:28.0px;left:290.0px;");
		
		return absLDireccion1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDireccion2() {
		// common part: create layout
		absLDireccion2 = new AbsoluteLayout();
		absLDireccion2.setImmediate(false);
		absLDireccion2.setWidth("100.0%");
		absLDireccion2.setHeight("45px");
		
		// txtLoc
		txtLoc = new TextField();
		txtLoc.setCaption("Localidad");
		txtLoc.setImmediate(false);
		txtLoc.setWidth("380px");
		txtLoc.setHeight("25px");
		absLDireccion2.addComponent(txtLoc, "top:18.0px;left:10.0px;");
		
		// txtCol
		txtCol = new TextField();
		txtCol.setCaption("Colonia");
		txtCol.setImmediate(false);
		txtCol.setWidth("380px");
		txtCol.setHeight("25px");
		absLDireccion2.addComponent(txtCol, "top:18.0px;left:410.0px;");
		
		return absLDireccion2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDireccion3() {
		// common part: create layout
		absLDireccion3 = new AbsoluteLayout();
		absLDireccion3.setImmediate(false);
		absLDireccion3.setWidth("100.0%");
		absLDireccion3.setHeight("55px");
		
		// txtCalle
		txtCalle = new TextField();
		txtCalle.setCaption("Calle");
		txtCalle.setImmediate(false);
		txtCalle.setWidth("450px");
		txtCalle.setHeight("25px");
		absLDireccion3.addComponent(txtCalle, "top:18.0px;left:10.0px;");
		
		// txtNoExt
		txtNoExt = new TextField();
		txtNoExt.setCaption("Núm. Ext.");
		txtNoExt.setImmediate(false);
		txtNoExt.setWidth("90px");
		txtNoExt.setHeight("25px");
		absLDireccion3.addComponent(txtNoExt, "top:18.0px;left:480.0px;");
		
		// txtNoInt
		txtNoInt = new TextField();
		txtNoInt.setCaption("Núm. Int.");
		txtNoInt.setImmediate(false);
		txtNoInt.setWidth("90px");
		txtNoInt.setHeight("25px");
		absLDireccion3.addComponent(txtNoInt, "top:18.0px;left:590.0px;");
		
		// txtCP
		txtCP = new TextField();
		txtCP.setCaption("C.P.");
		txtCP.setImmediate(true);
		txtCP.setWidth("90px");
		txtCP.setHeight("25px");
		absLDireccion3.addComponent(txtCP, "top:18.0px;left:700.0px;");
		
		return absLDireccion3;
	}

	@AutoGenerated
	private Panel buildPanContacto() {
		// common part: create layout
		panContacto = new Panel();
		panContacto.setCaption("Contacto");
		panContacto.setImmediate(false);
		panContacto.setWidth("801px");
		panContacto.setHeight("-1px");
		
		// absLContacto
		absLContacto = buildAbsLContacto();
		panContacto.setContent(absLContacto);
		
		return panContacto;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLContacto() {
		// common part: create layout
		absLContacto = new AbsoluteLayout();
		absLContacto.setImmediate(false);
		absLContacto.setWidth("100.0%");
		absLContacto.setHeight("65px");
		
		// txtTel
		txtTel = new TextField();
		txtTel.setCaption("Teléfono Fijo (10dig)");
		txtTel.setImmediate(false);
		txtTel.setWidth("170px");
		txtTel.setHeight("25px");
		absLContacto.addComponent(txtTel, "top:28.0px;left:10.0px;");
		
		// txtCel
		txtCel = new TextField();
		txtCel.setCaption("Celular (10dig)");
		txtCel.setImmediate(false);
		txtCel.setWidth("170px");
		txtCel.setHeight("25px");
		absLContacto.addComponent(txtCel, "top:28.0px;left:200.0px;");
		
		// txtEmail
		txtEmail = new TextField();
		txtEmail.setCaption("Correo electrónico");
		txtEmail.setImmediate(true);
		txtEmail.setWidth("400px");
		txtEmail.setHeight("25px");
		absLContacto.addComponent(txtEmail, "top:28.0px;left:390.0px;");
		
		return absLContacto;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLBotones() {
		// common part: create layout
		absLBotones = new AbsoluteLayout();
		absLBotones.setImmediate(false);
		absLBotones.setWidth("801px");
		absLBotones.setHeight("30px");
		
		// btnGuardar
		btnGuardar = new Button();
		btnGuardar.setCaption("Guardar");
		btnGuardar.setImmediate(true);
		btnGuardar.setWidth("-1px");
		btnGuardar.setHeight("-1px");
		absLBotones.addComponent(btnGuardar, "right:0.0px;bottom:0.0px;");
		
		// horLBotones
		horLBotones = buildHorLBotones();
		absLBotones.addComponent(horLBotones, "bottom:0.0px;left:0.0px;");
		
		return absLBotones;
	}

	@AutoGenerated
	private HorizontalLayout buildHorLBotones() {
		// common part: create layout
		horLBotones = new HorizontalLayout();
		horLBotones.setImmediate(false);
		horLBotones.setWidth("-1px");
		horLBotones.setHeight("-1px");
		horLBotones.setMargin(false);
		horLBotones.setSpacing(true);
		
		// btnNuevo
		btnNuevo = new Button();
		btnNuevo.setCaption("Agregar Nuevo");
		btnNuevo.setImmediate(true);
		btnNuevo.setWidth("-1px");
		btnNuevo.setHeight("-1px");
		horLBotones.addComponent(btnNuevo);
		
		// btnVolver
		btnVolver = new Button();
		btnVolver.setCaption("Volver");
		btnVolver.setImmediate(true);
		btnVolver.setWidth("-1px");
		btnVolver.setHeight("-1px");
		horLBotones.addComponent(btnVolver);
		
		return horLBotones;
	}
	
	//endregion
}