package com.saprigrat.ui.forms.parcelas;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.LinkedList;

import org.vaadin.dialogs.ConfirmDialog;

import com.saprigrat.entities.Usuario;
import com.saprigrat.enums.TipoUsuario;
import com.saprigrat.ui.interfaces.FormParcela;
import com.saprigrat.ui.interfaces.Formulario;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.validator.RegexpValidator;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.event.ItemClickEvent.ItemClickListener;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.event.ShortcutAction.ModifierKey;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class Riego extends CustomComponent implements Formulario, FormParcela
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	//region controles autogenerados
	
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout absLBotones;
	@AutoGenerated
	private HorizontalLayout horLBotones;
	@AutoGenerated
	private Button btnVolver;
	@AutoGenerated
	private Button btnNuevo;
	@AutoGenerated
	private Button btnGuardar;
	@AutoGenerated
	private VerticalLayout verLDatos;
	@AutoGenerated
	private Panel panObservaciones;
	@AutoGenerated
	private AbsoluteLayout absLObservaciones;
	@AutoGenerated
	private TextArea txtObservaciones;
	@AutoGenerated
	private VerticalLayout verLRiegos;
	@AutoGenerated
	private Table tblRiegos;
	@AutoGenerated
	private AbsoluteLayout absLRiego;
	@AutoGenerated
	private HorizontalLayout horLBotonesRiego;
	@AutoGenerated
	private Button btnCancel;
	@AutoGenerated
	private Button btnAdd;
	@AutoGenerated
	private Panel panRiego;
	@AutoGenerated
	private VerticalLayout verLRiego;
	@AutoGenerated
	private AbsoluteLayout absLRiego2;
	@AutoGenerated
	private Label lblLaminaCalc;
	@AutoGenerated
	private TextField txtLaminaCalc;
	@AutoGenerated
	private Label lblSuperficie;
	@AutoGenerated
	private TextField txtSuperficie;
	@AutoGenerated
	private AbsoluteLayout absLDirectos;
	@AutoGenerated
	private Label lblDatoDirecto;
	@AutoGenerated
	private TextField txtDatoDirecto;
	@AutoGenerated
	private DateField datFechaRiego;
	@AutoGenerated
	private AbsoluteLayout absLCalculables;
	@AutoGenerated
	private Label lblGasto;
	@AutoGenerated
	private TextField txtGasto;
	@AutoGenerated
	private DateField datFin;
	@AutoGenerated
	private DateField datInicio;
	@AutoGenerated
	private AbsoluteLayout absLRiego1;
	@AutoGenerated
	private ComboBox cmbDatosRiegoDisponibles;
	@AutoGenerated
	private TextField txtEtapa;
	@AutoGenerated
	private TextField txtNoRiego;
	@AutoGenerated
	private Panel panDetalles;
	@AutoGenerated
	private AbsoluteLayout absLDetalles;
	@AutoGenerated
	private Label lblLaminaAnt;
	@AutoGenerated
	private TextField txtLaminaAnt;
	@AutoGenerated
	private ComboBox cmbTipoRiego;
	@AutoGenerated
	private ComboBox cmbParcela;
	@AutoGenerated
	private VerticalLayout verLListado;
	@AutoGenerated
	private Label lblRowCount;
	@AutoGenerated
	private Table tblListado;
	@AutoGenerated
	private HorizontalLayout horLRespProd;
	@AutoGenerated
	private Panel panProductor;
	@AutoGenerated
	private AbsoluteLayout absLProductor;
	@AutoGenerated
	private ComboBox cmbProductor;
	@AutoGenerated
	private Panel panResponsable;
	@AutoGenerated
	private AbsoluteLayout absLResponsable;
	@AutoGenerated
	private ComboBox cmbResponsable;
	
	//endregion
	private Usuario usuario;
	private String formatoFechaTbl, formatoFechaForm, formatoFechaTblSH, formatoFechaFormSH;
	private LinkedList<String> datosRiegoDisponibles;
	private int idRiego, idParcela;
	private LinkedList<LinkedList<Object>> listaRiego;
	
	//region eventos
	private ClickListener agregarListener = new ClickListener()
			{
				@Override
				public void buttonClick(ClickEvent event)
				{
					if(validar())
					{
						LinkedList<Object> valores = llenarListaDeParametros();
						if(btnGuardar.getCaption().equals("Guardar"))
						{
							valores.add(0, cmbParcela.getValue());
							
							String status = datos.registrarRiego(valores);
							if(!status.isEmpty())
							{
								u.msjGuardado("El riego", "");
								//Se cambia a modo de modificación
								setTipo(MODO_MODIFICAR);
								idRiego = Integer.parseInt(status);
							}
							else
								u.msjNoGuardado("el riego");
						}
						else
						{
							valores.add(0, idRiego);
							
							if(!datos.modificarRiego(valores).isEmpty())
								u.msjModificado("El riego");
							else
								u.msjNoModificado("el riego");
						}
					}
				}
			};
	private ItemClickListener llenarFormListener = new ItemClickListener()
			{
				@Override
				public void itemClick(ItemClickEvent event)
				{
					if(event.isDoubleClick())
					{
						idRiego = (Integer)event.getItem().getItemProperty("ID").getValue();
						LinkedList<Object> valores = datos.getRiego(idRiego);
						if(!valores.isEmpty())
						{
							setTipo(MODO_MODIFICAR);
							
							u.llenarCombo(cmbProductor, datos.getRespProductores(((String)cmbResponsable.getValue()).split(" ")[0]));
							cmbProductor.setValue(valores.remove());
							u.llenarCombo(cmbParcela, datos.getCtasPadron(((String)cmbProductor.getValue()).split(" ")[0]));
							cmbParcela.setValue(valores.remove());
							cmbTipoRiego.setValue(valores.remove());
							txtLaminaAnt.setValue(u.doubleToString(valores.remove()));
							txtObservaciones.setValue((String)valores.remove());
							setupListaRiego(datos.getListaRiego(idRiego));
						}
						else
							u.msjRegistroNoObtenido();
					}
				}
				
				public void setupListaRiego(LinkedList<Object[]> listaRiegoBD)
				{
					if(listaRiegoBD.size() > 0)
					{
						listaRiego.clear();
						for(Object[] riego : listaRiegoBD)
						{
							LinkedList<Object> row = new LinkedList<Object>();
							row.add(0);
							for(Object valor : riego)
								row.add(valor);
							listaRiego.add(row);
						}
						recargarListaRiego();
					}
				}
			};
	private ValueChangeListener llenarTablaOProductoresListener = new ValueChangeListener()
			{
				@Override
				public void valueChange(ValueChangeEvent event)
				{
					String curr = ((String)cmbResponsable.getValue()).split(" ")[0];
					if(verLListado.isVisible())
						lblRowCount.setValue(u.llenarTabla(tblListado, horLRespProd.isVisible() ? datos.getRiegos(curr)
																								: datos.getRiegosByParcela(idParcela), "riego"));
					else
					{
						cmbParcela.removeAllItems();
						u.llenarCombo(cmbProductor, datos.getRespProductores(curr));
					}
				}
			};
	private ClickListener nuevoListener = new ClickListener()
			{
				@Override
				public void buttonClick(ClickEvent event)
				{
					if(horLRespProd.isVisible())
					{
						if(!verLListado.isVisible())
							showDialog(MODO_AGREGAR);
						else
							resetForm(MODO_AGREGAR);
					}
					else
					{
						idRiego = 0;
						cmbTipoRiego.setValue(null);
						txtLaminaAnt.setValue("");
						txtObservaciones.setValue("");
						
						tblRiegos.removeAllItems();
						listaRiego.clear();
						
						setTipo(MODO_AGREGAR);
					}
				}
			};
	private ClickListener volverListener = new ClickListener()
			{
				@Override
				public void buttonClick(ClickEvent event)
				{
					if(horLRespProd.isVisible())
						showDialog(MODO_LISTA);
					else
						setTipo(MODO_LISTA);
					llenarTablaByParcela();
				}
			};
	private ValueChangeListener llenarParcelasListener = new ValueChangeListener()
			{
				@Override
				public void valueChange(ValueChangeEvent event)
				{
					if(cmbProductor.size() != 0)
					{
						u.llenarCombo(cmbParcela, datos.getCtasPadron(((String)cmbProductor.getValue()).split(" ")[0]));
						if(cmbParcela.size() == 0)
							u.notificar("No se podrá agregar el registro ya que este " + TipoUsuario.PRODUCTOR + " no tiene asociada ninguna parcela", null, u.MSJ_ERROR);
					}
					else
						u.notificar("No se podrá agregar el registro ya que este " + TipoUsuario.RESPONSABLE_TECNICO + " no tiene asignado a ningún " + TipoUsuario.PRODUCTOR, null, u.MSJ_ERROR);
				}
			};
	private ClickListener addRiegoListener = new ClickListener()
			{
				@Override
				public void buttonClick(ClickEvent event)
				{
					if(panRiego.isVisible())
					{
						if(validarRiego())
						{
							if(btnAdd.getCaption().equals("Agregar"))
								listaRiego.add(getRiego());
							else
								listaRiego.set(Integer.parseInt(txtNoRiego.getValue()) - 1, getRiego());
							recargarListaRiego();
							ocultarFormRiego();
						}
					}
					else
						inicializarRiego();
				}

				private void inicializarRiego()
				{
					txtNoRiego.setValue((listaRiego.size() + 1) + "");
					txtEtapa.setValue("");
					cmbDatosRiegoDisponibles.setValue(datosRiegoDisponibles.get(0));
					datInicio.setValue(null);
					datFin.setValue(null);
					txtGasto.setValue("");
					datFechaRiego.setValue(null);
					txtDatoDirecto.setValue("");
					txtSuperficie.setValue("");
					txtLaminaCalc.setValue("");
					datosRiegoSolicitados(true);
					mostrarFormRiego();
				}
			};
	private ClickListener cancelarEliminarListener = new ClickListener()
			{
				@Override
				public void buttonClick(ClickEvent event)
				{
					if(btnCancel.getCaption().equals("Cancelar"))
						ocultarFormRiego();
					else
					{
						if(tblRiegos.getValue() != null)
						{
							ConfirmDialog.show( event.getButton().getUI(),
												"Atención:",
												"Está a punto de eliminar un riego y esta acción no se puede deshacer." +
												"\n¿Desea continuar?", "Si", "No",
												new ConfirmDialog.Listener()
												{
													public void onClose(ConfirmDialog dialog)
													{
														if (dialog.isConfirmed())
														{
															int rowId = (Integer)tblRiegos.getValue();
															rowId = (Integer)tblRiegos.getContainerProperty(rowId,"Núm.").getValue();
															listaRiego.remove(rowId - 1);
															recargarListaRiego();
														}
													}
												});
						}
						else
							u.notificar("No ha seleccionado ningún riego a eliminar", null, u.MSJ_ADVERTENCIA);
					}
				}
			};
	private ItemClickListener cargarRiegoListener = new ItemClickListener()
			{
				@Override
				public void itemClick(ItemClickEvent event)
				{
					if(event.isDoubleClick())
					{
						Item item = event.getItem();
						txtNoRiego.setValue((Integer)item.getItemProperty("Núm.").getValue() + "");
						txtEtapa.setValue(item.getItemProperty("Etapa Fenológica").getValue() + "");
						cmbDatosRiegoDisponibles.setValue(datosRiegoDisponibles.get((Integer)item.getItemProperty("DatosRiegoIndex").getValue()));
						switch(getDatosRiegoIndex())
						{
							case 0: datInicio.setValue(getFecha((String)item.getItemProperty("Fecha").getValue(), formatoFechaTbl));
									datFin.setValue(getFecha((String)item.getItemProperty("Fecha Fin").getValue(), formatoFechaTbl));
									txtGasto.setValue(item.getItemProperty("Gasto (L/s)").getValue() + "");
									datFechaRiego.setValue(null);
									txtDatoDirecto.setValue("");
									break;
							case 1: datInicio.setValue(null);
									datFin.setValue(null);
									txtGasto.setValue("");
									datFechaRiego.setValue(getFecha((String)item.getItemProperty("Fecha").getValue(), formatoFechaTblSH));
									txtDatoDirecto.setValue(item.getItemProperty("Lámina Aplicada (cm)").getValue() + "");
									break;
							case 2: datInicio.setValue(null);
									datFin.setValue(null);
									txtGasto.setValue("");
									datFechaRiego.setValue(getFecha((String)item.getItemProperty("Fecha").getValue(), formatoFechaTblSH));
									txtDatoDirecto.setValue(item.getItemProperty("Volumen (m³)").getValue() + "");
									break;
						}
						txtSuperficie.setValue(item.getItemProperty("Superficie Regada (ha)").getValue() + "");
						txtLaminaCalc.setValue(u.doubleToString(item.getItemProperty("Lámina Calculada (cm)").getValue()));
						
						mostrarFormRiego();
						btnAdd.setCaption("Modificar");
					}
				}
				
				private java.util.Date getFecha(String fechaStr, String formato)
				{
					try
					{
						return new SimpleDateFormat(formato).parse(fechaStr);
					}
					catch (ParseException e) { return null; }
				}
			};
	private ValueChangeListener cambiarDatosRiegoListener = new ValueChangeListener()
			{
				@Override
				public void valueChange(ValueChangeEvent event)
				{
					switch(getDatosRiegoIndex())
					{
						case 0: datosRiegoSolicitados(true);
								break;
						case 1: datosRiegoSolicitados(false);
								txtDatoDirecto.setCaption("Lámina Aplicada");
								lblDatoDirecto.setValue("cm");
								break;
						case 2: datosRiegoSolicitados(false);
								txtDatoDirecto.setCaption("Volumen");
								lblDatoDirecto.setValue("m³");
								break;
					}
				}
			};
	//endregion
	
	public Riego() {}
	public Riego(Usuario user) { init(user); }

	@Override
	public void init(Usuario user)
	{
		formatoFechaTbl = "dd-MM-yyyy, hh:mm a";
		formatoFechaForm = "dd/MM/yyyy, hh:mm a";
		formatoFechaTblSH = "dd-MM-yyyy";
		formatoFechaFormSH = "dd/MM/yyyy";
		usuario = user;
		datosRiegoDisponibles = datos.getDatosRiegoDisponibles();
	}

	@Override
	public void inicializar()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);

		//Variables
		listaRiego = new LinkedList<LinkedList<Object>>();
		//Textos
		txtNoRiego.setEnabled(false);
		//Combos
		u.setupCombo(cmbResponsable, null, "Busque por nombre o CURR.", FilteringMode.CONTAINS, false, true);
		u.setupCombo(cmbProductor, null, "Busque por nombre o CURR.", FilteringMode.CONTAINS, false, true);
		u.setupCombo(cmbParcela, null, "Busque por número de cuenta de padrón.", null, false, true);
		u.setupCombo(cmbTipoRiego, datos.getTipoRiego(), null, null, false, false);
		u.setupCombo(cmbDatosRiegoDisponibles, datosRiegoDisponibles, null, null, false, false);
		cmbResponsable.addValueChangeListener(llenarTablaOProductoresListener);
		cmbProductor.addValueChangeListener(llenarParcelasListener);
		cmbDatosRiegoDisponibles.addValueChangeListener(cambiarDatosRiegoListener);
		cmbDatosRiegoDisponibles.setValue(datosRiegoDisponibles.get(0));
		//Calendarios
		setCalendario(datInicio, Resolution.MINUTE, formatoFechaForm);
		setCalendario(datFin, Resolution.MINUTE, formatoFechaForm);
		setCalendario(datFechaRiego, Resolution.DAY, formatoFechaFormSH);
		//Botones
		btnAdd.addClickListener(addRiegoListener);
		btnCancel.addClickListener(cancelarEliminarListener);
		btnNuevo.addClickListener(nuevoListener);
		btnVolver.addClickListener(volverListener);
		btnGuardar.addClickListener(agregarListener);
		btnAdd.setClickShortcut(KeyCode.A, ModifierKey.ALT);
		//Tablas
		tblListado.setSelectable(true);
		tblListado.setSortEnabled(true);
		tblListado.setColumnCollapsingAllowed(true);
		tblListado.addItemClickListener(llenarFormListener);
		tblRiegos.addContainerProperty("Núm.", Object.class, null);
		tblRiegos.addContainerProperty("Fecha", Object.class, null);
		tblRiegos.addContainerProperty("Fecha Fin", Object.class, null);
		tblRiegos.addContainerProperty("Etapa Fenológica", Object.class, null);
		tblRiegos.addContainerProperty("Gasto (L/s)", Object.class, null);
		tblRiegos.addContainerProperty("Tiempo (h)", Object.class, null);
		tblRiegos.addContainerProperty("Volumen (m³)", Object.class, null);
		tblRiegos.addContainerProperty("Superficie Regada (ha)", Object.class, null);
		tblRiegos.addContainerProperty("Lámina Aplicada (cm)", Object.class, null);
		tblRiegos.addContainerProperty("Lámina Calculada (cm)", Object.class, null);
		tblRiegos.addContainerProperty("Eficiencia (%)", Object.class, null);
		tblRiegos.addContainerProperty("DatosRiegoIndex", Object.class, null);
		tblRiegos.setSelectable(true);
		tblRiegos.setSortEnabled(true);
		tblRiegos.setColumnCollapsingAllowed(true);
		tblRiegos.setColumnCollapsed("Fecha Fin", true);
		tblRiegos.setColumnCollapsed("DatosRiegoIndex", true);
		tblRiegos.addItemClickListener(cargarRiegoListener);
		//Inicializar en modo lista
		setTipo(MODO_LISTA);
		//Agregar las validaciones necesarias
		setValidaciones();
	}

	@Override
	public void setTipo(int modoOperacion)
	{
		btnNuevo.setClickShortcut(KeyCode.N, ModifierKey.ALT);
		if(modoOperacion == MODO_LISTA)
		{
			setResponsableTecnico(usuario.getTipo());
			mostrarTabla(true);
			btnGuardar.removeClickShortcut();
			btnGuardar.setVisible(false);
			btnVolver.removeClickShortcut();
			btnVolver.setVisible(false);
			btnNuevo.setCaption("Agregar Nuevo");
		}
		else
		{
			mostrarTabla(false);
			ocultarFormRiego();
			btnGuardar.setClickShortcut(KeyCode.G, ModifierKey.ALT);
			btnGuardar.setVisible(true);
			btnVolver.setClickShortcut(KeyCode.V, ModifierKey.ALT);
			btnVolver.setVisible(true);
			
			if(modoOperacion == MODO_AGREGAR)
			{
				elementosIdHabilitados(true);
				btnGuardar.setCaption("Guardar");
				btnNuevo.setClickShortcut(KeyCode.L, ModifierKey.ALT);
				btnNuevo.setCaption("Limpiar");
			}
			else
			{
				elementosIdHabilitados(false);
				btnGuardar.setCaption("Guardar cambios");
				btnNuevo.setCaption("Agregar Nuevo");
			}
		}
	}
	
	@Override
	public void quitarListeners ()
	{
		cmbResponsable.removeValueChangeListener(llenarTablaOProductoresListener);
		cmbProductor.removeValueChangeListener(llenarParcelasListener);
		
		horLRespProd.setVisible(false);
		cmbParcela.setVisible(false);
		absLDetalles.removeComponent(cmbTipoRiego);
		absLDetalles.removeComponent(txtLaminaAnt);
		absLDetalles.removeComponent(lblLaminaAnt);
		absLDetalles.addComponent(cmbTipoRiego, "top:28.0px;left:10.0px;");
		absLDetalles.addComponent(txtLaminaAnt, "top:28.0px;left:210.0px;");
		absLDetalles.addComponent(lblLaminaAnt, "top:32.0px;left:355.0px;");
		panDetalles.setWidth("381px");
	}

	@Override
	public void setParcela (int idParcela, String padron)
	{
		u.llenarCombo(cmbParcela, padron);
		this.idParcela = idParcela;
		llenarTablaByParcela();
	}

	@Override
	public void setResponsable (String responsable)
	{
		u.llenarCombo(cmbResponsable, responsable);
	}

	@Override
	public void setProductor (String productor)
	{
		u.llenarCombo(cmbProductor, productor);
	}
	
	private void setResponsableTecnico(int tipoAgregando)
	{
		if(horLRespProd.isVisible())
		{
			if(tipoAgregando != usuario.RESPONSABLE)
				u.llenarCombo(cmbResponsable, datos.getRespTecnicos(usuario.getCURR(), tipoAgregando, usuario.RESPONSABLE));
			else
				u.llenarCombo(cmbResponsable, usuario.getCURR() + " " + usuario.getNombre() + " " +
											  usuario.getApPaterno() + " " + usuario.getApMaterno());
			if(cmbResponsable.size() == 0)
			{
				mainLayout.removeAllComponents();
				u.notificar("Imposible registrar riego, se requiere que exista al menos una parcela a la cual aplicarlo", null, u.MSJ_ERROR);
			}
		}
	}

	private void llenarTablaByParcela ()
	{
		if(idParcela > 0)
			lblRowCount.setValue(u.llenarTabla(tblListado, datos.getRiegosByParcela(idParcela), "riego"));
		else
		{
			lblRowCount.setValue(u.llenarTabla(tblListado, new LinkedList<Object[]>(), "riego"));
			setTipo(MODO_LISTA);
		}
	}

	private void mostrarTabla(boolean estado)
	{
		panProductor.setVisible(!estado);
		verLListado.setVisible(estado);
		verLDatos.setVisible(!estado);
	}
	
	private void mostrarFormRiego()
	{
		btnCancel.setCaption("Cancelar");
		btnCancel.setClickShortcut(KeyCode.C, ModifierKey.ALT);
		panRiego.setVisible(true);
		absLRiego.setHeight("157px");
		txtEtapa.focus();
	}
	
	private void ocultarFormRiego()
	{
		btnAdd.setCaption("Agregar");
		btnAdd.setClickShortcut(KeyCode.A, ModifierKey.ALT);
		btnCancel.setCaption("Eliminar");
		btnCancel.setClickShortcut(KeyCode.E, ModifierKey.ALT);
		panRiego.setVisible(false);
		absLRiego.setHeight("30px");
	}
	
	private void datosRiegoSolicitados(boolean sonCalculables)
	{
		absLCalculables.setVisible(sonCalculables);
		absLDirectos.setVisible(!sonCalculables);
	}
	
	private void elementosIdHabilitados(boolean habilitado)
	{
		cmbResponsable.setEnabled(habilitado);
		cmbProductor.setEnabled(habilitado);
		cmbParcela.setEnabled(habilitado);
	}

	private void setCalendario(DateField cal, Resolution resolucion, String formato)
	{
		cal.setResolution(resolucion);
		cal.setValue(new java.util.Date());
		cal.setDateFormat(formato);
	}

	private void setValidaciones()
	{
		RegexpValidator esDecimal = u.getRegExDecimal();
		
		txtLaminaAnt.addValidator(esDecimal);
		txtGasto.addValidator(esDecimal);
		txtDatoDirecto.addValidator(esDecimal);
		txtSuperficie.addValidator(esDecimal);
		txtLaminaCalc.addValidator(esDecimal);
	}
	
	private boolean validar()
	{
		if(cmbResponsable.getValue() == null)
			return u.notificar("Se requiere especificar el responsable técnico", cmbResponsable, u.MSJ_ERROR);
		if(cmbProductor.getValue() == null)
			return u.notificar("Se requiere especificar el usuario", cmbProductor, u.MSJ_ERROR);
		if(cmbParcela.getValue() == null)
			return u.notificar("Se requiere especificar la parcela a la que se aplica el riego", cmbParcela, u.MSJ_ERROR);

		if(cmbTipoRiego.getValue() == null)
			return u.notificar("Se requiere especificar el método de riego", cmbTipoRiego, u.MSJ_ERROR);
		
		if(!txtLaminaAnt.isValid())
			return u.notificar("Se requiere especificar un valor estríctamente numérico para la lámina del ciclo anterior", txtLaminaAnt, u.MSJ_ERROR);

		return true;
	}
	
	private boolean validarRiego()
	{
		if(txtEtapa.getValue() == null)
			return u.notificar("Se requiere especificar la etapa fenológica", txtEtapa, u.MSJ_ERROR);

		if(getDatosRiegoIndex() == 0)
		{
			if(datInicio.getValue() == null)
				return u.notificar("Se requiere especificar la fecha y hora de inicio", datInicio, u.MSJ_ERROR);
			if(datFin.getValue() == null)
				return u.notificar("Se requiere especificar la fecha y hora de fin", datFin, u.MSJ_ERROR);
			if(txtGasto.getValue().isEmpty() || !txtGasto.isValid())
				return u.notificar("Se requiere especificar un valor estríctamente numérico para el gasto", txtGasto, u.MSJ_ERROR);
		}
		else
		{
			if(datFechaRiego.getValue() == null)
				return u.notificar("Se requiere especificar la fecha de riego", datFechaRiego, u.MSJ_ERROR);
			if(txtDatoDirecto.getValue().isEmpty() || !txtDatoDirecto.isValid())
				return u.notificar("Se requiere especificar un valor estríctamente numérico para " +
								 (getDatosRiegoIndex() == 1 ? "la lámina aplicada" : "el volumen"), txtDatoDirecto, u.MSJ_ERROR);
		}
		
		if(txtSuperficie.getValue().isEmpty() || !txtSuperficie.isValid())
			return u.notificar("Se requiere especificar un valor estríctamente numérico para la superficie", txtSuperficie, u.MSJ_ERROR);
		else
			if(Double.parseDouble(txtSuperficie.getValue()) == 0)
				return u.notificar("La superficie no puede ser igual a 0", txtSuperficie, u.MSJ_ERROR);
		
		if(!txtLaminaCalc.isValid())
			return u.notificar("Se requiere especificar un valor estríctamente numérico para la lámina calculada", txtLaminaCalc, u.MSJ_ERROR);
		
		return true;
	}

	private LinkedList<Object> llenarListaDeParametros()
	{
		LinkedList<Object> valores = new LinkedList<Object>();
		valores.add(cmbTipoRiego.getValue());
		valores.add(u.stringToDouble(txtLaminaAnt.getValue()));
		
		LinkedList<Object> arrs = getArreglosRiego();
		valores.add((String[]) arrs.pop());
		valores.add((String[]) arrs.pop());
		valores.add((String[]) arrs.pop());
		valores.add((Double[]) arrs.pop());
		valores.add((Integer[]) arrs.pop());
		valores.add((Double[]) arrs.pop());
		valores.add((Double[]) arrs.pop());
		valores.add((Double[]) arrs.pop());
		valores.add((Double[]) arrs.pop());
		valores.add((Double[]) arrs.pop());
		valores.add((Integer[]) arrs.pop());
		valores.add(listaRiego.size());
		
		valores.add(txtObservaciones.getValue());
		return valores;
	}
	
	private LinkedList<Object> getArreglosRiego()
	{
		int rows = listaRiego.size();
		String[] arrFechaIni = new String[rows],
				 arrFechaFin = new String[rows],
				 arrEtapa = new String[rows];
		Integer[] arrTiempo = new Integer[rows],
				  arrDatRIndex = new Integer[rows];
		Double[] arrGasto = new Double[rows],
				 arrVolumen = new Double[rows],
				 arrSuperficie = new Double[rows],
				 arrLamApl = new Double[rows],
				 arrLamCalc = new Double[rows],
				 arrEficiencia = new Double[rows];
		
		for(int i = 0; i < rows; i++)
		{
			LinkedList<Object> riego = new LinkedList<Object>();
			riego.addAll(listaRiego.get(i));
			riego.remove();
			
			arrFechaIni[i] = (String) riego.pop();
			arrFechaFin[i] = (String) riego.pop();
			arrEtapa[i] = (String) riego.pop();
			arrGasto[i] = (Double) riego.pop();
			arrTiempo[i] = (Integer) riego.pop();
			arrVolumen[i] = (Double) riego.pop();
			arrSuperficie[i] = (Double) riego.pop();
			arrLamApl[i] = (Double) riego.pop();
			arrLamCalc[i] = (Double) riego.pop();
			arrEficiencia[i] = (Double) riego.pop();
			arrDatRIndex[i] = (Integer) riego.pop();
		}
		
		LinkedList<Object> arreglos = new LinkedList<Object>();
		arreglos.add(arrFechaIni);
		arreglos.add(arrFechaFin);
		arreglos.add(arrEtapa);
		arreglos.add(arrGasto);
		arreglos.add(arrTiempo);
		arreglos.add(arrVolumen);
		arreglos.add(arrSuperficie);
		arreglos.add(arrLamApl);
		arreglos.add(arrLamCalc);
		arreglos.add(arrEficiencia);
		arreglos.add(arrDatRIndex);
		
		return arreglos;
	}
	
	private LinkedList<Object> getRiego()
	{
		Integer datRIndex = getDatosRiegoIndex(),
				tiempo = 0;
		Double  superficie = u.stringToDouble(txtSuperficie.getValue()),
				gasto = 0D,
				volumen = 0D,
				laminaApl = 0D,
				laminaCalc = u.stringToDouble(txtLaminaCalc.getValue());
		String  fechaIni = "",
				fechaFin = "";
		
		LinkedList<Object> row = new LinkedList<Object>();
		row.add(0);
		if(datRIndex == 0)
		{
			tiempo = (int)((datFin.getValue().getTime() - datInicio.getValue().getTime()) / 3600000);
			gasto = u.stringToDouble(txtGasto.getValue());
			volumen = gasto * 3600 * tiempo / 1000; //Gasto[L/s]*3600:[L/h] -> Gasto[L/h]*Tiempo[h]:[L] -> [L]/1000 = Volumen[m3]
			laminaApl = (volumen / (superficie * 10000)) * 100; //Superficie[ha]*10000:[m2] -> Volumen[m3]/Superficie[m2]:[m] -> [m]*100 = LaminaApl[cm]
			fechaIni = new SimpleDateFormat(formatoFechaTbl).format(datInicio.getValue());
			fechaFin = new SimpleDateFormat(formatoFechaTbl).format(datFin.getValue());
		}
		else
		{
			fechaIni = new SimpleDateFormat(formatoFechaTblSH).format(datFechaRiego.getValue());
			if(datRIndex == 1)
			{
				laminaApl = u.stringToDouble(txtDatoDirecto.getValue());
				volumen = (superficie * laminaApl) / 10;
			}
			else
			{
				volumen = u.stringToDouble(txtDatoDirecto.getValue());
				laminaApl = (volumen * 10) / superficie;
			}
		}
		
		row.add(fechaIni);
		row.add(fechaFin);
		row.add(txtEtapa.getValue());
		row.add(gasto);
		row.add(tiempo);
		row.add(volumen);
		row.add(superficie);
		row.add(laminaApl);
		row.add(laminaCalc);
		row.add(laminaCalc != null ? ((laminaCalc / laminaApl) * 100) : null);
		row.add(datRIndex);
		
		return row;
	}
	
	private void recargarListaRiego()
	{
		tblRiegos.removeAllItems();
		for(int i = 0; i < listaRiego.size(); i++)
		{
			LinkedList<Object> riego = listaRiego.get(i);
			riego.set(0, i + 1);
			
			Object[] arreglo = riego.toArray();
			int datosDisp = (Integer)riego.getLast();
			if(datosDisp > 0)
			{
				arreglo[4] = "-";
				arreglo[5] = "-";
			}
			
			tblRiegos.addItem(arreglo, null);
		}
	}
	
	private void showDialog(final int modo)
	{
		ConfirmDialog.show( this.getUI(),
							"Advertencia:",
							"Perderá todos los cambios realizados hasta el momento.\n¿Desea continuar?",
							"Si", "No",
							new ConfirmDialog.Listener()
							{
								public void onClose(ConfirmDialog dialog)
								{
									if (dialog.isConfirmed())
										resetForm(modo);
								}
							});
	}
	
	private void resetForm(int modo)
	{
		Object respSelected = cmbResponsable.getValue();
		inicializar();
		setTipo(modo);
		cmbResponsable.setValue(respSelected);
	}
	
	private int getDatosRiegoIndex()
	{
		return datosRiegoDisponibles.indexOf(cmbDatosRiegoDisponibles.getValue());
	}
	//region UI
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// horLRespProd
		horLRespProd = buildHorLRespProd();
		mainLayout.addComponent(horLRespProd);
		
		// verLListado
		verLListado = buildVerLListado();
		mainLayout.addComponent(verLListado);
		
		// verLDatos
		verLDatos = buildVerLDatos();
		mainLayout.addComponent(verLDatos);
		
		// absLBotones
		absLBotones = buildAbsLBotones();
		mainLayout.addComponent(absLBotones);
		mainLayout.setComponentAlignment(absLBotones, new Alignment(24));
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorLRespProd() {
		// common part: create layout
		horLRespProd = new HorizontalLayout();
		horLRespProd.setImmediate(false);
		horLRespProd.setWidth("801px");
		horLRespProd.setHeight("-1px");
		horLRespProd.setMargin(false);
		
		// panResponsable
		panResponsable = buildPanResponsable();
		horLRespProd.addComponent(panResponsable);
		
		// panProductor
		panProductor = buildPanProductor();
		horLRespProd.addComponent(panProductor);
		horLRespProd.setComponentAlignment(panProductor, new Alignment(6));
		
		return horLRespProd;
	}

	@AutoGenerated
	private Panel buildPanResponsable() {
		// common part: create layout
		panResponsable = new Panel();
		panResponsable.setCaption("Responsable Técnico");
		panResponsable.setImmediate(false);
		panResponsable.setWidth("396px");
		panResponsable.setHeight("-1px");
		
		// absLResponsable
		absLResponsable = buildAbsLResponsable();
		panResponsable.setContent(absLResponsable);
		
		return panResponsable;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLResponsable() {
		// common part: create layout
		absLResponsable = new AbsoluteLayout();
		absLResponsable.setImmediate(false);
		absLResponsable.setWidth("100.0%");
		absLResponsable.setHeight("45px");
		
		// cmbResponsable
		cmbResponsable = new ComboBox();
		cmbResponsable.setImmediate(true);
		cmbResponsable.setWidth("375px");
		cmbResponsable.setHeight("25px");
		absLResponsable.addComponent(cmbResponsable, "top:10.0px;left:10.0px;");
		
		return absLResponsable;
	}

	@AutoGenerated
	private Panel buildPanProductor() {
		// common part: create layout
		panProductor = new Panel();
		panProductor.setCaption("Usuario");
		panProductor.setImmediate(false);
		panProductor.setWidth("396px");
		panProductor.setHeight("-1px");
		
		// absLProductor
		absLProductor = buildAbsLProductor();
		panProductor.setContent(absLProductor);
		
		return panProductor;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLProductor() {
		// common part: create layout
		absLProductor = new AbsoluteLayout();
		absLProductor.setImmediate(false);
		absLProductor.setWidth("100.0%");
		absLProductor.setHeight("45px");
		
		// cmbProductor
		cmbProductor = new ComboBox();
		cmbProductor.setImmediate(true);
		cmbProductor.setWidth("375px");
		cmbProductor.setHeight("25px");
		absLProductor.addComponent(cmbProductor, "top:10.0px;left:10.0px;");
		
		return absLProductor;
	}
	
	@AutoGenerated
	private VerticalLayout buildVerLListado() {
		// common part: create layout
		verLListado = new VerticalLayout();
		verLListado.setImmediate(false);
		verLListado.setWidth("-1px");
		verLListado.setHeight("-1px");
		verLListado.setMargin(false);
		
		// tblListado
		tblListado = new Table();
		tblListado
				.setCaption("* Dar doble click sobre un elemento para modificarlo");
		tblListado.setImmediate(false);
		tblListado.setWidth("801px");
		tblListado.setHeight("300px");
		verLListado.addComponent(tblListado);
		
		// lblRowCount
		lblRowCount = new Label();
		lblRowCount.setImmediate(false);
		lblRowCount.setWidth("-1px");
		lblRowCount.setHeight("-1px");
		lblRowCount.setValue("0 registros encontrados");
		verLListado.addComponent(lblRowCount);
		
		return verLListado;
	}

	@AutoGenerated
	private VerticalLayout buildVerLDatos() {
		// common part: create layout
		verLDatos = new VerticalLayout();
		verLDatos.setImmediate(false);
		verLDatos.setWidth("-1px");
		verLDatos.setHeight("-1px");
		verLDatos.setMargin(false);
		verLDatos.setSpacing(true);
		
		// panDetalles
		panDetalles = buildPanDetalles();
		verLDatos.addComponent(panDetalles);
		
		// verLRiegos
		verLRiegos = buildVerLRiegos();
		verLDatos.addComponent(verLRiegos);
		
		// panObservaciones
		panObservaciones = buildPanObservaciones();
		verLDatos.addComponent(panObservaciones);
		
		return verLDatos;
	}

	@AutoGenerated
	private Panel buildPanDetalles() {
		// common part: create layout
		panDetalles = new Panel();
		panDetalles.setCaption("Detalles del Riego");
		panDetalles.setImmediate(false);
		panDetalles.setWidth("801px");
		panDetalles.setHeight("-1px");
		
		// absLDetalles
		absLDetalles = buildAbsLDetalles();
		panDetalles.setContent(absLDetalles);
		
		return panDetalles;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDetalles() {
		// common part: create layout
		absLDetalles = new AbsoluteLayout();
		absLDetalles.setImmediate(false);
		absLDetalles.setWidth("100.0%");
		absLDetalles.setHeight("65px");
		
		// cmbParcela
		cmbParcela = new ComboBox();
		cmbParcela.setCaption("Parcela (Núm. de Cta. / Subcta. de Padrón)");
		cmbParcela.setImmediate(true);
		cmbParcela.setWidth("400px");
		cmbParcela.setHeight("25px");
		absLDetalles.addComponent(cmbParcela, "top:28.0px;left:10.0px;");
		
		// cmbTipoRiego
		cmbTipoRiego = new ComboBox();
		cmbTipoRiego.setCaption("Método de Riego");
		cmbTipoRiego.setImmediate(false);
		cmbTipoRiego.setWidth("180px");
		cmbTipoRiego.setHeight("25px");
		absLDetalles.addComponent(cmbTipoRiego, "top:28.0px;left:430.0px;");
		
		// txtLaminaAnt
		txtLaminaAnt = new TextField();
		txtLaminaAnt.setCaption("Lamina del Ciclo Anterior");
		txtLaminaAnt.setImmediate(true);
		txtLaminaAnt.setWidth("140px");
		txtLaminaAnt.setHeight("25px");
		absLDetalles.addComponent(txtLaminaAnt, "top:28.0px;left:630.0px;");
		
		// lblLaminaAnt
		lblLaminaAnt = new Label();
		lblLaminaAnt.setImmediate(false);
		lblLaminaAnt.setWidth("-1px");
		lblLaminaAnt.setHeight("-1px");
		lblLaminaAnt.setValue("ha");
		absLDetalles.addComponent(lblLaminaAnt, "top:32.0px;left:775.0px;");
		
		return absLDetalles;
	}

	@AutoGenerated
	private VerticalLayout buildVerLRiegos() {
		// common part: create layout
		verLRiegos = new VerticalLayout();
		verLRiegos.setImmediate(false);
		verLRiegos.setWidth("801px");
		verLRiegos.setHeight("-1px");
		verLRiegos.setMargin(false);
		
		// absLRiego
		absLRiego = buildAbsLRiego();
		verLRiegos.addComponent(absLRiego);
		
		// tblRiegos
		tblRiegos = new Table();
		tblRiegos
				.setCaption("* Dar doble click sobre un elemento para modificarlo");
		tblRiegos.setImmediate(false);
		tblRiegos.setWidth("801px");
		tblRiegos.setHeight("200px");
		verLRiegos.addComponent(tblRiegos);
		
		return verLRiegos;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLRiego() {
		// common part: create layout
		absLRiego = new AbsoluteLayout();
		absLRiego.setImmediate(false);
		absLRiego.setWidth("100.0%");
		absLRiego.setHeight("202px");
		
		// panRiego
		panRiego = buildPanRiego();
		absLRiego.addComponent(panRiego, "top:0.0px;left:0.0px;");
		
		// horLBotonesRiego
		horLBotonesRiego = buildHorLBotonesRiego();
		absLRiego.addComponent(horLBotonesRiego, "right:0.0px;bottom:0.0px;");
		
		return absLRiego;
	}

	@AutoGenerated
	private Panel buildPanRiego() {
		// common part: create layout
		panRiego = new Panel();
		panRiego.setImmediate(false);
		panRiego.setWidth("621px");
		panRiego.setHeight("-1px");
		
		// verLRiego
		verLRiego = buildVerLRiego();
		panRiego.setContent(verLRiego);
		
		return panRiego;
	}

	@AutoGenerated
	private VerticalLayout buildVerLRiego() {
		// common part: create layout
		verLRiego = new VerticalLayout();
		verLRiego.setImmediate(false);
		verLRiego.setWidth("100.0%");
		verLRiego.setHeight("-1px");
		verLRiego.setMargin(false);
		
		// absLRiego1
		absLRiego1 = buildAbsLRiego1();
		verLRiego.addComponent(absLRiego1);
		
		// absLCalculables
		absLCalculables = buildAbsLCalculables();
		verLRiego.addComponent(absLCalculables);
		
		// absLDirectos
		absLDirectos = buildAbsLDirectos();
		verLRiego.addComponent(absLDirectos);
		
		// absLRiego2
		absLRiego2 = buildAbsLRiego2();
		verLRiego.addComponent(absLRiego2);
		
		return verLRiego;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLRiego1() {
		// common part: create layout
		absLRiego1 = new AbsoluteLayout();
		absLRiego1.setImmediate(false);
		absLRiego1.setWidth("100.0%");
		absLRiego1.setHeight("55px");
		
		// txtNoRiego
		txtNoRiego = new TextField();
		txtNoRiego.setCaption("Núm. de Riego");
		txtNoRiego.setImmediate(false);
		txtNoRiego.setWidth("90px");
		txtNoRiego.setHeight("25px");
		absLRiego1.addComponent(txtNoRiego, "top:28.0px;left:10.0px;");
		
		// txtEtapa
		txtEtapa = new TextField();
		txtEtapa.setCaption("Etapa Fenológica");
		txtEtapa.setImmediate(true);
		txtEtapa.setWidth("260px");
		txtEtapa.setHeight("25px");
		absLRiego1.addComponent(txtEtapa, "top:28.0px;left:120.0px;");
		
		// cmbDatosRiegoDisponibles
		cmbDatosRiegoDisponibles = new ComboBox();
		cmbDatosRiegoDisponibles.setCaption("¿Con qué datos cuenta?");
		cmbDatosRiegoDisponibles.setImmediate(true);
		cmbDatosRiegoDisponibles.setWidth("200px");
		cmbDatosRiegoDisponibles.setHeight("25px");
		absLRiego1.addComponent(cmbDatosRiegoDisponibles, "top:28.0px;left:400.0px;");
		
		return absLRiego1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCalculables() {
		// common part: create layout
		absLCalculables = new AbsoluteLayout();
		absLCalculables.setImmediate(false);
		absLCalculables.setWidth("100.0%");
		absLCalculables.setHeight("45px");
		
		// datInicio
		datInicio = new DateField();
		datInicio.setCaption("Fecha y Hora de Inicio");
		datInicio.setImmediate(false);
		datInicio.setWidth("180px");
		datInicio.setHeight("25px");
		absLCalculables.addComponent(datInicio, "top:18.0px;left:10.0px;");
		
		// datFin
		datFin = new DateField();
		datFin.setCaption("Fecha y Hora de Fin");
		datFin.setImmediate(false);
		datFin.setWidth("180px");
		datFin.setHeight("25px");
		absLCalculables.addComponent(datFin, "top:18.0px;left:210.0px;");
		
		// txtGasto
		txtGasto = new TextField();
		txtGasto.setCaption("Gasto");
		txtGasto.setImmediate(true);
		txtGasto.setWidth("165px");
		txtGasto.setHeight("25px");
		absLCalculables.addComponent(txtGasto, "top:18.0px;left:410.0px;");
		
		// lblGasto
		lblGasto = new Label();
		lblGasto.setImmediate(false);
		lblGasto.setWidth("-1px");
		lblGasto.setHeight("-1px");
		lblGasto.setValue("L/s");
		absLCalculables.addComponent(lblGasto, "top:22.0px;left:580.0px;");
		
		return absLCalculables;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDirectos() {
		// common part: create layout
		absLDirectos = new AbsoluteLayout();
		absLDirectos.setImmediate(false);
		absLDirectos.setWidth("100.0%");
		absLDirectos.setHeight("45px");
		
		// datFechaRiego
		datFechaRiego = new DateField();
		datFechaRiego.setCaption("Fecha de Riego");
		datFechaRiego.setImmediate(false);
		datFechaRiego.setWidth("180px");
		datFechaRiego.setHeight("25px");
		absLDirectos.addComponent(datFechaRiego, "top:18.0px;left:10.0px;");
		
		// txtDatoDirecto
		txtDatoDirecto = new TextField();
		txtDatoDirecto.setCaption("-");
		txtDatoDirecto.setImmediate(true);
		txtDatoDirecto.setWidth("165px");
		txtDatoDirecto.setHeight("25px");
		absLDirectos.addComponent(txtDatoDirecto, "top:18.0px;left:210.0px;");
		
		// lblDatoDirecto
		lblDatoDirecto = new Label();
		lblDatoDirecto.setImmediate(false);
		lblDatoDirecto.setWidth("-1px");
		lblDatoDirecto.setHeight("-1px");
		lblDatoDirecto.setValue("-");
		absLDirectos.addComponent(lblDatoDirecto, "top:22.0px;left:380.0px;");
		
		return absLDirectos;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLRiego2() {
		// common part: create layout
		absLRiego2 = new AbsoluteLayout();
		absLRiego2.setImmediate(false);
		absLRiego2.setWidth("100.0%");
		absLRiego2.setHeight("55px");
		
		// txtSuperficie
		txtSuperficie = new TextField();
		txtSuperficie.setCaption("Superficie Regada");
		txtSuperficie.setImmediate(true);
		txtSuperficie.setWidth("165px");
		txtSuperficie.setHeight("25px");
		absLRiego2.addComponent(txtSuperficie, "top:18.0px;left:10.0px;");
		
		// lblSuperficie
		lblSuperficie = new Label();
		lblSuperficie.setImmediate(false);
		lblSuperficie.setWidth("-1px");
		lblSuperficie.setHeight("-1px");
		lblSuperficie.setValue("ha");
		absLRiego2.addComponent(lblSuperficie, "top:22.0px;left:180.0px;");
		
		// txtLaminaCalc
		txtLaminaCalc = new TextField();
		txtLaminaCalc.setCaption("Lamina Calculada");
		txtLaminaCalc.setImmediate(true);
		txtLaminaCalc.setWidth("165px");
		txtLaminaCalc.setHeight("25px");
		absLRiego2.addComponent(txtLaminaCalc, "top:18.0px;left:215.0px;");
		
		// lblLaminaCalc
		lblLaminaCalc = new Label();
		lblLaminaCalc.setImmediate(false);
		lblLaminaCalc.setWidth("-1px");
		lblLaminaCalc.setHeight("-1px");
		lblLaminaCalc.setValue("cm");
		absLRiego2.addComponent(lblLaminaCalc, "top:22.0px;left:385.0px;");
		
		return absLRiego2;
	}

	@AutoGenerated
	private HorizontalLayout buildHorLBotonesRiego() {
		// common part: create layout
		horLBotonesRiego = new HorizontalLayout();
		horLBotonesRiego.setImmediate(false);
		horLBotonesRiego.setWidth("-1px");
		horLBotonesRiego.setHeight("-1px");
		horLBotonesRiego.setMargin(false);
		horLBotonesRiego.setSpacing(true);
		
		// btnAdd
		btnAdd = new Button();
		btnAdd.setCaption("Agregar");
		btnAdd.setImmediate(true);
		btnAdd.setWidth("80px");
		btnAdd.setHeight("-1px");
		horLBotonesRiego.addComponent(btnAdd);
		
		// btnCancelar
		btnCancel = new Button();
		btnCancel.setCaption("Cancelar");
		btnCancel.setImmediate(true);
		btnCancel.setWidth("80px");
		btnCancel.setHeight("-1px");
		horLBotonesRiego.addComponent(btnCancel);
		
		return horLBotonesRiego;
	}

	@AutoGenerated
	private Panel buildPanObservaciones() {
		// common part: create layout
		panObservaciones = new Panel();
		panObservaciones.setCaption("Observaciones");
		panObservaciones.setImmediate(false);
		panObservaciones.setWidth("801px");
		panObservaciones.setHeight("-1px");
		
		// absLObservaciones
		absLObservaciones = buildAbsLObservaciones();
		panObservaciones.setContent(absLObservaciones);
		
		return panObservaciones;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLObservaciones() {
		// common part: create layout
		absLObservaciones = new AbsoluteLayout();
		absLObservaciones.setImmediate(false);
		absLObservaciones.setWidth("100.0%");
		absLObservaciones.setHeight("120px");
		
		// txtObservaciones
		txtObservaciones = new TextArea();
		txtObservaciones.setImmediate(false);
		txtObservaciones.setWidth("780px");
		txtObservaciones.setHeight("100px");
		absLObservaciones.addComponent(txtObservaciones,
				"top:10.0px;left:10.0px;");
		
		return absLObservaciones;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLBotones() {
		// common part: create layout
		absLBotones = new AbsoluteLayout();
		absLBotones.setImmediate(false);
		absLBotones.setWidth("801px");
		absLBotones.setHeight("30px");
		
		// btnGuardar
		btnGuardar = new Button();
		btnGuardar.setCaption("Guardar");
		btnGuardar.setImmediate(true);
		btnGuardar.setWidth("-1px");
		btnGuardar.setHeight("-1px");
		absLBotones.addComponent(btnGuardar, "right:0.0px;bottom:0.0px;");
		
		// horLBotones
		horLBotones = buildHorLBotones();
		absLBotones.addComponent(horLBotones, "bottom:0.0px;left:0.0px;");
		
		return absLBotones;
	}

	@AutoGenerated
	private HorizontalLayout buildHorLBotones() {
		// common part: create layout
		horLBotones = new HorizontalLayout();
		horLBotones.setImmediate(false);
		horLBotones.setWidth("-1px");
		horLBotones.setHeight("-1px");
		horLBotones.setMargin(false);
		horLBotones.setSpacing(true);
		
		// btnNuevo
		btnNuevo = new Button();
		btnNuevo.setCaption("Agregar Nuevo");
		btnNuevo.setImmediate(true);
		btnNuevo.setWidth("-1px");
		btnNuevo.setHeight("-1px");
		horLBotones.addComponent(btnNuevo);
		
		// btnVolver
		btnVolver = new Button();
		btnVolver.setCaption("Volver");
		btnVolver.setImmediate(true);
		btnVolver.setWidth("-1px");
		btnVolver.setHeight("-1px");
		horLBotones.addComponent(btnVolver);
		
		return horLBotones;
	}
	
	//endregion
}