package com.saprigrat.ui.forms;

import com.saprigrat.ui.interfaces.Formulario;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class ReporteVisita extends CustomComponent implements Formulario
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_3;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_4;
	@AutoGenerated
	private ComboBox cmbLote;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	private ComboBox cmbModulo;
	@AutoGenerated
	private ComboBox cmbUsuario;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_1;
	public ReporteVisita()
	{
		inicializar();
	}
	
	public void inicializar()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
		cmbUsuario.setInputPrompt("Escribir CURR o nombre");
	}

	@Override
	public void setTipo(int tipo)
	{
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setCaption("Datos Generales");
		panel_1.setImmediate(false);
		panel_1.setWidth("601px");
		panel_1.setHeight("-1px");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panel_1.setContent(verticalLayout_2);
		
		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("200px");
		verticalLayout_2.setMargin(false);
		
		// absoluteLayout_1
		absoluteLayout_1 = new AbsoluteLayout();
		absoluteLayout_1.setImmediate(false);
		absoluteLayout_1.setWidth("100.0%");
		absoluteLayout_1.setHeight("55px");
		verticalLayout_2.addComponent(absoluteLayout_1);
		
		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		verticalLayout_2.addComponent(absoluteLayout_2);
		
		// absoluteLayout_4
		absoluteLayout_4 = buildAbsoluteLayout_4();
		verticalLayout_2.addComponent(absoluteLayout_4);
		
		// absoluteLayout_3
		absoluteLayout_3 = new AbsoluteLayout();
		absoluteLayout_3.setImmediate(false);
		absoluteLayout_3.setWidth("100.0%");
		absoluteLayout_3.setHeight("55px");
		verticalLayout_2.addComponent(absoluteLayout_3);
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("100.0%");
		absoluteLayout_2.setHeight("45px");
		
		// cmbUsuario
		cmbUsuario = new ComboBox();
		cmbUsuario.setCaption("Usuario/Productor");
		cmbUsuario.setImmediate(false);
		cmbUsuario.setWidth("280px");
		cmbUsuario.setHeight("25px");
		absoluteLayout_2.addComponent(cmbUsuario, "top:18.0px;left:10.0px;");
		
		// cmbModulo
		cmbModulo = new ComboBox();
		cmbModulo.setCaption("Módulo");
		cmbModulo.setImmediate(false);
		cmbModulo.setWidth("230px");
		cmbModulo.setHeight("-1px");
		absoluteLayout_2.addComponent(cmbModulo, "top:18.0px;left:310.0px;");
		
		return absoluteLayout_2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_4() {
		// common part: create layout
		absoluteLayout_4 = new AbsoluteLayout();
		absoluteLayout_4.setImmediate(false);
		absoluteLayout_4.setWidth("100.0%");
		absoluteLayout_4.setHeight("45px");
		
		// cmbLote
		cmbLote = new ComboBox();
		cmbLote.setCaption("Lote");
		cmbLote.setImmediate(false);
		cmbLote.setWidth("280px");
		cmbLote.setHeight("25px");
		absoluteLayout_4.addComponent(cmbLote, "top:18.0px;left:201.0px;");
		
		return absoluteLayout_4;
	}

}
