package com.saprigrat.ui.components;

import java.io.File;

import com.saprigrat.data.ManejoDeImagenes;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.FileResource;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Image;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Upload;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class Foto extends CustomComponent
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel panFoto;
	@AutoGenerated
	private AbsoluteLayout absLFoto;
	@AutoGenerated
	private Upload uplFoto;
	@AutoGenerated
	private Image imgFoto;
	public Foto()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		setFoto("");
		ManejoDeImagenes manejo = new ManejoDeImagenes(imgFoto);
		uplFoto.setReceiver(manejo);
		uplFoto.addSucceededListener(manejo);
		uplFoto.setButtonCaption("Subir");
	}
	
	public void setFoto(String fotoURL)
	{
		if(!fotoURL.isEmpty())
		{
			imgFoto.setSource(new FileResource(new File(fotoURL)));
			imgFoto.setAlternateText(fotoURL);
		}
		else
		{
			imgFoto.setSource(new ThemeResource("img/imgUnavailable.jpg"));
			imgFoto.setAlternateText("");
		}
	}
	
	public String getFoto()
	{
		return imgFoto.getAlternateText();
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// panFoto
		panFoto = buildPanFoto();
		mainLayout.addComponent(panFoto);
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanFoto() {
		// common part: create layout
		panFoto = new Panel();
		panFoto.setCaption("Foto");
		panFoto.setImmediate(false);
		panFoto.setWidth("311px");
		panFoto.setHeight("-1px");
		
		// absLFoto
		absLFoto = buildAbsLFoto();
		panFoto.setContent(absLFoto);
		
		return panFoto;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLFoto() {
		// common part: create layout
		absLFoto = new AbsoluteLayout();
		absLFoto.setImmediate(false);
		absLFoto.setWidth("100.0%");
		absLFoto.setHeight("200px");
		
		// imgFoto
		imgFoto = new Image();
		imgFoto.setImmediate(false);
		imgFoto.setWidth("-1px");
		imgFoto.setHeight("180px");
		absLFoto.addComponent(imgFoto, "top:10.0px;left:10.0px;");
		
		// uplFoto
		uplFoto = new Upload();
		uplFoto.setImmediate(true);
		uplFoto.setWidth("-1px");
		uplFoto.setHeight("-1px");
		absLFoto.addComponent(uplFoto, "right:5.0px;bottom:5.0px;");
		
		return absLFoto;
	}
}