package com.saprigrat.ui.components.pruebaderiego;

import java.util.LinkedList;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.validator.RegexpValidator;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.event.ItemClickEvent.ItemClickListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.AbstractField;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class Aforo extends CustomComponent
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout absLLecturaFlujo;
	@AutoGenerated
	private Panel panSalida;
	@AutoGenerated
	private AbsoluteLayout absSalida;
	@AutoGenerated
	private Label lblSalida;
	@AutoGenerated
	private TextField txtSalida;
	@AutoGenerated
	private Panel panRegadera;
	@AutoGenerated
	private AbsoluteLayout absLRegadera;
	@AutoGenerated
	private Label lblRegadera;
	@AutoGenerated
	private TextField txtRegadera;
	@AutoGenerated
	private Panel panGenerales;
	@AutoGenerated
	private VerticalLayout verLGenerales;
	@AutoGenerated
	private AbsoluteLayout absLGenerales2;
	@AutoGenerated
	private Label lblGastoSurco;
	@AutoGenerated
	private TextField txtGastoSurco;
	@AutoGenerated
	private TextField txtNoSurcos;
	@AutoGenerated
	private AbsoluteLayout absLGenerales1;
	@AutoGenerated
	private Label lblVolAplicado;
	@AutoGenerated
	private TextField txtVolAplicado;
	@AutoGenerated
	private Label lblGastoComp;
	@AutoGenerated
	private TextField txtGastoComp;
	@AutoGenerated
	private TextField txtNoComp;
	@AutoGenerated
	private Panel panAforo;
	@AutoGenerated
	private VerticalLayout verLAforo;
	@AutoGenerated
	private AbsoluteLayout absLAforo;
	@AutoGenerated
	private Button btnCancel;
	@AutoGenerated
	private Button btnAdd;
	@AutoGenerated
	private VerticalLayout verLSurcoTabla;
	@AutoGenerated
	private AbsoluteLayout absLTabla;
	@AutoGenerated
	private Table tblAforo;
	@AutoGenerated
	private AbsoluteLayout absLSurco;
	@AutoGenerated
	private Label lblTiempo;
	@AutoGenerated
	private TextField txtTiempo;
	@AutoGenerated
	private Label lblVolumen;
	@AutoGenerated
	private TextField txtVolumen;
	@AutoGenerated
	private TextField txtNoSurco;
	LinkedList<LinkedList<Object>> listaAforo;
	private ClickListener addAforoListener =new ClickListener()
											{
												@Override
												public void buttonClick(ClickEvent event)
												{
													if(absLSurco.isVisible())
													{
														if(validarAforo())
														{
															if(btnAdd.getCaption().equals("Agregar"))
																listaAforo.add(getRow());
															else
																listaAforo.set(Integer.parseInt(txtNoSurco.getValue()) - 1, getRow());
															recargarListaAforo();
															limpiarAforo();
														}
													}
													else
														mostrarFormAforos();
												}
											};
	private ClickListener cancelarListener =new ClickListener()
											{
												@Override
												public void buttonClick(ClickEvent event)
												{
													limpiarAforo();
												}
											};
	private ItemClickListener cargarAforoListener = new ItemClickListener()
													{
														@Override
														public void itemClick(ItemClickEvent event)
														{
															if(event.isDoubleClick())
															{
																Item item = event.getItem();
																txtNoSurco.setValue((Integer)item.getItemProperty("Surco").getValue() + "");
																txtVolumen.setValue(item.getItemProperty("Volumen (L)").getValue() + "");
																txtTiempo.setValue(item.getItemProperty("Tiempo (s)").getValue() + "");
																
																mostrarFormAforos();
																btnAdd.setCaption("Modificar");
															}
														}
													};
	public Aforo()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		//Variables
		listaAforo = new LinkedList<LinkedList<Object>>();
		//Textfields
		txtNoSurco.setEnabled(false);
		//Tables
		tblAforo.addContainerProperty("Surco", Object.class, null);
		tblAforo.addContainerProperty("Volumen (L)", Object.class, null);
		tblAforo.addContainerProperty("Tiempo (s)", Object.class, null);
		tblAforo.addContainerProperty("Gasto (L/s)", Object.class, null);
		tblAforo.setSelectable(true);
		tblAforo.setSortEnabled(true);
		tblAforo.addItemClickListener(cargarAforoListener);
		//Buttons
		btnAdd.addClickListener(addAforoListener);
		btnCancel.addClickListener(cancelarListener);
		
		limpiarAforo();
		setValidaciones();
	}
	
	public LinkedList<Object> getValores()
	{
		LinkedList<Object> aforo = new LinkedList<Object>();
		if(validar())
		{
			aforo.add(getAforos());
			aforo.add(Integer.parseInt(txtNoComp.getValue()));
			aforo.add(Double.parseDouble(txtGastoComp.getValue()));
			aforo.add(Double.parseDouble(txtVolAplicado.getValue()));
			aforo.add(Integer.parseInt(txtNoSurcos.getValue()));
			aforo.add(Double.parseDouble(txtGastoSurco.getValue()));
			aforo.add(Double.parseDouble(txtRegadera.getValue()));
			aforo.add(Double.parseDouble(txtSalida.getValue()));
		}
		return aforo;
	}
	
	public void setValores(LinkedList<Object> aforo)
	{
		setAforos((String)aforo.remove());
		txtNoComp.setValue((String)aforo.remove());
		txtGastoComp.setValue((String)aforo.remove());
		txtVolAplicado.setValue((String)aforo.remove());
		txtNoSurcos.setValue((String)aforo.remove());
		txtGastoSurco.setValue((String)aforo.remove());
		txtRegadera.setValue((String)aforo.remove());
		txtSalida.setValue((String)aforo.remove());
	}
	
	private void mostrarFormAforos()
	{
		btnCancel.setVisible(true);
		absLSurco.setVisible(true);
		absLAforo.setHeight("275px");
	}
	
	private String getAforos()
	{
		String aforo = "";
		for(LinkedList<Object> row : listaAforo)
			aforo += row.get(1) + "&" + row.get(2) + "@";
		return aforo;
	}
	/*private Double[][] getAforos()
	{
		Double[][] aforo = new Double[listaAforo.size()][2];
		for(int i=0; i<listaAforo.size(); i++)
		{
			LinkedList<Object>row = listaAforo.get(i);
			for(int j=0; j<aforo[i].length; j++)
				aforo[i][j] = (Double) row.get(j);
		}
		return aforo;
	}*/

	private void setAforos(String aforos)
	{
		String[]aforo = aforos.split("@");
		for(String row : aforo)
		{
			LinkedList<Object>auxList = new LinkedList<Object>();
			String[]auxArr = ("0&" + row).split("&");
			for(String auxVal : auxArr)
				auxList.add(auxVal);
			auxList.add(Double.parseDouble((String)auxList.get(1)) / Integer.parseInt((String)auxList.get(2)));
			listaAforo.add(auxList);
		}
		recargarListaAforo();
	}
	
	private LinkedList<Object> getRow()
	{
		LinkedList<Object> aforo = new LinkedList<Object>();
		aforo.add(0);
		aforo.add(txtVolumen.getValue());
		aforo.add(txtTiempo.getValue());
		aforo.add(Double.parseDouble(txtVolumen.getValue()) / Integer.parseInt(txtTiempo.getValue()));
		return aforo;
	}
	
	private void recargarListaAforo()
	{
		tblAforo.removeAllItems();
		for(int i = 0; i < listaAforo.size(); i++)
		{
			LinkedList<Object> aforo = listaAforo.get(i);
			aforo.set(0, i + 1);
			tblAforo.addItem(aforo.toArray(), null);
		}
	}
	
	private void limpiarAforo()
	{
		txtNoSurco.setValue(listaAforo.size() + 1 + "");
		txtVolumen.setValue("");
		txtTiempo.setValue("");

		btnAdd.setCaption("Agregar");
		btnCancel.setVisible(false);
		absLSurco.setVisible(false);
		absLAforo.setHeight("220px");
	}

	private void setValidaciones()
	{
		RegexpValidator esDecimal = new RegexpValidator("^[0-9]+(\\.[0-9]+)?$", "Debe ser un valor numérico"),
						esEntero = new RegexpValidator("^[0-9]+$", "Debe ser un valor numérico entero");
		txtVolumen.addValidator(esDecimal);
		txtTiempo.addValidator(esEntero);
		txtNoComp.addValidator(esDecimal);
		txtGastoComp.addValidator(esDecimal);
		txtVolAplicado.addValidator(esDecimal);
		txtNoSurcos.addValidator(esDecimal);
		txtGastoSurco.addValidator(esDecimal);
		txtRegadera.addValidator(esDecimal);
		txtSalida.addValidator(esDecimal);
	}
	
	private boolean validar()
	{
		if(txtNoComp.getValue().isEmpty() || !txtNoComp.isValid())
			return notificar("Se requiere especificar un valor estríctamente numérico para el número de compuertas", txtNoComp);
		if(txtGastoComp.getValue().isEmpty() || !txtGastoComp.isValid())
			return notificar("Se requiere especificar un valor estríctamente numérico para el gasto promedio por compuerta", txtGastoComp);
		if(txtVolAplicado.getValue().isEmpty() || !txtVolAplicado.isValid())
			return notificar("Se requiere especificar un valor estríctamente numérico para el volumen total aplicado", txtVolAplicado);
		if(txtNoSurcos.getValue().isEmpty() || !txtNoSurcos.isValid())
			return notificar("Se requiere especificar un valor estríctamente numérico para el número de surcos", txtNoSurcos);
		if(txtGastoSurco.getValue().isEmpty() || !txtGastoSurco.isValid())
			return notificar("Se requiere especificar un valor estríctamente numérico para el gasto promedio por surco o melga", txtGastoSurco);

		if(txtRegadera.getValue().isEmpty() || !txtRegadera.isValid())
			return notificar("Se requiere especificar un valor estríctamente numérico para el aforo en la regadera o canal", txtRegadera);
		if(txtSalida.getValue().isEmpty() || !txtSalida.isValid())
			return notificar("Se requiere especificar un valor estríctamente numérico para el aforo a la salida", txtSalida);
		
		return true;
	}
	
	private boolean validarAforo()
	{
		if(txtVolumen.getValue().isEmpty() || !txtVolumen.isValid())
			return notificar("Se requiere especificar un valor estríctamente numérico para el volumen", txtVolumen);
		if(txtTiempo.getValue().isEmpty() || !txtTiempo.isValid())
			return notificar("Se requiere especificar un valor numérico estríctamente entero para el tiempo", txtTiempo);
		
		return true;
	}
	
	@SuppressWarnings("rawtypes")
	private boolean notificar(String notificacion, AbstractField field)
	{
		Notification.show(notificacion, Notification.Type.ERROR_MESSAGE);
		field.focus();
		return false;
	}
	//region UI

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("581px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("581px");
		setHeight("-1px");
		
		// panAforo
		panAforo = buildPanAforo();
		mainLayout.addComponent(panAforo);
		
		// panGenerales
		panGenerales = buildPanGenerales();
		mainLayout.addComponent(panGenerales);
		
		// absLLecturaFlujo
		absLLecturaFlujo = buildAbsLLecturaFlujo();
		mainLayout.addComponent(absLLecturaFlujo);
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanAforo() {
		// common part: create layout
		panAforo = new Panel();
		panAforo.setCaption("Aforo en las Parcelas Demostrativas");
		panAforo.setImmediate(false);
		panAforo.setWidth("100.0%");
		panAforo.setHeight("-1px");
		
		// verLAforo
		verLAforo = buildVerLAforo();
		panAforo.setContent(verLAforo);
		
		return panAforo;
	}

	@AutoGenerated
	private VerticalLayout buildVerLAforo() {
		// common part: create layout
		verLAforo = new VerticalLayout();
		verLAforo.setImmediate(false);
		verLAforo.setWidth("100.0%");
		verLAforo.setHeight("-1px");
		verLAforo.setMargin(false);
		
		// absLAforo
		absLAforo = buildAbsLAforo();
		verLAforo.addComponent(absLAforo);
		
		return verLAforo;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLAforo() {
		// common part: create layout
		absLAforo = new AbsoluteLayout();
		absLAforo.setImmediate(false);
		absLAforo.setWidth("100.0%");
		absLAforo.setHeight("275px");
		
		// verLSurcoTabla
		verLSurcoTabla = buildVerLSurcoTabla();
		absLAforo.addComponent(verLSurcoTabla, "top:0.0px;left:0.0px;");
		
		// btnAdd
		btnAdd = new Button();
		btnAdd.setCaption("Agregar");
		btnAdd.setImmediate(true);
		btnAdd.setWidth("85px");
		btnAdd.setHeight("-1px");
		absLAforo.addComponent(btnAdd, "top:28.0px;right:10.0px;");
		
		// btnCancel
		btnCancel = new Button();
		btnCancel.setCaption("Cancelar");
		btnCancel.setImmediate(true);
		btnCancel.setWidth("85px");
		btnCancel.setHeight("-1px");
		absLAforo.addComponent(btnCancel, "top:60.0px;right:10.0px;");
		
		return absLAforo;
	}

	@AutoGenerated
	private VerticalLayout buildVerLSurcoTabla() {
		// common part: create layout
		verLSurcoTabla = new VerticalLayout();
		verLSurcoTabla.setImmediate(false);
		verLSurcoTabla.setWidth("440px");
		verLSurcoTabla.setHeight("-1px");
		verLSurcoTabla.setMargin(false);
		
		// absLSurco
		absLSurco = buildAbsLSurco();
		verLSurcoTabla.addComponent(absLSurco);
		
		// absLTabla
		absLTabla = buildAbsLTabla();
		verLSurcoTabla.addComponent(absLTabla);
		
		return verLSurcoTabla;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLSurco() {
		// common part: create layout
		absLSurco = new AbsoluteLayout();
		absLSurco.setImmediate(false);
		absLSurco.setWidth("100.0%");
		absLSurco.setHeight("55px");
		
		// txtNoSurco
		txtNoSurco = new TextField();
		txtNoSurco.setCaption("Núm. Surco");
		txtNoSurco.setImmediate(false);
		txtNoSurco.setWidth("100px");
		txtNoSurco.setHeight("25px");
		absLSurco.addComponent(txtNoSurco, "top:28.0px;left:10.0px;");
		
		// txtVolumen
		txtVolumen = new TextField();
		txtVolumen.setCaption("Volumen");
		txtVolumen.setImmediate(false);
		txtVolumen.setWidth("130px");
		txtVolumen.setHeight("25px");
		absLSurco.addComponent(txtVolumen, "top:28.0px;left:130.0px;");
		
		// lblVolumen
		lblVolumen = new Label();
		lblVolumen.setImmediate(false);
		lblVolumen.setWidth("-1px");
		lblVolumen.setHeight("-1px");
		lblVolumen.setValue("L");
		absLSurco.addComponent(lblVolumen, "top:32.0px;left:265.0px;");
		
		// txtTiempo
		txtTiempo = new TextField();
		txtTiempo.setCaption("Tiempo");
		txtTiempo.setImmediate(false);
		txtTiempo.setWidth("130px");
		txtTiempo.setHeight("25px");
		absLSurco.addComponent(txtTiempo, "top:28.0px;left:295.0px;");
		
		// lblTiempo
		lblTiempo = new Label();
		lblTiempo.setImmediate(false);
		lblTiempo.setWidth("-1px");
		lblTiempo.setHeight("-1px");
		lblTiempo.setValue("s");
		absLSurco.addComponent(lblTiempo, "top:32.0px;left:430.0px;");
		
		return absLSurco;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLTabla() {
		// common part: create layout
		absLTabla = new AbsoluteLayout();
		absLTabla.setImmediate(false);
		absLTabla.setWidth("100.0%");
		absLTabla.setHeight("220px");
		
		// tblAforo
		tblAforo = new Table();
		tblAforo.setCaption("* Dar doble click sobre un elemento para modificarlo");
		tblAforo.setImmediate(false);
		tblAforo.setWidth("425px");
		tblAforo.setHeight("180px");
		absLTabla.addComponent(tblAforo, "top:28.0px;left:10.0px;");
		
		return absLTabla;
	}

	@AutoGenerated
	private Panel buildPanGenerales() {
		// common part: create layout
		panGenerales = new Panel();
		panGenerales.setImmediate(false);
		panGenerales.setWidth("100.0%");
		panGenerales.setHeight("-1px");
		
		// verLGenerales
		verLGenerales = buildVerLGenerales();
		panGenerales.setContent(verLGenerales);
		
		return panGenerales;
	}

	@AutoGenerated
	private VerticalLayout buildVerLGenerales() {
		// common part: create layout
		verLGenerales = new VerticalLayout();
		verLGenerales.setImmediate(false);
		verLGenerales.setWidth("100.0%");
		verLGenerales.setHeight("100.0%");
		verLGenerales.setMargin(false);
		
		// absLGenerales1
		absLGenerales1 = buildAbsLGenerales1();
		verLGenerales.addComponent(absLGenerales1);
		
		// absLGenerales2
		absLGenerales2 = buildAbsLGenerales2();
		verLGenerales.addComponent(absLGenerales2);
		
		return verLGenerales;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLGenerales1() {
		// common part: create layout
		absLGenerales1 = new AbsoluteLayout();
		absLGenerales1.setImmediate(false);
		absLGenerales1.setWidth("100.0%");
		absLGenerales1.setHeight("55px");
		
		// txtNoComp
		txtNoComp = new TextField();
		txtNoComp.setCaption("Núm. de Compuertas");
		txtNoComp.setImmediate(false);
		txtNoComp.setWidth("120px");
		txtNoComp.setHeight("25px");
		absLGenerales1.addComponent(txtNoComp, "top:28.0px;left:10.0px;");
		
		// txtGastoComp
		txtGastoComp = new TextField();
		txtGastoComp.setCaption("Gasto Prom. por Compuerta");
		txtGastoComp.setImmediate(false);
		txtGastoComp.setWidth("170px");
		txtGastoComp.setHeight("25px");
		absLGenerales1.addComponent(txtGastoComp, "top:28.0px;left:150.0px;");
		
		// lblGastoComp
		lblGastoComp = new Label();
		lblGastoComp.setImmediate(false);
		lblGastoComp.setWidth("-1px");
		lblGastoComp.setHeight("-1px");
		lblGastoComp.setValue("L/s");
		absLGenerales1.addComponent(lblGastoComp, "top:32.0px;left:325.0px;");
		
		// txtVolAplicado
		txtVolAplicado = new TextField();
		txtVolAplicado.setCaption("Volumen Total Aplicado");
		txtVolAplicado.setImmediate(false);
		txtVolAplicado.setWidth("150px");
		txtVolAplicado.setHeight("25px");
		absLGenerales1.addComponent(txtVolAplicado, "top:28.0px;left:360.0px;");
		
		// lblVolAplicado
		lblVolAplicado = new Label();
		lblVolAplicado.setImmediate(false);
		lblVolAplicado.setWidth("-1px");
		lblVolAplicado.setHeight("-1px");
		lblVolAplicado.setValue("m3");
		absLGenerales1.addComponent(lblVolAplicado, "top:32.0px;left:515.0px;");
		
		return absLGenerales1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLGenerales2() {
		// common part: create layout
		absLGenerales2 = new AbsoluteLayout();
		absLGenerales2.setImmediate(false);
		absLGenerales2.setWidth("100.0%");
		absLGenerales2.setHeight("55px");
		
		// txtNoSurcos
		txtNoSurcos = new TextField();
		txtNoSurcos.setCaption("Núm. de Surcos");
		txtNoSurcos.setImmediate(false);
		txtNoSurcos.setWidth("120px");
		txtNoSurcos.setHeight("25px");
		absLGenerales2.addComponent(txtNoSurcos, "top:18.0px;left:10.0px;");
		
		// txtGastoSurco
		txtGastoSurco = new TextField();
		txtGastoSurco.setCaption("Gasto Prom. por Surco o Melga");
		txtGastoSurco.setImmediate(false);
		txtGastoSurco.setWidth("170px");
		txtGastoSurco.setHeight("25px");
		absLGenerales2.addComponent(txtGastoSurco, "top:18.0px;left:150.0px;");
		
		// lblGastoSurco
		lblGastoSurco = new Label();
		lblGastoSurco.setImmediate(false);
		lblGastoSurco.setWidth("-1px");
		lblGastoSurco.setHeight("-1px");
		lblGastoSurco.setValue("L/s");
		absLGenerales2.addComponent(lblGastoSurco, "top:22.0px;left:325.0px;");
		
		return absLGenerales2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLLecturaFlujo() {
		// common part: create layout
		absLLecturaFlujo = new AbsoluteLayout();
		absLLecturaFlujo.setImmediate(false);
		absLLecturaFlujo.setWidth("100.0%");
		absLLecturaFlujo.setHeight("66px");
		
		// panRegadera
		panRegadera = buildPanRegadera();
		absLLecturaFlujo.addComponent(panRegadera, "top:0.0px;left:0.0px;");
		
		// panSalida
		panSalida = buildPanSalida();
		absLLecturaFlujo.addComponent(panSalida, "top:0.0px;right:0.0px;");
		
		return absLLecturaFlujo;
	}

	@AutoGenerated
	private Panel buildPanRegadera() {
		// common part: create layout
		panRegadera = new Panel();
		panRegadera.setCaption("Aforo en la Regadera o Canal");
		panRegadera.setImmediate(false);
		panRegadera.setWidth("265px");
		panRegadera.setHeight("-1px");
		
		// absLRegadera
		absLRegadera = buildAbsLRegadera();
		panRegadera.setContent(absLRegadera);
		
		return panRegadera;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLRegadera() {
		// common part: create layout
		absLRegadera = new AbsoluteLayout();
		absLRegadera.setImmediate(false);
		absLRegadera.setWidth("100.0%");
		absLRegadera.setHeight("45px");
		
		// txtRegadera
		txtRegadera = new TextField();
		txtRegadera.setImmediate(false);
		txtRegadera.setWidth("225px");
		txtRegadera.setHeight("25px");
		absLRegadera.addComponent(txtRegadera, "top:10.0px;left:10.0px;");
		
		// lblRegadera
		lblRegadera = new Label();
		lblRegadera.setImmediate(false);
		lblRegadera.setWidth("-1px");
		lblRegadera.setHeight("-1px");
		lblRegadera.setValue("L/s");
		absLRegadera.addComponent(lblRegadera, "top:14.0px;left:240.0px;");
		
		return absLRegadera;
	}

	@AutoGenerated
	private Panel buildPanSalida() {
		// common part: create layout
		panSalida = new Panel();
		panSalida.setCaption("Aforo a la Salida");
		panSalida.setImmediate(false);
		panSalida.setWidth("265px");
		panSalida.setHeight("-1px");
		
		// absSalida
		absSalida = buildAbsSalida();
		panSalida.setContent(absSalida);
		
		return panSalida;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsSalida() {
		// common part: create layout
		absSalida = new AbsoluteLayout();
		absSalida.setImmediate(false);
		absSalida.setWidth("100.0%");
		absSalida.setHeight("45px");
		
		// txtSalida
		txtSalida = new TextField();
		txtSalida.setImmediate(false);
		txtSalida.setWidth("225px");
		txtSalida.setHeight("25px");
		absSalida.addComponent(txtSalida, "top:10.0px;left:10.0px;");
		
		// lblSalida
		lblSalida = new Label();
		lblSalida.setImmediate(false);
		lblSalida.setWidth("-1px");
		lblSalida.setHeight("-1px");
		lblSalida.setValue("L/s");
		absSalida.addComponent(lblSalida, "top:14.0px;left:240.0px;");
		
		return absSalida;
	}
	
	//endregion
}