package com.saprigrat.ui;

import com.saprigrat.data.Usuario;
import com.saprigrat.ui.forms.Aprovechamiento;
import com.saprigrat.ui.forms.Listado;
import com.saprigrat.ui.forms.Parcela;
import com.saprigrat.ui.forms.Pozo;
import com.saprigrat.ui.forms.PruebaRiego;
import com.saprigrat.ui.forms.personas.Productor;
import com.saprigrat.ui.forms.personas.Regador;
import com.saprigrat.ui.forms.personas.Tecnico;
import com.saprigrat.ui.interfaces.Formulario;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.MouseEvents.ClickEvent;
import com.vaadin.event.MouseEvents.ClickListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class MainView extends CustomComponent
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel panBody;
	@AutoGenerated
	private HorizontalLayout horLBody;
	@AutoGenerated
	private AbsoluteLayout absLOpcionSel;
	@AutoGenerated
	private Label lblOpcionSel;
	@AutoGenerated
	private Panel panHead;
	@AutoGenerated
	private AbsoluteLayout absLHead;
	@AutoGenerated
	private MenuBar mbrMenu;
	@AutoGenerated
	private Embedded imgUsprottia;
	@AutoGenerated
	private Embedded imgUach;
	@AutoGenerated
	private Embedded imgConagua;
	@AutoGenerated
	private Embedded imgHeader;
	private Usuario usuario;
	
	public MainView(Usuario user)
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);

		usuario = user;
		imgHeader.addClickListener(	new ClickListener()
									{
										@Override
										public void click(ClickEvent event)
										{
											horLBody.removeAllComponents();
											absLOpcionSel.setVisible(false);
										}
									});
		setMenu();
	}
	
	private void setMenu()
	{
		MenuItem menu = mbrMenu.addItem("Personas", null);
		addItems(menu.addItem("Administrador", null), new Tecnico(0, usuario));
		addItems(menu.addItem("Supervisor Técnico", null), new Tecnico(1, usuario));
		addItems(menu.addItem("Responsable Técnico", null), new Tecnico(2, usuario));
		addItems(menu.addItem("Usuario/Productor", null), new Productor(3, usuario));
		addItems(menu.addItem("Regador", null), new Regador(4, usuario));
		
		addItems(mbrMenu.addItem("Aprovechamiento", null), new Aprovechamiento());
		addItems(mbrMenu.addItem("Parcela", null), new Parcela());
		addItems(mbrMenu.addItem("Pozo", null), new Pozo());
		
		addItems(mbrMenu.addItem("Prueba de Riego", null), new PruebaRiego());
		
		mbrMenu.addItem("Reportes", null);
	}
	
	void addItems(MenuItem menu, final Formulario form)
	{
		menu.addItem("Listado", new Command()
								{
									@Override
									public void menuSelected(MenuItem selectedItem)
									{
										setPath(selectedItem);
										Listado lista = new Listado(form.getEntidad(), form.getRestricciones());
										lista.setTipo(lista.VER);
										addComponente(lista);
										
									}
								});
		menu.addSeparator();
		menu.addItem("Agregar", com(form, 1));
		menu.addItem("Modificar", com(form, 2));
	}
	
	Command com(final Formulario form, final int tipo)
	{
		return  new Command()
				{
					@Override
					public void menuSelected(MenuItem selectedItem)
					{
						setPath(selectedItem);
						form.inicializar();
						form.setTipo(tipo);
						addComponente(form);
					}
				};
	}
	
	private void setPath(MenuItem selectedItem)
	{
		//Obtener elementos del path
		String path = "";
		for (MenuItem parent = selectedItem.getParent(); parent!=null; parent = parent.getParent())
			path = parent.getText() + "  >  " + path;
		//Establecer path
		lblOpcionSel.setValue(path + selectedItem.getText());
		//Hacer visible el path
		absLOpcionSel.setVisible(true);
		lblOpcionSel.setVisible(true);
	}
	
	private void addComponente(Component form)
	{
		//Vaciar el contenido del panel principal
		horLBody.removeAllComponents();
		//Agregar nuevo contenido
		horLBody.addComponent(form);
		horLBody.setComponentAlignment(form, new Alignment(20));
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// panHead
		panHead = buildPanHead();
		mainLayout.addComponent(panHead);
		mainLayout.setComponentAlignment(panHead, new Alignment(20));
		
		// absLOpcionSel
		absLOpcionSel = buildAbsLOpcionSel();
		mainLayout.addComponent(absLOpcionSel);
		mainLayout.setComponentAlignment(absLOpcionSel, new Alignment(48));
		
		// panBody
		panBody = buildPanBody();
		mainLayout.addComponent(panBody);
		mainLayout.setComponentAlignment(panBody, new Alignment(20));
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanHead() {
		// common part: create layout
		panHead = new Panel();
		panHead.setImmediate(false);
		panHead.setWidth("800px");
		panHead.setHeight("140px");
		
		// absLHead
		absLHead = buildAbsLHead();
		panHead.setContent(absLHead);
		
		return panHead;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLHead() {
		// common part: create layout
		absLHead = new AbsoluteLayout();
		absLHead.setImmediate(false);
		absLHead.setWidth("100.0%");
		absLHead.setHeight("100.0%");
		
		// imgHeader
		imgHeader = new Embedded();
		imgHeader.setImmediate(false);
		imgHeader.setWidth("350px");
		imgHeader.setHeight("80px");
		imgHeader.setSource(new ThemeResource("img/header.png"));
		imgHeader.setType(1);
		imgHeader.setMimeType("image/png");
		absLHead.addComponent(imgHeader, "top:20.0px;left:20.0px;");
		
		// imgConagua
		imgConagua = new Embedded();
		imgConagua.setImmediate(false);
		imgConagua.setDescription("Comisión Nacional del Agua");
		imgConagua.setWidth("-1px");
		imgConagua.setHeight("28px");
		imgConagua.setSource(new ThemeResource("img/logos/conagua.png"));
		imgConagua.setType(1);
		imgConagua.setMimeType("image/png");
		absLHead.addComponent(imgConagua, "top:20.0px;right:20.0px;");
		
		// imgUach
		imgUach = new Embedded();
		imgUach.setImmediate(false);
		imgUach.setDescription("Universidad Autónoma Chapingo");
		imgUach.setWidth("-1px");
		imgUach.setHeight("30px");
		imgUach.setSource(new ThemeResource("img/logos/uach.png"));
		imgUach.setType(1);
		imgUach.setMimeType("image/png");
		absLHead.addComponent(imgUach, "top:60.0px;right:105.0px;");
		
		// imgUsprottia
		imgUsprottia = new Embedded();
		imgUsprottia.setImmediate(false);
		imgUsprottia.setWidth("-1px");
		imgUsprottia.setHeight("30px");
		imgUsprottia.setSource(new ThemeResource("img/logos/usprottia.png"));
		imgUsprottia.setType(1);
		imgUsprottia.setMimeType("image/png");
		absLHead.addComponent(imgUsprottia, "top:60.0px;right:20.0px;");
		
		// mbrMenu
		mbrMenu = new MenuBar();
		mbrMenu.setImmediate(false);
		mbrMenu.setWidth("1000px");
		mbrMenu.setHeight("-1px");
		absLHead.addComponent(mbrMenu, "bottom:0.0px;");
		
		return absLHead;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLOpcionSel() {
		// common part: create layout
		absLOpcionSel = new AbsoluteLayout();
		absLOpcionSel.setEnabled(false);
		absLOpcionSel.setImmediate(false);
		absLOpcionSel.setVisible(false);
		absLOpcionSel.setWidth("800px");
		absLOpcionSel.setHeight("25px");
		
		// lblOpcionSel
		lblOpcionSel = new Label();
		lblOpcionSel.setStyleName("lblOpcionSel");
		lblOpcionSel.setEnabled(false);
		lblOpcionSel.setImmediate(false);
		lblOpcionSel.setVisible(false);
		lblOpcionSel.setWidth("-1px");
		lblOpcionSel.setHeight("-1px");
		lblOpcionSel.setValue("Opc");
		absLOpcionSel.addComponent(lblOpcionSel, "top:5.0px;left:20.0px;");
		
		return absLOpcionSel;
	}

	@AutoGenerated
	private Panel buildPanBody() {
		// common part: create layout
		panBody = new Panel();
		panBody.setImmediate(false);
		panBody.setWidth("800px");
		panBody.setHeight("500px");
		
		// horLBody
		horLBody = new HorizontalLayout();
		horLBody.setStyleName("contenido");
		horLBody.setImmediate(false);
		horLBody.setWidth("100.0%");
		horLBody.setHeight("100.0%");
		horLBody.setMargin(true);
		panBody.setContent(horLBody);
		
		return panBody;
	}

}
