package com.saprigrat.ui;
import org.vaadin.addons.tuningdatefield.TuningDateField;
import org.vaadin.risto.stepper.IntStepper;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;
import com.vaadin.ui.VerticalLayout;


@SuppressWarnings("serial")
public class supervisorInfo extends CustomComponent
{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Panel panCredenciale;
	@AutoGenerated
	private VerticalLayout verLCredenciale;
	@AutoGenerated
	private AbsoluteLayout absLCredenciales1;
	@AutoGenerated
	private TextField textField_1;
	@AutoGenerated
	private AbsoluteLayout absLCredenciales3;
	@AutoGenerated
	private TextField txtAcredFIRA;
	@AutoGenerated
	private AbsoluteLayout absLCredenciales2;
	@AutoGenerated
	private CheckBox chkD;
	@AutoGenerated
	private CheckBox chkM;
	@AutoGenerated
	private NativeSelect selFormacion;
	@AutoGenerated
	private Panel panDetTecnicos;
	@AutoGenerated
	private VerticalLayout verLDetTecnicos;
	@AutoGenerated
	private AbsoluteLayout absLDetTecnicos2_2;
	@AutoGenerated
	private TextField txtModuloR;
	@AutoGenerated
	private ComboBox cmbSRL;
	@AutoGenerated
	private AbsoluteLayout absLDetTecnicos2_1;
	@AutoGenerated
	private Label lblHa;
	@AutoGenerated
	private TextField txtSupAtendida;
	@AutoGenerated
	private NativeSelect selDtoR;
	@AutoGenerated
	private TextField txtUdeRAtendidas;
	@AutoGenerated
	private AbsoluteLayout absLDetTecnicos1;
	@AutoGenerated
	private IntStepper stpTecnicos;
	@AutoGenerated
	private TuningDateField datIngreso;
	@AutoGenerated
	private NativeSelect selOrgCuenca;
	@AutoGenerated
	private Upload uplFoto;
	@AutoGenerated
	private Panel panDireccion;
	@AutoGenerated
	private VerticalLayout verLDireccion;
	@AutoGenerated
	private AbsoluteLayout absLDireccion3;
	@AutoGenerated
	private TextField txtCP;
	@AutoGenerated
	private TextField txtNoInt;
	@AutoGenerated
	private TextField txtNoExt;
	@AutoGenerated
	private TextField txtCalle;
	@AutoGenerated
	private AbsoluteLayout absLDireccion2;
	@AutoGenerated
	private ComboBox cmbLoc;
	@AutoGenerated
	private TextField txtCol;
	@AutoGenerated
	private AbsoluteLayout absLDireccion1;
	@AutoGenerated
	private ComboBox cmbDelMpio;
	@AutoGenerated
	private NativeSelect selEdo;
	@AutoGenerated
	private Embedded imgFoto;
	@AutoGenerated
	private AbsoluteLayout absLNombre;
	@AutoGenerated
	private TuningDateField datNacimiento;
	@AutoGenerated
	private TextField txtApM;
	@AutoGenerated
	private TextField txtApP;
	@AutoGenerated
	private TextField txtNombre;
	@AutoGenerated
	private Panel panContacto;
	@AutoGenerated
	private AbsoluteLayout absLContacto;
	@AutoGenerated
	private TextField txtEmail;
	@AutoGenerated
	private TextField txtCel;
	@AutoGenerated
	private TextField txtTel;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public supervisorInfo()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		this.init();
	}
	
	public void init()
	{
		stpTecnicos.setMinValue(0);
		stpTecnicos.setMaxValue(99);
		stpTecnicos.setRequired(true);
		datNacimiento.setRequired(true);
		datNacimiento.setWeekendDisabled(false);
		datIngreso.setRequired(true);
		datIngreso.setWeekendDisabled(false);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("200.0%");
		
		// panContacto
		panContacto = buildPanContacto();
		mainLayout.addComponent(panContacto, "top:400.0px;left:40.0px;");
		
		// absLNombre
		absLNombre = buildAbsLNombre();
		mainLayout.addComponent(absLNombre, "top:40.0px;left:40.0px;");
		
		// imgFoto
		imgFoto = new Embedded();
		imgFoto.setImmediate(false);
		imgFoto.setWidth("280px");
		imgFoto.setHeight("140px");
		imgFoto.setSource(new ThemeResource("img/component/embedded_icon.png"));
		imgFoto.setType(1);
		imgFoto.setMimeType("image/png");
		mainLayout.addComponent(imgFoto, "top:40.0px;left:340.0px;");
		
		// panDireccion
		panDireccion = buildPanDireccion();
		mainLayout.addComponent(panDireccion, "top:240.0px;left:40.0px;");
		
		// uplFoto
		uplFoto = new Upload();
		uplFoto.setImmediate(false);
		uplFoto.setWidth("-1px");
		uplFoto.setHeight("-1px");
		mainLayout.addComponent(uplFoto, "top:194.0px;left:323.0px;");
		
		// panDetTecnicos
		panDetTecnicos = buildPanDetTecnicos();
		mainLayout.addComponent(panDetTecnicos, "top:480.0px;left:40.0px;");
		
		// panCredenciale
		panCredenciale = buildPanCredenciale();
		mainLayout.addComponent(panCredenciale, "top:668.0px;left:40.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanContacto() {
		// common part: create layout
		panContacto = new Panel();
		panContacto.setCaption("Contacto");
		panContacto.setImmediate(false);
		panContacto.setWidth("590px");
		panContacto.setHeight("64px");
		
		// absLContacto
		absLContacto = buildAbsLContacto();
		panContacto.setContent(absLContacto);
		
		return panContacto;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLContacto() {
		// common part: create layout
		absLContacto = new AbsoluteLayout();
		absLContacto.setImmediate(false);
		absLContacto.setWidth("100.0%");
		absLContacto.setHeight("100.0%");
		
		// txtTel
		txtTel = new TextField();
		txtTel.setCaption("Teléfono Fijo");
		txtTel.setImmediate(false);
		txtTel.setWidth("80px");
		txtTel.setHeight("-1px");
		txtTel.setRequired(true);
		absLContacto.addComponent(txtTel, "top:18.0px;left:1.0px;");
		
		// txtCel
		txtCel = new TextField();
		txtCel.setCaption("Celular");
		txtCel.setImmediate(false);
		txtCel.setWidth("80px");
		txtCel.setHeight("-1px");
		absLContacto.addComponent(txtCel, "top:18.0px;left:101.0px;");
		
		// txtEmail
		txtEmail = new TextField();
		txtEmail.setCaption("Correo electrónico");
		txtEmail.setImmediate(false);
		txtEmail.setWidth("380px");
		txtEmail.setHeight("-1px");
		absLContacto.addComponent(txtEmail, "top:18.0px;left:201.0px;");
		
		return absLContacto;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLNombre() {
		// common part: create layout
		absLNombre = new AbsoluteLayout();
		absLNombre.setImmediate(false);
		absLNombre.setWidth("290px");
		absLNombre.setHeight("170px");
		
		// txtNombre
		txtNombre = new TextField();
		txtNombre.setCaption("Nombre");
		txtNombre.setImmediate(false);
		txtNombre.setWidth("280px");
		txtNombre.setHeight("-1px");
		txtNombre.setRequired(true);
		absLNombre.addComponent(txtNombre, "top:20.0px;left:1.0px;");
		
		// txtApP
		txtApP = new TextField();
		txtApP.setCaption("Ap. Paterno");
		txtApP.setImmediate(false);
		txtApP.setWidth("180px");
		txtApP.setHeight("-1px");
		txtApP.setRequired(true);
		absLNombre.addComponent(txtApP, "top:60.0px;left:1.0px;");
		
		// txtApM
		txtApM = new TextField();
		txtApM.setCaption("Ap. Materno");
		txtApM.setImmediate(false);
		txtApM.setWidth("180px");
		txtApM.setHeight("-1px");
		txtApM.setRequired(true);
		absLNombre.addComponent(txtApM, "top:100.0px;left:1.0px;");
		
		// datNacimiento
		datNacimiento = new TuningDateField();
		datNacimiento.setCaption("Fecha de Nacimiento");
		datNacimiento.setImmediate(false);
		datNacimiento.setWidth("180px");
		datNacimiento.setHeight("-1px");
		absLNombre.addComponent(datNacimiento, "top:140.0px;left:1.0px;");
		
		return absLNombre;
	}

	@AutoGenerated
	private Panel buildPanDireccion() {
		// common part: create layout
		panDireccion = new Panel();
		panDireccion.setCaption("Dirección");
		panDireccion.setImmediate(false);
		panDireccion.setWidth("589px");
		panDireccion.setHeight("-1px");
		
		// verLDireccion
		verLDireccion = buildVerLDireccion();
		panDireccion.setContent(verLDireccion);
		
		return panDireccion;
	}

	@AutoGenerated
	private VerticalLayout buildVerLDireccion() {
		// common part: create layout
		verLDireccion = new VerticalLayout();
		verLDireccion.setImmediate(false);
		verLDireccion.setWidth("100.0%");
		verLDireccion.setHeight("100.0%");
		verLDireccion.setMargin(false);
		
		// absLDireccion1
		absLDireccion1 = buildAbsLDireccion1();
		verLDireccion.addComponent(absLDireccion1);
		
		// absLDireccion2
		absLDireccion2 = buildAbsLDireccion2();
		verLDireccion.addComponent(absLDireccion2);
		
		// absLDireccion3
		absLDireccion3 = buildAbsLDireccion3();
		verLDireccion.addComponent(absLDireccion3);
		
		return verLDireccion;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDireccion1() {
		// common part: create layout
		absLDireccion1 = new AbsoluteLayout();
		absLDireccion1.setImmediate(false);
		absLDireccion1.setWidth("100.0%");
		absLDireccion1.setHeight("43px");
		
		// selEdo
		selEdo = new NativeSelect();
		selEdo.setCaption("Estado");
		selEdo.setImmediate(false);
		selEdo.setWidth("180px");
		selEdo.setHeight("-1px");
		selEdo.setRequired(true);
		absLDireccion1.addComponent(selEdo, "top:18.0px;left:1.0px;");
		
		// cmbDelMpio
		cmbDelMpio = new ComboBox();
		cmbDelMpio.setCaption("Delegación / Municipio");
		cmbDelMpio.setImmediate(false);
		cmbDelMpio.setWidth("378px");
		cmbDelMpio.setHeight("-1px");
		cmbDelMpio.setRequired(true);
		absLDireccion1.addComponent(cmbDelMpio, "top:18.0px;left:201.0px;");
		
		return absLDireccion1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDireccion2() {
		// common part: create layout
		absLDireccion2 = new AbsoluteLayout();
		absLDireccion2.setImmediate(false);
		absLDireccion2.setWidth("100.0%");
		absLDireccion2.setHeight("43px");
		
		// txtCol
		txtCol = new TextField();
		txtCol.setCaption("Colonia");
		txtCol.setImmediate(false);
		txtCol.setWidth("280px");
		txtCol.setHeight("-1px");
		absLDireccion2.addComponent(txtCol, "top:18.0px;left:301.0px;");
		
		// cmbLoc
		cmbLoc = new ComboBox();
		cmbLoc.setCaption("Localidad");
		cmbLoc.setImmediate(false);
		cmbLoc.setWidth("280px");
		cmbLoc.setHeight("-1px");
		absLDireccion2.addComponent(cmbLoc, "top:18.0px;left:1.0px;");
		
		return absLDireccion2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDireccion3() {
		// common part: create layout
		absLDireccion3 = new AbsoluteLayout();
		absLDireccion3.setImmediate(false);
		absLDireccion3.setWidth("100.0%");
		absLDireccion3.setHeight("43px");
		
		// txtCalle
		txtCalle = new TextField();
		txtCalle.setCaption("Calle");
		txtCalle.setImmediate(false);
		txtCalle.setWidth("340px");
		txtCalle.setHeight("-1px");
		txtCalle.setRequired(true);
		absLDireccion3.addComponent(txtCalle, "top:18.0px;left:1.0px;");
		
		// txtNoExt
		txtNoExt = new TextField();
		txtNoExt.setCaption("No. Ext.");
		txtNoExt.setImmediate(false);
		txtNoExt.setWidth("60px");
		txtNoExt.setHeight("-1px");
		txtNoExt.setRequired(true);
		absLDireccion3.addComponent(txtNoExt, "top:18.0px;left:361.0px;");
		
		// txtNoInt
		txtNoInt = new TextField();
		txtNoInt.setCaption("No. Int.");
		txtNoInt.setImmediate(false);
		txtNoInt.setWidth("60px");
		txtNoInt.setHeight("-1px");
		absLDireccion3.addComponent(txtNoInt, "top:18.0px;left:441.0px;");
		
		// txtCP
		txtCP = new TextField();
		txtCP.setCaption("C.P.");
		txtCP.setImmediate(false);
		txtCP.setWidth("60px");
		txtCP.setHeight("-1px");
		absLDireccion3.addComponent(txtCP, "top:18.0px;left:521.0px;");
		
		return absLDireccion3;
	}

	@AutoGenerated
	private Panel buildPanDetTecnicos() {
		// common part: create layout
		panDetTecnicos = new Panel();
		panDetTecnicos.setImmediate(false);
		panDetTecnicos.setWidth("590px");
		panDetTecnicos.setHeight("-1px");
		
		// verLDetTecnicos
		verLDetTecnicos = buildVerLDetTecnicos();
		panDetTecnicos.setContent(verLDetTecnicos);
		
		return panDetTecnicos;
	}

	@AutoGenerated
	private VerticalLayout buildVerLDetTecnicos() {
		// common part: create layout
		verLDetTecnicos = new VerticalLayout();
		verLDetTecnicos.setImmediate(false);
		verLDetTecnicos.setWidth("100.0%");
		verLDetTecnicos.setHeight("100.0%");
		verLDetTecnicos.setMargin(false);
		
		// absLDetTecnicos1
		absLDetTecnicos1 = buildAbsLDetTecnicos1();
		verLDetTecnicos.addComponent(absLDetTecnicos1);
		
		// absLDetTecnicos2_1
		absLDetTecnicos2_1 = buildAbsLDetTecnicos2_1();
		verLDetTecnicos.addComponent(absLDetTecnicos2_1);
		
		// absLDetTecnicos2_2
		absLDetTecnicos2_2 = buildAbsLDetTecnicos2_2();
		verLDetTecnicos.addComponent(absLDetTecnicos2_2);
		
		return verLDetTecnicos;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDetTecnicos1() {
		// common part: create layout
		absLDetTecnicos1 = new AbsoluteLayout();
		absLDetTecnicos1.setImmediate(false);
		absLDetTecnicos1.setWidth("100.0%");
		absLDetTecnicos1.setHeight("43px");
		
		// selOrgCuenca
		selOrgCuenca = new NativeSelect();
		selOrgCuenca.setCaption("Organismo de Cuenca");
		selOrgCuenca.setImmediate(false);
		selOrgCuenca.setWidth("260px");
		selOrgCuenca.setHeight("-1px");
		selOrgCuenca.setRequired(true);
		absLDetTecnicos1.addComponent(selOrgCuenca, "top:18.0px;left:181.0px;");
		
		// datIngreso
		datIngreso = new TuningDateField();
		datIngreso.setCaption("Ingreso al Programa");
		datIngreso.setImmediate(false);
		datIngreso.setWidth("160px");
		datIngreso.setHeight("-1px");
		absLDetTecnicos1.addComponent(datIngreso, "top:18.0px;left:1.0px;");
		
		// stpTecnicos
		stpTecnicos = new IntStepper();
		stpTecnicos.setCaption("Técnicos a su Cargo");
		stpTecnicos.setImmediate(false);
		stpTecnicos.setWidth("120px");
		stpTecnicos.setHeight("24px");
		absLDetTecnicos1.addComponent(stpTecnicos, "top:18.0px;left:461.0px;");
		
		return absLDetTecnicos1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDetTecnicos2_1() {
		// common part: create layout
		absLDetTecnicos2_1 = new AbsoluteLayout();
		absLDetTecnicos2_1.setImmediate(false);
		absLDetTecnicos2_1.setWidth("100.0%");
		absLDetTecnicos2_1.setHeight("43px");
		
		// txtUdeRAtendidas
		txtUdeRAtendidas = new TextField();
		txtUdeRAtendidas.setCaption("Unidades de Riego Atendidas");
		txtUdeRAtendidas.setImmediate(false);
		txtUdeRAtendidas.setWidth("160px");
		txtUdeRAtendidas.setHeight("-1px");
		absLDetTecnicos2_1.addComponent(txtUdeRAtendidas,
				"top:18.0px;left:1.0px;");
		
		// selDtoR
		selDtoR = new NativeSelect();
		selDtoR.setCaption("Distrito de Riego");
		selDtoR.setImmediate(false);
		selDtoR.setWidth("220px");
		selDtoR.setHeight("-1px");
		absLDetTecnicos2_1.addComponent(selDtoR, "top:18.0px;left:181.0px;");
		
		// txtSupAtendida
		txtSupAtendida = new TextField();
		txtSupAtendida.setCaption("Superficie Atendida");
		txtSupAtendida.setImmediate(false);
		txtSupAtendida.setWidth("140px");
		txtSupAtendida.setHeight("-1px");
		txtSupAtendida.setRequired(true);
		absLDetTecnicos2_1.addComponent(txtSupAtendida,
				"top:18.0px;left:421.0px;");
		
		// lblHa
		lblHa = new Label();
		lblHa.setImmediate(false);
		lblHa.setWidth("-1px");
		lblHa.setHeight("-1px");
		lblHa.setValue("ha");
		absLDetTecnicos2_1.addComponent(lblHa, "top:22.0px;left:566.0px;");
		
		return absLDetTecnicos2_1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDetTecnicos2_2() {
		// common part: create layout
		absLDetTecnicos2_2 = new AbsoluteLayout();
		absLDetTecnicos2_2.setImmediate(false);
		absLDetTecnicos2_2.setWidth("100.0%");
		absLDetTecnicos2_2.setHeight("86px");
		
		// cmbSRL
		cmbSRL = new ComboBox();
		cmbSRL.setCaption("S.R.L.");
		cmbSRL.setImmediate(false);
		cmbSRL.setWidth("580px");
		cmbSRL.setHeight("-1px");
		absLDetTecnicos2_2.addComponent(cmbSRL, "top:18.0px;left:1.0px;");
		
		// txtModuloR
		txtModuloR = new TextField();
		txtModuloR.setCaption("Módulo de Riego");
		txtModuloR.setImmediate(false);
		txtModuloR.setWidth("580px");
		txtModuloR.setHeight("-1px");
		absLDetTecnicos2_2.addComponent(txtModuloR, "top:60.0px;left:1.0px;");
		
		return absLDetTecnicos2_2;
	}

	@AutoGenerated
	private Panel buildPanCredenciale() {
		// common part: create layout
		panCredenciale = new Panel();
		panCredenciale.setImmediate(false);
		panCredenciale.setWidth("402px");
		panCredenciale.setHeight("-1px");
		
		// verLCredenciale
		verLCredenciale = buildVerLCredenciale();
		panCredenciale.setContent(verLCredenciale);
		
		return panCredenciale;
	}

	@AutoGenerated
	private VerticalLayout buildVerLCredenciale() {
		// common part: create layout
		verLCredenciale = new VerticalLayout();
		verLCredenciale.setImmediate(false);
		verLCredenciale.setWidth("100.0%");
		verLCredenciale.setHeight("100.0%");
		verLCredenciale.setMargin(false);
		
		// absLCredenciales2
		absLCredenciales2 = buildAbsLCredenciales2();
		verLCredenciale.addComponent(absLCredenciales2);
		
		// absLCredenciales3
		absLCredenciales3 = buildAbsLCredenciales3();
		verLCredenciale.addComponent(absLCredenciales3);
		
		// absLCredenciales1
		absLCredenciales1 = buildAbsLCredenciales1();
		verLCredenciale.addComponent(absLCredenciales1);
		
		return verLCredenciale;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCredenciales2() {
		// common part: create layout
		absLCredenciales2 = new AbsoluteLayout();
		absLCredenciales2.setImmediate(false);
		absLCredenciales2.setWidth("100.0%");
		absLCredenciales2.setHeight("43px");
		
		// selFormacion
		selFormacion = new NativeSelect();
		selFormacion.setCaption("Formación Académica");
		selFormacion.setImmediate(false);
		selFormacion.setWidth("200px");
		selFormacion.setHeight("-1px");
		selFormacion.setRequired(true);
		absLCredenciales2.addComponent(selFormacion, "top:18.0px;left:1.0px;");
		
		// chkM
		chkM = new CheckBox();
		chkM.setCaption("Maestría");
		chkM.setImmediate(false);
		chkM.setWidth("70px");
		chkM.setHeight("-1px");
		absLCredenciales2.addComponent(chkM, "top:18.0px;left:221.0px;");
		
		// chkD
		chkD = new CheckBox();
		chkD.setCaption("Doctorado");
		chkD.setImmediate(false);
		chkD.setWidth("80px");
		chkD.setHeight("-1px");
		absLCredenciales2.addComponent(chkD, "top:18.0px;left:311.0px;");
		
		return absLCredenciales2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCredenciales3() {
		// common part: create layout
		absLCredenciales3 = new AbsoluteLayout();
		absLCredenciales3.setImmediate(false);
		absLCredenciales3.setWidth("100.0%");
		absLCredenciales3.setHeight("43px");
		
		// txtAcredFIRA
		txtAcredFIRA = new TextField();
		txtAcredFIRA.setCaption("Acreditación por FIRA");
		txtAcredFIRA.setImmediate(false);
		txtAcredFIRA.setWidth("290px");
		txtAcredFIRA.setHeight("-1px");
		absLCredenciales3.addComponent(txtAcredFIRA, "top:18.0px;left:1.0px;");
		
		return absLCredenciales3;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCredenciales1() {
		// common part: create layout
		absLCredenciales1 = new AbsoluteLayout();
		absLCredenciales1.setImmediate(false);
		absLCredenciales1.setWidth("100.0%");
		absLCredenciales1.setHeight("43px");
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setCaption("Institución, Empresa o Persona Física");
		textField_1.setImmediate(false);
		textField_1.setWidth("390px");
		textField_1.setHeight("-1px");
		absLCredenciales1.addComponent(textField_1, "top:18.0px;left:1.0px;");
		
		return absLCredenciales1;
	}

}