package com.saprigrat.ui.forms;

import java.util.LinkedList;

import com.saprigrat.data.Datos;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.FieldEvents.TextChangeEvent;
import com.vaadin.event.FieldEvents.TextChangeListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class Busqueda extends CustomComponent
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Label lblCantRes;
	@AutoGenerated
	private Table tblResultados;
	@AutoGenerated
	private Panel panBuscar;
	@AutoGenerated
	private AbsoluteLayout absLBuscar;
	@AutoGenerated
	private Button btnSel;
	@AutoGenerated
	private TextField txtBusqueda;
	@AutoGenerated
	private ComboBox cmbParametro;
	private Datos datos;
	public Busqueda()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);

		datos = new Datos();
		//Evitar que se seleccione una opción inválida
		cmbParametro.setTextInputAllowed(false);
		cmbParametro.setNullSelectionAllowed(false);
		//Configurar el botón de selección para regresar el registro seleccionado
		btnSel.addClickListener(clickListener());
	}
	
	public void setListado(String[]opciones)
	{
		//Poblar la lista 'Buscar por'
		for(String opc : opciones)
			cmbParametro.addItem(opc);
		//Seleccionar la primera opción
		cmbParametro.select(opciones[0]);
		
		//Generar las columnas de la tabla
		String cols = "";
		for(String col : opciones)
		{
			tblResultados.addContainerProperty(col, String.class, null);
			cols += col + ",";
		}
		if(cols.indexOf("Nombre") != -1)
		{
			tblResultados.addContainerProperty("Ap. Paterno", String.class, null);
			tblResultados.addContainerProperty("Ap. Materno", String.class, null);
		}
		else
			cols = cols.substring(0, cols.length() - 1);
		
		//Configurar el campo de búsqueda para realizar una búsqueda dinámica
		txtBusqueda.addTextChangeListener(textListener(cols));
	}
	
	private TextChangeListener textListener(final String columnas)
	{
		return new TextChangeListener()
				{
					@Override
					public void textChange(TextChangeEvent event)
					{
						//Vaciar la lista de resultados
						tblResultados.removeAllItems();
						if(!event.getText().isEmpty())
						{
							//Obtener el nuevo listado de la base de datos
							LinkedList<String[]> resultados = datos.getBusqueda(columnas,
																				cmbParametro.getValue() + "",
																				event.getText());
							//Poblar la lista nuevamente
							int cont = 0;
							for (; !resultados.isEmpty(); cont++)
							{
								tblResultados.addItem(resultados.remove(), null);
							}
							lblCantRes.setValue("Resultados: " + cont);
						}
					}
				};
	}
	
	private ClickListener clickListener()
	{
		return  new ClickListener()
				{
					@Override
					public void buttonClick(ClickEvent event)
					{
						//TODO
					}
				};
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// panBuscar
		panBuscar = buildPanBuscar();
		mainLayout.addComponent(panBuscar);
		
		// tblResultados
		tblResultados = new Table();
		tblResultados.setCaption("Resultados de la Búsqueda");
		tblResultados.setImmediate(false);
		tblResultados.setWidth("475px");
		tblResultados.setHeight("101px");
		mainLayout.addComponent(tblResultados);
		
		// lblCantRes
		lblCantRes = new Label();
		lblCantRes.setImmediate(false);
		lblCantRes.setWidth("-1px");
		lblCantRes.setHeight("-1px");
		lblCantRes.setValue("Resultados: 0");
		mainLayout.addComponent(lblCantRes);
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanBuscar() {
		// common part: create layout
		panBuscar = new Panel();
		panBuscar.setImmediate(false);
		panBuscar.setWidth("601px");
		panBuscar.setHeight("-1px");
		
		// absLBuscar
		absLBuscar = buildAbsLBuscar();
		panBuscar.setContent(absLBuscar);
		
		return panBuscar;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLBuscar() {
		// common part: create layout
		absLBuscar = new AbsoluteLayout();
		absLBuscar.setImmediate(false);
		absLBuscar.setWidth("100.0%");
		absLBuscar.setHeight("65px");
		
		// cmbParametro
		cmbParametro = new ComboBox();
		cmbParametro.setCaption("Buscar por:");
		cmbParametro.setImmediate(false);
		cmbParametro.setWidth("120px");
		cmbParametro.setHeight("25px");
		absLBuscar.addComponent(cmbParametro, "top:28.0px;left:10.0px;");
		
		// txtBusqueda
		txtBusqueda = new TextField();
		txtBusqueda.setImmediate(true);
		txtBusqueda.setWidth("325px");
		txtBusqueda.setHeight("25px");
		absLBuscar.addComponent(txtBusqueda, "top:28.0px;left:150.0px;");
		
		// btnSel
		btnSel = new Button();
		btnSel.setCaption("Seleccionar");
		btnSel.setImmediate(true);
		btnSel.setWidth("-1px");
		btnSel.setHeight("-1px");
		absLBuscar.addComponent(btnSel, "top:28.0px;left:495.0px;");
		
		return absLBuscar;
	}
}