package com.saprigrat.ui.forms;

import org.joda.time.format.DateTimeFormat;
import org.vaadin.addons.tuningdatefield.TuningDateField;

import com.saprigrat.ui.interfaces.Formulario;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Validator;
import com.vaadin.data.validator.RegexpValidator;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class Persona extends CustomComponent implements Formulario
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verLDatos;
	@AutoGenerated
	private Button btnAccion;
	@AutoGenerated
	private Panel panCredenciales;
	@AutoGenerated
	private VerticalLayout verLCredenciales;
	@AutoGenerated
	private AbsoluteLayout absLCredenciales3;
	@AutoGenerated
	private TextField txtInstitucion;
	@AutoGenerated
	private AbsoluteLayout absLCredenciales2;
	@AutoGenerated
	private TextField txtAcredFIRA;
	@AutoGenerated
	private AbsoluteLayout absLCredenciales1;
	@AutoGenerated
	private CheckBox chkD;
	@AutoGenerated
	private CheckBox chkM;
	@AutoGenerated
	private ComboBox cmbFormacion;
	@AutoGenerated
	private Panel panContacto;
	@AutoGenerated
	private AbsoluteLayout absLContacto;
	@AutoGenerated
	private TextField txtEmail;
	@AutoGenerated
	private TextField txtCel;
	@AutoGenerated
	private TextField txtTel;
	@AutoGenerated
	private Panel panDireccion;
	@AutoGenerated
	private VerticalLayout verLDireccion;
	@AutoGenerated
	private AbsoluteLayout absLDireccion3;
	@AutoGenerated
	private TextField txtCP;
	@AutoGenerated
	private TextField txtNoInt;
	@AutoGenerated
	private TextField txtNoExt;
	@AutoGenerated
	private TextField txtCalle;
	@AutoGenerated
	private AbsoluteLayout absLDireccion2;
	@AutoGenerated
	private TextField txtCol;
	@AutoGenerated
	private ComboBox cmbLoc;
	@AutoGenerated
	private AbsoluteLayout absLDireccion1;
	@AutoGenerated
	private ComboBox cmbMpio;
	@AutoGenerated
	private ComboBox cmbEdo;
	@AutoGenerated
	private Panel panGenerales;
	@AutoGenerated
	private AbsoluteLayout absLGenerales;
	@AutoGenerated
	private TuningDateField datIngreso;
	@AutoGenerated
	private Upload uplFoto;
	@AutoGenerated
	private Embedded imgFoto;
	@AutoGenerated
	private TuningDateField datNacimiento;
	@AutoGenerated
	private TextField txtApM;
	@AutoGenerated
	private TextField txtApP;
	@AutoGenerated
	private TextField txtNombre;
	@AutoGenerated
	private Panel panCURR;
	@AutoGenerated
	private AbsoluteLayout absLCURR;
	@AutoGenerated
	private Button btnBuscar;
	@AutoGenerated
	private TextField txtCURR;
	public Persona(int tipo)
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		if(tipo==3)
			panCredenciales.setVisible(false);
		
		setCalendario(datNacimiento);
		setCalendario(datIngreso);
		
		cmbMpio.setNewItemsAllowed(true);
		cmbLoc.setNewItemsAllowed(true);
		
		for(String item : arrEdos)		cmbEdo.addItem(item);
		for(String item : arrFormacion)	cmbFormacion.addItem(item);
		
		btnBuscar.addClickListener( new ClickListener()
									{
										@Override
										public void buttonClick(ClickEvent event)
										{
											verLDatos.setVisible(true);
										}
									});
		setValidaciones();
	}
	
	private void setCalendario(TuningDateField cal)
	{
		cal.setRequired(true);
		cal.setWeekendDisabled(false);
		cal.setDateTimeFormatter(DateTimeFormat.longDate());
		cal.setDateTextReadOnly(true);
	}
	
	private void setValidaciones()
	{
//		txtCURR.setMaxLength();
//		txtCURR.addValidator(validarRegEx());
		txtNombre.setMaxLength(40);
		txtApP.setMaxLength(20);
		txtApM.setMaxLength(20);
		
		txtCol.setMaxLength(40);
		txtCalle.setMaxLength(40);
		txtNoExt.setMaxLength(5);
		txtNoInt.setMaxLength(5);
		txtCP.setMaxLength(5);
//		txtCP.addValidator(validarInt(0, 99999));
		
		txtTel.setMaxLength(10);
		txtCel.setMaxLength(10);
		txtEmail.setMaxLength(254);
		txtEmail.addValidator(validarRegEx("^[0-9a-zA-Z\\._-]+@[0-9a-zA-Z_-]+(\\.[0-9a-zA-Z_-]+)+$",
										   "usuario@dominio.com"));
		txtEmail.setValidationVisible(true);
		
//		txtAcredFIRA.setMaxLength();
//		txtInstitucion.setMaxLength();
	}
	
	private Validator validarRegEx(String regex, String formato)
	{
		return new RegexpValidator( regex,
									"Debe cumplir con el formato: " + formato);
	}
	
	public void setTipo(int tipo)
	{
		if(tipo == 1)
		{
			btnAccion.setCaption("Agregar");
			panCURR.setVisible(false);
			verLDatos.setVisible(true);
		}
		else
		{
			btnAccion.setCaption("Modificar");
			panCURR.setVisible(true);
			verLDatos.setVisible(false);
		}
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// panCURR
		panCURR = buildPanCURR();
		mainLayout.addComponent(panCURR);
		
		// verLDatos
		verLDatos = buildVerLDatos();
		mainLayout.addComponent(verLDatos);
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanCURR() {
		// common part: create layout
		panCURR = new Panel();
		panCURR.setImmediate(false);
		panCURR.setWidth("601px");
		panCURR.setHeight("-1px");
		
		// absLCURR
		absLCURR = buildAbsLCURR();
		panCURR.setContent(absLCURR);
		
		return panCURR;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCURR() {
		// common part: create layout
		absLCURR = new AbsoluteLayout();
		absLCURR.setImmediate(false);
		absLCURR.setWidth("100.0%");
		absLCURR.setHeight("65px");
		
		// txtCURR
		txtCURR = new TextField();
		txtCURR.setCaption("CURR");
		txtCURR.setImmediate(true);
		txtCURR.setWidth("250px");
		txtCURR.setHeight("25px");
		txtCURR.setRequired(true);
		absLCURR.addComponent(txtCURR, "top:28.0px;left:10.0px;");
		
		// btnBuscar
		btnBuscar = new Button();
		btnBuscar.setCaption("Buscar");
		btnBuscar.setImmediate(true);
		btnBuscar.setWidth("70px");
		btnBuscar.setHeight("-1px");
		absLCURR.addComponent(btnBuscar, "top:28.0px;left:270.0px;");
		
		return absLCURR;
	}

	@AutoGenerated
	private VerticalLayout buildVerLDatos() {
		// common part: create layout
		verLDatos = new VerticalLayout();
		verLDatos.setImmediate(false);
		verLDatos.setWidth("-1px");
		verLDatos.setHeight("-1px");
		verLDatos.setMargin(false);
		verLDatos.setSpacing(true);
		
		// panGenerales
		panGenerales = buildPanGenerales();
		verLDatos.addComponent(panGenerales);
		
		// panDireccion
		panDireccion = buildPanDireccion();
		verLDatos.addComponent(panDireccion);
		
		// panContacto
		panContacto = buildPanContacto();
		verLDatos.addComponent(panContacto);
		
		// panCredenciales
		panCredenciales = buildPanCredenciales();
		verLDatos.addComponent(panCredenciales);
		
		// btnAccion
		btnAccion = new Button();
		btnAccion.setCaption("Button");
		btnAccion.setImmediate(true);
		btnAccion.setWidth("120px");
		btnAccion.setHeight("-1px");
		verLDatos.addComponent(btnAccion);
		verLDatos.setComponentAlignment(btnAccion, new Alignment(34));
		
		return verLDatos;
	}

	@AutoGenerated
	private Panel buildPanGenerales() {
		// common part: create layout
		panGenerales = new Panel();
		panGenerales.setCaption("Datos Generales");
		panGenerales.setImmediate(false);
		panGenerales.setWidth("601px");
		panGenerales.setHeight("-1px");
		
		// absLGenerales
		absLGenerales = buildAbsLGenerales();
		panGenerales.setContent(absLGenerales);
		
		return panGenerales;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLGenerales() {
		// common part: create layout
		absLGenerales = new AbsoluteLayout();
		absLGenerales.setImmediate(false);
		absLGenerales.setWidth("100.0%");
		absLGenerales.setHeight("245px");
		
		// txtNombre
		txtNombre = new TextField();
		txtNombre.setCaption("Nombre");
		txtNombre.setImmediate(false);
		txtNombre.setWidth("280px");
		txtNombre.setHeight("25px");
		txtNombre.setRequired(true);
		absLGenerales.addComponent(txtNombre, "top:28.0px;left:10.0px;");
		
		// txtApP
		txtApP = new TextField();
		txtApP.setCaption("Apellido Paterno");
		txtApP.setImmediate(false);
		txtApP.setWidth("170px");
		txtApP.setHeight("25px");
		txtApP.setRequired(true);
		absLGenerales.addComponent(txtApP, "top:73.0px;left:10.0px;");
		
		// txtApM
		txtApM = new TextField();
		txtApM.setCaption("Apellido Materno");
		txtApM.setImmediate(false);
		txtApM.setWidth("170px");
		txtApM.setHeight("25px");
		txtApM.setRequired(true);
		absLGenerales.addComponent(txtApM, "top:118.0px;left:10.0px;");
		
		// datNacimiento
		datNacimiento = new TuningDateField();
		datNacimiento.setCaption("Fecha de Nacimiento");
		datNacimiento.setImmediate(false);
		datNacimiento.setWidth("170px");
		datNacimiento.setHeight("25px");
		absLGenerales.addComponent(datNacimiento, "top:163.0px;left:10.0px;");
		
		// imgFoto
		imgFoto = new Embedded();
		imgFoto.setCaption("Foto (click para seleccionar)");
		imgFoto.setImmediate(false);
		imgFoto.setWidth("-1px");
		imgFoto.setHeight("200px");
		imgFoto.setSource(new ThemeResource("img/imgUnavailable.jpg"));
		imgFoto.setType(1);
		imgFoto.setMimeType("image/png");
		absLGenerales.addComponent(imgFoto, "top:28.0px;right:10.0px;");
		
		// uplFoto
		uplFoto = new Upload();
		uplFoto.setCaption("Foto");
		uplFoto.setEnabled(false);
		uplFoto.setImmediate(false);
		uplFoto.setVisible(false);
		uplFoto.setWidth("-1px");
		uplFoto.setHeight("27px");
		absLGenerales.addComponent(uplFoto, "top:163.0px;right:10.0px;");
		
		// datIngreso
		datIngreso = new TuningDateField();
		datIngreso.setCaption("Fecha de Ingreso al Programa");
		datIngreso.setImmediate(false);
		datIngreso.setWidth("170px");
		datIngreso.setHeight("25px");
		absLGenerales.addComponent(datIngreso, "top:208.0px;left:10.0px;");
		
		return absLGenerales;
	}

	@AutoGenerated
	private Panel buildPanDireccion() {
		// common part: create layout
		panDireccion = new Panel();
		panDireccion.setCaption("Dirección");
		panDireccion.setImmediate(false);
		panDireccion.setWidth("601px");
		panDireccion.setHeight("-1px");
		
		// verLDireccion
		verLDireccion = buildVerLDireccion();
		panDireccion.setContent(verLDireccion);
		
		return panDireccion;
	}

	@AutoGenerated
	private VerticalLayout buildVerLDireccion() {
		// common part: create layout
		verLDireccion = new VerticalLayout();
		verLDireccion.setImmediate(false);
		verLDireccion.setWidth("100.0%");
		verLDireccion.setHeight("100.0%");
		verLDireccion.setMargin(false);
		
		// absLDireccion1
		absLDireccion1 = buildAbsLDireccion1();
		verLDireccion.addComponent(absLDireccion1);
		
		// absLDireccion2
		absLDireccion2 = buildAbsLDireccion2();
		verLDireccion.addComponent(absLDireccion2);
		
		// absLDireccion3
		absLDireccion3 = buildAbsLDireccion3();
		verLDireccion.addComponent(absLDireccion3);
		
		return verLDireccion;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDireccion1() {
		// common part: create layout
		absLDireccion1 = new AbsoluteLayout();
		absLDireccion1.setImmediate(false);
		absLDireccion1.setWidth("100.0%");
		absLDireccion1.setHeight("55px");
		
		// cmbEdo
		cmbEdo = new ComboBox();
		cmbEdo.setCaption("Estado");
		cmbEdo.setImmediate(false);
		cmbEdo.setWidth("180px");
		cmbEdo.setHeight("25px");
		cmbEdo.setRequired(true);
		absLDireccion1.addComponent(cmbEdo, "top:28.0px;left:10.0px;");
		
		// cmbMpio
		cmbMpio = new ComboBox();
		cmbMpio.setCaption("Municipio");
		cmbMpio.setImmediate(true);
		cmbMpio.setWidth("380px");
		cmbMpio.setHeight("25px");
		cmbMpio.setRequired(true);
		absLDireccion1.addComponent(cmbMpio, "top:28.0px;left:210.0px;");
		
		return absLDireccion1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDireccion2() {
		// common part: create layout
		absLDireccion2 = new AbsoluteLayout();
		absLDireccion2.setImmediate(false);
		absLDireccion2.setWidth("100.0%");
		absLDireccion2.setHeight("45px");
		
		// cmbLoc
		cmbLoc = new ComboBox();
		cmbLoc.setCaption("Localidad");
		cmbLoc.setImmediate(true);
		cmbLoc.setWidth("280px");
		cmbLoc.setHeight("25px");
		absLDireccion2.addComponent(cmbLoc, "top:18.0px;left:10.0px;");
		
		// txtCol
		txtCol = new TextField();
		txtCol.setCaption("Colonia");
		txtCol.setImmediate(false);
		txtCol.setWidth("280px");
		txtCol.setHeight("25px");
		absLDireccion2.addComponent(txtCol, "top:18.0px;left:310.0px;");
		
		return absLDireccion2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDireccion3() {
		// common part: create layout
		absLDireccion3 = new AbsoluteLayout();
		absLDireccion3.setImmediate(false);
		absLDireccion3.setWidth("100.0%");
		absLDireccion3.setHeight("55px");
		
		// txtCalle
		txtCalle = new TextField();
		txtCalle.setCaption("Calle");
		txtCalle.setImmediate(false);
		txtCalle.setWidth("340px");
		txtCalle.setHeight("25px");
		txtCalle.setRequired(true);
		absLDireccion3.addComponent(txtCalle, "top:18.0px;left:10.0px;");
		
		// txtNoExt
		txtNoExt = new TextField();
		txtNoExt.setCaption("Núm. Ext.");
		txtNoExt.setImmediate(false);
		txtNoExt.setWidth("60px");
		txtNoExt.setHeight("25px");
		txtNoExt.setRequired(true);
		absLDireccion3.addComponent(txtNoExt, "top:18.0px;left:370.0px;");
		
		// txtNoInt
		txtNoInt = new TextField();
		txtNoInt.setCaption("Núm. Int.");
		txtNoInt.setImmediate(false);
		txtNoInt.setWidth("60px");
		txtNoInt.setHeight("25px");
		absLDireccion3.addComponent(txtNoInt, "top:18.0px;left:450.0px;");
		
		// txtCP
		txtCP = new TextField();
		txtCP.setCaption("C.P.");
		txtCP.setImmediate(true);
		txtCP.setWidth("60px");
		txtCP.setHeight("25px");
		absLDireccion3.addComponent(txtCP, "top:18.0px;left:530.0px;");
		
		return absLDireccion3;
	}

	@AutoGenerated
	private Panel buildPanContacto() {
		// common part: create layout
		panContacto = new Panel();
		panContacto.setCaption("Contacto");
		panContacto.setImmediate(false);
		panContacto.setWidth("601px");
		panContacto.setHeight("-1px");
		
		// absLContacto
		absLContacto = buildAbsLContacto();
		panContacto.setContent(absLContacto);
		
		return panContacto;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLContacto() {
		// common part: create layout
		absLContacto = new AbsoluteLayout();
		absLContacto.setImmediate(false);
		absLContacto.setWidth("100.0%");
		absLContacto.setHeight("65px");
		
		// txtTel
		txtTel = new TextField();
		txtTel.setCaption("Teléfono Fijo");
		txtTel.setImmediate(false);
		txtTel.setWidth("80px");
		txtTel.setHeight("25px");
		txtTel.setRequired(true);
		absLContacto.addComponent(txtTel, "top:28.0px;left:10.0px;");
		
		// txtCel
		txtCel = new TextField();
		txtCel.setCaption("Celular");
		txtCel.setImmediate(false);
		txtCel.setWidth("80px");
		txtCel.setHeight("25px");
		absLContacto.addComponent(txtCel, "top:28.0px;left:110.0px;");
		
		// txtEmail
		txtEmail = new TextField();
		txtEmail.setCaption("Correo electrónico");
		txtEmail.setImmediate(true);
		txtEmail.setWidth("380px");
		txtEmail.setHeight("25px");
		absLContacto.addComponent(txtEmail, "top:28.0px;left:210.0px;");
		
		return absLContacto;
	}

	@AutoGenerated
	private Panel buildPanCredenciales() {
		// common part: create layout
		panCredenciales = new Panel();
		panCredenciales.setImmediate(false);
		panCredenciales.setWidth("411px");
		panCredenciales.setHeight("-1px");
		
		// verLCredenciales
		verLCredenciales = buildVerLCredenciales();
		panCredenciales.setContent(verLCredenciales);
		
		return panCredenciales;
	}

	@AutoGenerated
	private VerticalLayout buildVerLCredenciales() {
		// common part: create layout
		verLCredenciales = new VerticalLayout();
		verLCredenciales.setImmediate(false);
		verLCredenciales.setWidth("100.0%");
		verLCredenciales.setHeight("100.0%");
		verLCredenciales.setMargin(false);
		
		// absLCredenciales1
		absLCredenciales1 = buildAbsLCredenciales1();
		verLCredenciales.addComponent(absLCredenciales1);
		
		// absLCredenciales2
		absLCredenciales2 = buildAbsLCredenciales2();
		verLCredenciales.addComponent(absLCredenciales2);
		
		// absLCredenciales3
		absLCredenciales3 = buildAbsLCredenciales3();
		verLCredenciales.addComponent(absLCredenciales3);
		
		return verLCredenciales;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCredenciales1() {
		// common part: create layout
		absLCredenciales1 = new AbsoluteLayout();
		absLCredenciales1.setImmediate(false);
		absLCredenciales1.setWidth("100.0%");
		absLCredenciales1.setHeight("55px");
		
		// cmbFormacion
		cmbFormacion = new ComboBox();
		cmbFormacion.setCaption("Formación Académica");
		cmbFormacion.setImmediate(false);
		cmbFormacion.setWidth("200px");
		cmbFormacion.setHeight("25px");
		cmbFormacion.setRequired(true);
		absLCredenciales1.addComponent(cmbFormacion, "top:28.0px;left:10.0px;");
		
		// chkM
		chkM = new CheckBox();
		chkM.setCaption("Maestría");
		chkM.setImmediate(false);
		chkM.setWidth("70px");
		chkM.setHeight("-1px");
		absLCredenciales1.addComponent(chkM, "top:28.0px;left:230.0px;");
		
		// chkD
		chkD = new CheckBox();
		chkD.setCaption("Doctorado");
		chkD.setImmediate(false);
		chkD.setWidth("80px");
		chkD.setHeight("-1px");
		absLCredenciales1.addComponent(chkD, "top:28.0px;left:320.0px;");
		
		return absLCredenciales1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCredenciales2() {
		// common part: create layout
		absLCredenciales2 = new AbsoluteLayout();
		absLCredenciales2.setImmediate(false);
		absLCredenciales2.setWidth("100.0%");
		absLCredenciales2.setHeight("45px");
		
		// txtAcredFIRA
		txtAcredFIRA = new TextField();
		txtAcredFIRA.setCaption("Acreditación por FIRA");
		txtAcredFIRA.setImmediate(false);
		txtAcredFIRA.setWidth("290px");
		txtAcredFIRA.setHeight("25px");
		absLCredenciales2.addComponent(txtAcredFIRA, "top:18.0px;left:10.0px;");
		
		return absLCredenciales2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCredenciales3() {
		// common part: create layout
		absLCredenciales3 = new AbsoluteLayout();
		absLCredenciales3.setImmediate(false);
		absLCredenciales3.setWidth("100.0%");
		absLCredenciales3.setHeight("55px");
		
		// txtInstitucion
		txtInstitucion = new TextField();
		txtInstitucion.setCaption("Institución, Empresa o Persona Física");
		txtInstitucion.setImmediate(false);
		txtInstitucion.setWidth("390px");
		txtInstitucion.setHeight("25px");
		absLCredenciales3.addComponent(txtInstitucion,
				"top:18.0px;left:10.0px;");
		
		return absLCredenciales3;
	}

}