package com.saprigrat.ui.forms;

import java.sql.Date;
import java.text.DecimalFormat;
import java.util.LinkedList;

import org.joda.time.LocalDate;
import org.joda.time.format.DateTimeFormat;
import org.vaadin.addons.tuningdatefield.TuningDateField;

import com.saprigrat.data.Datos;
import com.saprigrat.ui.interfaces.Formulario;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.validator.RegexpValidator;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Image;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class Persona extends CustomComponent implements Formulario
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verLDatos;
	@AutoGenerated
	private Button btnAccion;
	@AutoGenerated
	private Panel panCredenciales;
	@AutoGenerated
	private VerticalLayout verLCredenciales;
	@AutoGenerated
	private AbsoluteLayout absLCredenciales3;
	@AutoGenerated
	private TextField txtInstitucion;
	@AutoGenerated
	private AbsoluteLayout absLCredenciales2;
	@AutoGenerated
	private TextField txtAcredFIRA;
	@AutoGenerated
	private AbsoluteLayout absLCredenciales1;
	@AutoGenerated
	private CheckBox chkD;
	@AutoGenerated
	private CheckBox chkM;
	@AutoGenerated
	private ComboBox cmbFormacion;
	@AutoGenerated
	private Panel panContacto;
	@AutoGenerated
	private AbsoluteLayout absLContacto;
	@AutoGenerated
	private TextField txtEmail;
	@AutoGenerated
	private TextField txtCel;
	@AutoGenerated
	private TextField txtTel;
	@AutoGenerated
	private Panel panDireccion;
	@AutoGenerated
	private VerticalLayout verLDireccion;
	@AutoGenerated
	private AbsoluteLayout absLDireccion3;
	@AutoGenerated
	private TextField txtCP;
	@AutoGenerated
	private TextField txtNoInt;
	@AutoGenerated
	private TextField txtNoExt;
	@AutoGenerated
	private TextField txtCalle;
	@AutoGenerated
	private AbsoluteLayout absLDireccion2;
	@AutoGenerated
	private TextField txtCol;
	@AutoGenerated
	private ComboBox cmbLoc;
	@AutoGenerated
	private AbsoluteLayout absLDireccion1;
	@AutoGenerated
	private ComboBox cmbMpio;
	@AutoGenerated
	private ComboBox cmbEdo;
	@AutoGenerated
	private AbsoluteLayout absLGeneralesFoto;
	@AutoGenerated
	private Panel panGenerales;
	@AutoGenerated
	private VerticalLayout verLGenerales;
	@AutoGenerated
	private AbsoluteLayout absLGenerales4;
	@AutoGenerated
	private TuningDateField datIngreso;
	@AutoGenerated
	private AbsoluteLayout absLGenerales3;
	@AutoGenerated
	private TuningDateField datNacimiento;
	@AutoGenerated
	private AbsoluteLayout absLGenerales2;
	@AutoGenerated
	private TextField txtApM;
	@AutoGenerated
	private TextField txtApP;
	@AutoGenerated
	private AbsoluteLayout absLGenerales1;
	@AutoGenerated
	private TextField txtNombre;
	@AutoGenerated
	private Panel panFoto;
	@AutoGenerated
	private AbsoluteLayout absLFoto;
	@AutoGenerated
	private Upload uplFoto;
	@AutoGenerated
	private Image imgFoto;
	@AutoGenerated
	private Panel panCURR;
	@AutoGenerated
	private AbsoluteLayout absLCURR;
	@AutoGenerated
	private TextField txtCURR;
	@AutoGenerated
	private Busqueda panBusqueda;
	private Datos datos;
	private int tipoPersona;
	private LinkedList<String> estados;
	public Persona(int tipoPersona)
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);

		datos = new Datos();
		estados = new LinkedList<String>();
		this.tipoPersona = tipoPersona;
		if(tipoPersona!=3)
		{
			//Configurar el formato de fecha mostrado
			setCalendario(datNacimiento);
			//Configurar la imagen inicial (pendiente: poner botón de eliminar que regrese el componente a esta imagen)
			imgFoto.setSource(new ThemeResource("img/imgUnavailable.jpg"));
			uplFoto.setButtonCaption("Subir");
			//Configurar el manejo de la subida de imagen para que se muestre un preview
			ManejoDeImagenes manejo = new ManejoDeImagenes(imgFoto);
			uplFoto.setReceiver(manejo);
			uplFoto.addSucceededListener(manejo);
			//Poblar la lista de 'Formación'
			String[]formacion = {"Ing. Agrónomo",
								"Ing. en Irrigación",
								"Ing. Civil",
								"Ing. Agropecuario",
								"Otra Ingeniería",
								"Otro" };
			for(String item : formacion)
				cmbFormacion.addItem(item);
		}
		else
		{
			//No solicitar fecha de nacimiento
			datNacimiento.setLocalDate(new LocalDate());
			absLGenerales3.setVisible(false);
			absLGeneralesFoto.setHeight("176px");
			//No solicitar fotografía
			panFoto.setVisible(false);
			//No solicitar detalles académicos
			panCredenciales.setVisible(false);
		}
		
		//Configurar el formato de fecha mostrado
		setCalendario(datIngreso);
		datIngreso.setLocalDate(new LocalDate());
		//Poblar la lista de 'Estado'
		LinkedList<String>edos = datos.getEstados();
		estados.addAll(edos); 
		while(!edos.isEmpty())
			cmbEdo.addItem(edos.remove());
		//Agregar un listener a la lista para poblar la lista 'Municipio' dependiendo del estado seleccionado
		cmbEdo.addValueChangeListener(  new ValueChangeListener()
										{
											@Override
											public void valueChange(ValueChangeEvent event)
											{
												//Vaciar la lista 'Municipio'
												cmbMpio.removeAllItems();
												//Obtener el nuevo listado de la base de datos
												LinkedList<String>mpios = datos.getMunicipios(cmbEdo.getValue() + "");
												//Poblar la lista nuevamente
												while(!mpios.isEmpty())
													cmbMpio.addItem(mpios.remove());
											}
										});
		cmbEdo.select("Sonora");
		cmbLoc.setNewItemsAllowed(true);
		
		//Agregar las validaciones necesarias
		setValidaciones();
	}
	
	private void setCalendario(TuningDateField cal)
	{
		cal.setRequired(true);
		cal.setWeekendDisabled(false);
		cal.setDateTimeFormatter(DateTimeFormat.longDate());
		cal.setDateTextReadOnly(true);
	}
	
	private void setValidaciones()
	{
		txtNombre.setMaxLength(40);
		txtApP.setMaxLength(20);
		txtApM.setMaxLength(20);
		
		txtCol.setMaxLength(40);
		txtCalle.setMaxLength(40);
		txtNoExt.setMaxLength(5);
		txtNoInt.setMaxLength(5);
		txtCP.setMaxLength(5);
		
		txtTel.setMaxLength(10);
		txtCel.setMaxLength(10);
		txtEmail.setMaxLength(254);
		txtEmail.addValidator( new RegexpValidator( "^[0-9a-zA-Z\\._-]+@[0-9a-zA-Z_-]+(\\.[0-9a-zA-Z_-]+)+$",
													"Debe cumplir con el formato 'usuario@dominio.com'"));
		txtEmail.setValidationVisible(true);
		
		txtInstitucion.setMaxLength(200);
	}
	
	public void setTipo(int tipoOperacion)
	{
		if(tipoOperacion == 1)
		{
			btnAccion.setCaption("Agregar");
			btnAccion.addClickListener(agregarListener());
			panBusqueda.setVisible(false);
			verLDatos.setVisible(true);
		}
		else
		{
			panBusqueda.setListado(new String[]{"CURR", "Nombre"});
			btnAccion.setCaption("Modificar");
			btnAccion.addClickListener(modificarListener());
			panBusqueda.setVisible(true);
			verLDatos.setVisible(false);
		}
	}
	
	private String darFormato(String formato, int numero)
	{
		return new DecimalFormat(formato).format(numero);
	}
	
	private ClickListener agregarListener()
	{
		return  new ClickListener()
				{
					@Override
					public void buttonClick(ClickEvent event)
					{
						LocalDate fecha = datIngreso.getLocalDate();
						String curr =   darFormato("00", tipoPersona) +
										darFormato("00", estados.indexOf(cmbEdo.getValue()) + 1) +
										darFormato("00", fecha.getYearOfCentury()) +
										darFormato("00", fecha.getMonthOfYear()) +
										darFormato("00", fecha.getDayOfMonth()) +
										darFormato("0000", datos.getContadorEstatal(tipoPersona, cmbEdo.getValue() + "") + 1);
						
						LinkedList<Object> valores = new LinkedList<Object>();
						valores.add("CURR");
						valores.add(curr);
						valores.add("tipo");
						valores.add(tipoPersona);
						valores.add("nombre");
						valores.add(txtNombre.getValue());
						valores.add("apPat");
						valores.add(txtApP.getValue());
						valores.add("apMat");
						valores.add(txtApM.getValue());
						valores.add("fechaNac");
						valores.add(new Date(datNacimiento.getLocalDate().toDate().getTime()));
						valores.add("foto");
						valores.add(imgFoto.getAlternateText());
						valores.add("fechaIng");
						valores.add(new Date(datIngreso.getLocalDate().toDate().getTime()));
						valores.add("estado");
						valores.add(cmbEdo.getValue());
						valores.add("municipio");
						valores.add(cmbMpio.getValue());
						valores.add("localidad");
						valores.add(cmbLoc.getValue());
						valores.add("colonia");
						valores.add(txtCol.getValue());
						valores.add("calle");
						valores.add(txtCalle.getValue());
						valores.add("noExt");
						valores.add(txtNoExt.getValue());
						valores.add("noInt");
						valores.add(txtNoInt.getValue());
						valores.add("cp");
						valores.add(txtCP.getValue());
						valores.add("tel");
						valores.add(txtTel.getValue());
						valores.add("cel");
						valores.add(txtCel.getValue());
						valores.add("email");
						valores.add(txtEmail.getValue());
						valores.add("formAcademica");
						valores.add(cmbFormacion.getValue());
						valores.add("maestria");
						valores.add(chkM.getValue());
						valores.add("doctorado");
						valores.add(chkD.getValue());
						valores.add("acredFIRA");
						valores.add(txtAcredFIRA.getValue());
						valores.add("institucion");
						valores.add(txtInstitucion.getValue());
						
						if(datos.registrar("personas", valores))
							Notification.show("Registro añadido correctamente.\nCURR asignado: " + curr, Notification.Type.TRAY_NOTIFICATION);
					}
				};
	}
	
	private ClickListener modificarListener()
	{
		return  new ClickListener()
				{
					@Override
					public void buttonClick(ClickEvent event)
					{
						LinkedList<Object> valores = new LinkedList<Object>();
						valores.add("CURR");
						valores.add(txtCURR.getValue());
						valores.add("nombre");
						valores.add(txtNombre.getValue());
						valores.add("apPat");
						valores.add(txtApP.getValue());
						valores.add("apMat");
						valores.add(txtApM.getValue());
						valores.add("fechaNac");
						valores.add(new Date(datNacimiento.getLocalDate().toDate().getTime()));
						valores.add("foto");
						valores.add(imgFoto.getAlternateText());
						valores.add("municipio");
						valores.add(cmbMpio.getValue());
						valores.add("localidad");
						valores.add(cmbLoc.getValue());
						valores.add("colonia");
						valores.add(txtCol.getValue());
						valores.add("calle");
						valores.add(txtCalle.getValue());
						valores.add("noExt");
						valores.add(txtNoExt.getValue());
						valores.add("noInt");
						valores.add(txtNoInt.getValue());
						valores.add("cp");
						valores.add(txtCP.getValue());
						valores.add("tel");
						valores.add(txtTel.getValue());
						valores.add("cel");
						valores.add(txtCel.getValue());
						valores.add("email");
						valores.add(txtEmail.getValue());
						valores.add("formAcademica");
						valores.add(cmbFormacion.getValue());
						valores.add("maestria");
						valores.add(chkM.getValue());
						valores.add("doctorado");
						valores.add(chkD.getValue());
						valores.add("acredFIRA");
						valores.add(txtAcredFIRA.getValue());
						valores.add("institucion");
						valores.add(txtInstitucion.getValue());
						
						datos.registrar("personas", valores);
					}
				};
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// panBusqueda
		panBusqueda = new Busqueda();
		panBusqueda.setImmediate(false);
		panBusqueda.setWidth("100.0%");
		panBusqueda.setHeight("-1px");
		mainLayout.addComponent(panBusqueda);
		
		// verLDatos
		verLDatos = buildVerLDatos();
		mainLayout.addComponent(verLDatos);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerLDatos() {
		// common part: create layout
		verLDatos = new VerticalLayout();
		verLDatos.setImmediate(false);
		verLDatos.setWidth("-1px");
		verLDatos.setHeight("-1px");
		verLDatos.setMargin(false);
		verLDatos.setSpacing(true);
		
		// panCURR
		panCURR = buildPanCURR();
		verLDatos.addComponent(panCURR);
		
		// absLGeneralesFoto
		absLGeneralesFoto = buildAbsLGeneralesFoto();
		verLDatos.addComponent(absLGeneralesFoto);
		
		// panDireccion
		panDireccion = buildPanDireccion();
		verLDatos.addComponent(panDireccion);
		
		// panContacto
		panContacto = buildPanContacto();
		verLDatos.addComponent(panContacto);
		
		// panCredenciales
		panCredenciales = buildPanCredenciales();
		verLDatos.addComponent(panCredenciales);
		
		// btnAccion
		btnAccion = new Button();
		btnAccion.setCaption("Button");
		btnAccion.setImmediate(true);
		btnAccion.setWidth("120px");
		btnAccion.setHeight("-1px");
		verLDatos.addComponent(btnAccion);
		verLDatos.setComponentAlignment(btnAccion, new Alignment(34));
		
		return verLDatos;
	}

	@AutoGenerated
	private Panel buildPanCURR() {
		// common part: create layout
		panCURR = new Panel();
		panCURR.setCaption("CURR (Clave Unica de Registro de RIGRAT)");
		panCURR.setImmediate(false);
		panCURR.setWidth("281px");
		panCURR.setHeight("-1px");
		
		// absLCURR
		absLCURR = buildAbsLCURR();
		panCURR.setContent(absLCURR);
		
		return panCURR;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCURR() {
		// common part: create layout
		absLCURR = new AbsoluteLayout();
		absLCURR.setImmediate(false);
		absLCURR.setWidth("100.0%");
		absLCURR.setHeight("45px");
		
		// txtCURR
		txtCURR = new TextField();
		txtCURR.setImmediate(false);
		txtCURR.setWidth("260px");
		txtCURR.setHeight("25px");
		absLCURR.addComponent(txtCURR, "top:10.0px;left:10.0px;");
		
		return absLCURR;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLGeneralesFoto() {
		// common part: create layout
		absLGeneralesFoto = new AbsoluteLayout();
		absLGeneralesFoto.setImmediate(false);
		absLGeneralesFoto.setWidth("100.0%");
		absLGeneralesFoto.setHeight("221px");
		
		// panFoto
		panFoto = buildPanFoto();
		absLGeneralesFoto.addComponent(panFoto, "top:0.0px;right:0.0px;");
		
		// panGenerales
		panGenerales = buildPanGenerales();
		absLGeneralesFoto.addComponent(panGenerales, "top:0.0px;left:0.0px;");
		
		return absLGeneralesFoto;
	}

	@AutoGenerated
	private Panel buildPanFoto() {
		// common part: create layout
		panFoto = new Panel();
		panFoto.setCaption("Foto");
		panFoto.setImmediate(false);
		panFoto.setWidth("311px");
		panFoto.setHeight("-1px");
		
		// absLFoto
		absLFoto = buildAbsLFoto();
		panFoto.setContent(absLFoto);
		
		return panFoto;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLFoto() {
		// common part: create layout
		absLFoto = new AbsoluteLayout();
		absLFoto.setImmediate(false);
		absLFoto.setWidth("100.0%");
		absLFoto.setHeight("200px");
		
		// imgFoto
		imgFoto = new Image();
		imgFoto.setImmediate(false);
		imgFoto.setWidth("-1px");
		imgFoto.setHeight("180px");
		absLFoto.addComponent(imgFoto, "top:10.0px;left:10.0px;");
		
		// uplFoto
		uplFoto = new Upload();
		uplFoto.setImmediate(true);
		uplFoto.setWidth("-1px");
		uplFoto.setHeight("-1px");
		absLFoto.addComponent(uplFoto, "right:5.0px;bottom:5.0px;");
		
		return absLFoto;
	}

	@AutoGenerated
	private Panel buildPanGenerales() {
		// common part: create layout
		panGenerales = new Panel();
		panGenerales.setCaption("Datos Generales");
		panGenerales.setImmediate(false);
		panGenerales.setWidth("281px");
		panGenerales.setHeight("-1px");
		
		// verLGenerales
		verLGenerales = buildVerLGenerales();
		panGenerales.setContent(verLGenerales);
		
		return panGenerales;
	}

	@AutoGenerated
	private VerticalLayout buildVerLGenerales() {
		// common part: create layout
		verLGenerales = new VerticalLayout();
		verLGenerales.setImmediate(false);
		verLGenerales.setWidth("100.0%");
		verLGenerales.setHeight("-1px");
		verLGenerales.setMargin(false);
		
		// absLGenerales1
		absLGenerales1 = buildAbsLGenerales1();
		verLGenerales.addComponent(absLGenerales1);
		
		// absLGenerales2
		absLGenerales2 = buildAbsLGenerales2();
		verLGenerales.addComponent(absLGenerales2);
		
		// absLGenerales3
		absLGenerales3 = buildAbsLGenerales3();
		verLGenerales.addComponent(absLGenerales3);
		
		// absLGenerales4
		absLGenerales4 = buildAbsLGenerales4();
		verLGenerales.addComponent(absLGenerales4);
		
		return verLGenerales;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLGenerales1() {
		// common part: create layout
		absLGenerales1 = new AbsoluteLayout();
		absLGenerales1.setImmediate(false);
		absLGenerales1.setWidth("100.0%");
		absLGenerales1.setHeight("55px");
		
		// txtNombre
		txtNombre = new TextField();
		txtNombre.setCaption("Nombre");
		txtNombre.setImmediate(false);
		txtNombre.setWidth("260px");
		txtNombre.setHeight("25px");
		txtNombre.setInvalidAllowed(false);
		txtNombre.setRequired(true);
		absLGenerales1.addComponent(txtNombre, "top:28.0px;left:10.0px;");
		
		return absLGenerales1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLGenerales2() {
		// common part: create layout
		absLGenerales2 = new AbsoluteLayout();
		absLGenerales2.setImmediate(false);
		absLGenerales2.setWidth("100.0%");
		absLGenerales2.setHeight("45px");
		
		// txtApP
		txtApP = new TextField();
		txtApP.setCaption("Apellido Paterno");
		txtApP.setImmediate(false);
		txtApP.setWidth("120px");
		txtApP.setHeight("25px");
		txtApP.setRequired(true);
		absLGenerales2.addComponent(txtApP, "top:18.0px;left:10.0px;");
		
		// txtApM
		txtApM = new TextField();
		txtApM.setCaption("Apellido Materno");
		txtApM.setImmediate(false);
		txtApM.setWidth("120px");
		txtApM.setHeight("25px");
		txtApM.setRequired(true);
		absLGenerales2.addComponent(txtApM, "top:18.0px;left:150.0px;");
		
		return absLGenerales2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLGenerales3() {
		// common part: create layout
		absLGenerales3 = new AbsoluteLayout();
		absLGenerales3.setImmediate(false);
		absLGenerales3.setWidth("100.0%");
		absLGenerales3.setHeight("45px");
		
		// datNacimiento
		datNacimiento = new TuningDateField();
		datNacimiento.setCaption("Fecha de Nacimiento");
		datNacimiento.setImmediate(false);
		datNacimiento.setWidth("200px");
		datNacimiento.setHeight("25px");
		absLGenerales3.addComponent(datNacimiento, "top:18.0px;left:10.0px;");
		
		return absLGenerales3;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLGenerales4() {
		// common part: create layout
		absLGenerales4 = new AbsoluteLayout();
		absLGenerales4.setImmediate(false);
		absLGenerales4.setWidth("100.0%");
		absLGenerales4.setHeight("55px");
		
		// datIngreso
		datIngreso = new TuningDateField();
		datIngreso.setCaption("Fecha de Ingreso al Programa");
		datIngreso.setImmediate(false);
		datIngreso.setWidth("200px");
		datIngreso.setHeight("25px");
		absLGenerales4.addComponent(datIngreso, "top:18.0px;left:10.0px;");
		
		return absLGenerales4;
	}

	@AutoGenerated
	private Panel buildPanDireccion() {
		// common part: create layout
		panDireccion = new Panel();
		panDireccion.setCaption("Dirección");
		panDireccion.setImmediate(false);
		panDireccion.setWidth("601px");
		panDireccion.setHeight("-1px");
		
		// verLDireccion
		verLDireccion = buildVerLDireccion();
		panDireccion.setContent(verLDireccion);
		
		return panDireccion;
	}

	@AutoGenerated
	private VerticalLayout buildVerLDireccion() {
		// common part: create layout
		verLDireccion = new VerticalLayout();
		verLDireccion.setImmediate(false);
		verLDireccion.setWidth("100.0%");
		verLDireccion.setHeight("100.0%");
		verLDireccion.setMargin(false);
		
		// absLDireccion1
		absLDireccion1 = buildAbsLDireccion1();
		verLDireccion.addComponent(absLDireccion1);
		
		// absLDireccion2
		absLDireccion2 = buildAbsLDireccion2();
		verLDireccion.addComponent(absLDireccion2);
		
		// absLDireccion3
		absLDireccion3 = buildAbsLDireccion3();
		verLDireccion.addComponent(absLDireccion3);
		
		return verLDireccion;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDireccion1() {
		// common part: create layout
		absLDireccion1 = new AbsoluteLayout();
		absLDireccion1.setImmediate(false);
		absLDireccion1.setWidth("100.0%");
		absLDireccion1.setHeight("55px");
		
		// cmbEdo
		cmbEdo = new ComboBox();
		cmbEdo.setCaption("Estado");
		cmbEdo.setImmediate(true);
		cmbEdo.setWidth("180px");
		cmbEdo.setHeight("25px");
		cmbEdo.setRequired(true);
		absLDireccion1.addComponent(cmbEdo, "top:28.0px;left:10.0px;");
		
		// cmbMpio
		cmbMpio = new ComboBox();
		cmbMpio.setCaption("Municipio");
		cmbMpio.setImmediate(true);
		cmbMpio.setWidth("380px");
		cmbMpio.setHeight("25px");
		cmbMpio.setRequired(true);
		absLDireccion1.addComponent(cmbMpio, "top:28.0px;left:210.0px;");
		
		return absLDireccion1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDireccion2() {
		// common part: create layout
		absLDireccion2 = new AbsoluteLayout();
		absLDireccion2.setImmediate(false);
		absLDireccion2.setWidth("100.0%");
		absLDireccion2.setHeight("45px");
		
		// cmbLoc
		cmbLoc = new ComboBox();
		cmbLoc.setCaption("Localidad");
		cmbLoc.setImmediate(false);
		cmbLoc.setWidth("280px");
		cmbLoc.setHeight("25px");
		absLDireccion2.addComponent(cmbLoc, "top:18.0px;left:10.0px;");
		
		// txtCol
		txtCol = new TextField();
		txtCol.setCaption("Colonia");
		txtCol.setImmediate(false);
		txtCol.setWidth("280px");
		txtCol.setHeight("25px");
		absLDireccion2.addComponent(txtCol, "top:18.0px;left:310.0px;");
		
		return absLDireccion2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDireccion3() {
		// common part: create layout
		absLDireccion3 = new AbsoluteLayout();
		absLDireccion3.setImmediate(false);
		absLDireccion3.setWidth("100.0%");
		absLDireccion3.setHeight("55px");
		
		// txtCalle
		txtCalle = new TextField();
		txtCalle.setCaption("Calle");
		txtCalle.setImmediate(false);
		txtCalle.setWidth("340px");
		txtCalle.setHeight("25px");
		txtCalle.setRequired(true);
		absLDireccion3.addComponent(txtCalle, "top:18.0px;left:10.0px;");
		
		// txtNoExt
		txtNoExt = new TextField();
		txtNoExt.setCaption("Núm. Ext.");
		txtNoExt.setImmediate(false);
		txtNoExt.setWidth("60px");
		txtNoExt.setHeight("25px");
		txtNoExt.setRequired(true);
		absLDireccion3.addComponent(txtNoExt, "top:18.0px;left:370.0px;");
		
		// txtNoInt
		txtNoInt = new TextField();
		txtNoInt.setCaption("Núm. Int.");
		txtNoInt.setImmediate(false);
		txtNoInt.setWidth("60px");
		txtNoInt.setHeight("25px");
		absLDireccion3.addComponent(txtNoInt, "top:18.0px;left:450.0px;");
		
		// txtCP
		txtCP = new TextField();
		txtCP.setCaption("C.P.");
		txtCP.setImmediate(true);
		txtCP.setWidth("60px");
		txtCP.setHeight("25px");
		absLDireccion3.addComponent(txtCP, "top:18.0px;left:530.0px;");
		
		return absLDireccion3;
	}

	@AutoGenerated
	private Panel buildPanContacto() {
		// common part: create layout
		panContacto = new Panel();
		panContacto.setCaption("Contacto");
		panContacto.setImmediate(false);
		panContacto.setWidth("601px");
		panContacto.setHeight("-1px");
		
		// absLContacto
		absLContacto = buildAbsLContacto();
		panContacto.setContent(absLContacto);
		
		return panContacto;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLContacto() {
		// common part: create layout
		absLContacto = new AbsoluteLayout();
		absLContacto.setImmediate(false);
		absLContacto.setWidth("100.0%");
		absLContacto.setHeight("65px");
		
		// txtTel
		txtTel = new TextField();
		txtTel.setCaption("Teléfono Fijo (10dig)");
		txtTel.setImmediate(false);
		txtTel.setWidth("115px");
		txtTel.setHeight("25px");
		txtTel.setRequired(true);
		absLContacto.addComponent(txtTel, "top:28.0px;left:10.0px;");
		
		// txtCel
		txtCel = new TextField();
		txtCel.setCaption("Celular (10dig)");
		txtCel.setImmediate(false);
		txtCel.setWidth("115px");
		txtCel.setHeight("25px");
		absLContacto.addComponent(txtCel, "top:28.0px;left:145.0px;");
		
		// txtEmail
		txtEmail = new TextField();
		txtEmail.setCaption("Correo electrónico");
		txtEmail.setImmediate(true);
		txtEmail.setWidth("310px");
		txtEmail.setHeight("25px");
		absLContacto.addComponent(txtEmail, "top:28.0px;left:280.0px;");
		
		return absLContacto;
	}

	@AutoGenerated
	private Panel buildPanCredenciales() {
		// common part: create layout
		panCredenciales = new Panel();
		panCredenciales.setImmediate(false);
		panCredenciales.setWidth("411px");
		panCredenciales.setHeight("-1px");
		
		// verLCredenciales
		verLCredenciales = buildVerLCredenciales();
		panCredenciales.setContent(verLCredenciales);
		
		return panCredenciales;
	}

	@AutoGenerated
	private VerticalLayout buildVerLCredenciales() {
		// common part: create layout
		verLCredenciales = new VerticalLayout();
		verLCredenciales.setImmediate(false);
		verLCredenciales.setWidth("100.0%");
		verLCredenciales.setHeight("100.0%");
		verLCredenciales.setMargin(false);
		
		// absLCredenciales1
		absLCredenciales1 = buildAbsLCredenciales1();
		verLCredenciales.addComponent(absLCredenciales1);
		
		// absLCredenciales2
		absLCredenciales2 = buildAbsLCredenciales2();
		verLCredenciales.addComponent(absLCredenciales2);
		
		// absLCredenciales3
		absLCredenciales3 = buildAbsLCredenciales3();
		verLCredenciales.addComponent(absLCredenciales3);
		
		return verLCredenciales;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCredenciales1() {
		// common part: create layout
		absLCredenciales1 = new AbsoluteLayout();
		absLCredenciales1.setImmediate(false);
		absLCredenciales1.setWidth("100.0%");
		absLCredenciales1.setHeight("55px");
		
		// cmbFormacion
		cmbFormacion = new ComboBox();
		cmbFormacion.setCaption("Formación Académica");
		cmbFormacion.setImmediate(false);
		cmbFormacion.setWidth("200px");
		cmbFormacion.setHeight("25px");
		cmbFormacion.setRequired(true);
		absLCredenciales1.addComponent(cmbFormacion, "top:28.0px;left:10.0px;");
		
		// chkM
		chkM = new CheckBox();
		chkM.setCaption("Maestría");
		chkM.setImmediate(false);
		chkM.setWidth("70px");
		chkM.setHeight("-1px");
		absLCredenciales1.addComponent(chkM, "top:28.0px;left:230.0px;");
		
		// chkD
		chkD = new CheckBox();
		chkD.setCaption("Doctorado");
		chkD.setImmediate(false);
		chkD.setWidth("80px");
		chkD.setHeight("-1px");
		absLCredenciales1.addComponent(chkD, "top:28.0px;left:320.0px;");
		
		return absLCredenciales1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCredenciales2() {
		// common part: create layout
		absLCredenciales2 = new AbsoluteLayout();
		absLCredenciales2.setImmediate(false);
		absLCredenciales2.setWidth("100.0%");
		absLCredenciales2.setHeight("45px");
		
		// txtAcredFIRA
		txtAcredFIRA = new TextField();
		txtAcredFIRA.setCaption("Acreditación por FIRA");
		txtAcredFIRA.setImmediate(false);
		txtAcredFIRA.setWidth("290px");
		txtAcredFIRA.setHeight("25px");
		absLCredenciales2.addComponent(txtAcredFIRA, "top:18.0px;left:10.0px;");
		
		return absLCredenciales2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCredenciales3() {
		// common part: create layout
		absLCredenciales3 = new AbsoluteLayout();
		absLCredenciales3.setImmediate(false);
		absLCredenciales3.setWidth("100.0%");
		absLCredenciales3.setHeight("55px");
		
		// txtInstitucion
		txtInstitucion = new TextField();
		txtInstitucion.setCaption("Institución, Empresa o Persona Física");
		txtInstitucion.setImmediate(false);
		txtInstitucion.setWidth("390px");
		txtInstitucion.setHeight("25px");
		absLCredenciales3.addComponent(txtInstitucion,
				"top:18.0px;left:10.0px;");
		
		return absLCredenciales3;
	}

}