package com.saprigrat.ui.forms;

import com.saprigrat.data.Datos;
import com.saprigrat.ui.components.Busqueda;
import com.saprigrat.ui.components.Foto;
import com.saprigrat.ui.interfaces.Formulario;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class Pozo extends CustomComponent implements Formulario
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verLDatos;
	@AutoGenerated
	private Button btnAccion;
	@AutoGenerated
	private Panel panObservaciones;
	@AutoGenerated
	private AbsoluteLayout absLObservaciones;
	@AutoGenerated
	private TextArea txtObservaciones;
	@AutoGenerated
	private AbsoluteLayout absLCFEBombaFlujo;
	@AutoGenerated
	private Panel panMedidorCFE;
	@AutoGenerated
	private AbsoluteLayout absLMedidorCFE;
	@AutoGenerated
	private TextField txtMultiplicador;
	@AutoGenerated
	private TextField txtTarifa;
	@AutoGenerated
	private TextField txtNoMedidor;
	@AutoGenerated
	private Panel panMedidorFlujo;
	@AutoGenerated
	private AbsoluteLayout absLMedidorFlujo;
	@AutoGenerated
	private TextField txtNoSerie;
	@AutoGenerated
	private Label lblGasto;
	@AutoGenerated
	private TextField txtGasto;
	@AutoGenerated
	private TextField txtMarca;
	@AutoGenerated
	private Panel panBomba;
	@AutoGenerated
	private AbsoluteLayout absLBomba;
	@AutoGenerated
	private Label lblDiametro;
	@AutoGenerated
	private TextField txtDiametro;
	@AutoGenerated
	private Label lblPotencia;
	@AutoGenerated
	private TextField txtPotencia;
	@AutoGenerated
	private ComboBox cmbTipoBomba;
	@AutoGenerated
	private AbsoluteLayout absLGralesFotoCaractsCoords;
	@AutoGenerated
	private Foto panFoto;
	@AutoGenerated
	private Panel panCoordenadas;
	@AutoGenerated
	private AbsoluteLayout absLCoordenadas;
	@AutoGenerated
	private TextField txtCoordY;
	@AutoGenerated
	private TextField txtCoordX;
	@AutoGenerated
	private Panel panCaracteristicas;
	@AutoGenerated
	private AbsoluteLayout absLCaracteristicas;
	@AutoGenerated
	private Label lblProfPerforacion;
	@AutoGenerated
	private TextField txtProfPerforacion;
	@AutoGenerated
	private Label lblNivelDin;
	@AutoGenerated
	private TextField txtNivelDin;
	@AutoGenerated
	private Label lblNivelEst;
	@AutoGenerated
	private TextField txtNivelEst;
	@AutoGenerated
	private Label lblVolCon;
	@AutoGenerated
	private TextField txtVolCon;
	@AutoGenerated
	private Label lblGastoCon;
	@AutoGenerated
	private TextField txtGastoCon;
	@AutoGenerated
	private Panel panGenerales;
	@AutoGenerated
	private AbsoluteLayout absLGenerales;
	@AutoGenerated
	private TextField txtAcuifero;
	@AutoGenerated
	private TextField txtNoIdentificacion;
	@AutoGenerated
	private TextField txtNoConcesion;
	@AutoGenerated
	private Busqueda panBusqueda;
	private Datos datos;
	public Pozo()
	{
		inicializar();
	}
	
	public void inicializar()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
		datos = new Datos();
		
	}

	@Override
	public void setTipo(int tipoOperacion)
	{
		if(tipoOperacion == 1)
		{
			panBusqueda.setVisible(false);
			verLDatos.setVisible(true);
			btnAccion.addClickListener(agregarListener());
		}
		else
		{
			panBusqueda.setListado(new String[]{"CURR", "Nombre"}, null);
			panBusqueda.setVisible(true);
			verLDatos.setVisible(false);
			btnAccion.setCaption("Modificar");
			btnAccion.addClickListener(modificarListener());
		}
	}

	@Override
	public int getEntidad()
	{
		return 2;
	}
	
	@Override
	public Object[] getRestricciones()
	{
		return new Object[]{};
	}
	
	private ClickListener agregarListener()
	{
		return null;
	}
	
	private ClickListener modificarListener()
	{
		return null;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// panBusqueda
		panBusqueda = new Busqueda();
		panBusqueda.setImmediate(false);
		panBusqueda.setWidth("100.0%");
		panBusqueda.setHeight("-1px");
		mainLayout.addComponent(panBusqueda);
		
		// verLDatos
		verLDatos = buildVerLDatos();
		mainLayout.addComponent(verLDatos);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerLDatos() {
		// common part: create layout
		verLDatos = new VerticalLayout();
		verLDatos.setImmediate(false);
		verLDatos.setWidth("-1px");
		verLDatos.setHeight("-1px");
		verLDatos.setMargin(false);
		verLDatos.setSpacing(true);
		
		// absLGralesFotoCaractsCoords
		absLGralesFotoCaractsCoords = buildAbsLGralesFotoCaractsCoords();
		verLDatos.addComponent(absLGralesFotoCaractsCoords);
		
		// absLCFEBombaFlujo
		absLCFEBombaFlujo = buildAbsLCFEBombaFlujo();
		verLDatos.addComponent(absLCFEBombaFlujo);
		
		// panObservaciones
		panObservaciones = buildPanObservaciones();
		verLDatos.addComponent(panObservaciones);
		
		// btnAccion
		btnAccion = new Button();
		btnAccion.setCaption("Agregar");
		btnAccion.setImmediate(true);
		btnAccion.setWidth("120px");
		btnAccion.setHeight("-1px");
		verLDatos.addComponent(btnAccion);
		verLDatos.setComponentAlignment(btnAccion, new Alignment(34));
		
		return verLDatos;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLGralesFotoCaractsCoords() {
		// common part: create layout
		absLGralesFotoCaractsCoords = new AbsoluteLayout();
		absLGralesFotoCaractsCoords.setImmediate(false);
		absLGralesFotoCaractsCoords.setWidth("100.0%");
		absLGralesFotoCaractsCoords.setHeight("362px");
		
		// panGenerales
		panGenerales = buildPanGenerales();
		absLGralesFotoCaractsCoords.addComponent(panGenerales,
				"top:0.0px;left:0.0px;");
		
		// panCaracteristicas
		panCaracteristicas = buildPanCaracteristicas();
		absLGralesFotoCaractsCoords.addComponent(panCaracteristicas,
				"bottom:0.0px;left:0.0px;");
		
		// panCoordenadas
		panCoordenadas = buildPanCoordenadas();
		absLGralesFotoCaractsCoords.addComponent(panCoordenadas,
				"bottom:0.0px;left:310.0px;");
		
		// panFoto
		panFoto = new Foto();
		panFoto.setImmediate(false);
		panFoto.setWidth("-1px");
		panFoto.setHeight("-1px");
		absLGralesFotoCaractsCoords.addComponent(panFoto,
				"top:0.0px;right:0.0px;");
		
		return absLGralesFotoCaractsCoords;
	}

	@AutoGenerated
	private Panel buildPanGenerales() {
		// common part: create layout
		panGenerales = new Panel();
		panGenerales.setCaption("Datos Generales");
		panGenerales.setImmediate(false);
		panGenerales.setWidth("301px");
		panGenerales.setHeight("-1px");
		
		// absLGenerales
		absLGenerales = buildAbsLGenerales();
		panGenerales.setContent(absLGenerales);
		
		return panGenerales;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLGenerales() {
		// common part: create layout
		absLGenerales = new AbsoluteLayout();
		absLGenerales.setImmediate(false);
		absLGenerales.setWidth("100.0%");
		absLGenerales.setHeight("155px");
		
		// txtNoConcesion
		txtNoConcesion = new TextField();
		txtNoConcesion.setCaption("Núm. de Concesión CNA");
		txtNoConcesion.setImmediate(false);
		txtNoConcesion.setWidth("220px");
		txtNoConcesion.setHeight("25px");
		absLGenerales.addComponent(txtNoConcesion, "top:28.0px;left:10.0px;");
		
		// txtNoIdentificacion
		txtNoIdentificacion = new TextField();
		txtNoIdentificacion.setCaption("Núm. de Identificación");
		txtNoIdentificacion.setImmediate(false);
		txtNoIdentificacion.setWidth("280px");
		txtNoIdentificacion.setHeight("25px");
		absLGenerales.addComponent(txtNoIdentificacion,
				"top:73.0px;left:10.0px;");
		
		// txtAcuifero
		txtAcuifero = new TextField();
		txtAcuifero.setCaption("Acuífero");
		txtAcuifero.setImmediate(false);
		txtAcuifero.setWidth("280px");
		txtAcuifero.setHeight("25px");
		absLGenerales.addComponent(txtAcuifero, "top:118.0px;left:10.0px;");
		
		return absLGenerales;
	}

	@AutoGenerated
	private Panel buildPanCaracteristicas() {
		// common part: create layout
		panCaracteristicas = new Panel();
		panCaracteristicas.setCaption("Características");
		panCaracteristicas.setImmediate(false);
		panCaracteristicas.setWidth("304px");
		panCaracteristicas.setHeight("-1px");
		
		// absLCaracteristicas
		absLCaracteristicas = buildAbsLCaracteristicas();
		panCaracteristicas.setContent(absLCaracteristicas);
		
		return panCaracteristicas;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCaracteristicas() {
		// common part: create layout
		absLCaracteristicas = new AbsoluteLayout();
		absLCaracteristicas.setImmediate(false);
		absLCaracteristicas.setWidth("100.0%");
		absLCaracteristicas.setHeight("155px");
		
		// txtGastoCon
		txtGastoCon = new TextField();
		txtGastoCon.setCaption("Gasto Concesionado");
		txtGastoCon.setImmediate(false);
		txtGastoCon.setWidth("100px");
		txtGastoCon.setHeight("25px");
		absLCaracteristicas
				.addComponent(txtGastoCon, "top:28.0px;left:10.0px;");
		
		// lblGastoCon
		lblGastoCon = new Label();
		lblGastoCon.setImmediate(false);
		lblGastoCon.setWidth("-1px");
		lblGastoCon.setHeight("-1px");
		lblGastoCon.setValue("lps");
		absLCaracteristicas.addComponent(lblGastoCon,
				"top:32.0px;left:115.0px;");
		
		// txtVolCon
		txtVolCon = new TextField();
		txtVolCon.setCaption("Vol. Concesionado");
		txtVolCon.setImmediate(false);
		txtVolCon.setWidth("100px");
		txtVolCon.setHeight("25px");
		absLCaracteristicas.addComponent(txtVolCon, "top:28.0px;left:150.0px;");
		
		// lblVolCon
		lblVolCon = new Label();
		lblVolCon.setImmediate(false);
		lblVolCon.setWidth("-1px");
		lblVolCon.setHeight("-1px");
		lblVolCon.setValue("m³/año");
		absLCaracteristicas.addComponent(lblVolCon, "top:32.0px;left:255.0px;");
		
		// txtNivelEst
		txtNivelEst = new TextField();
		txtNivelEst.setCaption("Nivel Estático");
		txtNivelEst.setImmediate(false);
		txtNivelEst.setWidth("100px");
		txtNivelEst.setHeight("25px");
		absLCaracteristicas
				.addComponent(txtNivelEst, "top:73.0px;left:10.0px;");
		
		// lblNivelEst
		lblNivelEst = new Label();
		lblNivelEst.setImmediate(false);
		lblNivelEst.setWidth("-1px");
		lblNivelEst.setHeight("-1px");
		lblNivelEst.setValue("m");
		absLCaracteristicas.addComponent(lblNivelEst,
				"top:77.0px;left:115.0px;");
		
		// txtNivelDin
		txtNivelDin = new TextField();
		txtNivelDin.setCaption("Nivel Dinámico");
		txtNivelDin.setImmediate(false);
		txtNivelDin.setWidth("100px");
		txtNivelDin.setHeight("25px");
		absLCaracteristicas.addComponent(txtNivelDin,
				"top:73.0px;left:150.0px;");
		
		// lblNivelDin
		lblNivelDin = new Label();
		lblNivelDin.setImmediate(false);
		lblNivelDin.setWidth("-1px");
		lblNivelDin.setHeight("-1px");
		lblNivelDin.setValue("m");
		absLCaracteristicas.addComponent(lblNivelDin,
				"top:77.0px;left:255.0px;");
		
		// txtProfPerforacion
		txtProfPerforacion = new TextField();
		txtProfPerforacion.setCaption("Prof. de Perforación");
		txtProfPerforacion.setImmediate(false);
		txtProfPerforacion.setWidth("100px");
		txtProfPerforacion.setHeight("25px");
		absLCaracteristicas.addComponent(txtProfPerforacion,
				"top:118.0px;left:10.0px;");
		
		// lblProfPerforacion
		lblProfPerforacion = new Label();
		lblProfPerforacion.setImmediate(false);
		lblProfPerforacion.setWidth("-1px");
		lblProfPerforacion.setHeight("-1px");
		lblProfPerforacion.setValue("m");
		absLCaracteristicas.addComponent(lblProfPerforacion,
				"top:122.0px;left:115.0px;");
		
		return absLCaracteristicas;
	}

	@AutoGenerated
	private Panel buildPanCoordenadas() {
		// common part: create layout
		panCoordenadas = new Panel();
		panCoordenadas.setCaption("Coordenadas del Pozo");
		panCoordenadas.setImmediate(false);
		panCoordenadas.setWidth("221px");
		panCoordenadas.setHeight("-1px");
		
		// absLCoordenadas
		absLCoordenadas = buildAbsLCoordenadas();
		panCoordenadas.setContent(absLCoordenadas);
		
		return panCoordenadas;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCoordenadas() {
		// common part: create layout
		absLCoordenadas = new AbsoluteLayout();
		absLCoordenadas.setImmediate(false);
		absLCoordenadas.setWidth("100.0%");
		absLCoordenadas.setHeight("110px");
		
		// txtCoordX
		txtCoordX = new TextField();
		txtCoordX.setCaption("Coordenada X");
		txtCoordX.setImmediate(false);
		txtCoordX.setWidth("200px");
		txtCoordX.setHeight("25px");
		absLCoordenadas.addComponent(txtCoordX, "top:28.0px;left:10.0px;");
		
		// txtCoordY
		txtCoordY = new TextField();
		txtCoordY.setCaption("Coordenada Y");
		txtCoordY.setImmediate(false);
		txtCoordY.setWidth("200px");
		txtCoordY.setHeight("25px");
		absLCoordenadas.addComponent(txtCoordY, "top:73.0px;left:10.0px;");
		
		return absLCoordenadas;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCFEBombaFlujo() {
		// common part: create layout
		absLCFEBombaFlujo = new AbsoluteLayout();
		absLCFEBombaFlujo.setImmediate(false);
		absLCFEBombaFlujo.setWidth("100.0%");
		absLCFEBombaFlujo.setHeight("176px");
		
		// panBomba
		panBomba = buildPanBomba();
		absLCFEBombaFlujo.addComponent(panBomba, "top:0.0px;left:170.0px;");
		
		// panMedidorFlujo
		panMedidorFlujo = buildPanMedidorFlujo();
		absLCFEBombaFlujo.addComponent(panMedidorFlujo,
				"top:0.0px;right:0.0px;");
		
		// panMedidorCFE
		panMedidorCFE = buildPanMedidorCFE();
		absLCFEBombaFlujo.addComponent(panMedidorCFE, "top:0.0px;left:0.0px;");
		
		return absLCFEBombaFlujo;
	}

	@AutoGenerated
	private Panel buildPanBomba() {
		// common part: create layout
		panBomba = new Panel();
		panBomba.setCaption("Datos de la Bomba");
		panBomba.setImmediate(false);
		panBomba.setWidth("221px");
		panBomba.setHeight("-1px");
		
		// absLBomba
		absLBomba = buildAbsLBomba();
		panBomba.setContent(absLBomba);
		
		return panBomba;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLBomba() {
		// common part: create layout
		absLBomba = new AbsoluteLayout();
		absLBomba.setImmediate(false);
		absLBomba.setWidth("100.0%");
		absLBomba.setHeight("155px");
		
		// cmbTipoBomba
		cmbTipoBomba = new ComboBox();
		cmbTipoBomba.setCaption("Tipo de Bomba");
		cmbTipoBomba.setImmediate(false);
		cmbTipoBomba.setWidth("200px");
		cmbTipoBomba.setHeight("25px");
		absLBomba.addComponent(cmbTipoBomba, "top:28.0px;left:10.0px;");
		
		// txtPotencia
		txtPotencia = new TextField();
		txtPotencia.setCaption("Potencia del Motor");
		txtPotencia.setImmediate(false);
		txtPotencia.setWidth("140px");
		txtPotencia.setHeight("25px");
		absLBomba.addComponent(txtPotencia, "top:73.0px;left:10.0px;");
		
		// lblPotencia
		lblPotencia = new Label();
		lblPotencia.setImmediate(false);
		lblPotencia.setWidth("-1px");
		lblPotencia.setHeight("-1px");
		lblPotencia.setValue("Hp");
		absLBomba.addComponent(lblPotencia, "top:77.0px;left:155.0px;");
		
		// txtDiametro
		txtDiametro = new TextField();
		txtDiametro.setCaption("Diámetro de Descarga");
		txtDiametro.setImmediate(false);
		txtDiametro.setWidth("140px");
		txtDiametro.setHeight("25px");
		absLBomba.addComponent(txtDiametro, "top:118.0px;left:10.0px;");
		
		// lblDiametro
		lblDiametro = new Label();
		lblDiametro.setImmediate(false);
		lblDiametro.setWidth("-1px");
		lblDiametro.setHeight("-1px");
		lblDiametro.setValue("pulg");
		absLBomba.addComponent(lblDiametro, "top:122.0px;left:155.0px;");
		
		return absLBomba;
	}

	@AutoGenerated
	private Panel buildPanMedidorFlujo() {
		// common part: create layout
		panMedidorFlujo = new Panel();
		panMedidorFlujo.setCaption("Datos del Medidor de Flujo");
		panMedidorFlujo.setImmediate(false);
		panMedidorFlujo.setWidth("221px");
		panMedidorFlujo.setHeight("-1px");
		
		// absLMedidorFlujo
		absLMedidorFlujo = buildAbsLMedidorFlujo();
		panMedidorFlujo.setContent(absLMedidorFlujo);
		
		return panMedidorFlujo;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLMedidorFlujo() {
		// common part: create layout
		absLMedidorFlujo = new AbsoluteLayout();
		absLMedidorFlujo.setImmediate(false);
		absLMedidorFlujo.setWidth("100.0%");
		absLMedidorFlujo.setHeight("155px");
		
		// txtMarca
		txtMarca = new TextField();
		txtMarca.setCaption("Marca");
		txtMarca.setImmediate(false);
		txtMarca.setWidth("200px");
		txtMarca.setHeight("25px");
		absLMedidorFlujo.addComponent(txtMarca, "top:28.0px;left:10.0px;");
		
		// txtGasto
		txtGasto = new TextField();
		txtGasto.setCaption("Gasto");
		txtGasto.setImmediate(false);
		txtGasto.setWidth("140px");
		txtGasto.setHeight("25px");
		absLMedidorFlujo.addComponent(txtGasto, "top:73.0px;left:10.0px;");
		
		// lblGasto
		lblGasto = new Label();
		lblGasto.setImmediate(false);
		lblGasto.setWidth("-1px");
		lblGasto.setHeight("-1px");
		lblGasto.setValue("lps");
		absLMedidorFlujo.addComponent(lblGasto, "top:77.0px;left:155.0px;");
		
		// txtNoSerie
		txtNoSerie = new TextField();
		txtNoSerie.setCaption("Núm. de Serie");
		txtNoSerie.setImmediate(false);
		txtNoSerie.setWidth("200px");
		txtNoSerie.setHeight("25px");
		absLMedidorFlujo.addComponent(txtNoSerie, "top:118.0px;left:10.0px;");
		
		return absLMedidorFlujo;
	}

	@AutoGenerated
	private Panel buildPanMedidorCFE() {
		// common part: create layout
		panMedidorCFE = new Panel();
		panMedidorCFE.setCaption("Datos del Medidor de CFE");
		panMedidorCFE.setImmediate(false);
		panMedidorCFE.setWidth("161px");
		panMedidorCFE.setHeight("-1px");
		
		// absLMedidorCFE
		absLMedidorCFE = buildAbsLMedidorCFE();
		panMedidorCFE.setContent(absLMedidorCFE);
		
		return panMedidorCFE;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLMedidorCFE() {
		// common part: create layout
		absLMedidorCFE = new AbsoluteLayout();
		absLMedidorCFE.setImmediate(false);
		absLMedidorCFE.setWidth("100.0%");
		absLMedidorCFE.setHeight("155px");
		
		// txtNoMedidor
		txtNoMedidor = new TextField();
		txtNoMedidor.setCaption("Núm. de Medidor");
		txtNoMedidor.setImmediate(false);
		txtNoMedidor.setWidth("140px");
		txtNoMedidor.setHeight("25px");
		absLMedidorCFE.addComponent(txtNoMedidor, "top:28.0px;left:10.0px;");
		
		// txtTarifa
		txtTarifa = new TextField();
		txtTarifa.setCaption("Tarifa");
		txtTarifa.setImmediate(false);
		txtTarifa.setWidth("140px");
		txtTarifa.setHeight("25px");
		absLMedidorCFE.addComponent(txtTarifa, "top:73.0px;left:10.0px;");
		
		// txtMultiplicador
		txtMultiplicador = new TextField();
		txtMultiplicador.setCaption("Multiplicador");
		txtMultiplicador.setImmediate(false);
		txtMultiplicador.setWidth("140px");
		txtMultiplicador.setHeight("25px");
		absLMedidorCFE.addComponent(txtMultiplicador,
				"top:118.0px;left:10.0px;");
		
		return absLMedidorCFE;
	}

	@AutoGenerated
	private Panel buildPanObservaciones() {
		// common part: create layout
		panObservaciones = new Panel();
		panObservaciones.setCaption("Observaciones");
		panObservaciones.setImmediate(false);
		panObservaciones.setWidth("621px");
		panObservaciones.setHeight("-1px");
		
		// absLObservaciones
		absLObservaciones = buildAbsLObservaciones();
		panObservaciones.setContent(absLObservaciones);
		
		return panObservaciones;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLObservaciones() {
		// common part: create layout
		absLObservaciones = new AbsoluteLayout();
		absLObservaciones.setImmediate(false);
		absLObservaciones.setWidth("100.0%");
		absLObservaciones.setHeight("120px");
		
		// txtObservaciones
		txtObservaciones = new TextArea();
		txtObservaciones.setImmediate(false);
		txtObservaciones.setWidth("600px");
		txtObservaciones.setHeight("100px");
		absLObservaciones.addComponent(txtObservaciones,
				"top:10.0px;left:10.0px;");
		
		return absLObservaciones;
	}
}