package com.saprigrat.ui.forms.reportes;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.sql.ResultSet;
import java.util.LinkedList;

import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperPrint;

import com.saprigrat.entities.Usuario;
import com.saprigrat.ui.interfaces.Formulario;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.server.StreamResource;
import com.vaadin.server.StreamResource.StreamSource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

@SuppressWarnings("serial")
public class Reportes2 extends CustomComponent implements Formulario
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	//region controles autogenerados
	
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button btnGenerar;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private AbsoluteLayout absLUsuario;
	@AutoGenerated
	private ComboBox cmbUsuario;
	@AutoGenerated
	private CheckBox chkUsuario;
	@AutoGenerated
	private AbsoluteLayout absLRT;
	@AutoGenerated
	private ComboBox cmbRT;
	@AutoGenerated
	private CheckBox chkRT;
	@AutoGenerated
	private AbsoluteLayout absLST;
	@AutoGenerated
	private ComboBox cmbST;
	@AutoGenerated
	private CheckBox chkST;
	@AutoGenerated
	private AbsoluteLayout absLModulo;
	@AutoGenerated
	private ComboBox cmbModulo;
	@AutoGenerated
	private CheckBox chkModulo;
	@AutoGenerated
	private AbsoluteLayout absLDistrito;
	@AutoGenerated
	private ComboBox cmbDistrito;
	@AutoGenerated
	private CheckBox chkDistrito;
	@AutoGenerated
	private AbsoluteLayout absLEstado;
	@AutoGenerated
	private ComboBox cmbEstado;
	@AutoGenerated
	private CheckBox chkEstado;
	@AutoGenerated
	private AbsoluteLayout absLSRL;
	@AutoGenerated
	private ComboBox cmbSRL;
	@AutoGenerated
	private CheckBox chkSRL;
	@AutoGenerated
	private AbsoluteLayout absLOrganismo;
	@AutoGenerated
	private ComboBox cmbOrganismo;
	@AutoGenerated
	private CheckBox chkOrganismo;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	private ComboBox cmbTipoReporte;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button btnRT;
	@AutoGenerated
	private Button btnST;
	@AutoGenerated
	private Button btnAdminDto;
	@AutoGenerated
	private Button btnAdminGral;
	//endregion
	private Usuario usuario;
	
	//region eventos
	private ClickListener isAdminGralListener = new ClickListener()
	{
		@Override
		public void buttonClick(ClickEvent event)
		{
			absLOrganismo.setVisible(true);
			absLSRL.setVisible(true);
			absLEstado.setVisible(true);
			absLDistrito.setVisible(true);
			absLModulo.setVisible(true);
			absLST.setVisible(true);
			absLRT.setVisible(true);
			absLUsuario.setVisible(true);
			verticalLayout_2.setHeight("360px");
		}
	};
	private ClickListener isAdminDtoListener = new ClickListener()
	{
		@Override
		public void buttonClick(ClickEvent event)
		{
			absLOrganismo.setVisible(false);
			absLSRL.setVisible(false);
			absLEstado.setVisible(true);
			absLDistrito.setVisible(false);
			absLModulo.setVisible(true);
			absLST.setVisible(true);
			absLRT.setVisible(true);
			absLUsuario.setVisible(true);
			verticalLayout_2.setHeight("225px");
		}
	};
	private ClickListener isStListener = new ClickListener()
	{
		@Override
		public void buttonClick(ClickEvent event)
		{
			absLOrganismo.setVisible(false);
			absLSRL.setVisible(false);
			absLEstado.setVisible(false);
			absLDistrito.setVisible(true);
			absLModulo.setVisible(true);
			absLST.setVisible(false);
			absLRT.setVisible(true);
			absLUsuario.setVisible(true);
			verticalLayout_2.setHeight("180px");
		}
	};
	private ClickListener isRtListener = new ClickListener()
	{
		@Override
		public void buttonClick(ClickEvent event)
		{
			absLOrganismo.setVisible(false);
			absLSRL.setVisible(false);
			absLEstado.setVisible(false);
			absLDistrito.setVisible(false);
			absLModulo.setVisible(true);
			absLST.setVisible(false);
			absLRT.setVisible(false);
			absLUsuario.setVisible(true);
			verticalLayout_2.setHeight("90px");
		}
	};
	private ValueChangeListener organismoListener = new ValueChangeListener()
	{
		@Override
		public void valueChange(ValueChangeEvent event)
		{
			cmbOrganismo.setVisible(chkOrganismo.getValue());
		}
	};
	private ValueChangeListener srlListener = new ValueChangeListener()
	{
		@Override
		public void valueChange(ValueChangeEvent event)
		{
			cmbSRL.setVisible(chkSRL.getValue());
		}
	};
	private ValueChangeListener estadoListener = new ValueChangeListener()
	{
		@Override
		public void valueChange(ValueChangeEvent event)
		{
			cmbEstado.setVisible(chkEstado.getValue());
		}
	};
	private ValueChangeListener distritoListener = new ValueChangeListener()
	{
		@Override
		public void valueChange(ValueChangeEvent event)
		{
			cmbDistrito.setVisible(chkDistrito.getValue());
		}
	};
	private ValueChangeListener moduloListener = new ValueChangeListener()
	{
		@Override
		public void valueChange(ValueChangeEvent event)
		{
			cmbModulo.setVisible(chkModulo.getValue());
		}
	};
	private ValueChangeListener stListener = new ValueChangeListener()
	{
		@Override
		public void valueChange(ValueChangeEvent event)
		{
			cmbST.setVisible(chkST.getValue());
		}
	};
	private ValueChangeListener rtListener = new ValueChangeListener()
	{
		@Override
		public void valueChange(ValueChangeEvent event)
		{
			cmbRT.setVisible(chkRT.getValue());
		}
	};
	private ValueChangeListener usuarioListener = new ValueChangeListener()
	{
		@Override
		public void valueChange(ValueChangeEvent event)
		{
			cmbUsuario.setVisible(chkUsuario.getValue());
		}
	};
	//endregion

	public Reportes2(Usuario user)
	{
		usuario = user;
	}

	@Override
	public void inicializar()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		LinkedList<String> tipos = new LinkedList<String>();
		tipos.add("Hidrométricas");
		tipos.add("Producción agrícola");
		tipos.add("Hidrométricas basadas en producción agrícola");
		tipos.add("Datos generales");
		u.llenarCombo(cmbTipoReporte, tipos);
		
		btnAdminGral.addClickListener(isAdminGralListener);
		btnAdminDto.addClickListener(isAdminDtoListener);
		btnST.addClickListener(isStListener);
		btnRT.addClickListener(isRtListener);
		
		chkOrganismo.addValueChangeListener(organismoListener);
		chkSRL.addValueChangeListener(srlListener);
		chkEstado.addValueChangeListener(estadoListener);
		chkDistrito.addValueChangeListener(distritoListener);
		chkModulo.addValueChangeListener(moduloListener);
		chkST.addValueChangeListener(stListener);
		chkRT.addValueChangeListener(rtListener);
		chkUsuario.addValueChangeListener(usuarioListener);
	}
	
	@Override
	public void setTipo(int modoOperacion)
	{
		
	}
	
	private boolean validar()
	{
		return true;
	}
	
	public void runReport(int columnCount, LinkedList<String[]> columns, String titulo, String subtitulo, ResultSet resultset) 
	{
		try
		{
			JRResultSetDataSource dataSource = new JRResultSetDataSource(resultset);
			final JasperPrint jasperPrint = new ReporteDinamico().getReport(columns, titulo, subtitulo, dataSource);
			if(jasperPrint != null)
			{
				StreamSource source = new StreamSource()
				{
					public InputStream getStream()
					{
						try { return new ByteArrayInputStream(JasperExportManager.exportReportToPdf(jasperPrint)); }
						catch(Exception e) { return null; }
					}
				};
				StreamResource resource = new StreamResource(source, "reporte.pdf");
				Embedded e = new Embedded("", resource);
				e.setType(Embedded.TYPE_BROWSER);
				e.setMimeType("application/pdf");
				e.setSizeFull();
				
				UI.getCurrent().addWindow(getWindow(e));
			}
			//JasperExportManager.exportReportToPdfFile(jasperPrint, System.getProperty("user.home") + "\\RptLaminas.pdf");
		}
		catch (Exception e)
		{
			u.msjReporteNoGenerado();
		}
	}
	
	private Window getWindow(Embedded e)
	{
		Window w = new Window("Reporte SAPRIGRAT");
		w.setWidth("90%");
		w.setHeight("90%");
		w.setModal(true);
		w.center();
		w.setContent(e);
		return w;
	}
	//region UI

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		mainLayout.addComponent(absoluteLayout_2);
		
		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1);
		
		// btnGenerar
		btnGenerar = new Button();
		btnGenerar.setCaption("Generar Reporte");
		btnGenerar.setImmediate(true);
		btnGenerar.setWidth("-1px");
		btnGenerar.setHeight("-1px");
		mainLayout.addComponent(btnGenerar);
		mainLayout.setComponentAlignment(btnGenerar, new Alignment(24));
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("701px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// btnAdminGral
		btnAdminGral = new Button();
		btnAdminGral.setCaption("Admin. General");
		btnAdminGral.setImmediate(true);
		btnAdminGral.setWidth("-1px");
		btnAdminGral.setHeight("-1px");
		horizontalLayout_1.addComponent(btnAdminGral);
		horizontalLayout_1.setComponentAlignment(btnAdminGral,
				new Alignment(48));
		
		// btnAdminDto
		btnAdminDto = new Button();
		btnAdminDto.setCaption("Admin. Distrito");
		btnAdminDto.setImmediate(true);
		btnAdminDto.setWidth("-1px");
		btnAdminDto.setHeight("-1px");
		horizontalLayout_1.addComponent(btnAdminDto);
		horizontalLayout_1
				.setComponentAlignment(btnAdminDto, new Alignment(48));
		
		// btnST
		btnST = new Button();
		btnST.setCaption("ST");
		btnST.setImmediate(true);
		btnST.setWidth("-1px");
		btnST.setHeight("-1px");
		horizontalLayout_1.addComponent(btnST);
		horizontalLayout_1.setComponentAlignment(btnST, new Alignment(48));
		
		// btnRT
		btnRT = new Button();
		btnRT.setCaption("RT");
		btnRT.setImmediate(true);
		btnRT.setWidth("-1px");
		btnRT.setHeight("-1px");
		horizontalLayout_1.addComponent(btnRT);
		horizontalLayout_1.setComponentAlignment(btnRT, new Alignment(48));
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("701px");
		absoluteLayout_2.setHeight("55px");
		
		// cmbTipoReporte
		cmbTipoReporte = new ComboBox();
		cmbTipoReporte.setCaption("Tipo de Reporte");
		cmbTipoReporte.setImmediate(false);
		cmbTipoReporte.setWidth("700px");
		cmbTipoReporte.setHeight("25px");
		absoluteLayout_2.addComponent(cmbTipoReporte, "top:28.0px;left:0.0px;");
		
		return absoluteLayout_2;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setCaption("Filtros");
		panel_1.setImmediate(false);
		panel_1.setWidth("701px");
		panel_1.setHeight("100.0%");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panel_1.setContent(verticalLayout_2);
		
		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("360px");
		verticalLayout_2.setMargin(false);
		
		// absLOrganismo
		absLOrganismo = buildAbsLOrganismo();
		verticalLayout_2.addComponent(absLOrganismo);
		
		// absLSRL
		absLSRL = buildAbsLSRL();
		verticalLayout_2.addComponent(absLSRL);
		
		// absLEstado
		absLEstado = buildAbsLEstado();
		verticalLayout_2.addComponent(absLEstado);
		
		// absLDistrito
		absLDistrito = buildAbsLDistrito();
		verticalLayout_2.addComponent(absLDistrito);
		
		// absLModulo
		absLModulo = buildAbsLModulo();
		verticalLayout_2.addComponent(absLModulo);
		
		// absLST
		absLST = buildAbsLST();
		verticalLayout_2.addComponent(absLST);
		
		// absLRT
		absLRT = buildAbsLRT();
		verticalLayout_2.addComponent(absLRT);
		
		// absLUsuario
		absLUsuario = buildAbsLUsuario();
		verticalLayout_2.addComponent(absLUsuario);
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLOrganismo() {
		// common part: create layout
		absLOrganismo = new AbsoluteLayout();
		absLOrganismo.setImmediate(false);
		absLOrganismo.setWidth("100%");
		absLOrganismo.setHeight("45px");
		
		// chkOrganismo
		chkOrganismo = new CheckBox();
		chkOrganismo.setCaption("Organismo de Cuenca");
		chkOrganismo.setImmediate(false);
		chkOrganismo.setWidth("-1px");
		chkOrganismo.setHeight("-1px");
		absLOrganismo.addComponent(chkOrganismo, "top:18.0px;left:9.0px;");
		
		// cmbOrganismo
		cmbOrganismo = new ComboBox();
		cmbOrganismo.setCaption("Nombre (opcional)");
		cmbOrganismo.setImmediate(false);
		cmbOrganismo.setVisible(false);
		cmbOrganismo.setWidth("510px");
		cmbOrganismo.setHeight("25px");
		absLOrganismo.addComponent(cmbOrganismo, "top:18.0px;left:180.0px;");
		
		return absLOrganismo;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLSRL() {
		// common part: create layout
		absLSRL = new AbsoluteLayout();
		absLSRL.setImmediate(false);
		absLSRL.setWidth("100%");
		absLSRL.setHeight("45px");
		
		// chkSRL
		chkSRL = new CheckBox();
		chkSRL.setCaption("SRL");
		chkSRL.setImmediate(false);
		chkSRL.setWidth("-1px");
		chkSRL.setHeight("-1px");
		absLSRL.addComponent(chkSRL, "top:18.0px;left:9.0px;");
		
		// cmbSRL
		cmbSRL = new ComboBox();
		cmbSRL.setCaption("Nombre (opcional)");
		cmbSRL.setImmediate(false);
		cmbSRL.setVisible(false);
		cmbSRL.setWidth("510px");
		cmbSRL.setHeight("25px");
		absLSRL.addComponent(cmbSRL, "top:18.0px;left:180.0px;");
		
		return absLSRL;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLEstado() {
		// common part: create layout
		absLEstado = new AbsoluteLayout();
		absLEstado.setImmediate(false);
		absLEstado.setWidth("100%");
		absLEstado.setHeight("45px");
		
		// chkEstado
		chkEstado = new CheckBox();
		chkEstado.setCaption("Estado");
		chkEstado.setImmediate(false);
		chkEstado.setWidth("-1px");
		chkEstado.setHeight("-1px");
		absLEstado.addComponent(chkEstado, "top:18.0px;left:9.0px;");
		
		// cmbEstado
		cmbEstado = new ComboBox();
		cmbEstado.setCaption("Nombre (opcional)");
		cmbEstado.setImmediate(false);
		cmbEstado.setVisible(false);
		cmbEstado.setWidth("510px");
		cmbEstado.setHeight("25px");
		absLEstado.addComponent(cmbEstado, "top:18.0px;left:180.0px;");
		
		return absLEstado;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDistrito() {
		// common part: create layout
		absLDistrito = new AbsoluteLayout();
		absLDistrito.setImmediate(false);
		absLDistrito.setWidth("100%");
		absLDistrito.setHeight("45px");
		
		// chkDistrito
		chkDistrito = new CheckBox();
		chkDistrito.setCaption("Distrito de Riego");
		chkDistrito.setImmediate(false);
		chkDistrito.setWidth("-1px");
		chkDistrito.setHeight("-1px");
		absLDistrito.addComponent(chkDistrito, "top:18.0px;left:9.0px;");
		
		// cmbDistrito
		cmbDistrito = new ComboBox();
		cmbDistrito.setCaption("Nombre (opcional)");
		cmbDistrito.setImmediate(false);
		cmbDistrito.setVisible(false);
		cmbDistrito.setWidth("510px");
		cmbDistrito.setHeight("25px");
		absLDistrito.addComponent(cmbDistrito, "top:18.0px;left:180.0px;");
		
		return absLDistrito;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLModulo() {
		// common part: create layout
		absLModulo = new AbsoluteLayout();
		absLModulo.setImmediate(false);
		absLModulo.setWidth("100%");
		absLModulo.setHeight("45px");
		
		// chkModulo
		chkModulo = new CheckBox();
		chkModulo.setCaption("Módulo de Riego");
		chkModulo.setImmediate(false);
		chkModulo.setWidth("-1px");
		chkModulo.setHeight("-1px");
		absLModulo.addComponent(chkModulo, "top:18.0px;left:9.0px;");
		
		// cmbModulo
		cmbModulo = new ComboBox();
		cmbModulo.setCaption("Nombre (opcional)");
		cmbModulo.setImmediate(false);
		cmbModulo.setVisible(false);
		cmbModulo.setWidth("510px");
		cmbModulo.setHeight("25px");
		absLModulo.addComponent(cmbModulo, "top:18.0px;left:180.0px;");
		
		return absLModulo;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLST() {
		// common part: create layout
		absLST = new AbsoluteLayout();
		absLST.setImmediate(false);
		absLST.setWidth("100%");
		absLST.setHeight("45px");
		
		// chkST
		chkST = new CheckBox();
		chkST.setCaption("Supervisor Técnico");
		chkST.setImmediate(false);
		chkST.setWidth("-1px");
		chkST.setHeight("-1px");
		absLST.addComponent(chkST, "top:18.0px;left:9.0px;");
		
		// cmbST
		cmbST = new ComboBox();
		cmbST.setCaption("Nombre (opcional)");
		cmbST.setImmediate(false);
		cmbST.setVisible(false);
		cmbST.setWidth("510px");
		cmbST.setHeight("25px");
		absLST.addComponent(cmbST, "top:18.0px;left:180.0px;");
		
		return absLST;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLRT() {
		// common part: create layout
		absLRT = new AbsoluteLayout();
		absLRT.setImmediate(false);
		absLRT.setWidth("100%");
		absLRT.setHeight("45px");
		
		// chkRT
		chkRT = new CheckBox();
		chkRT.setCaption("Responsable Técnico");
		chkRT.setImmediate(false);
		chkRT.setWidth("-1px");
		chkRT.setHeight("-1px");
		absLRT.addComponent(chkRT, "top:18.0px;left:9.0px;");
		
		// cmbRT
		cmbRT = new ComboBox();
		cmbRT.setCaption("Nombre (opcional)");
		cmbRT.setImmediate(false);
		cmbRT.setVisible(false);
		cmbRT.setWidth("510px");
		cmbRT.setHeight("25px");
		absLRT.addComponent(cmbRT, "top:18.0px;left:180.0px;");
		
		return absLRT;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLUsuario() {
		// common part: create layout
		absLUsuario = new AbsoluteLayout();
		absLUsuario.setImmediate(false);
		absLUsuario.setWidth("100%");
		absLUsuario.setHeight("55px");
		
		// chkUsuario
		chkUsuario = new CheckBox();
		chkUsuario.setCaption("Usuario");
		chkUsuario.setImmediate(false);
		chkUsuario.setWidth("-1px");
		chkUsuario.setHeight("-1px");
		absLUsuario.addComponent(chkUsuario, "top:18.0px;left:9.0px;");
		
		// cmbUsuario
		cmbUsuario = new ComboBox();
		cmbUsuario.setCaption("Nombre (opcional)");
		cmbUsuario.setImmediate(false);
		cmbUsuario.setVisible(false);
		cmbUsuario.setWidth("510px");
		cmbUsuario.setHeight("25px");
		absLUsuario.addComponent(cmbUsuario, "top:18.0px;left:180.0px;");
		
		return absLUsuario;
	}
	
	//endregion
}