package com.saprigrat.ui.forms.reportes;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.Map;

import com.saprigrat.data.AdvancedFileDownloader;
import com.saprigrat.data.AdvancedFileDownloader.AdvancedDownloaderListener;
import com.saprigrat.data.AdvancedFileDownloader.DownloaderEvent;
import com.saprigrat.data.InterfazReportes;
import com.saprigrat.entities.Usuario;
import com.saprigrat.enums.Formato;
import com.saprigrat.enums.TipoResultado;
import com.saprigrat.ui.interfaces.Formulario;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.event.MouseEvents;
import com.vaadin.server.ThemeResource;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class Resultados extends CustomComponent implements Formulario
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	//region controles autogenerados
	
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Label lblRptPath;
	@AutoGenerated
	private VerticalLayout verLInfoBtns;
	@AutoGenerated
	private HorizontalLayout horLBotonesExportacion;
	@AutoGenerated
	private Button btnVerOtro;
	@AutoGenerated
	private HorizontalLayout horLExportacion;
	@AutoGenerated
	private Embedded btnPDF;
	@AutoGenerated
	private Embedded btnWord;
	@AutoGenerated
	private Embedded btnExcel;
	@AutoGenerated
	private OptionGroup optDescarga;
	@AutoGenerated
	private Panel panInfoIndicadores;
	@AutoGenerated
	private VerticalLayout verLInfoIndicadores;
	@AutoGenerated
	private AbsoluteLayout absLSAT;
	@AutoGenerated
	private TextField txtSAT;
	@AutoGenerated
	private Label label_22;
	@AutoGenerated
	private AbsoluteLayout absLABP;
	@AutoGenerated
	private TextField txtABP;
	@AutoGenerated
	private Label label_24;
	@AutoGenerated
	private AbsoluteLayout absLSBP;
	@AutoGenerated
	private TextField txtSBP;
	@AutoGenerated
	private Label label_23;
	@AutoGenerated
	private Label label_28;
	@AutoGenerated
	private AbsoluteLayout absLIRP;
	@AutoGenerated
	private Table tblIRP;
	@AutoGenerated
	private Label label_29;
	@AutoGenerated
	private AbsoluteLayout absLAAP;
	@AutoGenerated
	private TextField txtAAP;
	@AutoGenerated
	private Label label_21;
	@AutoGenerated
	private AbsoluteLayout absLIEA;
	@AutoGenerated
	private TextField txtIEA;
	@AutoGenerated
	private Label label_20;
	@AutoGenerated
	private Label label_10;
	@AutoGenerated
	private Panel panInfo;
	@AutoGenerated
	private VerticalLayout verLInfo;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_3;
	@AutoGenerated
	private AbsoluteLayout absLNumMedioRiegos;
	@AutoGenerated
	private Label label_19;
	@AutoGenerated
	private TextField txtNumMedioRiegos;
	@AutoGenerated
	private AbsoluteLayout absLProdTotal;
	@AutoGenerated
	private Label label_18;
	@AutoGenerated
	private TextField txtProdTotal;
	@AutoGenerated
	private Label label_15;
	@AutoGenerated
	private AbsoluteLayout absLRendMedio;
	@AutoGenerated
	private Label label_14;
	@AutoGenerated
	private TextField txtRendMedio;
	@AutoGenerated
	private Label label_13;
	@AutoGenerated
	private AbsoluteLayout absLLamMedia;
	@AutoGenerated
	private Label label_12;
	@AutoGenerated
	private TextField txtLamMedia;
	@AutoGenerated
	private Label label_11;
	@AutoGenerated
	private AbsoluteLayout absLVolMedio;
	@AutoGenerated
	private Label label_37;
	@AutoGenerated
	private TextField txtVolMedio;
	@AutoGenerated
	private Label label_36;
	@AutoGenerated
	private AbsoluteLayout absLVolAplicado;
	@AutoGenerated
	private Label label_9;
	@AutoGenerated
	private TextField txtVolAplicado;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private AbsoluteLayout absLHecRiego;
	@AutoGenerated
	private Label label_8;
	@AutoGenerated
	private TextField txtHecRiego;
	@AutoGenerated
	private Label label_7;
	@AutoGenerated
	private AbsoluteLayout absLSupSembrada;
	@AutoGenerated
	private Label label_17;
	@AutoGenerated
	private TextField txtSupSembrada;
	@AutoGenerated
	private Label label_16;
	@AutoGenerated
	private AbsoluteLayout absLSupAtendida;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private TextField txtSupAtendida;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private AbsoluteLayout absLNumRT;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private TextField txtNumRT;
	@AutoGenerated
	private AbsoluteLayout absLNumST;
	@AutoGenerated
	private Label label_5;
	@AutoGenerated
	private TextField txtNumST;
	@AutoGenerated
	private AbsoluteLayout absLNumDR;
	@AutoGenerated
	private Label label_6;
	@AutoGenerated
	private TextField txtNumDR;
	@AutoGenerated
	private Panel panFiltros;
	@AutoGenerated
	private VerticalLayout verLFiltros;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_1;
	@AutoGenerated
	private VerticalLayout verLCultivo;
	@AutoGenerated
	private HorizontalLayout horLBotonesCultivo;
	@AutoGenerated
	private Button btnHidr;
	@AutoGenerated
	private Button btnProd;
	@AutoGenerated
	private AbsoluteLayout absLCultivo;
	@AutoGenerated
	private ComboBox cmbCultivo;
	@AutoGenerated
	private HorizontalLayout horLBotones2;
	@AutoGenerated
	private Button btnRT;
	@AutoGenerated
	private Button btnST;
	@AutoGenerated
	private Button btnMR;
	@AutoGenerated
	private Button btnCultivo;
	@AutoGenerated
	private Button btnDR;
	@AutoGenerated
	private HorizontalLayout horLBotones;
	@AutoGenerated
	private Button btnIndicadores;
	@AutoGenerated
	private Button btnGral;
	@AutoGenerated
	private AbsoluteLayout absLRT;
	@AutoGenerated
	private ComboBox cmbRT;
	@AutoGenerated
	private AbsoluteLayout absLST;
	@AutoGenerated
	private ComboBox cmbST;
	@AutoGenerated
	private AbsoluteLayout absLMR;
	@AutoGenerated
	private ComboBox cmbMR;
	@AutoGenerated
	private AbsoluteLayout absLDR;
	@AutoGenerated
	private ComboBox cmbDR;
	@AutoGenerated
	private AbsoluteLayout absLOC;
	@AutoGenerated
	private ComboBox cmbOC;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	//endregion
	private Usuario usuario;
	private TipoResultado tipoResultadoAbs, tipoResultadoRel, tipoReporte;
	private final int CURR_TECNICO = 0, NOMBRE_TECNICO = 1; 
	Map<String, Object> parametros;
	
	//region eventos
	private ClickListener generalListener = new ClickListener()
	{
		@Override
		public void buttonClick(ClickEvent event)
		{
			if (validar())
			{
				setupInfoGeneral();
				
				LinkedList<Object> valores = datos.getResultadoGeneral(getOC(), getDR(), getMR(), getCURRST(), getCURRRT());
				if(!valores.isEmpty())
				{
					txtNumDR.setValue(u.longToString(valores.remove()));
					txtNumST.setValue(u.longToString(valores.remove()));
					txtNumRT.setValue(u.longToString(valores.remove()));
					txtSupAtendida.setValue(u.doubleToString(valores.remove()));
					txtHecRiego.setValue(u.doubleToString(valores.remove()));
					txtVolAplicado.setValue(u.doubleToString(valores.remove()));
					
					tipoReporte = TipoResultado.GENERAL;
					parametros = new HashMap<String, Object>();
					parametros.put("showNumDR", absLNumDR.isVisible());
					parametros.put("numDR", txtNumDR.getValue());
					parametros.put("showNumST", absLNumST.isVisible());
					parametros.put("numST", txtNumST.getValue());
					parametros.put("showNumRT", absLNumRT.isVisible());
					parametros.put("numRT", txtNumRT.getValue());
					parametros.put("supAtendida", txtSupAtendida.getValue());
					parametros.put("haRiego", txtHecRiego.getValue());
					parametros.put("volTotal", txtVolAplicado.getValue());
				}
				else
					u.msjRegistroNoObtenido();
			}
			else
				u.msjNoSeleccionFiltros();
		}
	};
	private ClickListener produccionListener = new ClickListener()
	{
		@Override
		public void buttonClick(ClickEvent event)
		{
			if (validar())
			{
				setupInfoProduccion();
				
				LinkedList<Object> valores = datos.getResultadoProduccion(getOC(), getDR(), getMR(), getCURRST(), getCURRRT(), getCultivo());
				if(!valores.isEmpty())
				{
					double  supSembrada = u.getDouble(valores.remove()),
							supTotal = u.getDouble(valores.remove()),
							rendMedio = u.getDouble(valores.remove()),
							rendTotal = u.getDouble(valores.remove());
					
					if(supSembrada == 0)
						supSembrada = supTotal;
					
					txtSupSembrada.setValue(u.doubleToString(supSembrada));
					txtRendMedio.setValue(u.doubleToString(rendMedio));
					txtProdTotal.setValue(u.doubleToString(supSembrada * rendTotal));
					
					tipoReporte = TipoResultado.PRODUCCION;
					parametros = new HashMap<String, Object>();
					parametros.put("supSembrada", txtSupSembrada.getValue());
					parametros.put("rendMedio", txtRendMedio.getValue());
					parametros.put("prodTotal", txtProdTotal.getValue());
				}
				else
					u.msjRegistroNoObtenido();
			}
			else
				u.msjNoSeleccionFiltros();
		}
	};
	private ClickListener hidrometricoListener = new ClickListener()
	{
		@Override
		public void buttonClick(ClickEvent event)
		{
			if (validar())
			{
				setupInfoHidrometrico();
				
				LinkedList<Object> valores = datos.getResultadoHidrometrico(getOC(), getDR(), getMR(), getCURRST(), getCURRRT(), getCultivo());
				if(!valores.isEmpty())
				{
					txtSupSembrada.setValue(u.doubleToString(valores.remove()));
					txtHecRiego.setValue(u.doubleToString(valores.remove()));
					txtVolAplicado.setValue(u.doubleToString(valores.remove()));
					txtVolMedio.setValue(u.doubleToString(valores.remove()));
					txtLamMedia.setValue(u.doubleToString(valores.remove()));
					
					String numRiegos = u.doubleToString(valores.remove());
					int indexDec = numRiegos.indexOf(".");
					if(indexDec != -1)
						numRiegos = numRiegos.substring(0, indexDec);
					
					txtNumMedioRiegos.setValue(numRiegos);
					
					tipoReporte = TipoResultado.HIDROMETRICO;
					parametros = new HashMap<String, Object>();
					parametros.put("supSembrada", txtSupSembrada.getValue());
					parametros.put("haRiego", txtHecRiego.getValue());
					parametros.put("volTotal", txtVolAplicado.getValue());
					parametros.put("volMedio", txtVolMedio.getValue());
					parametros.put("lamMedia", txtLamMedia.getValue());
					parametros.put("promRiegos", txtNumMedioRiegos.getValue());
				}
				else
					u.msjRegistroNoObtenido();
			}
			else
				u.msjNoSeleccionFiltros();
		}
	};
	private ClickListener indicadoresListener = new ClickListener()
	{
		@Override
		public void buttonClick(ClickEvent event)
		{
			if (validar())
			{
				setupInfoIndicadores();
				
				LinkedList<Object> valores = datos.getResultadoIndicadores(getOC(), getDR(), getMR(), getCURRST(), getCURRRT());
				if(!valores.isEmpty())
				{
					double	lamApl = (Double)valores.remove(),
							lamCalc = (Double)valores.remove(),
							lamAplAnt = (Double)valores.remove(),
							lamCalcAnt = (Double)valores.remove(),
							VUD = (Double)valores.remove(),
							SIP = (Double)valores.remove(),
							SPP = (Double)valores.remove();
					long	ACB = (Long)valores.remove(),
							ACR = (Long)valores.remove();
					
					double	EAD = lamApl > 0 ? (lamCalc / lamApl * 100) : 0,
							EAA = lamAplAnt > 0 ? (lamCalcAnt / lamAplAnt * 100) : 0,
							VUA = 0.1 * lamAplAnt * SIP,
							
							IEA = EAA > 0 ? ((EAD - EAA) / EAA * 100) : 0,
							AAP = VUA > 0 ? ((VUD - VUA) / VUA * 100) : 0,
							SBP = SPP > 0 ? (SIP / SPP * 100) : 0,
							ABP = ACR > 0 ? ((double)ACB / (double)ACR * 100) : 0;
					
					txtIEA.setValue(u.doubleToString(IEA));
					txtAAP.setValue(u.doubleToString(AAP));
					txtSBP.setValue(u.doubleToString(SBP));
					txtABP.setValue(u.doubleToString(ABP));
					txtSAT.setValue(u.doubleToString(SBP));
					
					tipoReporte = TipoResultado.INDICADORES;
					parametros = new HashMap<String, Object>();
					parametros.put("IEA", txtIEA.getValue());
					parametros.put("AAP", txtAAP.getValue());
					parametros.put("SBP", txtSBP.getValue());
					parametros.put("ABP", txtABP.getValue());
					parametros.put("SAT", txtSAT.getValue());
					u.llenarTabla(tblIRP, datos.getIndicadoresRendimiento(getOC(), getDR(), getMR(), getCURRST(), getCURRRT()), "");
				}
				else
					u.msjRegistroNoObtenido();
			}
			else
				u.msjNoSeleccionFiltros();
		}
	};
	private ClickListener verOtroListener = new ClickListener()
	{
		@Override
		public void buttonClick(ClickEvent event)
		{
			setupInfo(true);
			if(!verLCultivo.isVisible())
			{
				horLBotones.setVisible(true);
				horLBotones2.setVisible(true);
			}
			else
				horLBotonesCultivo.setVisible(true);
		}
	};
	
	private MouseEvents.ClickListener excelListener = new MouseEvents.ClickListener()
	{
		@Override
		public void click(MouseEvents.ClickEvent event)
		{
			runReporte(Formato.EXCEL, btnExcel);
		}
	};
	private MouseEvents.ClickListener wordListener = new MouseEvents.ClickListener()
	{
		@Override
		public void click(MouseEvents.ClickEvent event)
		{
			runReporte(Formato.WORD, btnWord);
		}
	};
	private MouseEvents.ClickListener pdfListener = new MouseEvents.ClickListener()
	{
		@Override
		public void click(MouseEvents.ClickEvent event)
		{
			runReporte(Formato.PDF, btnPDF);
		}
	};
	
	private ClickListener drListener = new ClickListener()
	{
		@Override
		public void buttonClick(ClickEvent event)
		{
			tipoResultadoRel = TipoResultado.DISTRITO_RIEGO;
			absLDR.setVisible(true);
			btnDR.setVisible(false);
			btnMR.setVisible(true);
			btnCultivo.setVisible(true);
			btnST.setVisible(true);
			btnRT.setVisible(true);
		}
	};
	private ClickListener mrListener = new ClickListener()
	{
		@Override
		public void buttonClick(ClickEvent event)
		{
			tipoResultadoRel = TipoResultado.MODULO_RIEGO;
			absLMR.setVisible(true);
			btnMR.setVisible(false);
		}
	};
	private ClickListener stListener = new ClickListener()
	{
		@Override
		public void buttonClick(ClickEvent event)
		{
			tipoResultadoRel = TipoResultado.SUPERVISOR_TECNICO;
			absLST.setVisible(true);
			btnST.setVisible(false);
		}
	};
	private ClickListener rtListener = new ClickListener()
	{
		@Override
		public void buttonClick(ClickEvent event)
		{
			tipoResultadoRel = TipoResultado.RESPONSABLE_TECNICO;
			absLRT.setVisible(true);
			btnRT.setVisible(false);
		}
	};
	private ClickListener cultivoListener = new ClickListener()
	{
		@Override
		public void buttonClick(ClickEvent event)
		{
			verLCultivo.setVisible(true);
			horLBotones.setVisible(false);
			horLBotones2.setVisible(false);
		}
	};
	
	private ValueChangeListener onChangeOCListener = new ValueChangeListener()
	{
		@Override
		public void valueChange(ValueChangeEvent event)
		{
//			if(absLDR.isVisible())
//				reloadCombo(cmbDR, datos.getDR(getRT(), getST(), getOC()));
//			if(absLST.isVisible())
//				reloadCombo(cmbST, datos.getST(getRT(), getDR(), getOC()));
//			if(absLRT.isVisible())
//				reloadCombo(cmbRT, datos.getRT(getST(), getDR(), getOC()));
			
			reloadCombo(cmbDR, datos.getDRByOC(getOC()));
			cmbST.removeAllItems();
			cmbRT.removeAllItems();
			cmbCultivo.removeAllItems();
		}
	};
	private ValueChangeListener onChangeDRListener = new ValueChangeListener()
	{
		@Override
		public void valueChange(ValueChangeEvent event)
		{
//			if(absLOC.isVisible())
//				reloadCombo(cmbOC, datos.getOC(getRT(), getST(), getDR()));
//			if(absLST.isVisible())
//				reloadCombo(cmbST, datos.getST(getRT(), getDR(), getOC()));
//			if(absLRT.isVisible())
//				reloadCombo(cmbRT, datos.getRT(getST(), getDR(), getOC()));

			reloadCombo(cmbMR, datos.getModuloRiego(getDR()));
			reloadCombo(cmbST, datos.getSTByDR(getDR()));
			reloadCombo(cmbRT, datos.getRTByDR(getDR()));
			reloadCombo(cmbCultivo, datos.getCultivosByDR(getDR()));
		}
	};
	private ValueChangeListener onChangeMRListener = new ValueChangeListener()
	{
		@Override
		public void valueChange(ValueChangeEvent event)
		{
			reloadCombo(cmbST, datos.getSTByMR(getMR()));
			reloadCombo(cmbRT, datos.getRTByMR(getMR()));
			reloadCombo(cmbCultivo, datos.getCultivosByMR(getMR()));
		}
	};
	private ValueChangeListener onChangeSTListener = new ValueChangeListener()
	{
		@Override
		public void valueChange(ValueChangeEvent event)
		{
//			if(absLOC.isVisible())
//				reloadCombo(cmbOC, datos.getOC(getRT(), getST(), getDR()));
//			if(absLDR.isVisible())
//				reloadCombo(cmbDR, datos.getDR(getRT(), getST(), getOC()));
//			if(absLRT.isVisible())
//				reloadCombo(cmbRT, datos.getRT(getST(), getDR(), getOC()));
			
			reloadCombo(cmbRT, datos.getRTBySTyDR(getCURRST(), getDR()));
			reloadCombo(cmbCultivo, datos.getCultivosByST(getCURRST()));
		}
	};
	private ValueChangeListener onChangeRTListener = new ValueChangeListener()
	{
		@Override
		public void valueChange(ValueChangeEvent event)
		{
//			if(absLOC.isVisible())
//				reloadCombo(cmbOC, datos.getOC(getRT(), getST(), getDR()));
//			if(absLDR.isVisible())
//				reloadCombo(cmbDR, datos.getDR(getRT(), getST(), getOC()));
//			if(absLST.isVisible())
//				reloadCombo(cmbST, datos.getST(getRT(), getDR(), getOC()));
			
			reloadCombo(cmbCultivo, datos.getCultivosByRT(getCURRRT()));
		}
	};
	//endregion

	public Resultados(TipoResultado tipo, Usuario user)
	{
		usuario = user;
		tipoResultadoAbs = tipo;
	}

	@Override
	public void inicializar()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		tipoResultadoRel = tipoResultadoAbs;

		label_10.setContentMode(ContentMode.HTML);
		label_28.setContentMode(ContentMode.HTML);
		label_29.setContentMode(ContentMode.HTML);
		
		optDescarga.addItem("Descargar");
		optDescarga.addItem("Descargar todo");
		optDescarga.setValue("Descargar");
		
		btnGral.addClickListener(generalListener);
		btnIndicadores.addClickListener(indicadoresListener);
		btnDR.addClickListener(drListener);
		btnMR.addClickListener(mrListener);
		btnCultivo.addClickListener(cultivoListener);
		btnProd.addClickListener(produccionListener);
		btnHidr.addClickListener(hidrometricoListener);
		btnST.addClickListener(stListener);
		btnRT.addClickListener(rtListener);
		btnVerOtro.addClickListener(verOtroListener);
		
		inicializarDownloader(btnExcel, excelListener);
        inicializarDownloader(btnWord, wordListener);
		inicializarDownloader(btnPDF, pdfListener);

		u.setupCombo(cmbOC, null, "Busque por nombre de organismo.", FilteringMode.CONTAINS, true, true);
		u.setupCombo(cmbDR, null, "Busque por número de distrito.", FilteringMode.CONTAINS, true, true);
		u.setupCombo(cmbMR, null, "Busque por nombre de módulo.", FilteringMode.CONTAINS, true, true);
		u.setupCombo(cmbST, null, "Busque por nombre o CURR.", FilteringMode.CONTAINS, true, true);
		u.setupCombo(cmbRT, null, "Busque por nombre o CURR.", FilteringMode.CONTAINS, true, true);
		u.setupCombo(cmbCultivo, null, "Busque por cultivo.", FilteringMode.CONTAINS, true, true);
		cmbOC.addValueChangeListener(onChangeOCListener);
		cmbDR.addValueChangeListener(onChangeDRListener);
		cmbMR.addValueChangeListener(onChangeMRListener);
		cmbST.addValueChangeListener(onChangeSTListener);
		cmbRT.addValueChangeListener(onChangeRTListener);
		
		tblIRP.setSelectable(true);
		tblIRP.setSortEnabled(true);
		
		switch(tipoResultadoAbs)
		{
			case ORGANISMO_CUENCA:	u.setupCombo(cmbOC, datos.getOrgCuenca(), "Busque por nombre de organismo.", FilteringMode.CONTAINS, false, true);
									absLDR.setVisible(false);
									absLMR.setVisible(false);
									absLST.setVisible(false);
									absLRT.setVisible(false);
									btnCultivo.setVisible(false);
									btnMR.setVisible(false);
									btnST.setVisible(false);
									btnRT.setVisible(false);
									verLCultivo.setVisible(false);
									verLInfoBtns.setVisible(false);
									break;
			case DISTRITO_RIEGO:	u.setupCombo(cmbDR, datos.getDtoRiego(), "Busque por número de distrito.", FilteringMode.CONTAINS, false, true);
									absLOC.setVisible(false);
									absLMR.setVisible(false);
									absLST.setVisible(false);
									absLRT.setVisible(false);
									btnDR.setVisible(false);
									verLCultivo.setVisible(false);
									verLInfoBtns.setVisible(false);
									break;
			case MODULO_RIEGO:		u.setupCombo(cmbMR, datos.getModuloRiego(), "Busque por nombre de módulo.", FilteringMode.CONTAINS, false, true);
									absLOC.setVisible(false);
									absLDR.setVisible(false);
									absLST.setVisible(false);
									absLRT.setVisible(false);
									btnDR.setVisible(false);
									btnMR.setVisible(false);
									verLCultivo.setVisible(false);
									verLInfoBtns.setVisible(false);
									break;
			case SUPERVISOR_TECNICO:inicializarTecnico(usuario.SUPERVISOR, cmbST, datos.getTecnicosByTipo(usuario.SUPERVISOR));//datos.getST("", "", ""));
									absLOC.setVisible(false);
									absLDR.setVisible(false);
									absLMR.setVisible(false);
									absLRT.setVisible(false);
									btnDR.setVisible(false);
									btnMR.setVisible(false);
									btnST.setVisible(false);
									verLCultivo.setVisible(false);
									verLInfoBtns.setVisible(false);
									break;
			case RESPONSABLE_TECNICO://inicializarTecnico(usuario.SUPERVISOR, cmbST, datos.getST("", "", ""));
									inicializarTecnico(usuario.RESPONSABLE, cmbRT, datos.getTecnicosByTipo(usuario.RESPONSABLE));//datos.getRT(cmbST.getValue() != null ? cmbST.getValue().toString().split(" ")[0] : "", "", ""));
									//cmbOC.setEnabled(false);
									btnDR.setVisible(false);
									btnMR.setVisible(false);
									btnST.setVisible(false);
									btnRT.setVisible(false);
									verLCultivo.setVisible(false);
									verLInfoBtns.setVisible(false);
									break;
		}
		
		txtNumDR.setEnabled(false);
		txtNumST.setEnabled(false);
		txtNumRT.setEnabled(false);
		txtSupAtendida.setEnabled(false);
		txtSupSembrada.setEnabled(false);
		txtHecRiego.setEnabled(false);
		txtVolAplicado.setEnabled(false);
		txtVolMedio.setEnabled(false);
		txtLamMedia.setEnabled(false);
		txtRendMedio.setEnabled(false);
		txtProdTotal.setEnabled(false);
		txtNumMedioRiegos.setEnabled(false);
		txtIEA.setEnabled(false);
		txtAAP.setEnabled(false);
		txtSBP.setEnabled(false);
		txtABP.setEnabled(false);
		txtSAT.setEnabled(false);
	}
	
	private void inicializarDownloader(Embedded btn, MouseEvents.ClickListener listener)
	{
		btn.addClickListener(listener);
		
		final AdvancedFileDownloader downloader = new AdvancedFileDownloader();
		downloader.addAdvancedDownloaderListener(new AdvancedDownloaderListener()
		{
			@Override
			public void beforeDownload(DownloaderEvent downloadEvent)
			{
				downloader.setFilePath(lblRptPath.getValue());
			}
		});
        downloader.extend(btn);
	}
	
	private void inicializarTecnico(int tipoTecnico, ComboBox cmb, LinkedList<String> lista)
	{
		if(usuario.getTipo() != tipoTecnico)
			u.setupCombo(cmb, lista, "Busque por nombre o CURR.", FilteringMode.CONTAINS, false, true);
		else
			u.llenarCombo(cmb, usuario.getCURR() + " | " + usuario.getNombre() + " " + usuario.getApPaterno() + " " + usuario.getApMaterno());
	}
	
	@Override
	public void setTipo(int modoOperacion)
	{
		
	}
	
	private boolean validar()
	{
		return !(getOC() + getDR() + getMR() + getCURRST() + getCURRRT() + getCultivo()).isEmpty();
	}

	private void reloadCombo(ComboBox cmb, LinkedList<String> lista)
	{
		Object val = cmb.getValue();
		u.llenarCombo(cmb, lista);
		cmb.setValue(val);
	}
	
	private String getOC()
	{
		return getValor(cmbOC, absLOC);
	}
	
	private String getDR()
	{
		return getValor(cmbDR, absLDR);
	}

	private String getMR()
	{
		return getValor(cmbMR, absLMR);
	}
	
	private String getCURRST()
	{
		return getTecnico(cmbST, absLST, CURR_TECNICO);
	}
	
	private String getCURRRT()
	{
		return getTecnico(cmbRT, absLRT, CURR_TECNICO);
	}
	
	private String getNombreST()
	{
		return getTecnico(cmbST, absLST, NOMBRE_TECNICO);
	}
	
	private String getNombreRT()
	{
		return getTecnico(cmbRT, absLRT, NOMBRE_TECNICO);
	}

	private String getCultivo()
	{
		return getValor(cmbCultivo, absLCultivo);
	}
	
	private String getTecnico(ComboBox cmb, AbsoluteLayout absL, int index)
	{
		return (absL.isVisible() && cmb.getValue() != null) ? cmb.getValue().toString().split(" \\| ")[index] : "";
	}

	private String getValor(ComboBox cmb, AbsoluteLayout absL)
	{
		return (absL.isVisible() && cmb.getValue() != null) ? cmb.getValue().toString() : "";
	}

	/**
	 * Método que muestra u oculta los datos del resultado calculado
	 * @param hideInfo
	 *            : <i>true</i> si se quieren ocultar los datos, <i>false</i> si se quieren mostrar  
	 */
	private void setupInfo(boolean hideInfo)
	{
		verLInfoBtns.setVisible(!hideInfo);
		cmbOC.setEnabled(hideInfo);
		cmbDR.setEnabled(hideInfo);
		cmbMR.setEnabled(hideInfo);
		cmbST.setEnabled(hideInfo);
		cmbRT.setEnabled(hideInfo);
		cmbCultivo.setEnabled(hideInfo);
		
		if(hideInfo)
		{
			txtNumDR.setValue("");
			txtNumST.setValue("");
			txtNumRT.setValue("");
			txtSupAtendida.setValue("");
			txtSupSembrada.setValue("");
			txtHecRiego.setValue("");
			txtVolAplicado.setValue("");
			txtVolMedio.setValue("");
			txtLamMedia.setValue("");
			txtRendMedio.setValue("");
			txtProdTotal.setValue("");
			txtNumMedioRiegos.setValue("");
			
			txtIEA.setValue("");
			txtAAP.setValue("");
			txtSBP.setValue("");
			txtABP.setValue("");
			txtSAT.setValue("");
			tblIRP.removeAllItems();
			
			if(!optDescarga.containsId("Descargar todo"))
				optDescarga.addItem("Descargar todo");
		}
	}
	
	private void setupNums(boolean showNumDR, boolean showNumST, boolean showNumRT)
	{
		absLNumDR.setVisible(showNumDR);
		absLNumST.setVisible(showNumST);
		absLNumRT.setVisible(showNumRT);
	}
	
	private void setupInfoGeneral()
	{
		setupInfo(false);
		setupNums(tipoResultadoRel == TipoResultado.ORGANISMO_CUENCA,
				  tipoResultadoRel != TipoResultado.SUPERVISOR_TECNICO && tipoResultadoRel != TipoResultado.RESPONSABLE_TECNICO,
				  tipoResultadoRel != TipoResultado.RESPONSABLE_TECNICO);
		panInfo.setVisible(true);
		panInfoIndicadores.setVisible(false);
		
		horLBotones.setVisible(false);
		horLBotones2.setVisible(false);
		
		absLSupAtendida.setVisible(true);
		absLSupSembrada.setVisible(false);
		absLHecRiego.setVisible(true);
		absLVolAplicado.setVisible(true);
		absLVolMedio.setVisible(false);
		absLLamMedia.setVisible(false);
		absLRendMedio.setVisible(false);
		absLProdTotal.setVisible(false);
		absLNumMedioRiegos.setVisible(false);
	}
	
	private void setupInfoProduccion()
	{
		setupInfo(false);
		setupNums(false, false, false);
		panInfo.setVisible(true);
		panInfoIndicadores.setVisible(false);
		
		horLBotonesCultivo.setVisible(false);
		
		absLSupAtendida.setVisible(false);
		absLSupSembrada.setVisible(true);
		absLHecRiego.setVisible(false);
		absLVolAplicado.setVisible(false);
		absLVolMedio.setVisible(false);
		absLLamMedia.setVisible(false);
		absLRendMedio.setVisible(true);
		absLProdTotal.setVisible(true);
		absLNumMedioRiegos.setVisible(false);
	}
	
	private void setupInfoHidrometrico()
	{
		setupInfo(false);
		setupNums(false, false, false);
		panInfo.setVisible(true);
		panInfoIndicadores.setVisible(false);
		
		horLBotonesCultivo.setVisible(false);
		
		absLSupAtendida.setVisible(false);
		absLSupSembrada.setVisible(true);
		absLHecRiego.setVisible(true);
		absLVolAplicado.setVisible(true);
		absLVolMedio.setVisible(true);
		absLLamMedia.setVisible(true);
		absLRendMedio.setVisible(false);
		absLProdTotal.setVisible(false);
		absLNumMedioRiegos.setVisible(true);
	}
	
	private void setupInfoIndicadores()
	{
		setupInfo(false);
		setupNums(false, false, false);
		panInfo.setVisible(false);
		panInfoIndicadores.setVisible(true);

		optDescarga.removeItem("Descargar todo");
		optDescarga.setValue("Descargar");
		
		horLBotones.setVisible(false);
		horLBotones2.setVisible(false);
	}
	
	private void runReporte(Formato formato, Embedded boton)
	{
		parametros.put("showOC", !getOC().isEmpty());
		parametros.put("OC", getOC());
		parametros.put("showDR", !getDR().isEmpty());
		parametros.put("DR", getDR());
		parametros.put("showMR", !getMR().isEmpty());
		parametros.put("MR", getMR());
		parametros.put("showST", !getCURRST().isEmpty());
		parametros.put("ST", getNombreST());
		parametros.put("showRT", !getCURRRT().isEmpty());
		parametros.put("RT", getNombreRT());
		parametros.put("showCultivo", !getCultivo().isEmpty());
		parametros.put("cultivo", getCultivo());
		
		ResultSet resultset = null;
		if(((String)optDescarga.getValue()).indexOf("todo") != -1)
			resultset = datos.getResultadoSubReporte(getOC(), getDR(), getMR(), getCURRST(), getCURRRT(), getCultivo());
		if(tipoReporte == TipoResultado.INDICADORES)
			resultset = datos.getResultadoSubReporteIndicadores(getOC(), getDR(), getMR(), getCURRST(), getCURRRT());
		
		new InterfazReportes().getReport(tipoReporte, parametros, resultset, formato, lblRptPath);
	}
	//region UI

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// panFiltros
		panFiltros = buildPanFiltros();
		mainLayout.addComponent(panFiltros);
		
		// verLInfoBtns
		verLInfoBtns = buildVerLInfoBtns();
		mainLayout.addComponent(verLInfoBtns);
		
		// lblRptPath
		lblRptPath = new Label();
		lblRptPath.setEnabled(false);
		lblRptPath.setImmediate(false);
		lblRptPath.setVisible(false);
		lblRptPath.setWidth("-1px");
		lblRptPath.setHeight("-1px");
		lblRptPath.setValue("Label");
		mainLayout.addComponent(lblRptPath);
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanFiltros() {
		// common part: create layout
		panFiltros = new Panel();
		panFiltros.setImmediate(false);
		panFiltros.setWidth("610px");
		panFiltros.setHeight("-1px");
		
		// verLFiltros
		verLFiltros = buildVerLFiltros();
		panFiltros.setContent(verLFiltros);
		
		return panFiltros;
	}

	@AutoGenerated
	private VerticalLayout buildVerLFiltros() {
		// common part: create layout
		verLFiltros = new VerticalLayout();
		verLFiltros.setImmediate(false);
		verLFiltros.setWidth("100.0%");
		verLFiltros.setHeight("-1px");
		verLFiltros.setMargin(false);
		
		// absoluteLayout_2
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("100.0%");
		absoluteLayout_2.setHeight("10px");
		verLFiltros.addComponent(absoluteLayout_2);
		
		// absLOC
		absLOC = buildAbsLOC();
		verLFiltros.addComponent(absLOC);
		
		// absLDR
		absLDR = buildAbsLDR();
		verLFiltros.addComponent(absLDR);
		
		// absLMR
		absLMR = buildAbsLMR();
		verLFiltros.addComponent(absLMR);
		
		// absLST
		absLST = buildAbsLST();
		verLFiltros.addComponent(absLST);
		
		// absLRT
		absLRT = buildAbsLRT();
		verLFiltros.addComponent(absLRT);
		
		// horLBotones
		horLBotones = buildHorLBotones();
		verLFiltros.addComponent(horLBotones);
		verLFiltros.setComponentAlignment(horLBotones, new Alignment(48));
		
		// horLBotones2
		horLBotones2 = buildHorLBotones2();
		verLFiltros.addComponent(horLBotones2);
		verLFiltros.setComponentAlignment(horLBotones2, new Alignment(48));
		
		// verLCultivo
		verLCultivo = buildVerLCultivo();
		verLFiltros.addComponent(verLCultivo);
		
		// absoluteLayout_1
		absoluteLayout_1 = new AbsoluteLayout();
		absoluteLayout_1.setImmediate(false);
		absoluteLayout_1.setWidth("100.0%");
		absoluteLayout_1.setHeight("10px");
		verLFiltros.addComponent(absoluteLayout_1);
		
		return verLFiltros;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLOC() {
		// common part: create layout
		absLOC = new AbsoluteLayout();
		absLOC.setImmediate(false);
		absLOC.setWidth("100.0%");
		absLOC.setHeight("45px");
		
		// cmbOC
		cmbOC = new ComboBox();
		cmbOC.setCaption("Organismo de Cuenca");
		cmbOC.setImmediate(true);
		cmbOC.setWidth("590px");
		cmbOC.setHeight("25px");
		absLOC.addComponent(cmbOC, "top:18.0px;left:10.0px;");
		
		return absLOC;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDR() {
		// common part: create layout
		absLDR = new AbsoluteLayout();
		absLDR.setImmediate(false);
		absLDR.setWidth("100.0%");
		absLDR.setHeight("45px");
		
		// cmbDR
		cmbDR = new ComboBox();
		cmbDR.setCaption("Distrito de Riego");
		cmbDR.setImmediate(true);
		cmbDR.setWidth("590px");
		cmbDR.setHeight("25px");
		absLDR.addComponent(cmbDR, "top:18.0px;left:10.0px;");
		
		return absLDR;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLMR() {
		// common part: create layout
		absLMR = new AbsoluteLayout();
		absLMR.setImmediate(false);
		absLMR.setWidth("100.0%");
		absLMR.setHeight("45px");
		
		// cmbMR
		cmbMR = new ComboBox();
		cmbMR.setCaption("Módulo de Riego");
		cmbMR.setImmediate(true);
		cmbMR.setWidth("590px");
		cmbMR.setHeight("25px");
		absLMR.addComponent(cmbMR, "top:18.0px;left:10.0px;");
		
		return absLMR;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLST() {
		// common part: create layout
		absLST = new AbsoluteLayout();
		absLST.setImmediate(false);
		absLST.setWidth("100.0%");
		absLST.setHeight("45px");
		
		// cmbST
		cmbST = new ComboBox();
		cmbST.setCaption("Supervisor Técnico");
		cmbST.setImmediate(true);
		cmbST.setWidth("590px");
		cmbST.setHeight("25px");
		absLST.addComponent(cmbST, "top:18.0px;left:10.0px;");
		
		return absLST;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLRT() {
		// common part: create layout
		absLRT = new AbsoluteLayout();
		absLRT.setImmediate(false);
		absLRT.setWidth("100.0%");
		absLRT.setHeight("45px");
		
		// cmbRT
		cmbRT = new ComboBox();
		cmbRT.setCaption("Responsable Técnico");
		cmbRT.setImmediate(true);
		cmbRT.setWidth("590px");
		cmbRT.setHeight("25px");
		absLRT.addComponent(cmbRT, "top:18.0px;left:10.0px;");
		
		return absLRT;
	}

	@AutoGenerated
	private HorizontalLayout buildHorLBotones() {
		// common part: create layout
		horLBotones = new HorizontalLayout();
		horLBotones.setImmediate(false);
		horLBotones.setWidth("-1px");
		horLBotones.setHeight("30px");
		horLBotones.setMargin(false);
		horLBotones.setSpacing(true);
		
		// btnGral
		btnGral = new Button();
		btnGral.setCaption("Generar Reporte General");
		btnGral.setImmediate(true);
		btnGral.setWidth("170px");
		btnGral.setHeight("-1px");
		horLBotones.addComponent(btnGral);
		horLBotones.setComponentAlignment(btnGral, new Alignment(10));
		
		// btnIndicadores
		btnIndicadores = new Button();
		btnIndicadores.setCaption("Generar Reporte de Indicadores");
		btnIndicadores.setImmediate(true);
		btnIndicadores.setWidth("210px");
		btnIndicadores.setHeight("-1px");
		horLBotones.addComponent(btnIndicadores);
		horLBotones.setComponentAlignment(btnIndicadores, new Alignment(9));
		
		return horLBotones;
	}

	@AutoGenerated
	private HorizontalLayout buildHorLBotones2() {
		// common part: create layout
		horLBotones2 = new HorizontalLayout();
		horLBotones2.setImmediate(false);
		horLBotones2.setWidth("-1px");
		horLBotones2.setHeight("30px");
		horLBotones2.setMargin(false);
		horLBotones2.setSpacing(true);
		
		// btnDR
		btnDR = new Button();
		btnDR.setCaption("Distrito de Riego");
		btnDR.setImmediate(true);
		btnDR.setWidth("120px");
		btnDR.setHeight("-1px");
		horLBotones2.addComponent(btnDR);
		horLBotones2.setComponentAlignment(btnDR, new Alignment(10));
		
		// btnCultivo
		btnCultivo = new Button();
		btnCultivo.setCaption("Cultivo");
		btnCultivo.setImmediate(true);
		btnCultivo.setWidth("70px");
		btnCultivo.setHeight("-1px");
		horLBotones2.addComponent(btnCultivo);
		horLBotones2.setComponentAlignment(btnCultivo, new Alignment(24));
		
		// btnMR
		btnMR = new Button();
		btnMR.setCaption("Módulo de Riego");
		btnMR.setImmediate(true);
		btnMR.setWidth("120px");
		btnMR.setHeight("-1px");
		horLBotones2.addComponent(btnMR);
		horLBotones2.setComponentAlignment(btnMR, new Alignment(24));
		
		// btnST
		btnST = new Button();
		btnST.setCaption("Supervisor Técnico");
		btnST.setImmediate(true);
		btnST.setWidth("130px");
		btnST.setHeight("-1px");
		horLBotones2.addComponent(btnST);
		horLBotones2.setComponentAlignment(btnST, new Alignment(24));
		
		// btnRT
		btnRT = new Button();
		btnRT.setCaption("Responsable Técnico");
		btnRT.setImmediate(true);
		btnRT.setWidth("145px");
		btnRT.setHeight("-1px");
		horLBotones2.addComponent(btnRT);
		horLBotones2.setComponentAlignment(btnRT, new Alignment(9));
		
		return horLBotones2;
	}

	@AutoGenerated
	private VerticalLayout buildVerLCultivo() {
		// common part: create layout
		verLCultivo = new VerticalLayout();
		verLCultivo.setImmediate(false);
		verLCultivo.setWidth("100.0%");
		verLCultivo.setHeight("-1px");
		verLCultivo.setMargin(false);
		
		// absLCultivo
		absLCultivo = buildAbsLCultivo();
		verLCultivo.addComponent(absLCultivo);
		
		// horLBotonesCultivo
		horLBotonesCultivo = buildHorLBotonesCultivo();
		verLCultivo.addComponent(horLBotonesCultivo);
		verLCultivo
				.setComponentAlignment(horLBotonesCultivo, new Alignment(48));
		
		return verLCultivo;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCultivo() {
		// common part: create layout
		absLCultivo = new AbsoluteLayout();
		absLCultivo.setImmediate(false);
		absLCultivo.setWidth("100.0%");
		absLCultivo.setHeight("45px");
		
		// cmbCultivo
		cmbCultivo = new ComboBox();
		cmbCultivo.setCaption("Cultivo");
		cmbCultivo.setImmediate(true);
		cmbCultivo.setWidth("590px");
		cmbCultivo.setHeight("25px");
		absLCultivo.addComponent(cmbCultivo, "top:18.0px;left:10.0px;");
		
		return absLCultivo;
	}

	@AutoGenerated
	private HorizontalLayout buildHorLBotonesCultivo() {
		// common part: create layout
		horLBotonesCultivo = new HorizontalLayout();
		horLBotonesCultivo.setImmediate(false);
		horLBotonesCultivo.setWidth("-1px");
		horLBotonesCultivo.setHeight("30px");
		horLBotonesCultivo.setMargin(false);
		horLBotonesCultivo.setSpacing(true);
		
		// btnProd
		btnProd = new Button();
		btnProd.setCaption("Generar Reporte de Producción");
		btnProd.setImmediate(true);
		btnProd.setWidth("210px");
		btnProd.setHeight("-1px");
		horLBotonesCultivo.addComponent(btnProd);
		horLBotonesCultivo.setComponentAlignment(btnProd, new Alignment(10));
		
		// btnHidr
		btnHidr = new Button();
		btnHidr.setCaption("Generar Reporte Hidrométrico");
		btnHidr.setImmediate(true);
		btnHidr.setWidth("200px");
		btnHidr.setHeight("-1px");
		horLBotonesCultivo.addComponent(btnHidr);
		horLBotonesCultivo.setComponentAlignment(btnHidr, new Alignment(9));
		
		return horLBotonesCultivo;
	}

	@AutoGenerated
	private VerticalLayout buildVerLInfoBtns() {
		// common part: create layout
		verLInfoBtns = new VerticalLayout();
		verLInfoBtns.setImmediate(false);
		verLInfoBtns.setWidth("100.0%");
		verLInfoBtns.setHeight("-1px");
		verLInfoBtns.setMargin(false);
		verLInfoBtns.setSpacing(true);
		
		// panInfo
		panInfo = buildPanInfo();
		verLInfoBtns.addComponent(panInfo);
		
		// panInfoIndicadores
		panInfoIndicadores = buildPanInfoIndicadores();
		verLInfoBtns.addComponent(panInfoIndicadores);
		
		// horLBotonesExportacion
		horLBotonesExportacion = buildHorLBotonesExportacion();
		verLInfoBtns.addComponent(horLBotonesExportacion);
		
		return verLInfoBtns;
	}

	@AutoGenerated
	private Panel buildPanInfo() {
		// common part: create layout
		panInfo = new Panel();
		panInfo.setCaption("* Los datos presentados corresponden al último ciclo agrícola (ciclo actual)");
		panInfo.setImmediate(false);
		panInfo.setWidth("610px");
		panInfo.setHeight("-1px");
		
		// verLInfo
		verLInfo = buildVerLInfo();
		panInfo.setContent(verLInfo);
		
		return panInfo;
	}

	@AutoGenerated
	private VerticalLayout buildVerLInfo() {
		// common part: create layout
		verLInfo = new VerticalLayout();
		verLInfo.setImmediate(false);
		verLInfo.setWidth("100.0%");
		verLInfo.setHeight("-1px");
		verLInfo.setMargin(false);
		
		// absLNumDR
		absLNumDR = buildAbsLNumDR();
		verLInfo.addComponent(absLNumDR);
		
		// absLNumST
		absLNumST = buildAbsLNumST();
		verLInfo.addComponent(absLNumST);
		
		// absLNumRT
		absLNumRT = buildAbsLNumRT();
		verLInfo.addComponent(absLNumRT);
		
		// absLSupAtendida
		absLSupAtendida = buildAbsLSupAtendida();
		verLInfo.addComponent(absLSupAtendida);
		
		// absLSupSembrada
		absLSupSembrada = buildAbsLSupSembrada();
		verLInfo.addComponent(absLSupSembrada);
		
		// absLHecRiego
		absLHecRiego = buildAbsLHecRiego();
		verLInfo.addComponent(absLHecRiego);
		
		// absLVolAplicado
		absLVolAplicado = buildAbsLVolAplicado();
		verLInfo.addComponent(absLVolAplicado);
		
		// absLVolMedio
		absLVolMedio = buildAbsLVolMedio();
		verLInfo.addComponent(absLVolMedio);
		
		// absLLamMedia
		absLLamMedia = buildAbsLLamMedia();
		verLInfo.addComponent(absLLamMedia);
		
		// absLRendMedio
		absLRendMedio = buildAbsLRendMedio();
		verLInfo.addComponent(absLRendMedio);
		
		// absLProdTotal
		absLProdTotal = buildAbsLProdTotal();
		verLInfo.addComponent(absLProdTotal);
		
		// absLNumMedioRiegos
		absLNumMedioRiegos = buildAbsLNumMedioRiegos();
		verLInfo.addComponent(absLNumMedioRiegos);
		
		// absoluteLayout_3
		absoluteLayout_3 = new AbsoluteLayout();
		absoluteLayout_3.setImmediate(false);
		absoluteLayout_3.setWidth("100.0%");
		absoluteLayout_3.setHeight("5px");
		verLInfo.addComponent(absoluteLayout_3);
		
		return verLInfo;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLNumDR() {
		// common part: create layout
		absLNumDR = new AbsoluteLayout();
		absLNumDR.setImmediate(false);
		absLNumDR.setWidth("100.0%");
		absLNumDR.setHeight("40px");
		
		// txtNumDR
		txtNumDR = new TextField();
		txtNumDR.setImmediate(false);
		txtNumDR.setWidth("80px");
		txtNumDR.setHeight("25px");
		absLNumDR.addComponent(txtNumDR, "top:10.0px;left:210.0px;");
		
		// label_6
		label_6 = new Label();
		label_6.setImmediate(false);
		label_6.setWidth("-1px");
		label_6.setHeight("-1px");
		label_6.setValue("Núm. de Distritos de Riego");
		absLNumDR.addComponent(label_6, "top:14.0px;left:10.0px;");
		
		return absLNumDR;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLNumST() {
		// common part: create layout
		absLNumST = new AbsoluteLayout();
		absLNumST.setImmediate(false);
		absLNumST.setWidth("100.0%");
		absLNumST.setHeight("40px");
		
		// txtNumST
		txtNumST = new TextField();
		txtNumST.setImmediate(false);
		txtNumST.setWidth("80px");
		txtNumST.setHeight("25px");
		absLNumST.addComponent(txtNumST, "top:10.0px;left:210.0px;");
		
		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("-1px");
		label_5.setHeight("-1px");
		label_5.setValue("Núm. de Supervisores Técnicos");
		absLNumST.addComponent(label_5, "top:14.0px;left:10.0px;");
		
		return absLNumST;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLNumRT() {
		// common part: create layout
		absLNumRT = new AbsoluteLayout();
		absLNumRT.setImmediate(false);
		absLNumRT.setWidth("100.0%");
		absLNumRT.setHeight("40px");
		
		// txtNumRT
		txtNumRT = new TextField();
		txtNumRT.setImmediate(false);
		txtNumRT.setWidth("80px");
		txtNumRT.setHeight("25px");
		absLNumRT.addComponent(txtNumRT, "top:10.0px;left:210.0px;");
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("Núm. de Responsables Técnicos");
		absLNumRT.addComponent(label_4, "top:14.0px;left:10.0px;");
		
		return absLNumRT;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLSupAtendida() {
		// common part: create layout
		absLSupAtendida = new AbsoluteLayout();
		absLSupAtendida.setImmediate(false);
		absLSupAtendida.setWidth("100.0%");
		absLSupAtendida.setHeight("40px");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Superficie atendida");
		absLSupAtendida.addComponent(label_1, "top:14.0px;left:10.0px;");
		
		// txtSupAtendida
		txtSupAtendida = new TextField();
		txtSupAtendida.setImmediate(false);
		txtSupAtendida.setWidth("100px");
		txtSupAtendida.setHeight("25px");
		absLSupAtendida
				.addComponent(txtSupAtendida, "top:10.0px;left:165.0px;");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("ha");
		absLSupAtendida.addComponent(label_2, "top:12.0px;left:275.0px;");
		
		return absLSupAtendida;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLSupSembrada() {
		// common part: create layout
		absLSupSembrada = new AbsoluteLayout();
		absLSupSembrada.setImmediate(false);
		absLSupSembrada.setWidth("100.0%");
		absLSupSembrada.setHeight("40px");
		
		// label_16
		label_16 = new Label();
		label_16.setImmediate(false);
		label_16.setWidth("-1px");
		label_16.setHeight("-1px");
		label_16.setValue("Superficie total sembrada");
		absLSupSembrada.addComponent(label_16, "top:14.0px;left:10.0px;");
		
		// txtSupSembrada
		txtSupSembrada = new TextField();
		txtSupSembrada.setImmediate(false);
		txtSupSembrada.setWidth("100px");
		txtSupSembrada.setHeight("25px");
		absLSupSembrada
				.addComponent(txtSupSembrada, "top:10.0px;left:165.0px;");
		
		// label_17
		label_17 = new Label();
		label_17.setImmediate(false);
		label_17.setWidth("-1px");
		label_17.setHeight("-1px");
		label_17.setValue("ha");
		absLSupSembrada.addComponent(label_17, "top:14.0px;left:275.0px;");
		
		return absLSupSembrada;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLHecRiego() {
		// common part: create layout
		absLHecRiego = new AbsoluteLayout();
		absLHecRiego.setImmediate(false);
		absLHecRiego.setWidth("100.0%");
		absLHecRiego.setHeight("40px");
		
		// label_7
		label_7 = new Label();
		label_7.setImmediate(false);
		label_7.setWidth("-1px");
		label_7.setHeight("-1px");
		label_7.setValue("Hectáreas - riego");
		absLHecRiego.addComponent(label_7, "top:14.0px;left:10.0px;");
		
		// txtHecRiego
		txtHecRiego = new TextField();
		txtHecRiego.setImmediate(false);
		txtHecRiego.setWidth("100px");
		txtHecRiego.setHeight("25px");
		absLHecRiego.addComponent(txtHecRiego, "top:10.0px;left:165.0px;");
		
		// label_8
		label_8 = new Label();
		label_8.setImmediate(false);
		label_8.setWidth("-1px");
		label_8.setHeight("-1px");
		label_8.setValue("ha");
		absLHecRiego.addComponent(label_8, "top:14.0px;left:275.0px;");
		
		return absLHecRiego;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLVolAplicado() {
		// common part: create layout
		absLVolAplicado = new AbsoluteLayout();
		absLVolAplicado.setImmediate(false);
		absLVolAplicado.setWidth("100.0%");
		absLVolAplicado.setHeight("40px");
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Volumen total aplicado");
		absLVolAplicado.addComponent(label_3, "top:14.0px;left:10.0px;");
		
		// txtVolAplicado
		txtVolAplicado = new TextField();
		txtVolAplicado.setImmediate(false);
		txtVolAplicado.setWidth("100px");
		txtVolAplicado.setHeight("25px");
		absLVolAplicado
				.addComponent(txtVolAplicado, "top:10.0px;left:165.0px;");
		
		// label_9
		label_9 = new Label();
		label_9.setImmediate(false);
		label_9.setWidth("-1px");
		label_9.setHeight("-1px");
		label_9.setValue("Mm³");
		absLVolAplicado.addComponent(label_9, "top:14.0px;left:275.0px;");
		
		return absLVolAplicado;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLVolMedio() {
		// common part: create layout
		absLVolMedio = new AbsoluteLayout();
		absLVolMedio.setImmediate(false);
		absLVolMedio.setWidth("100.0%");
		absLVolMedio.setHeight("40px");
		
		// label_36
		label_36 = new Label();
		label_36.setImmediate(false);
		label_36.setWidth("-1px");
		label_36.setHeight("-1px");
		label_36.setValue("Volumen medio");
		absLVolMedio.addComponent(label_36, "top:14.0px;left:10.0px;");
		
		// txtVolMedio
		txtVolMedio = new TextField();
		txtVolMedio.setImmediate(false);
		txtVolMedio.setWidth("100px");
		txtVolMedio.setHeight("25px");
		absLVolMedio.addComponent(txtVolMedio, "top:10.0px;left:165.0px;");
		
		// label_37
		label_37 = new Label();
		label_37.setImmediate(false);
		label_37.setWidth("-1px");
		label_37.setHeight("-1px");
		label_37.setValue("m³");
		absLVolMedio.addComponent(label_37, "top:14.0px;left:275.0px;");
		
		return absLVolMedio;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLLamMedia() {
		// common part: create layout
		absLLamMedia = new AbsoluteLayout();
		absLLamMedia.setImmediate(false);
		absLLamMedia.setWidth("100.0%");
		absLLamMedia.setHeight("40px");
		
		// label_11
		label_11 = new Label();
		label_11.setImmediate(false);
		label_11.setWidth("-1px");
		label_11.setHeight("-1px");
		label_11.setValue("Lámina media");
		absLLamMedia.addComponent(label_11, "top:14.0px;left:10.0px;");
		
		// txtLamMedia
		txtLamMedia = new TextField();
		txtLamMedia.setImmediate(false);
		txtLamMedia.setWidth("100px");
		txtLamMedia.setHeight("25px");
		absLLamMedia.addComponent(txtLamMedia, "top:8.0px;left:165.0px;");
		
		// label_12
		label_12 = new Label();
		label_12.setImmediate(false);
		label_12.setWidth("-1px");
		label_12.setHeight("-1px");
		label_12.setValue("cm");
		absLLamMedia.addComponent(label_12, "top:14.0px;left:272.0px;");
		
		return absLLamMedia;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLRendMedio() {
		// common part: create layout
		absLRendMedio = new AbsoluteLayout();
		absLRendMedio.setImmediate(false);
		absLRendMedio.setWidth("100.0%");
		absLRendMedio.setHeight("40px");
		
		// label_13
		label_13 = new Label();
		label_13.setImmediate(false);
		label_13.setWidth("-1px");
		label_13.setHeight("-1px");
		label_13.setValue("Rendimiento medio");
		absLRendMedio.addComponent(label_13, "top:14.0px;left:10.0px;");
		
		// txtRendMedio
		txtRendMedio = new TextField();
		txtRendMedio.setImmediate(false);
		txtRendMedio.setWidth("100px");
		txtRendMedio.setHeight("25px");
		absLRendMedio.addComponent(txtRendMedio, "top:10.0px;left:165.0px;");
		
		// label_14
		label_14 = new Label();
		label_14.setImmediate(false);
		label_14.setWidth("-1px");
		label_14.setHeight("-1px");
		label_14.setValue("t/ha");
		absLRendMedio.addComponent(label_14, "top:14.0px;left:272.0px;");
		
		return absLRendMedio;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLProdTotal() {
		// common part: create layout
		absLProdTotal = new AbsoluteLayout();
		absLProdTotal.setImmediate(false);
		absLProdTotal.setWidth("100.0%");
		absLProdTotal.setHeight("40px");
		
		// label_15
		label_15 = new Label();
		label_15.setImmediate(false);
		label_15.setWidth("-1px");
		label_15.setHeight("-1px");
		label_15.setValue("Producción total");
		absLProdTotal.addComponent(label_15, "top:14.0px;left:10.0px;");
		
		// txtProdTotal
		txtProdTotal = new TextField();
		txtProdTotal.setImmediate(false);
		txtProdTotal.setWidth("100px");
		txtProdTotal.setHeight("25px");
		absLProdTotal.addComponent(txtProdTotal, "top:8.0px;left:165.0px;");
		
		// label_18
		label_18 = new Label();
		label_18.setImmediate(false);
		label_18.setWidth("-1px");
		label_18.setHeight("-1px");
		label_18.setValue("t");
		absLProdTotal.addComponent(label_18, "top:14.0px;left:272.0px;");
		
		return absLProdTotal;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLNumMedioRiegos() {
		// common part: create layout
		absLNumMedioRiegos = new AbsoluteLayout();
		absLNumMedioRiegos.setImmediate(false);
		absLNumMedioRiegos.setWidth("100.0%");
		absLNumMedioRiegos.setHeight("40px");
		
		// txtNumMedioRiegos
		txtNumMedioRiegos = new TextField();
		txtNumMedioRiegos.setImmediate(false);
		txtNumMedioRiegos.setWidth("100px");
		txtNumMedioRiegos.setHeight("25px");
		absLNumMedioRiegos.addComponent(txtNumMedioRiegos,
				"top:10.0px;left:165.0px;");
		
		// label_19
		label_19 = new Label();
		label_19.setImmediate(false);
		label_19.setWidth("-1px");
		label_19.setHeight("-1px");
		label_19.setValue("Núm. medio de riegos");
		absLNumMedioRiegos.addComponent(label_19, "top:14.0px;left:10.0px;");
		
		return absLNumMedioRiegos;
	}

	@AutoGenerated
	private Panel buildPanInfoIndicadores() {
		// common part: create layout
		panInfoIndicadores = new Panel();
		panInfoIndicadores
				.setCaption("* Los datos presentados corresponden al último ciclo agrícola (ciclo actual)");
		panInfoIndicadores.setImmediate(false);
		panInfoIndicadores.setWidth("610px");
		panInfoIndicadores.setHeight("-1px");
		
		// verLInfoIndicadores
		verLInfoIndicadores = buildVerLInfoIndicadores();
		panInfoIndicadores.setContent(verLInfoIndicadores);
		
		return panInfoIndicadores;
	}

	@AutoGenerated
	private VerticalLayout buildVerLInfoIndicadores() {
		// common part: create layout
		verLInfoIndicadores = new VerticalLayout();
		verLInfoIndicadores.setImmediate(false);
		verLInfoIndicadores.setWidth("100.0%");
		verLInfoIndicadores.setHeight("-1px");
		verLInfoIndicadores.setMargin(false);
		
		// absLIEA
		absLIEA = buildAbsLIEA();
		verLInfoIndicadores.addComponent(absLIEA);
		
		// absLAAP
		absLAAP = buildAbsLAAP();
		verLInfoIndicadores.addComponent(absLAAP);
		
		// absLIRP
		absLIRP = buildAbsLIRP();
		verLInfoIndicadores.addComponent(absLIRP);
		
		// absLSBP
		absLSBP = buildAbsLSBP();
		verLInfoIndicadores.addComponent(absLSBP);
		
		// absLABP
		absLABP = buildAbsLABP();
		verLInfoIndicadores.addComponent(absLABP);
		
		// absLSAT
		absLSAT = buildAbsLSAT();
		verLInfoIndicadores.addComponent(absLSAT);
		
		return verLInfoIndicadores;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLIEA() {
		// common part: create layout
		absLIEA = new AbsoluteLayout();
		absLIEA.setImmediate(false);
		absLIEA.setWidth("100.0%");
		absLIEA.setHeight("70px");
		
		// label_10
		label_10 = new Label();
		label_10.setImmediate(false);
		label_10.setWidth("-1px");
		label_10.setHeight("-1px");
		label_10.setValue("<b><u>Indicadores de Eficiencia</u></b>");
		absLIEA.addComponent(label_10, "top:14.0px;left:10.0px;");
		
		// label_20
		label_20 = new Label();
		label_20.setImmediate(false);
		label_20.setWidth("-1px");
		label_20.setHeight("-1px");
		label_20.setValue("Incremento de la Eficiencia de Aplicación (IEA)");
		absLIEA.addComponent(label_20, "top:44.0px;left:10.0px;");
		
		// txtIEA
		txtIEA = new TextField();
		txtIEA.setImmediate(false);
		txtIEA.setWidth("100px");
		txtIEA.setHeight("25px");
		absLIEA.addComponent(txtIEA, "top:40.0px;left:320.0px;");
		
		return absLIEA;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLAAP() {
		// common part: create layout
		absLAAP = new AbsoluteLayout();
		absLAAP.setImmediate(false);
		absLAAP.setWidth("100.0%");
		absLAAP.setHeight("40px");
		
		// label_21
		label_21 = new Label();
		label_21.setImmediate(false);
		label_21.setWidth("-1px");
		label_21.setHeight("-1px");
		label_21.setValue("Ahorro de Agua con el Proyecto (AAP)");
		absLAAP.addComponent(label_21, "top:14.0px;left:10.0px;");
		
		// txtAAP
		txtAAP = new TextField();
		txtAAP.setImmediate(false);
		txtAAP.setWidth("100px");
		txtAAP.setHeight("25px");
		absLAAP.addComponent(txtAAP, "top:10.0px;left:320.0px;");
		
		return absLAAP;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLIRP() {
		// common part: create layout
		absLIRP = new AbsoluteLayout();
		absLIRP.setImmediate(false);
		absLIRP.setWidth("100.0%");
		absLIRP.setHeight("200px");
		
		// label_29
		label_29 = new Label();
		label_29.setImmediate(false);
		label_29.setWidth("-1px");
		label_29.setHeight("-1px");
		label_29.setValue("<b><u>Indicadores de Rendimiento</u></b>");
		absLIRP.addComponent(label_29, "top:14.0px;left:10.0px;");
		
		// tblIRP
		tblIRP = new Table();
		tblIRP.setImmediate(false);
		tblIRP.setWidth("590px");
		tblIRP.setHeight("150px");
		absLIRP.addComponent(tblIRP, "top:44.0px;left:10.0px;");
		
		return absLIRP;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLSBP() {
		// common part: create layout
		absLSBP = new AbsoluteLayout();
		absLSBP.setImmediate(false);
		absLSBP.setWidth("100.0%");
		absLSBP.setHeight("70px");
		
		// label_28
		label_28 = new Label();
		label_28.setImmediate(false);
		label_28.setWidth("-1px");
		label_28.setHeight("-1px");
		label_28.setValue("<b><u>Indicadores de Cumplimiento</u></b>");
		absLSBP.addComponent(label_28, "top:14.0px;left:10.0px;");
		
		// label_23
		label_23 = new Label();
		label_23.setImmediate(false);
		label_23.setWidth("-1px");
		label_23.setHeight("-1px");
		label_23.setValue("Superficie Beneficiada con el Proyecto (SBP)");
		absLSBP.addComponent(label_23, "top:44.0px;left:10.0px;");
		
		// txtSBP
		txtSBP = new TextField();
		txtSBP.setImmediate(false);
		txtSBP.setWidth("100px");
		txtSBP.setHeight("25px");
		absLSBP.addComponent(txtSBP, "top:40.0px;left:320.0px;");
		
		return absLSBP;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLABP() {
		// common part: create layout
		absLABP = new AbsoluteLayout();
		absLABP.setImmediate(false);
		absLABP.setWidth("100.0%");
		absLABP.setHeight("40px");
		
		// label_24
		label_24 = new Label();
		label_24.setImmediate(false);
		label_24.setWidth("-1px");
		label_24.setHeight("-1px");
		label_24.setValue("ACUs Beneficiadas con el Proyecto (ABP)");
		absLABP.addComponent(label_24, "top:14.0px;left:10.0px;");
		
		// txtABP
		txtABP = new TextField();
		txtABP.setImmediate(false);
		txtABP.setWidth("100px");
		txtABP.setHeight("25px");
		absLABP.addComponent(txtABP, "top:10.0px;left:320.0px;");
		
		return absLABP;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLSAT() {
		// common part: create layout
		absLSAT = new AbsoluteLayout();
		absLSAT.setImmediate(false);
		absLSAT.setWidth("100.0%");
		absLSAT.setHeight("45px");
		
		// label_22
		label_22 = new Label();
		label_22.setImmediate(false);
		label_22.setWidth("-1px");
		label_22.setHeight("-1px");
		label_22.setValue("Superficie Atendida por los Técnicos de Campo (SAT)");
		absLSAT.addComponent(label_22, "top:14.0px;left:10.0px;");
		
		// txtSAT
		txtSAT = new TextField();
		txtSAT.setImmediate(false);
		txtSAT.setWidth("100px");
		txtSAT.setHeight("25px");
		absLSAT.addComponent(txtSAT, "top:10.0px;left:320.0px;");
		
		return absLSAT;
	}

	@AutoGenerated
	private HorizontalLayout buildHorLBotonesExportacion() {
		// common part: create layout
		horLBotonesExportacion = new HorizontalLayout();
		horLBotonesExportacion.setImmediate(false);
		horLBotonesExportacion.setWidth("100.0%");
		horLBotonesExportacion.setHeight("-1px");
		horLBotonesExportacion.setMargin(false);
		
		// horLExportacion
		horLExportacion = buildHorLExportacion();
		horLBotonesExportacion.addComponent(horLExportacion);
		
		// btnVerOtro
		btnVerOtro = new Button();
		btnVerOtro.setCaption("Ver Otro");
		btnVerOtro.setImmediate(true);
		btnVerOtro.setWidth("-1px");
		btnVerOtro.setHeight("-1px");
		horLBotonesExportacion.addComponent(btnVerOtro);
		horLBotonesExportacion.setComponentAlignment(btnVerOtro, new Alignment(
				34));
		
		return horLBotonesExportacion;
	}

	@AutoGenerated
	private HorizontalLayout buildHorLExportacion() {
		// common part: create layout
		horLExportacion = new HorizontalLayout();
		horLExportacion.setImmediate(false);
		horLExportacion.setWidth("-1px");
		horLExportacion.setHeight("-1px");
		horLExportacion.setMargin(false);
		horLExportacion.setSpacing(true);
		
		// optDescarga
		optDescarga = new OptionGroup();
		optDescarga.setImmediate(false);
		optDescarga.setWidth("-1px");
		optDescarga.setHeight("-1px");
		horLExportacion.addComponent(optDescarga);
		
		// btnExcel
		btnExcel = new Embedded();
		btnExcel.setImmediate(true);
		btnExcel.setDescription("Descargar en Excel");
		btnExcel.setWidth("-1px");
		btnExcel.setHeight("30px");
		btnExcel.setSource(new ThemeResource("img/excel.png"));
		btnExcel.setType(1);
		btnExcel.setMimeType("image/png");
		horLExportacion.addComponent(btnExcel);
		horLExportacion.setComponentAlignment(btnExcel, new Alignment(33));
		
		// btnWord
		btnWord = new Embedded();
		btnWord.setImmediate(true);
		btnWord.setDescription("Descargar en Word");
		btnWord.setWidth("-1px");
		btnWord.setHeight("30px");
		btnWord.setSource(new ThemeResource("img/word.png"));
		btnWord.setType(1);
		btnWord.setMimeType("image/png");
		horLExportacion.addComponent(btnWord);
		horLExportacion.setComponentAlignment(btnWord, new Alignment(33));
		
		// btnPDF
		btnPDF = new Embedded();
		btnPDF.setImmediate(true);
		btnPDF.setDescription("Descargar en PDF");
		btnPDF.setWidth("-1px");
		btnPDF.setHeight("30px");
		btnPDF.setSource(new ThemeResource("img/pdf.png"));
		btnPDF.setType(1);
		btnPDF.setMimeType("image/png");
		horLExportacion.addComponent(btnPDF);
		horLExportacion.setComponentAlignment(btnPDF, new Alignment(33));
		
		return horLExportacion;
	}
	
	//endregion
}