package com.saprigrat.ui.forms.pruebaderiego;

import org.joda.time.format.DateTimeFormat;
import org.vaadin.addons.tuningdatefield.TuningDateField;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class Caracteristicas extends CustomComponent
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel panCaracteristicas;
	@AutoGenerated
	private AbsoluteLayout absLCaracteristicas;
	@AutoGenerated
	private Label lblGastoSurco;
	@AutoGenerated
	private TextField txtGastoSurco;
	@AutoGenerated
	private TextField txtNoSurcos;
	@AutoGenerated
	private Label lblVolAplicado;
	@AutoGenerated
	private TextField txtVolAplicado;
	@AutoGenerated
	private Label lblGastoComp;
	@AutoGenerated
	private TextField txtHumIni;
	@AutoGenerated
	private TuningDateField datRiegoAnt;
	@AutoGenerated
	private ComboBox cmbEtapa;
	@AutoGenerated
	private TextField txtNoRiego;
	@AutoGenerated
	private Panel panAvance;
	@AutoGenerated
	private AbsoluteLayout absLAvance;
	@AutoGenerated
	private Table tblAvance;
	@AutoGenerated
	private Panel panGenerales;
	@AutoGenerated
	private AbsoluteLayout absLGenerales;
	@AutoGenerated
	private Label lblSupRegada;
	@AutoGenerated
	private TextField txtSupRegada;
	@AutoGenerated
	private TuningDateField datRiego;
	@AutoGenerated
	private ComboBox cmbTecnico;
	public Caracteristicas()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		tblAvance.addContainerProperty("Núm.", Integer.class, null);
		tblAvance.addContainerProperty("Distancia (m)", Float.class, null);
		tblAvance.addContainerProperty("Avance (tiempo)", String.class, null);
		tblAvance.addContainerProperty("Recesión (tiempo)", String.class, null);
		cmbTecnico.setInputPrompt("Escribir CURR o nombre");
		setCalendario(datRiego);
	}
	
	private void setCalendario(TuningDateField cal)
	{
		cal.setRequired(true);
		cal.setWeekendDisabled(false);
		cal.setDateTimeFormatter(DateTimeFormat.longDate());
		cal.setDateTextReadOnly(true);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// panGenerales
		panGenerales = buildPanGenerales();
		mainLayout.addComponent(panGenerales);
		
		// panAvance
		panAvance = buildPanAvance();
		mainLayout.addComponent(panAvance);
		
		// panCaracteristicas
		panCaracteristicas = buildPanCaracteristicas();
		mainLayout.addComponent(panCaracteristicas);
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanGenerales() {
		// common part: create layout
		panGenerales = new Panel();
		panGenerales.setImmediate(false);
		panGenerales.setWidth("501px");
		panGenerales.setHeight("-1px");
		
		// absLGenerales
		absLGenerales = buildAbsLGenerales();
		panGenerales.setContent(absLGenerales);
		
		return panGenerales;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLGenerales() {
		// common part: create layout
		absLGenerales = new AbsoluteLayout();
		absLGenerales.setImmediate(false);
		absLGenerales.setWidth("100.0%");
		absLGenerales.setHeight("110px");
		
		// cmbTecnico
		cmbTecnico = new ComboBox();
		cmbTecnico.setCaption("Supervisor Técnico");
		cmbTecnico.setImmediate(false);
		cmbTecnico.setWidth("480px");
		cmbTecnico.setHeight("25px");
		absLGenerales.addComponent(cmbTecnico, "top:28.0px;left:10.0px;");
		
		// datRiego
		datRiego = new TuningDateField();
		datRiego.setCaption("Fecha de Riego");
		datRiego.setImmediate(false);
		datRiego.setWidth("200px");
		datRiego.setHeight("25px");
		absLGenerales.addComponent(datRiego, "top:73.0px;left:10.0px;");
		
		// txtSupRegada
		txtSupRegada = new TextField();
		txtSupRegada.setCaption("Superficie Regada");
		txtSupRegada.setImmediate(false);
		txtSupRegada.setWidth("120px");
		txtSupRegada.setHeight("25px");
		absLGenerales.addComponent(txtSupRegada, "top:73.0px;left:230.0px;");
		
		// lblSupRegada
		lblSupRegada = new Label();
		lblSupRegada.setImmediate(false);
		lblSupRegada.setWidth("-1px");
		lblSupRegada.setHeight("-1px");
		lblSupRegada.setValue("ha");
		absLGenerales.addComponent(lblSupRegada, "top:77.0px;left:355.0px;");
		
		return absLGenerales;
	}

	@AutoGenerated
	private Panel buildPanAvance() {
		// common part: create layout
		panAvance = new Panel();
		panAvance.setCaption("Avance-Recesión");
		panAvance.setImmediate(false);
		panAvance.setWidth("501px");
		panAvance.setHeight("-1px");
		
		// absLAvance
		absLAvance = buildAbsLAvance();
		panAvance.setContent(absLAvance);
		
		return panAvance;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLAvance() {
		// common part: create layout
		absLAvance = new AbsoluteLayout();
		absLAvance.setImmediate(false);
		absLAvance.setWidth("100.0%");
		absLAvance.setHeight("241px");
		
		// tblAvance
		tblAvance = new Table();
		tblAvance.setImmediate(false);
		tblAvance.setWidth("480px");
		tblAvance.setHeight("221px");
		absLAvance.addComponent(tblAvance, "top:10.0px;left:10.0px;");
		
		return absLAvance;
	}

	@AutoGenerated
	private Panel buildPanCaracteristicas() {
		// common part: create layout
		panCaracteristicas = new Panel();
		panCaracteristicas.setImmediate(false);
		panCaracteristicas.setWidth("501px");
		panCaracteristicas.setHeight("-1px");
		
		// absLCaracteristicas
		absLCaracteristicas = buildAbsLCaracteristicas();
		panCaracteristicas.setContent(absLCaracteristicas);
		
		return panCaracteristicas;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCaracteristicas() {
		// common part: create layout
		absLCaracteristicas = new AbsoluteLayout();
		absLCaracteristicas.setImmediate(false);
		absLCaracteristicas.setWidth("100.0%");
		absLCaracteristicas.setHeight("361px");
		
		// txtNoRiego
		txtNoRiego = new TextField();
		txtNoRiego.setCaption("Núm. de Riego");
		txtNoRiego.setImmediate(false);
		txtNoRiego.setWidth("80px");
		txtNoRiego.setHeight("25px");
		absLCaracteristicas.addComponent(txtNoRiego, "top:28.0px;left:10.0px;");
		
		// cmbEtapa
		cmbEtapa = new ComboBox();
		cmbEtapa.setCaption("Etapa Fenológica");
		cmbEtapa.setImmediate(false);
		cmbEtapa.setWidth("180px");
		cmbEtapa.setHeight("25px");
		absLCaracteristicas.addComponent(cmbEtapa, "top:28.0px;left:110.0px;");
		
		// datRiegoAnt
		datRiegoAnt = new TuningDateField();
		datRiegoAnt.setCaption("Fecha del Riego Anterior");
		datRiegoAnt.setImmediate(false);
		datRiegoAnt.setWidth("180px");
		datRiegoAnt.setHeight("25px");
		absLCaracteristicas.addComponent(datRiegoAnt,
				"top:28.0px;left:310.0px;");
		
		// txtHumIni
		txtHumIni = new TextField();
		txtHumIni.setCaption("Cont. de Hum. Inicial");
		txtHumIni.setImmediate(false);
		txtHumIni.setWidth("120px");
		txtHumIni.setHeight("25px");
		absLCaracteristicas.addComponent(txtHumIni, "top:73.0px;left:10.0px;");
		
		// lblGastoComp
		lblGastoComp = new Label();
		lblGastoComp.setImmediate(false);
		lblGastoComp.setWidth("12px");
		lblGastoComp.setHeight("-1px");
		lblGastoComp.setValue("l/s");
		absLCaracteristicas.addComponent(lblGastoComp,
				"top:77.0px;left:135.0px;");
		
		// txtVolAplicado
		txtVolAplicado = new TextField();
		txtVolAplicado.setCaption("Volumen Total Aplicado");
		txtVolAplicado.setImmediate(false);
		txtVolAplicado.setWidth("130px");
		txtVolAplicado.setHeight("25px");
		absLCaracteristicas.addComponent(txtVolAplicado,
				"top:218.0px;left:11.0px;");
		
		// lblVolAplicado
		lblVolAplicado = new Label();
		lblVolAplicado.setImmediate(false);
		lblVolAplicado.setWidth("-1px");
		lblVolAplicado.setHeight("-1px");
		lblVolAplicado.setValue("m³");
		absLCaracteristicas.addComponent(lblVolAplicado,
				"top:222.0px;left:147.0px;");
		
		// txtNoSurcos
		txtNoSurcos = new TextField();
		txtNoSurcos.setCaption("Núm. de Surcos");
		txtNoSurcos.setImmediate(false);
		txtNoSurcos.setWidth("120px");
		txtNoSurcos.setHeight("25px");
		absLCaracteristicas.addComponent(txtNoSurcos,
				"top:263.0px;left:10.0px;");
		
		// txtGastoSurco
		txtGastoSurco = new TextField();
		txtGastoSurco.setCaption("Gasto Prom. por Surco o Melga");
		txtGastoSurco.setImmediate(false);
		txtGastoSurco.setWidth("150px");
		txtGastoSurco.setHeight("25px");
		absLCaracteristicas.addComponent(txtGastoSurco,
				"top:308.0px;left:10.0px;");
		
		// lblGastoSurco
		lblGastoSurco = new Label();
		lblGastoSurco.setImmediate(false);
		lblGastoSurco.setWidth("-1px");
		lblGastoSurco.setHeight("-1px");
		lblGastoSurco.setValue("l/s");
		absLCaracteristicas.addComponent(lblGastoSurco,
				"top:312.0px;left:161.0px;");
		
		return absLCaracteristicas;
	}
}