package com.saprigrat.ui.forms.parcelas;

import org.joda.time.format.DateTimeFormat;
import org.vaadin.addons.tuningdatefield.TuningDateField;

import com.saprigrat.ui.interfaces.Formulario;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class Parcela extends CustomComponent implements Formulario
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verLDatos;
	@AutoGenerated
	private Button btnAccion;
	@AutoGenerated
	private HorizontalLayout horLCultivo;
	@AutoGenerated
	private Panel panCultivoAnt;
	@AutoGenerated
	private AbsoluteLayout absLCultivoAnt;
	@AutoGenerated
	private TuningDateField datCosechaAnt;
	@AutoGenerated
	private TuningDateField datSiembraAnt;
	@AutoGenerated
	private Label lblRendimientoAnt;
	@AutoGenerated
	private TextField txtRendimientoAnt;
	@AutoGenerated
	private TextField txtCultivoAnt;
	@AutoGenerated
	private ComboBox cmbCicloAnt;
	@AutoGenerated
	private Panel panCultivoAct;
	@AutoGenerated
	private AbsoluteLayout absLCultivoAct;
	@AutoGenerated
	private TuningDateField datCosecha;
	@AutoGenerated
	private TuningDateField datSiembra;
	@AutoGenerated
	private Label lblRendimiento;
	@AutoGenerated
	private TextField txtRendimiento;
	@AutoGenerated
	private TextField txtCultivo;
	@AutoGenerated
	private ComboBox cmbCiclo;
	@AutoGenerated
	private Panel panCaracteristicas;
	@AutoGenerated
	private VerticalLayout verLCaracteristicas;
	@AutoGenerated
	private AbsoluteLayout absLCaracteristicas6;
	@AutoGenerated
	private Label lblPendiente;
	@AutoGenerated
	private TextField txtPendiente;
	@AutoGenerated
	private Label lblParamHF;
	@AutoGenerated
	private TextField txtParamHF;
	@AutoGenerated
	private Label lblAnchoTendido;
	@AutoGenerated
	private TextField txtAnchoTendido;
	@AutoGenerated
	private AbsoluteLayout absLCaracteristicas5;
	@AutoGenerated
	private Label lblLimo;
	@AutoGenerated
	private TextField txtLimo;
	@AutoGenerated
	private Label lblCondHidSat;
	@AutoGenerated
	private TextField txtCondHidSat;
	@AutoGenerated
	private Label lblAnchoSurco;
	@AutoGenerated
	private TextField txtAnchoSurco;
	@AutoGenerated
	private AbsoluteLayout absLCaracteristicas4;
	@AutoGenerated
	private Label lblArcilla;
	@AutoGenerated
	private TextField txtArcilla;
	@AutoGenerated
	private Label lblHumPMP;
	@AutoGenerated
	private TextField txtHumPMP;
	@AutoGenerated
	private Label lblSupRegada;
	@AutoGenerated
	private TextField txtSupRegada;
	@AutoGenerated
	private AbsoluteLayout absLCaracteristicas3;
	@AutoGenerated
	private Label lblArena;
	@AutoGenerated
	private TextField txtArena;
	@AutoGenerated
	private Label lblHumCC;
	@AutoGenerated
	private TextField txtHumCC;
	@AutoGenerated
	private Label lblAncho;
	@AutoGenerated
	private TextField txtAncho;
	@AutoGenerated
	private AbsoluteLayout absLCaracteristicas2;
	@AutoGenerated
	private Label lblDensidad;
	@AutoGenerated
	private TextField txtDensidad;
	@AutoGenerated
	private Label lblHumSat;
	@AutoGenerated
	private TextField txtHumSat;
	@AutoGenerated
	private Label lblLongitud;
	@AutoGenerated
	private TextField txtLongitud;
	@AutoGenerated
	private AbsoluteLayout absLCaracteristicas1;
	@AutoGenerated
	private Label lblRugosidad;
	@AutoGenerated
	private TextField txtRugosidad;
	@AutoGenerated
	private TextField txtTipoSuelo;
	@AutoGenerated
	private HorizontalLayout horLGralesNivelacionTrazo;
	@AutoGenerated
	private VerticalLayout verLNivelacionTrazo;
	@AutoGenerated
	private Panel panTrazo;
	@AutoGenerated
	private AbsoluteLayout absLTrazo;
	@AutoGenerated
	private CheckBox chkTrazo;
	@AutoGenerated
	private Panel panNivelacion;
	@AutoGenerated
	private VerticalLayout verLNivelacion;
	@AutoGenerated
	private AbsoluteLayout absLNivelacionNo;
	@AutoGenerated
	private CheckBox chkProyecto;
	@AutoGenerated
	private CheckBox chkRequiere;
	@AutoGenerated
	private AbsoluteLayout absLNivelacionSi;
	@AutoGenerated
	private TuningDateField datNivelacion;
	@AutoGenerated
	private AbsoluteLayout absLNivelacion;
	@AutoGenerated
	private CheckBox chkNivelada;
	@AutoGenerated
	private Panel panGenerales;
	@AutoGenerated
	private AbsoluteLayout absLGenerales;
	@AutoGenerated
	private ComboBox cmbLote;
	@AutoGenerated
	private TextField txtTecnico;
	@AutoGenerated
	private ComboBox cmbUsuario;
	public Parcela()
	{
		inicializar();
	}

	@Override
	public void inicializar()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		cmbUsuario.focus();
		txtTecnico.setEnabled(false);
		absLNivelacionSi.setVisible(false);
		chkProyecto.setVisible(false);
		setCalendario(datNivelacion, 4);
		setCalendario(datSiembra, 28);
		setCalendario(datCosecha, 29);
		setCalendario(datSiembraAnt, 33);
		setCalendario(datCosechaAnt, 34);
		
		chkNivelada.addValueChangeListener( new ValueChangeListener()
											{
												@Override
												public void valueChange(ValueChangeEvent event)
												{
													absLNivelacionSi.setVisible(chkNivelada.getValue());
												}
											});
		chkRequiere.addValueChangeListener( new ValueChangeListener()
											{
												@Override
												public void valueChange(ValueChangeEvent event)
												{
													chkProyecto.setVisible(chkRequiere.getValue());
												}
											});
		llenarListas();
	}
	
	private void llenarListas()
	{
		//Llenar la lista de ciclo de cultivo
		cmbCiclo.setNewItemsAllowed(false);
		cmbCiclo.addItem("Primavera-Verano");
		cmbCiclo.addItem("Otoño-Invierno");
		cmbCiclo.addItem("Perene");
		//Llenar la lista de ciclo anterior de cultivo
		cmbCicloAnt.setNewItemsAllowed(false);
		cmbCicloAnt.addItem("Primavera-Verano");
		cmbCicloAnt.addItem("Otoño-Invierno");
		cmbCicloAnt.addItem("Perene");
	}

	private void setCalendario(TuningDateField cal, int tabIndex)
	{
		cal.setWeekendDisabled(false);
		cal.setDateTimeFormatter(DateTimeFormat.longDate());
		cal.setDateTextReadOnly(true);
//		cal.setTabIndex(tabIndex);
	}

	@Override
	public void setTipo(int tipo)
	{
		if(tipo == 1)
		{
			btnAccion.setCaption("Agregar");
//			panCURR.setVisible(false);
			verLDatos.setVisible(true);
		}
		else
		{
			btnAccion.setCaption("Modificar");
//			panCURR.setVisible(true);
			verLDatos.setVisible(false);
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// verLDatos
		verLDatos = buildVerLDatos();
		mainLayout.addComponent(verLDatos);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerLDatos() {
		// common part: create layout
		verLDatos = new VerticalLayout();
		verLDatos.setImmediate(false);
		verLDatos.setWidth("-1px");
		verLDatos.setHeight("-1px");
		verLDatos.setMargin(false);
		verLDatos.setSpacing(true);
		
		// horLGralesNivelacionTrazo
		horLGralesNivelacionTrazo = buildHorLGralesNivelacionTrazo();
		verLDatos.addComponent(horLGralesNivelacionTrazo);
		
		// panCaracteristicas
		panCaracteristicas = buildPanCaracteristicas();
		verLDatos.addComponent(panCaracteristicas);
		
		// horLCultivo
		horLCultivo = buildHorLCultivo();
		verLDatos.addComponent(horLCultivo);
		
		// btnAccion
		btnAccion = new Button();
		btnAccion.setCaption("Button");
		btnAccion.setImmediate(true);
		btnAccion.setWidth("120px");
		btnAccion.setHeight("-1px");
		btnAccion.setTabIndex(35);
		verLDatos.addComponent(btnAccion);
		verLDatos.setComponentAlignment(btnAccion, new Alignment(34));
		
		return verLDatos;
	}

	@AutoGenerated
	private HorizontalLayout buildHorLGralesNivelacionTrazo() {
		// common part: create layout
		horLGralesNivelacionTrazo = new HorizontalLayout();
		horLGralesNivelacionTrazo.setImmediate(false);
		horLGralesNivelacionTrazo.setWidth("601px");
		horLGralesNivelacionTrazo.setHeight("-1px");
		horLGralesNivelacionTrazo.setMargin(false);
		
		// panGenerales
		panGenerales = buildPanGenerales();
		horLGralesNivelacionTrazo.addComponent(panGenerales);
		
		// verLNivelacionTrazo
		verLNivelacionTrazo = buildVerLNivelacionTrazo();
		horLGralesNivelacionTrazo.addComponent(verLNivelacionTrazo);
		horLGralesNivelacionTrazo.setComponentAlignment(verLNivelacionTrazo,
				new Alignment(6));
		
		return horLGralesNivelacionTrazo;
	}

	@AutoGenerated
	private Panel buildPanGenerales() {
		// common part: create layout
		panGenerales = new Panel();
		panGenerales.setCaption("Datos Generales");
		panGenerales.setImmediate(false);
		panGenerales.setWidth("301px");
		panGenerales.setHeight("-1px");
		
		// absLGenerales
		absLGenerales = buildAbsLGenerales();
		panGenerales.setContent(absLGenerales);
		
		return panGenerales;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLGenerales() {
		// common part: create layout
		absLGenerales = new AbsoluteLayout();
		absLGenerales.setImmediate(false);
		absLGenerales.setWidth("100.0%");
		absLGenerales.setHeight("155px");
		
		// cmbUsuario
		cmbUsuario = new ComboBox();
		cmbUsuario.setCaption("Usuario/Productor");
		cmbUsuario.setImmediate(false);
		cmbUsuario.setWidth("280px");
		cmbUsuario.setHeight("25px");
		cmbUsuario.setTabIndex(1);
		absLGenerales.addComponent(cmbUsuario, "top:28.0px;left:10.0px;");
		
		// txtTecnico
		txtTecnico = new TextField();
		txtTecnico.setCaption("Técnico");
		txtTecnico.setImmediate(false);
		txtTecnico.setWidth("280px");
		txtTecnico.setHeight("25px");
		absLGenerales.addComponent(txtTecnico, "top:73.0px;left:10.0px;");
		
		// cmbLote
		cmbLote = new ComboBox();
		cmbLote.setCaption("Lote");
		cmbLote.setImmediate(false);
		cmbLote.setWidth("280px");
		cmbLote.setHeight("25px");
		cmbLote.setTabIndex(2);
		absLGenerales.addComponent(cmbLote, "top:118.0px;left:10.0px;");
		
		return absLGenerales;
	}

	@AutoGenerated
	private VerticalLayout buildVerLNivelacionTrazo() {
		// common part: create layout
		verLNivelacionTrazo = new VerticalLayout();
		verLNivelacionTrazo.setImmediate(false);
		verLNivelacionTrazo.setWidth("-1px");
		verLNivelacionTrazo.setHeight("-1px");
		verLNivelacionTrazo.setMargin(false);
		verLNivelacionTrazo.setSpacing(true);
		
		// panNivelacion
		panNivelacion = buildPanNivelacion();
		verLNivelacionTrazo.addComponent(panNivelacion);
		
		// panTrazo
		panTrazo = buildPanTrazo();
		verLNivelacionTrazo.addComponent(panTrazo);
		
		return verLNivelacionTrazo;
	}

	@AutoGenerated
	private Panel buildPanNivelacion() {
		// common part: create layout
		panNivelacion = new Panel();
		panNivelacion.setCaption("Nivelación");
		panNivelacion.setImmediate(false);
		panNivelacion.setWidth("281px");
		panNivelacion.setHeight("-1px");
		
		// verLNivelacion
		verLNivelacion = buildVerLNivelacion();
		panNivelacion.setContent(verLNivelacion);
		
		return panNivelacion;
	}

	@AutoGenerated
	private VerticalLayout buildVerLNivelacion() {
		// common part: create layout
		verLNivelacion = new VerticalLayout();
		verLNivelacion.setImmediate(false);
		verLNivelacion.setWidth("100.0%");
		verLNivelacion.setHeight("-1px");
		verLNivelacion.setMargin(false);
		
		// absLNivelacion
		absLNivelacion = buildAbsLNivelacion();
		verLNivelacion.addComponent(absLNivelacion);
		
		// absLNivelacionSi
		absLNivelacionSi = buildAbsLNivelacionSi();
		verLNivelacion.addComponent(absLNivelacionSi);
		
		// absLNivelacionNo
		absLNivelacionNo = buildAbsLNivelacionNo();
		verLNivelacion.addComponent(absLNivelacionNo);
		
		return verLNivelacion;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLNivelacion() {
		// common part: create layout
		absLNivelacion = new AbsoluteLayout();
		absLNivelacion.setImmediate(false);
		absLNivelacion.setWidth("100.0%");
		absLNivelacion.setHeight("30px");
		
		// chkNivelada
		chkNivelada = new CheckBox();
		chkNivelada.setCaption("Ha sido nivelada");
		chkNivelada.setImmediate(false);
		chkNivelada.setWidth("-1px");
		chkNivelada.setHeight("-1px");
		chkNivelada.setTabIndex(3);
		absLNivelacion.addComponent(chkNivelada, "top:10.0px;left:10.0px;");
		
		return absLNivelacion;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLNivelacionSi() {
		// common part: create layout
		absLNivelacionSi = new AbsoluteLayout();
		absLNivelacionSi.setImmediate(false);
		absLNivelacionSi.setWidth("100.0%");
		absLNivelacionSi.setHeight("30px");
		
		// datNivelacion
		datNivelacion = new TuningDateField();
		datNivelacion.setImmediate(false);
		datNivelacion.setWidth("230px");
		datNivelacion.setHeight("25px");
		absLNivelacionSi.addComponent(datNivelacion, "top:3.0px;left:30.0px;");
		
		return absLNivelacionSi;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLNivelacionNo() {
		// common part: create layout
		absLNivelacionNo = new AbsoluteLayout();
		absLNivelacionNo.setImmediate(false);
		absLNivelacionNo.setWidth("100.0%");
		absLNivelacionNo.setHeight("30px");
		
		// chkRequiere
		chkRequiere = new CheckBox();
		chkRequiere.setCaption("Requiere nivelación");
		chkRequiere.setImmediate(false);
		chkRequiere.setWidth("-1px");
		chkRequiere.setHeight("-1px");
		chkRequiere.setTabIndex(5);
		absLNivelacionNo.addComponent(chkRequiere, "top:5.0px;left:10.0px;");
		
		// chkProyecto
		chkProyecto = new CheckBox();
		chkProyecto.setCaption("Tiene proyecto");
		chkProyecto.setImmediate(false);
		chkProyecto.setWidth("-1px");
		chkProyecto.setHeight("-1px");
		chkProyecto.setTabIndex(6);
		absLNivelacionNo.addComponent(chkProyecto, "top:5.0px;left:155.0px;");
		
		return absLNivelacionNo;
	}

	@AutoGenerated
	private Panel buildPanTrazo() {
		// common part: create layout
		panTrazo = new Panel();
		panTrazo.setCaption("Trazo de Riego");
		panTrazo.setImmediate(false);
		panTrazo.setWidth("160px");
		panTrazo.setHeight("-1px");
		
		// absLTrazo
		absLTrazo = buildAbsLTrazo();
		panTrazo.setContent(absLTrazo);
		
		return panTrazo;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLTrazo() {
		// common part: create layout
		absLTrazo = new AbsoluteLayout();
		absLTrazo.setImmediate(false);
		absLTrazo.setWidth("100.0%");
		absLTrazo.setHeight("35px");
		
		// chkTrazo
		chkTrazo = new CheckBox();
		chkTrazo.setCaption("Tiene trazo de riego");
		chkTrazo.setImmediate(false);
		chkTrazo.setWidth("-1px");
		chkTrazo.setHeight("-1px");
		chkTrazo.setTabIndex(7);
		absLTrazo.addComponent(chkTrazo, "top:8.0px;left:10.0px;");
		
		return absLTrazo;
	}

	@AutoGenerated
	private Panel buildPanCaracteristicas() {
		// common part: create layout
		panCaracteristicas = new Panel();
		panCaracteristicas.setCaption("Caracteristicas de la Parcela");
		panCaracteristicas.setImmediate(false);
		panCaracteristicas.setWidth("601px");
		panCaracteristicas.setHeight("-1px");
		
		// verLCaracteristicas
		verLCaracteristicas = buildVerLCaracteristicas();
		panCaracteristicas.setContent(verLCaracteristicas);
		
		return panCaracteristicas;
	}

	@AutoGenerated
	private VerticalLayout buildVerLCaracteristicas() {
		// common part: create layout
		verLCaracteristicas = new VerticalLayout();
		verLCaracteristicas.setImmediate(false);
		verLCaracteristicas.setWidth("100.0%");
		verLCaracteristicas.setHeight("-1px");
		verLCaracteristicas.setMargin(false);
		
		// absLCaracteristicas1
		absLCaracteristicas1 = buildAbsLCaracteristicas1();
		verLCaracteristicas.addComponent(absLCaracteristicas1);
		
		// absLCaracteristicas2
		absLCaracteristicas2 = buildAbsLCaracteristicas2();
		verLCaracteristicas.addComponent(absLCaracteristicas2);
		
		// absLCaracteristicas3
		absLCaracteristicas3 = buildAbsLCaracteristicas3();
		verLCaracteristicas.addComponent(absLCaracteristicas3);
		
		// absLCaracteristicas4
		absLCaracteristicas4 = buildAbsLCaracteristicas4();
		verLCaracteristicas.addComponent(absLCaracteristicas4);
		
		// absLCaracteristicas5
		absLCaracteristicas5 = buildAbsLCaracteristicas5();
		verLCaracteristicas.addComponent(absLCaracteristicas5);
		
		// absLCaracteristicas6
		absLCaracteristicas6 = buildAbsLCaracteristicas6();
		verLCaracteristicas.addComponent(absLCaracteristicas6);
		
		return verLCaracteristicas;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCaracteristicas1() {
		// common part: create layout
		absLCaracteristicas1 = new AbsoluteLayout();
		absLCaracteristicas1.setImmediate(false);
		absLCaracteristicas1.setWidth("100.0%");
		absLCaracteristicas1.setHeight("55px");
		
		// txtTipoSuelo
		txtTipoSuelo = new TextField();
		txtTipoSuelo.setCaption("Tipo de Suelo");
		txtTipoSuelo.setImmediate(false);
		txtTipoSuelo.setWidth("330px");
		txtTipoSuelo.setHeight("25px");
		txtTipoSuelo.setTabIndex(8);
		absLCaracteristicas1.addComponent(txtTipoSuelo,
				"top:28.0px;left:10.0px;");
		
		// txtRugosidad
		txtRugosidad = new TextField();
		txtRugosidad.setCaption("Rugosidad del Suelo");
		txtRugosidad.setImmediate(false);
		txtRugosidad.setWidth("145px");
		txtRugosidad.setHeight("25px");
		txtRugosidad.setTabIndex(19);
		absLCaracteristicas1.addComponent(txtRugosidad,
				"top:28.0px;left:410.0px;");
		
		// lblRugosidad
		lblRugosidad = new Label();
		lblRugosidad.setImmediate(false);
		lblRugosidad.setWidth("-1px");
		lblRugosidad.setHeight("-1px");
		lblRugosidad.setValue("adim");
		absLCaracteristicas1.addComponent(lblRugosidad,
				"top:32.0px;left:555.0px;");
		
		return absLCaracteristicas1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCaracteristicas2() {
		// common part: create layout
		absLCaracteristicas2 = new AbsoluteLayout();
		absLCaracteristicas2.setImmediate(false);
		absLCaracteristicas2.setWidth("100.0%");
		absLCaracteristicas2.setHeight("45px");
		
		// txtLongitud
		txtLongitud = new TextField();
		txtLongitud.setCaption("Longitud");
		txtLongitud.setImmediate(false);
		txtLongitud.setWidth("145px");
		txtLongitud.setHeight("25px");
		txtLongitud.setTabIndex(9);
		absLCaracteristicas2.addComponent(txtLongitud,
				"top:18.0px;left:10.0px;");
		
		// lblLongitud
		lblLongitud = new Label();
		lblLongitud.setImmediate(false);
		lblLongitud.setWidth("-1px");
		lblLongitud.setHeight("-1px");
		lblLongitud.setValue("m");
		absLCaracteristicas2.addComponent(lblLongitud,
				"top:22.0px;left:160.0px;");
		
		// txtHumSat
		txtHumSat = new TextField();
		txtHumSat.setCaption("Cont. de Hum. a Saturación");
		txtHumSat.setImmediate(false);
		txtHumSat.setWidth("145px");
		txtHumSat.setHeight("25px");
		txtHumSat.setTabIndex(14);
		absLCaracteristicas2
				.addComponent(txtHumSat, "top:18.0px;left:195.0px;");
		
		// lblHumSat
		lblHumSat = new Label();
		lblHumSat.setImmediate(false);
		lblHumSat.setWidth("-1px");
		lblHumSat.setHeight("-1px");
		lblHumSat.setValue("cm³/cm³");
		absLCaracteristicas2
				.addComponent(lblHumSat, "top:22.0px;left:345.0px;");
		
		// txtDensidad
		txtDensidad = new TextField();
		txtDensidad.setCaption("Densidad Aparente");
		txtDensidad.setImmediate(false);
		txtDensidad.setWidth("145px");
		txtDensidad.setHeight("25px");
		txtDensidad.setTabIndex(20);
		absLCaracteristicas2.addComponent(txtDensidad,
				"top:18.0px;left:410.0px;");
		
		// lblDensidad
		lblDensidad = new Label();
		lblDensidad.setImmediate(false);
		lblDensidad.setWidth("-1px");
		lblDensidad.setHeight("-1px");
		lblDensidad.setValue("m");
		absLCaracteristicas2.addComponent(lblDensidad,
				"top:22.0px;left:560.0px;");
		
		return absLCaracteristicas2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCaracteristicas3() {
		// common part: create layout
		absLCaracteristicas3 = new AbsoluteLayout();
		absLCaracteristicas3.setImmediate(false);
		absLCaracteristicas3.setWidth("100.0%");
		absLCaracteristicas3.setHeight("45px");
		
		// txtAncho
		txtAncho = new TextField();
		txtAncho.setCaption("Ancho");
		txtAncho.setImmediate(false);
		txtAncho.setWidth("145px");
		txtAncho.setHeight("25px");
		txtAncho.setTabIndex(10);
		absLCaracteristicas3.addComponent(txtAncho, "top:18.0px;left:10.0px;");
		
		// lblAncho
		lblAncho = new Label();
		lblAncho.setImmediate(false);
		lblAncho.setWidth("-1px");
		lblAncho.setHeight("-1px");
		lblAncho.setValue("m");
		absLCaracteristicas3.addComponent(lblAncho, "top:22.0px;left:160.0px;");
		
		// txtHumCC
		txtHumCC = new TextField();
		txtHumCC.setCaption("Cont. de Hum. CC");
		txtHumCC.setImmediate(false);
		txtHumCC.setWidth("145px");
		txtHumCC.setHeight("25px");
		txtHumCC.setTabIndex(15);
		absLCaracteristicas3.addComponent(txtHumCC, "top:18.0px;left:195.0px;");
		
		// lblHumCC
		lblHumCC = new Label();
		lblHumCC.setImmediate(false);
		lblHumCC.setWidth("-1px");
		lblHumCC.setHeight("-1px");
		lblHumCC.setValue("cm³/cm³");
		absLCaracteristicas3.addComponent(lblHumCC, "top:22.0px;left:345.0px;");
		
		// txtArena
		txtArena = new TextField();
		txtArena.setCaption("Arena");
		txtArena.setImmediate(false);
		txtArena.setWidth("145px");
		txtArena.setHeight("25px");
		txtArena.setTabIndex(21);
		absLCaracteristicas3.addComponent(txtArena, "top:18.0px;left:410.0px;");
		
		// lblArena
		lblArena = new Label();
		lblArena.setImmediate(false);
		lblArena.setWidth("-1px");
		lblArena.setHeight("-1px");
		lblArena.setValue("%");
		absLCaracteristicas3.addComponent(lblArena, "top:22.0px;left:560.0px;");
		
		return absLCaracteristicas3;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCaracteristicas4() {
		// common part: create layout
		absLCaracteristicas4 = new AbsoluteLayout();
		absLCaracteristicas4.setImmediate(false);
		absLCaracteristicas4.setWidth("100.0%");
		absLCaracteristicas4.setHeight("45px");
		
		// txtSupRegada
		txtSupRegada = new TextField();
		txtSupRegada.setCaption("Superficie Regada");
		txtSupRegada.setImmediate(false);
		txtSupRegada.setWidth("145px");
		txtSupRegada.setHeight("25px");
		txtSupRegada.setTabIndex(11);
		absLCaracteristicas4.addComponent(txtSupRegada,
				"top:18.0px;left:10.0px;");
		
		// lblSupRegada
		lblSupRegada = new Label();
		lblSupRegada.setImmediate(false);
		lblSupRegada.setWidth("-1px");
		lblSupRegada.setHeight("-1px");
		lblSupRegada.setValue("ha");
		absLCaracteristicas4.addComponent(lblSupRegada,
				"top:22.0px;left:160.0px;");
		
		// txtHumPMP
		txtHumPMP = new TextField();
		txtHumPMP.setCaption("Cont. de Hum. a PMP");
		txtHumPMP.setImmediate(false);
		txtHumPMP.setWidth("145px");
		txtHumPMP.setHeight("25px");
		txtHumPMP.setTabIndex(16);
		absLCaracteristicas4
				.addComponent(txtHumPMP, "top:18.0px;left:195.0px;");
		
		// lblHumPMP
		lblHumPMP = new Label();
		lblHumPMP.setImmediate(false);
		lblHumPMP.setWidth("-1px");
		lblHumPMP.setHeight("-1px");
		lblHumPMP.setValue("cm³/cm³");
		absLCaracteristicas4
				.addComponent(lblHumPMP, "top:22.0px;left:345.0px;");
		
		// txtArcilla
		txtArcilla = new TextField();
		txtArcilla.setCaption("Arcilla");
		txtArcilla.setImmediate(false);
		txtArcilla.setWidth("145px");
		txtArcilla.setHeight("25px");
		txtArcilla.setTabIndex(22);
		absLCaracteristicas4.addComponent(txtArcilla,
				"top:18.0px;left:410.0px;");
		
		// lblArcilla
		lblArcilla = new Label();
		lblArcilla.setImmediate(false);
		lblArcilla.setWidth("-1px");
		lblArcilla.setHeight("-1px");
		lblArcilla.setValue("%");
		absLCaracteristicas4.addComponent(lblArcilla,
				"top:22.0px;left:560.0px;");
		
		return absLCaracteristicas4;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCaracteristicas5() {
		// common part: create layout
		absLCaracteristicas5 = new AbsoluteLayout();
		absLCaracteristicas5.setImmediate(false);
		absLCaracteristicas5.setWidth("100.0%");
		absLCaracteristicas5.setHeight("45px");
		
		// txtAnchoSurco
		txtAnchoSurco = new TextField();
		txtAnchoSurco.setCaption("Ancho del Surco");
		txtAnchoSurco.setImmediate(false);
		txtAnchoSurco.setWidth("145px");
		txtAnchoSurco.setHeight("25px");
		txtAnchoSurco.setTabIndex(12);
		absLCaracteristicas5.addComponent(txtAnchoSurco,
				"top:18.0px;left:10.0px;");
		
		// lblAnchoSurco
		lblAnchoSurco = new Label();
		lblAnchoSurco.setImmediate(false);
		lblAnchoSurco.setWidth("-1px");
		lblAnchoSurco.setHeight("-1px");
		lblAnchoSurco.setValue("m");
		absLCaracteristicas5.addComponent(lblAnchoSurco,
				"top:22.0px;left:160.0px;");
		
		// txtCondHidSat
		txtCondHidSat = new TextField();
		txtCondHidSat.setCaption("Cond. Hidráulica a Saturación");
		txtCondHidSat.setImmediate(false);
		txtCondHidSat.setWidth("145px");
		txtCondHidSat.setHeight("25px");
		txtCondHidSat.setTabIndex(17);
		absLCaracteristicas5.addComponent(txtCondHidSat,
				"top:18.0px;left:195.0px;");
		
		// lblCondHidSat
		lblCondHidSat = new Label();
		lblCondHidSat.setImmediate(false);
		lblCondHidSat.setWidth("-1px");
		lblCondHidSat.setHeight("-1px");
		lblCondHidSat.setValue("cm/h");
		absLCaracteristicas5.addComponent(lblCondHidSat,
				"top:22.0px;left:345.0px;");
		
		// txtLimo
		txtLimo = new TextField();
		txtLimo.setCaption("Limo");
		txtLimo.setImmediate(false);
		txtLimo.setWidth("145px");
		txtLimo.setHeight("25px");
		txtLimo.setTabIndex(23);
		absLCaracteristicas5.addComponent(txtLimo, "top:18.0px;left:410.0px;");
		
		// lblLimo
		lblLimo = new Label();
		lblLimo.setImmediate(false);
		lblLimo.setWidth("-1px");
		lblLimo.setHeight("-1px");
		lblLimo.setValue("%");
		absLCaracteristicas5.addComponent(lblLimo, "top:22.0px;left:560.0px;");
		
		return absLCaracteristicas5;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCaracteristicas6() {
		// common part: create layout
		absLCaracteristicas6 = new AbsoluteLayout();
		absLCaracteristicas6.setImmediate(false);
		absLCaracteristicas6.setWidth("100.0%");
		absLCaracteristicas6.setHeight("55px");
		
		// txtAnchoTendido
		txtAnchoTendido = new TextField();
		txtAnchoTendido.setCaption("Ancho del Tendido");
		txtAnchoTendido.setImmediate(false);
		txtAnchoTendido.setWidth("145px");
		txtAnchoTendido.setHeight("25px");
		txtAnchoTendido.setTabIndex(13);
		absLCaracteristicas6.addComponent(txtAnchoTendido,
				"top:18.0px;left:10.0px;");
		
		// lblAnchoTendido
		lblAnchoTendido = new Label();
		lblAnchoTendido.setImmediate(false);
		lblAnchoTendido.setWidth("-1px");
		lblAnchoTendido.setHeight("-1px");
		lblAnchoTendido.setValue("m");
		absLCaracteristicas6.addComponent(lblAnchoTendido,
				"top:22.0px;left:160.0px;");
		
		// txtParamHF
		txtParamHF = new TextField();
		txtParamHF.setCaption("Parámetro HF");
		txtParamHF.setImmediate(false);
		txtParamHF.setWidth("145px");
		txtParamHF.setHeight("25px");
		txtParamHF.setTabIndex(18);
		absLCaracteristicas6.addComponent(txtParamHF,
				"top:18.0px;left:195.0px;");
		
		// lblParamHF
		lblParamHF = new Label();
		lblParamHF.setImmediate(false);
		lblParamHF.setWidth("-1px");
		lblParamHF.setHeight("-1px");
		lblParamHF.setValue("cm");
		absLCaracteristicas6.addComponent(lblParamHF,
				"top:22.0px;left:345.0px;");
		
		// txtPendiente
		txtPendiente = new TextField();
		txtPendiente.setCaption("Pendiente");
		txtPendiente.setImmediate(false);
		txtPendiente.setWidth("145px");
		txtPendiente.setHeight("25px");
		txtPendiente.setTabIndex(24);
		absLCaracteristicas6.addComponent(txtPendiente,
				"top:18.0px;left:410.0px;");
		
		// lblPendiente
		lblPendiente = new Label();
		lblPendiente.setImmediate(false);
		lblPendiente.setWidth("-1px");
		lblPendiente.setHeight("-1px");
		lblPendiente.setValue("%");
		absLCaracteristicas6.addComponent(lblPendiente,
				"top:22.0px;left:560.0px;");
		
		return absLCaracteristicas6;
	}

	@AutoGenerated
	private HorizontalLayout buildHorLCultivo() {
		// common part: create layout
		horLCultivo = new HorizontalLayout();
		horLCultivo.setImmediate(false);
		horLCultivo.setWidth("601px");
		horLCultivo.setHeight("-1px");
		horLCultivo.setMargin(false);
		
		// panCultivoAct
		panCultivoAct = buildPanCultivoAct();
		horLCultivo.addComponent(panCultivoAct);
		
		// panCultivoAnt
		panCultivoAnt = buildPanCultivoAnt();
		horLCultivo.addComponent(panCultivoAnt);
		horLCultivo.setComponentAlignment(panCultivoAnt, new Alignment(6));
		
		return horLCultivo;
	}

	@AutoGenerated
	private Panel buildPanCultivoAct() {
		// common part: create layout
		panCultivoAct = new Panel();
		panCultivoAct.setCaption("Cultivo Actual");
		panCultivoAct.setImmediate(false);
		panCultivoAct.setWidth("281px");
		panCultivoAct.setHeight("-1px");
		
		// absLCultivoAct
		absLCultivoAct = buildAbsLCultivoAct();
		panCultivoAct.setContent(absLCultivoAct);
		
		return panCultivoAct;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCultivoAct() {
		// common part: create layout
		absLCultivoAct = new AbsoluteLayout();
		absLCultivoAct.setImmediate(false);
		absLCultivoAct.setWidth("100.0%");
		absLCultivoAct.setHeight("245px");
		
		// cmbCiclo
		cmbCiclo = new ComboBox();
		cmbCiclo.setCaption("Ciclo");
		cmbCiclo.setImmediate(false);
		cmbCiclo.setWidth("260px");
		cmbCiclo.setHeight("25px");
		cmbCiclo.setTabIndex(25);
		absLCultivoAct.addComponent(cmbCiclo, "top:28.0px;left:10.0px;");
		
		// txtCultivo
		txtCultivo = new TextField();
		txtCultivo.setCaption("Cultivo");
		txtCultivo.setImmediate(false);
		txtCultivo.setWidth("260px");
		txtCultivo.setHeight("25px");
		txtCultivo.setTabIndex(26);
		absLCultivoAct.addComponent(txtCultivo, "top:73.0px;left:10.0px;");
		
		// txtRendimiento
		txtRendimiento = new TextField();
		txtRendimiento.setCaption("Rendimiento");
		txtRendimiento.setImmediate(false);
		txtRendimiento.setWidth("160px");
		txtRendimiento.setHeight("25px");
		txtRendimiento.setTabIndex(27);
		absLCultivoAct.addComponent(txtRendimiento, "top:118.0px;left:10.0px;");
		
		// lblRendimiento
		lblRendimiento = new Label();
		lblRendimiento.setImmediate(false);
		lblRendimiento.setWidth("-1px");
		lblRendimiento.setHeight("-1px");
		lblRendimiento.setValue("ton/ha");
		absLCultivoAct
				.addComponent(lblRendimiento, "top:122.0px;left:175.0px;");
		
		// datSiembra
		datSiembra = new TuningDateField();
		datSiembra.setCaption("Fecha de Siembra");
		datSiembra.setImmediate(false);
		datSiembra.setWidth("200px");
		datSiembra.setHeight("25px");
		absLCultivoAct.addComponent(datSiembra, "top:163.0px;left:10.0px;");
		
		// datCosecha
		datCosecha = new TuningDateField();
		datCosecha.setCaption("Fecha de Cosecha");
		datCosecha.setImmediate(false);
		datCosecha.setWidth("200px");
		datCosecha.setHeight("25px");
		absLCultivoAct.addComponent(datCosecha, "top:208.0px;left:10.0px;");
		
		return absLCultivoAct;
	}

	@AutoGenerated
	private Panel buildPanCultivoAnt() {
		// common part: create layout
		panCultivoAnt = new Panel();
		panCultivoAnt.setCaption("Cultivo Anterior");
		panCultivoAnt.setImmediate(false);
		panCultivoAnt.setWidth("281px");
		panCultivoAnt.setHeight("-1px");
		
		// absLCultivoAnt
		absLCultivoAnt = buildAbsLCultivoAnt();
		panCultivoAnt.setContent(absLCultivoAnt);
		
		return panCultivoAnt;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLCultivoAnt() {
		// common part: create layout
		absLCultivoAnt = new AbsoluteLayout();
		absLCultivoAnt.setImmediate(false);
		absLCultivoAnt.setWidth("100.0%");
		absLCultivoAnt.setHeight("245px");
		
		// cmbCicloAnt
		cmbCicloAnt = new ComboBox();
		cmbCicloAnt.setCaption("Ciclo");
		cmbCicloAnt.setImmediate(false);
		cmbCicloAnt.setWidth("260px");
		cmbCicloAnt.setHeight("25px");
		cmbCicloAnt.setTabIndex(30);
		absLCultivoAnt.addComponent(cmbCicloAnt, "top:28.0px;left:10.0px;");
		
		// txtCultivoAnt
		txtCultivoAnt = new TextField();
		txtCultivoAnt.setCaption("Cultivo");
		txtCultivoAnt.setImmediate(false);
		txtCultivoAnt.setWidth("260px");
		txtCultivoAnt.setHeight("25px");
		txtCultivoAnt.setTabIndex(31);
		absLCultivoAnt.addComponent(txtCultivoAnt, "top:73.0px;left:10.0px;");
		
		// txtRendimientoAnt
		txtRendimientoAnt = new TextField();
		txtRendimientoAnt.setCaption("Rendimiento");
		txtRendimientoAnt.setImmediate(false);
		txtRendimientoAnt.setWidth("160px");
		txtRendimientoAnt.setHeight("25px");
		txtRendimientoAnt.setTabIndex(32);
		absLCultivoAnt.addComponent(txtRendimientoAnt,
				"top:118.0px;left:10.0px;");
		
		// lblRendimientoAnt
		lblRendimientoAnt = new Label();
		lblRendimientoAnt.setImmediate(false);
		lblRendimientoAnt.setWidth("-1px");
		lblRendimientoAnt.setHeight("-1px");
		lblRendimientoAnt.setValue("ton/ha");
		absLCultivoAnt.addComponent(lblRendimientoAnt,
				"top:122.0px;left:175.0px;");
		
		// datSiembraAnt
		datSiembraAnt = new TuningDateField();
		datSiembraAnt.setCaption("Fecha de Siembra");
		datSiembraAnt.setImmediate(false);
		datSiembraAnt.setWidth("200px");
		datSiembraAnt.setHeight("25px");
		absLCultivoAnt.addComponent(datSiembraAnt, "top:163.0px;left:10.0px;");
		
		// datCosechaAnt
		datCosechaAnt = new TuningDateField();
		datCosechaAnt.setCaption("Fecha de Cosecha");
		datCosechaAnt.setImmediate(false);
		datCosechaAnt.setWidth("200px");
		datCosechaAnt.setHeight("25px");
		absLCultivoAnt.addComponent(datCosechaAnt, "top:208.0px;left:10.0px;");
		
		return absLCultivoAnt;
	}
}