package com.saprigrat.ui.forms.parcelas;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.LinkedList;

import com.saprigrat.data.Datos;
import com.saprigrat.data.Usuario;
import com.saprigrat.ui.interfaces.Formulario;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.event.ItemClickEvent.ItemClickListener;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class Riego extends CustomComponent implements Formulario
{
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verLDatos;
	@AutoGenerated
	private AbsoluteLayout absLBotones;
	@AutoGenerated
	private Button btnNuevo;
	@AutoGenerated
	private Button btnAccion;
	@AutoGenerated
	private Table tblRiegos;
	@AutoGenerated
	private HorizontalLayout horLParcelaAdd;
	@AutoGenerated
	private Button btnAdd;
	@AutoGenerated
	private Panel panRiego;
	@AutoGenerated
	private VerticalLayout verLRiego;
	@AutoGenerated
	private AbsoluteLayout absLRiego3;
	@AutoGenerated
	private Label lblEficiencia;
	@AutoGenerated
	private TextField txtEficiencia;
	@AutoGenerated
	private Label lblSuperficie;
	@AutoGenerated
	private TextField txtSuperficie;
	@AutoGenerated
	private DateField datFin;
	@AutoGenerated
	private AbsoluteLayout absLRiego2;
	@AutoGenerated
	private Label lblLaminaCalc;
	@AutoGenerated
	private TextField txtLaminaCalc;
	@AutoGenerated
	private Label lblGasto;
	@AutoGenerated
	private TextField txtGasto;
	@AutoGenerated
	private DateField datInicio;
	@AutoGenerated
	private AbsoluteLayout absLRiego1;
	@AutoGenerated
	private ComboBox cmbEtapa;
	@AutoGenerated
	private Panel panDetalles;
	@AutoGenerated
	private AbsoluteLayout absLDetalles;
	@AutoGenerated
	private Label lblLaminaAnt;
	@AutoGenerated
	private TextField txtLaminaAnt;
	@AutoGenerated
	private ComboBox cmbTipoRiego;
	@AutoGenerated
	private ComboBox cmbParcela;
	private Usuario usuario;
	private Datos datos;
	private String formatoFecha;
	
	private ClickListener showPanelListener =   new ClickListener()
												{
													@Override
													public void buttonClick(ClickEvent event)
													{
														cmbEtapa.focus();
														txtGasto.setValue("0");
														txtSuperficie.setValue("0");
														txtLaminaCalc.setValue("0");
														txtEficiencia.setValue("0");
														panRiego.setVisible(true);
														btnAdd.removeClickListener(showPanelListener);
														btnAdd.addClickListener(addRowListener);
													}
												};
	private ClickListener addRowListener =  new ClickListener()
											{
												@Override
												public void buttonClick(ClickEvent event)
												{
													tblRiegos.addItem(getRow(), null);
													panRiego.setVisible(false);
													btnAdd.removeClickListener(addRowListener);
													btnAdd.addClickListener(showPanelListener);
												}
												
												private Object[] getRow()
												{
													double gasto = Double.parseDouble(txtGasto.getValue());
													int tiempo = (int)((datFin.getValue().getTime() - datInicio.getValue().getTime()) / 3600000);
													double volumen = gasto * tiempo * 3600000; //Gasto[L/s]*3600:[L/h] -> Gasto[L/h]*Tiempo[h]:[L] -> [L]*1000 = Volumen[m³]
													double superficie = Double.parseDouble(txtSuperficie.getValue());
													double laminaApl = volumen / superficie * 1000000; //Superficie[ha]*10000:[m2] -> Volumen[m³]/Superficie[m2]:[m] -> [m]*100 = LaminaApl[cm]
													
													Object[] row = new Object[9];
													row[0] = new SimpleDateFormat(formatoFecha).format(datInicio.getValue());
													row[1] = cmbEtapa.getValue();
													row[2] = gasto;
													row[3] = tiempo;
													row[4] = volumen;
													row[5] = superficie;
													row[6] = laminaApl;
													row[7] = Double.parseDouble(txtLaminaCalc.getValue());
													row[8] = txtEficiencia.getValue();
													
													return row;
												}
											};
	private ClickListener agregarListener = new ClickListener()
											{
												@Override
												public void buttonClick(ClickEvent event)
												{
													if(validar())
													{
														
													}
												}
												
												private Date getFecha(DateField calendario)
												{
													if(calendario.getValue() == null)
														return null;
													else
														return new Date(calendario.getValue().getTime());
												}
											};
	private ClickListener modificarListener =   new ClickListener()
												{
													@Override
													public void buttonClick(ClickEvent event)
													{
														if(validar())
														{
															
														}
													}
												};
	
	public Riego(Usuario user)
	{
		formatoFecha = "dd/MM/yyyy, hh:mm a";
		usuario = user;
		inicializar();
	}

	@Override
	public void inicializar()
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		datos = new Datos();

		cmbParcela.focus();
		
		setCalendario(datInicio);
		setCalendario(datFin);
		panRiego.setVisible(false);
		btnAdd.addClickListener(showPanelListener);
		//Crear los encabezados de la tabla
		tblRiegos.setRowHeaderMode(Table.RowHeaderMode.INDEX);
//		tblRiegos.addContainerProperty("Núm. de Riego", Object.class, null);
		tblRiegos.addContainerProperty("Fecha", Object.class, null);
		tblRiegos.addContainerProperty("Etapa Fenológica", Object.class, null);
		tblRiegos.addContainerProperty("Gasto (L/s)", Object.class, null);
		tblRiegos.addContainerProperty("Tiempo (h)", Object.class, null);
		tblRiegos.addContainerProperty("Volúmen (m³)", Object.class, null);
		tblRiegos.addContainerProperty("Superficie Regada (ha)", Object.class, null);
		tblRiegos.addContainerProperty("Lámina Aplicada (cm)", Object.class, null);
		tblRiegos.addContainerProperty("Lámina Calculada (cm)", Object.class, null);
		tblRiegos.addContainerProperty("Eficiencia", Object.class, null);
		//Ocultar boton de reseteo
		btnNuevo.setVisible(false);
		//Agregar las validaciones necesarias
		setValidaciones();
	}

	@Override
	public void setTipo(int modoOperacion)
	{
		if(modoOperacion == MODO_AGREGAR)
		{
			btnAccion.addClickListener(agregarListener);
		}
		else
		{
			if(modoOperacion == MODO_MODIFICAR)
			{
				tblRiegos.addItemClickListener(new ItemClickListener()
												{
													@Override
													public void itemClick(ItemClickEvent event)
													{
														if(event.isDoubleClick())
														{
															String curr = tblRiegos.getItemCaption(event.getItem()).split(" ")[0];
															LinkedList<Object> valores = datos.getProductor(curr);
															if(!valores.isEmpty())
															{
																
															}
															else
																Notification.show("Error al obtener el registro, comuníquese con el administrador.", Notification.Type.ERROR_MESSAGE);
														}
													}
												});
				btnAccion.setCaption("Modificar");
				btnAccion.addClickListener(modificarListener);
			}
		}
	}

	private void setCalendario(DateField cal)
	{
		cal.setResolution(Resolution.MINUTE);
		cal.setValue(new java.util.Date());
		cal.setDateFormat(formatoFecha);
	}

	private void setValidaciones()
	{
	}
	
	private boolean validar()
	{
		return true;
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// verLDatos
		verLDatos = buildVerLDatos();
		mainLayout.addComponent(verLDatos);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerLDatos() {
		// common part: create layout
		verLDatos = new VerticalLayout();
		verLDatos.setImmediate(false);
		verLDatos.setWidth("-1px");
		verLDatos.setHeight("-1px");
		verLDatos.setMargin(false);
		verLDatos.setSpacing(true);
		
		// panDetalles
		panDetalles = buildPanDetalles();
		verLDatos.addComponent(panDetalles);
		
		// horLParcelaAdd
		horLParcelaAdd = buildHorLParcelaAdd();
		verLDatos.addComponent(horLParcelaAdd);
		
		// tblRiegos
		tblRiegos = new Table();
		tblRiegos.setImmediate(false);
		tblRiegos.setWidth("601px");
		tblRiegos.setHeight("100.0%");
		verLDatos.addComponent(tblRiegos);
		
		// absLBotones
		absLBotones = buildAbsLBotones();
		verLDatos.addComponent(absLBotones);
		verLDatos.setComponentAlignment(absLBotones, new Alignment(10));
		
		return verLDatos;
	}

	@AutoGenerated
	private Panel buildPanDetalles() {
		// common part: create layout
		panDetalles = new Panel();
		panDetalles.setCaption("Detalles del Riego");
		panDetalles.setImmediate(false);
		panDetalles.setWidth("601px");
		panDetalles.setHeight("-1px");
		
		// absLDetalles
		absLDetalles = buildAbsLDetalles();
		panDetalles.setContent(absLDetalles);
		
		return panDetalles;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLDetalles() {
		// common part: create layout
		absLDetalles = new AbsoluteLayout();
		absLDetalles.setImmediate(false);
		absLDetalles.setWidth("100.0%");
		absLDetalles.setHeight("65px");
		
		// cmbParcela
		cmbParcela = new ComboBox();
		cmbParcela.setCaption("Parcela");
		cmbParcela.setImmediate(true);
		cmbParcela.setWidth("220px");
		cmbParcela.setHeight("25px");
		cmbParcela.setTabIndex(1);
		absLDetalles.addComponent(cmbParcela, "top:28.0px;left:10.0px;");
		
		// cmbTipoRiego
		cmbTipoRiego = new ComboBox();
		cmbTipoRiego.setCaption("Tipo de Riego");
		cmbTipoRiego.setImmediate(false);
		cmbTipoRiego.setWidth("180px");
		cmbTipoRiego.setHeight("25px");
		cmbTipoRiego.setTabIndex(2);
		absLDetalles.addComponent(cmbTipoRiego, "top:28.0px;left:250.0px;");
		
		// txtLaminaAnt
		txtLaminaAnt = new TextField();
		txtLaminaAnt.setCaption("Lamina del Ciclo Anterior");
		txtLaminaAnt.setImmediate(false);
		txtLaminaAnt.setWidth("120px");
		txtLaminaAnt.setHeight("25px");
		txtLaminaAnt.setInvalidAllowed(false);
		txtLaminaAnt.setTabIndex(3);
		absLDetalles.addComponent(txtLaminaAnt, "top:28.0px;left:450.0px;");
		
		// lblLaminaAnt
		lblLaminaAnt = new Label();
		lblLaminaAnt.setImmediate(false);
		lblLaminaAnt.setWidth("-1px");
		lblLaminaAnt.setHeight("-1px");
		lblLaminaAnt.setValue("ha");
		absLDetalles.addComponent(lblLaminaAnt, "top:32.0px;left:575.0px;");
		
		return absLDetalles;
	}

	@AutoGenerated
	private HorizontalLayout buildHorLParcelaAdd() {
		// common part: create layout
		horLParcelaAdd = new HorizontalLayout();
		horLParcelaAdd.setImmediate(false);
		horLParcelaAdd.setWidth("601px");
		horLParcelaAdd.setHeight("-1px");
		horLParcelaAdd.setMargin(false);
		
		// panRiego
		panRiego = buildPanRiego();
		horLParcelaAdd.addComponent(panRiego);
		
		// btnAdd
		btnAdd = new Button();
		btnAdd.setCaption("+");
		btnAdd.setImmediate(true);
		btnAdd.setWidth("-1px");
		btnAdd.setHeight("-1px");
		btnAdd.setTabIndex(11);
		horLParcelaAdd.addComponent(btnAdd);
		horLParcelaAdd.setComponentAlignment(btnAdd, new Alignment(6));
		
		return horLParcelaAdd;
	}

	@AutoGenerated
	private Panel buildPanRiego() {
		// common part: create layout
		panRiego = new Panel();
		panRiego.setImmediate(false);
		panRiego.setWidth("551px");
		panRiego.setHeight("-1px");
		
		// verLRiego
		verLRiego = buildVerLRiego();
		panRiego.setContent(verLRiego);
		
		return panRiego;
	}

	@AutoGenerated
	private VerticalLayout buildVerLRiego() {
		// common part: create layout
		verLRiego = new VerticalLayout();
		verLRiego.setImmediate(false);
		verLRiego.setWidth("100.0%");
		verLRiego.setHeight("-1px");
		verLRiego.setMargin(false);
		
		// absLRiego1
		absLRiego1 = buildAbsLRiego1();
		verLRiego.addComponent(absLRiego1);
		
		// absLRiego2
		absLRiego2 = buildAbsLRiego2();
		verLRiego.addComponent(absLRiego2);
		
		// absLRiego3
		absLRiego3 = buildAbsLRiego3();
		verLRiego.addComponent(absLRiego3);
		
		return verLRiego;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLRiego1() {
		// common part: create layout
		absLRiego1 = new AbsoluteLayout();
		absLRiego1.setImmediate(false);
		absLRiego1.setWidth("100.0%");
		absLRiego1.setHeight("55px");
		
		// cmbEtapa
		cmbEtapa = new ComboBox();
		cmbEtapa.setCaption("Etapa Fenológica");
		cmbEtapa.setImmediate(true);
		cmbEtapa.setWidth("250px");
		cmbEtapa.setHeight("25px");
		cmbEtapa.setTabIndex(4);
		absLRiego1.addComponent(cmbEtapa, "top:28.0px;left:10.0px;");
		
		return absLRiego1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLRiego2() {
		// common part: create layout
		absLRiego2 = new AbsoluteLayout();
		absLRiego2.setImmediate(false);
		absLRiego2.setWidth("100.0%");
		absLRiego2.setHeight("45px");
		
		// datInicio
		datInicio = new DateField();
		datInicio.setCaption("Fecha de Inicio");
		datInicio.setImmediate(false);
		datInicio.setWidth("250px");
		datInicio.setHeight("25px");
		datInicio.setTabIndex(5);
		absLRiego2.addComponent(datInicio, "top:18.0px;left:10.0px;");
		
		// txtGasto
		txtGasto = new TextField();
		txtGasto.setCaption("Gasto");
		txtGasto.setImmediate(false);
		txtGasto.setWidth("100px");
		txtGasto.setHeight("25px");
		txtGasto.setTabIndex(7);
		absLRiego2.addComponent(txtGasto, "top:18.0px;left:280.0px;");
		
		// lblGasto
		lblGasto = new Label();
		lblGasto.setImmediate(false);
		lblGasto.setWidth("-1px");
		lblGasto.setHeight("-1px");
		lblGasto.setValue("L/s");
		absLRiego2.addComponent(lblGasto, "top:22.0px;left:385.0px;");
		
		// txtLaminaCalc
		txtLaminaCalc = new TextField();
		txtLaminaCalc.setCaption("Lamina Calculada");
		txtLaminaCalc.setImmediate(false);
		txtLaminaCalc.setWidth("100px");
		txtLaminaCalc.setHeight("25px");
		txtLaminaCalc.setTabIndex(9);
		absLRiego2.addComponent(txtLaminaCalc, "top:18.0px;left:420.0px;");
		
		// lblLaminaCalc
		lblLaminaCalc = new Label();
		lblLaminaCalc.setImmediate(false);
		lblLaminaCalc.setWidth("-1px");
		lblLaminaCalc.setHeight("-1px");
		lblLaminaCalc.setValue("cm");
		absLRiego2.addComponent(lblLaminaCalc, "top:22.0px;left:525.0px;");
		
		return absLRiego2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLRiego3() {
		// common part: create layout
		absLRiego3 = new AbsoluteLayout();
		absLRiego3.setImmediate(false);
		absLRiego3.setWidth("100.0%");
		absLRiego3.setHeight("55px");
		
		// datFin
		datFin = new DateField();
		datFin.setCaption("Fecha de Fin");
		datFin.setImmediate(false);
		datFin.setWidth("250px");
		datFin.setHeight("25px");
		datFin.setTabIndex(6);
		absLRiego3.addComponent(datFin, "top:18.0px;left:10.0px;");
		
		// txtSuperficie
		txtSuperficie = new TextField();
		txtSuperficie.setCaption("Superficie Regada");
		txtSuperficie.setImmediate(false);
		txtSuperficie.setWidth("100px");
		txtSuperficie.setHeight("25px");
		txtSuperficie.setTabIndex(8);
		absLRiego3.addComponent(txtSuperficie, "top:18.0px;left:280.0px;");
		
		// lblSuperficie
		lblSuperficie = new Label();
		lblSuperficie.setImmediate(false);
		lblSuperficie.setWidth("-1px");
		lblSuperficie.setHeight("-1px");
		lblSuperficie.setValue("ha");
		absLRiego3.addComponent(lblSuperficie, "top:22.0px;left:385.0px;");
		
		// txtEficiencia
		txtEficiencia = new TextField();
		txtEficiencia.setCaption("Eficiencia Parcelaria");
		txtEficiencia.setImmediate(false);
		txtEficiencia.setWidth("100px");
		txtEficiencia.setHeight("25px");
		txtEficiencia.setTabIndex(10);
		absLRiego3.addComponent(txtEficiencia, "top:18.0px;left:420.0px;");
		
		// lblEficiencia
		lblEficiencia = new Label();
		lblEficiencia.setImmediate(false);
		lblEficiencia.setWidth("-1px");
		lblEficiencia.setHeight("-1px");
		lblEficiencia.setValue("?");
		absLRiego3.addComponent(lblEficiencia, "top:22.0px;left:525.0px;");
		
		return absLRiego3;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsLBotones() {
		// common part: create layout
		absLBotones = new AbsoluteLayout();
		absLBotones.setImmediate(false);
		absLBotones.setWidth("260px");
		absLBotones.setHeight("30px");
		
		// btnAccion
		btnAccion = new Button();
		btnAccion.setCaption("Agregar");
		btnAccion.setImmediate(true);
		btnAccion.setWidth("120px");
		btnAccion.setHeight("-1px");
		btnAccion.setTabIndex(12);
		absLBotones.addComponent(btnAccion, "right:0.0px;bottom:0.0px;");
		
		// btnNuevo
		btnNuevo = new Button();
		btnNuevo.setCaption("Agregar Nuevo");
		btnNuevo.setImmediate(true);
		btnNuevo.setWidth("120px");
		btnNuevo.setHeight("-1px");
		btnNuevo.setTabIndex(13);
		absLBotones.addComponent(btnNuevo, "bottom:0.0px;left:0.0px;");
		
		return absLBotones;
	}
}